### ISSUE TITLE
Add git short hash to end of version string if not building a release version

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#1179]
It would be really nice if the version string reported by `rclone --version` included the short git hash it is built from if the build is of a development version.  This of course assumes that the build is being done from a git checkout, but I think that should be possible to verify as part of the build process.

Currently the version strings are simply `v1.35-DEV` rather than something like `v1.35-DEV-6bad0ad` which makes it hard to verify exactly what the version being used is.  I think this would also help ensure that you know exactly what is being used in bug/problem reports from people who are using beta or development versions to test specific fixes.

**Comment by ncw** [comment]
You'll find the release builds (the betas and the release) are built like that.

However if you build with `go install` or `go build` I don't think there is any way to get the git version into the build.

I changed the Makefile in f7252645ba8cd1844a20cad982c8fc2d9dc3c035 so that if you just run `make` you'll get an rclone with the correct version number.

**Comment by animosity22** [comment]
This looks answered. If there is any other question, please feel free to ask on the forums.
