### ISSUE TITLE
Two-way (bidirectional) synchronization

### ISSUE THREAD

**Issue by alexander-yakushev** [rclone/rclone#118]
I'm sorry if this is answered elsewhere but I couldn't find it in that case.

I want to replace my current `Owncloud+Owncloud client (Linux)+FolderSync(Android)` setup with `Drive+Rclone+FolderSync`. But there is one thing I can't figure out how to do with rclone — smart two-way deletion synchronization. Which means: if a file was present on both server (Drive) and local machine, and then was deleted on either of them, the file will be eventually removed on both regardless of which direction you run `sync` first. Same, if a file was added on either server or client, it will be uploaded to the other one.

Can rclone do that, and if doesn't is there a chance of such functionality in future?

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
No rclone can't do that yet.

However it could be done I think.  Rclone would need to store a little bit of metadata - time of last sync. It could then use that for working out what to do in the delete files case.

**Comment by alexander-yakushev** [comment]
Thank you for the prompt response!

**Comment by ncw** [comment]
I've made a note about this for the FAQ - I'll leave this ticket open for future developments!

**Comment by nigelhorne** [comment]
It's been a year, what progress has been made?

**Comment by ncw** [comment]
None at the moment.  All the primitives needed are there in rclone, it just needs a 2-way sync expert to fill in the gaps!

**Comment by ywLBhGk2noZLbY7** [comment]
@nigelhorne Kinda creepy, I was just Googling for this exact issue...

**Comment by bmlong137** [comment]
I think a basic "2-way-sync" could be achieved with two commands.  Execute "rclone copy -u <local> <remote>" followed by "rclone copy -u <remote> <local>".  Obviously doesn't work if both sides are changed, but what generic solution will?

**Comment by allanlaal** [comment]
2-way bi-directional sync is really needed considering that the official Dropbox Linux client has not worked for years

**Comment by nu111** [comment]
It would be great to have 2-way bi-directional sync!
This way rclone would be a great open-soruce alternative to odrive!
Maybe we could get inspired by the MEGAsync client https://github.com/meganz/MEGAsync

**Comment by supagu** [comment]
yes would love to see a 2 way sync

**Comment by benji791** [comment]
Would be great to see this. It would allow to keep in sync OneDrive and Freenas.

**Comment by wilbowma** [comment]
FWIW, I'm currently using Unison for two way sync via ssh (https://github.com/bcpierce00/unison). I was considering trying to use rclone, since I use rclone for other syncing. Unison is written in OCaml, so you probably can't reuse the code directly, but it might provide a starting place for developing a good two-way syncing algorithm. It's an academic project with several publications about Unison, http://www.cis.upenn.edu/%7Ebcpierce/papers/index.shtml#File%20Synchronization, which might also be of help.

**Comment by hildogjr** [comment]
There is also the python @cjnaz work around (I tryed to did some improvements https://github.com/hildogjr/RCloneSync/). But still just a work around.

**Comment by cjnaz** [comment]
See [https://github.com/ncw/rclone/wiki/Third-Party-Integrations-with-rclone](url) for RCloneSync which points to [https://github.com/cjnaz/RCloneSync](url).  This is my original version that I've been running for since July 2017.  The README.md has an in-depth discussion of the nuances of bidir sync.  @hildogjr has updated this for Python 3 support, Python style standards, standardized Linux command line arguments, and added a few features.  I have yet to merge his pull requests, but they look good.  I would recommend his version (link above) but the core functionality is unchanged, I believe.

**Comment by yonjah** [comment]
@cjnaz  are you planing to merge @hildogjr  changes ?
It seem like both of you are actively working on each fork without merging in quite some time.

**Comment by hildogjr** [comment]
There is also a branch of mine by @deeuu that appear to trying to make a formal package.

**Comment by hildogjr** [comment]
Since Rclone browser still stoped on development. This could be used on future by wxPython interface (just a long long shot).

**Comment by cjnaz** [comment]
Hello folks.  I'm about to release a good sized update.  A primary addition
are test cases for the various switches.  Also changed the switches to
Linux standard.  Some Python style guide edits as well.

There is only 1 pull request on my repo for an edit for Python 3 support,
which I need to install Py3 to validate.

The nodelete switch may be a good edition but my brief look at the change
is that it actually only disables the local empty rmdir, not deletes
locally of deleted files on the Remote side.

I don't agree with the make cron addition. That would better be in a
separate script,  and what the cron should be may be very user specific. I
added a suggestion to the new TROUBLESHOOTING.md

There have been many forked edits which would need to be considered.  I
don't plan to change names from mixedCase to lower_case_with_underscores.
I'll consider this to be legacy code and not that important to touch
globally.

Cjn

**Comment by deeuu** [comment]
@hildogjr Are you planning to merge into the original repo of @cjnaz ?
@cjnaz Would you consider the package (+ some styling) work I['ve been working on](https://github.com/deeuu/RCloneSync)?

It would be great to fuse our efforts (Thanks again to @cjnaz for your original work).

**Comment by cjnaz** [comment]
@deeuu, I'll certainly look through the commits list
<https://github.com/deeuu/RCloneSync/commits/master> and see what's new.
I'll likely need to manually incorporate the edits since I've made
substantial changes.  The new version is functionally equivalent, with
changes to the command line interface, and a couple bug fixes.  Also added
is a hash of the `--filters-file`  (was `--ExcludesListFile`) to
effectively force a `--first-sync` if the filters are changed.

**Comment by cjnaz** [comment]
@deeuu, please point me to your changes / commits.  (I'm a bit of a git
noob.)

**Comment by deeuu** [comment]
There are quite a few [here](https://github.com/deeuu/RCloneSync/commit/decbf517f6f61eb8abf932408cb3c6096b434236) but perhaps it is best if I start again from your latest version; after all, I'm the new guy. Do take a look anyway and let me know what you think.

I haven't really looked into the python 3 support mods of @hildogjr, but it might make sense to get those merged before you comit your big revision? Thoughts?

**Comment by cjnaz** [comment]
I've not set up a Python package before.  I'll have a look at this and read
some docs.  What's the real value of turning this into a package from your
point of view?

**Comment by hildogjr** [comment]
Cold be easily installed (and dependences) and configured by a simple command for this cold be `pip install rclonesync` in the command terminal (Windows/Linux/Mac-OS). Also the user can easy update and track version.

You will need to create a account in https://pypi.org/ for this. I am just a collaborator and administrator of one package there until now.

**Comment by cjnaz** [comment]
I'll plan on manually doing the Py3 updates and post the single file
version, then Dominic can do the package edits.

**Comment by cjnaz** [comment]
Hi,
I've posted a big update on the V2 branch (not merged with Master):
https://github.com/cjnaz/RCloneSync/tree/V2.  This version should operate
the same as the master, but with changes in the command line arguments.

See V2CHANGES.md <https://github.com/cjnaz/RCloneSync/blob/V2/V2CHANGES.md>.
There are some items we'll need to discuss

I look forward to your feedback,
cjn

**Comment by cjnaz** [comment]
I will be out of town for a week.  Hopefully you guys can check out V2.

**Comment by whoamin** [comment]
https://github.com/cjnaz/RCloneSync/tree/V2
page not found

**Comment by deeuu** [comment]
Looks like there is another repo:
https://github.com/cjnaz/rclonesync-V2
@cjnaz how come?
btw, I'm planning on looking over this very soon!

**Comment by brenthuisman** [comment]
Isn't this something that should be part of rclone, perhaps even its default operation when syncing? It is what I initially expected the `sync` command to do.

**Comment by hildogjr** [comment]
I think is o what most of "not expert user" expected. Something to replace or provide some desktop bidirectional synchronization.

**Comment by ncw** [comment]
What do you think @cjnaz - would you like to integrate the functionality of rclonesync as a new rclone command?

**Comment by hildogjr** [comment]
For me, would be very nice. Something such as `rclone bisync` (bidirectional synchronization).
I could even join to effort.

**Comment by cjnaz** [comment]
Having rclone support bisync (thanks @hildogjr that's a better name) would be great.  A few thoughts...

- rclone bisync would wrap the capability into a well supported tool, rather than a side script that will chase rclone bugs and new features.  
- I don't know about the behavior and corner cases of all the other remotes.  We'd probably want to phase in wider support over time.
- My scheme of saving prior bisync status in a local working directory has no precedent in rlcone, and the  error cases and their handling may not be widely agreed to.  We should have a discussion on these topics before proceeding.
- What is the real problem we are solving?  Having this as a separate rclonesync.py script is inconvenient, or unfortunate, or seriously broken for what reasons?  Just wanting to understand the true value proposition.

cjn

**Comment by hildogjr** [comment]
1. Better user experience and integration;
2. Neither I, but after an alpha release of this command a lot of user will improve this discussion and may be finish and stable to all clouds in few releases;
3. Total agree, this is the critical point of this implementation and I appreciate opinions, mainly of the programmers of rclone. Even opinion about the implementation in Go-language.
4. This may be a step forward to create a fully and unique integrated tool to the most common cloud services.

**Comment by ncw** [comment]
> Having rclone support bisync (thanks @hildogjr that's a better name) would be great. A few thoughts...
> 
> rclone bisync would wrap the capability into a well supported tool, rather than a side script that will chase rclone bugs and new features.

Yes.  It would get maintained as part of rclone and would have a test suite run as part of rclone's testing infrastructure.

> I don't know about the behavior and corner cases of all the other remotes. We'd probably want to phase in wider support over time.

The remotes are very consistent - the integration tests ensure that.  I'm always amazed at when I add a new remote, get the integration tests to pass, then everything else just works!

> My scheme of saving prior bisync status in a local working directory has no precedent in rlcone, and the error cases and their handling may not be widely agreed to. We should have a discussion on these topics before proceeding.

Yes, rclone has steered clear of making a local database.  However the cache backend does now so there is precedent.

> What is the real problem we are solving? Having this as a separate rclonesync.py script is inconvenient, or unfortunate, or seriously broken for what reasons? Just wanting to understand the true value proposition.

I think having it as an rclone subcommand would be of benefit to users.  It then only one thing for the user to install.  Making it part of rclone itself will make consistent with the rest of rclone.

It would mean re-writing it in go, and reworking the internals to call rclone's internal APIs rather than the command line interface so would be quite a lot of work.  I'd be willing to help with some of that.

**Comment by RasmusKallas** [comment]
[SyncThing](https://github.com/syncthing/syncthing) (also in Go) might be useful.

**Comment by cjnaz** [comment]
[V2.3 adds](https://github.com/cjnaz/rclonesync-V2) Windows support, support for UNC paths, and adds a `--rclone` switch for specifying an alternate version of rclone from what's found in the path environment var.  I also explored an [rclone Crypt setup](https://github.com/cjnaz/rclonesync-V2/blob/master/USAGE.md) that I find quite useful for securing passing/synching files between various endpoints.  I need to look into getting rclone and rclonesync up on Android so that I have a clear path for syncing secure files with my phone.  
I hope to start working on incorporating bisync into rclone proper in a few weeks.

**Comment by erakli** [comment]
@cjnaz how about to create fork of rclone and plan integration of this feature?

Even it's in Go, we could perform code migration from Python together.

**Comment by AWalton** [comment]
@cjnaz hi, any update?

**Comment by hildogjr** [comment]
I think don't, there was some discussion at the forum https://forum.rclone.org/t/bi-directional-rclone-solution/3478/5 but nothing new.
The first viable idea was passing the https://github.com/cjnaz/rclonesync-V2 to Go language and merge into RClone.

**Comment by ConorWilliams** [comment]
Hi there, found this old thread after having implemented my own small two-way sync client in python using rclone: [https://github.com/ConorWilliams/rsinc](https://github.com/ConorWilliams/rsinc). I think it improves over some other python scripts written to do this as it makes use of rclones lsjson and hashing and multitasking. Hope this can help anyone trying to use rclone as a replacment for 1st party cloud sync clients missing from Linux

**Comment by ncw** [comment]
@ConorWilliams nice!  I'd really like someone to step up and make a 2-way sync command that is part of rclone - interested?

**Comment by ConorWilliams** [comment]
Cheers @ncw, I had considered porting rsinc to Go and intergrating it into rclone but unfortunatly I have no knowledge of the language so I'm not the person for the job. After having written rsinc (at least 40% of which is talking to rclone and class/multiprocess boilerplate) I suspect adding a 2-way sync into rclone shouldn't be too bad, literally all the primatives are there and the sync logic - whilst more complex for tracking moves and compund changes - is easily portable from one of the several 3rd party attempts.

**Comment by lpan** [comment]
@ConorWilliams I am interested in adding two-way sync into rclone and have opened an issue to track it -> https://github.com/rclone/rclone/issues/2870 And thanks for sharing `rsinc`! I will make sure to study it :slightly_smiling_face:

**Comment by dmacvicar** [comment]
@ncw, do you think the path of taking advantage of the [Nexcloud clients](https://nextcloud.com/clients/) by improving the `rclone serve webdav` story is a promising one, eg:

* Implementing the extensions in `rclone serve webdav` that Nextcloud Webdav server side offers to the client to perform better eg. `oc:data-fingerprint` and other properties in the `http://owncloud.org/ns` namespace, headers like `OC-ETag`, `OC-Total-Length`, `OC-Chunk-Size`, `OC-ErrorString`, etc.
* Improving local security (https, authentication).
* Solving potential bugs related to the mapping. Eg. webdav layer doing something inefficient on the backing cloud

I am under the impression that filling that gap is simpler than attempting to write a full sync client.  I am using NextCloud and their client works very well.

**Comment by cjnaz** [comment]
@lpan , please also see [rclonesync](https://github.com/cjnaz/rclonesync-V2)
for another implementation, and a discussion of the corner cases.  One
consideration is fail-safe - ensuring that the tool cant unintentionally
delete everything, due to network access problems, for example.  There also
needs to be a history mechanism so that changes can be cleanly detected on
both paths.

**Comment by cjnaz** [comment]
@lpan, please also see https://github.com/cjnaz/rclonesync-V2 for another implementation, and a discussion of the corner cases.  One consideration is fail-safe - ensuring that the tool cant unintentionally delete everything, due to network access problems, for example.  There also needs to be a history mechanism so that changes can be cleanly detected on both paths.

**Comment by GoddessOfCreation** [comment]
Surely this can be achieved already? I think something like outputting the list of objects in the source path with modification time (using rclone lsl), comparing that to a previous file, and syncing the local destination with the remote if there is a difference. In addition, the opposite can be done for any write/save event on the local machine. I'll see if I can make a bash file for it, although some event read utility might be needed. A cron might be fine, but could lead to inconsistencies.

**Comment by GoddessOfCreation** [comment]
Actually, no, a faster way would just be to change the timestamp of a remove file on a push event, and regularly comparing that to what's saved on the local system. If the two timestamps don't match up, sync the local files.

**Comment by ivandeex** [comment]
I believe this issue is superseded by more concrete https://github.com/rclone/rclone/issues/2870

However due to amount of discussion and thumbs up marking _this_ one important.

**Comment by ivandeex** [comment]
I am going to implement @cjnaz 's rclonesync as rclone bisync command mentioned earlier as part if this issue.

**Comment by ivandeex** [comment]
In the meantime you can propose names for the new command:
- `bisync`
- `bidisync`
- `bidi`
- your variant
Please put your thumbs up below

**Comment by ivandeex** [comment]
I like `bisync`

**Comment by ivandeex** [comment]
I like `bidisync`

**Comment by ivandeex** [comment]
I like `bidi`

**Comment by ivandeex** [comment]
None of the above. I **have added** my favorite name in a comment below.

**Comment by 7HE-W0R1D** [comment]
Wow so we will soon be able to use the cool bisync command?

**Comment by ivandeex** [comment]
I provide ETA only for commercial projects.

**Comment by Scannow** [comment]
I suggest `bsync`.

**Comment by shiftgeist** [comment]
Although I like bisync; I suggest `syncboth` for simplicity and autosuggestion benefits (`rcloud s<tab>` would show both). If the sync and bidirectional sync commands are to be kept better separated, I could understand that it would be unfavorable.

**Comment by hildogjr** [comment]
It is a good point, thinking on user experience.

**Comment by 0x3333** [comment]
Would `syncbidi` more descriptive? What you guys think?

**Comment by deeuu** [comment]
Controversial:
`rclone sync --both`

**Comment by ewen-lbh** [comment]
> Although I like bisync; I suggest `syncboth` for simplicity and autosuggestion benefits (`rcloud s<tab>` would show both). If the sync and bidirectional sync commands are to be kept separated, I could understand that it would be unfavorable.

Wouldn't `bisync` be _better_ than `syncboth`, completion-wise? rclone does not currently have any subcommands starting with "b": 

- `rclone b⭾` would autocomplete directly to `rclone bisync`
- `rclone s⭾` would show `sha1sum`, `size`, `sync` and `syncboth`

**Comment by ewen-lbh** [comment]
> Controversial:
> `rclone sync --both`

Except that if you run some script with `--both` tugged at the end of a long line that you didn't catch beforehand because line-wrapping was disabled:

![image](https://user-images.githubusercontent.com/39094199/108887558-b5fded00-760a-11eb-9cb8-d8c6a034ae64.png)

**Comment by smammy** [comment]
Maybe we could postpone the bikeshedding until this feature has actually been implemented.

**Comment by ivandeex** [comment]
`bisync` will be a separate command.
Kindly asking everyone to keep large cartoons for reddit...

**Comment by ivandeex** [comment]
I'm going to end the vote to stop spamming the thread.
With a count of 26 to 4 it's gonna be `bisync`.

**Comment by Jwink3101** [comment]
@ivandeex , will this include support for `--backup-dir` out of the box? What about `--track-renames`? How will you handle deletion conflicts?

I can't help with the coding part but if you have any questions of the sync process, I wrote https://github.com/Jwink3101/syncrclone where I dealt with a lot of these questions and added functionality. For example, since bidirectional sync tracks state, you can use the past state to track renames even if you have no or incompatible hashes. 

I also wrote up my algorithm [here](https://github.com/Jwink3101/syncrclone/blob/master/docs/algorithm.md)

Let me know if I can help

**Comment by ivandeex** [comment]
> will this include support for .... ?

Someday it will. You can track my plans/progress at #5164 (with [ivandeex/rclone#ci-bisync](https://github.com/ivandeex/rclone/commits/ci-bisync)  behind the scenes)

> --backup-dir? --track-renames? deletion conflicts?

Not in the initial release. I don't want to abruptly diverge from rclonesync right in the first hop. I'd rather let the code settle, the tests pass (@cjnaz wrote a cool test framework), and the first wave of user requests calm down before others or myself start adding features on top of rclonesync.

> I can't help with the coding part

:(

> Let me know if I can help

:)

P.S. Also, I have other stuff on my backlog, rclon'ish and beyond. Gonna keep the balance.

**Comment by ivandeex** [comment]
After 3 months we have a working bisync beta that is feature-wise on par with [rclonesync](https://github.com/cjnaz/rclonesync-V2). It still should go through the merge review (up to 1-2 months).
If you are impatient, you are free to try [current beta](https://github.com/ivandeex/rclone/releases/tag/v1.55.1-bisync01) at your own risk.
Note that a number of [important features](https://github.com/rclone/rclone/pull/5164#issuecomment-839764078) has not been included due to time constraints. Please refrain from reporting them here. I will work on adding them as well as on extending backend support, after 1.57.

**Comment by cjnaz** [comment]
Ivan, thank you hugely for your work on this long haul project.  I'll be experimenting with the beta(s) over the coming weeks.  Where do you want issues posted?

**Comment by ivandeex** [comment]
> Where do you want issues posted?

#5164 is fine

**Comment by iamtalhaasghar** [comment]
Great work @ivandeex. Can't wait for this to come out in a final release of rclone.

**Comment by ivandeex** [comment]
#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ivandeex** [comment]
Bisync code review has been delayed after rclone 1.56 release slip schedule by a month (probably due next week). We can still hope to have bisync in 1.57 which is not scheduled yet, can be expected this fall.

In the meantime I relased [bisync beta 2](https://github.com/ivandeex/rclone/releases/tag/v1.55.1-bisync02) for your evaluation. You can try it on _non-production data_. It still has a limitation: your backend must support _file modification time_, or command will abort.

**Comment by typxxi** [comment]
> In the meantime I relased [bisync beta 2](https://github.com/ivandeex/rclone/releases/tag/v1.55.1-bisync02) for your evaluation. You can try it on _non-production data_. It still has a limitation: your backend must support _file modification time_, or command will abort.

Thanks for that, but I have a question: wis webgui  supported in this beta 2 ?
thx

**Comment by ivandeex** [comment]
The feature will appear in rclone beta builds right after release 1.57 for limited beta testing.
Then it will be released for wider audience with 1.58 (2-3 months from now).
Thx

**Comment by ivandeex** [comment]
The feature will appear in _rclone beta builds_ right **after** release 1.57, for limited beta testing. You will be able to use `rclone selfupdate --beta` or direct downloads from https://beta.rclone.org to obtain a beta.

Then it will be released for wider audience with 1.58 (2-3 months from now).

:)

**Comment by ivandeex** [comment]
Merged on master.
Beta released on https://beta.rclone.org

**Comment by typxxi** [comment]
I guess it will become a present for chrismas or eastern cause I wanna avoid the risks of betas.
thx

**Comment by Harvie** [comment]
> Merged on master. Beta released on https://beta.rclone.org

Nice :-) Will this work in star topology? eg.: multiple devices doing bidirectional sync with shared directory on the server?
I am looking for dropbox/googledrive replacement. So my data is available when offline and will resync later to ordinary SFTP server with no server side software.

**Comment by ivandeex** [comment]
@Harvie 
This ticket is about BASIC 2-way sync. 
It is closed. It will not handle advanced use cases.
We predicted further questions about applicability to other topologies.
Please post your question to the closest related ticket #5689
Thank you.

**Comment by cjnaz** [comment]
If you are careful about scheduling, yes you can sync more than two
targets.  With rclonesync I used to sync both my home storage to Dropbox
and also/separately my work computer to the same Dropbox root location.
This allowed me to pass personal files back and forth.

Multi-target sync is not a native function of rclone bisync or rclonesync.
It is two separate operations.  It will likely break if both syncs are
running at the same time.  Schedule carefully.  Probably best to set up a
wrapper script with some sort of lock file.  Early on, rclonesync's lock
file did not track the path names so it worked nicely for blocking one sync
while the other was still running.

**Comment by gerardbosch** [comment]
Hi there, what are the known backends that _"support file modification time"_? I was trying with mega.nz as it offers good amount of free storage and strong security. But after trying `bisync` I got the error:

> Failed to bisync: modification time support is missing on path2

I'm wondering about free and good alternatives I can use. I liked also mega.nz as their application is very lightweight compared to something like Dropbox app that eats a lot of RAM. But on an old low spec Windows server I wanted to use `rclone` as the mega app does not work (requires extra stuff to be installed).

I guess that nothing can be done with mega, at least right now. Any ideas or recommended free backend? Thanks!

**Comment by Jwink3101** [comment]
> Hi there, what are the known backends that _"support file modification time"_? I was trying with mega.nz as it offers good amount of free storage and strong security. But after trying `bisync` I got the error:
> 
> > Failed to bisync: modification time support is missing on path2
> 
> I'm wondering about free and good alternatives I can use. I liked also mega.nz as their application is very lightweight compared to something like Dropbox app that eats a lot of RAM. But on an old low spec Windows server I wanted to use `rclone` as the mega app does not work (requires extra stuff to be installed).
> 
> I guess that nothing can be done with mega, at least right now. Any ideas or recommended free backend compatible with `bisync`? Thanks!

This really is a better question for the forum. But see [the remote overview](https://rclone.org/overview/)

Also, I am the author of [syncrclone](https://github.com/Jwink3101/syncrclone) which can support remotes that don’t support modtime. It has pros and cons. See [my comparison](https://github.com/Jwink3101/syncrclone/blob/master/docs/rclone_bisync_compare.md)

**Comment by gerardbosch** [comment]
Thanks @Jwink3101 for your answer, and sorry for posting here the question that belongs to the forum –just landed here looking for the bisync error :)
Now that I see the link to the remote overview, I think that Google Drive will perfectly meet my requirements, just in case it helps someone else. Not 20GB but 15GB of free storage, still enough =)
