### ISSUE TITLE
[Feature request] --order-by flag

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#1205]
For some content the order in which it is downloaded is important (say a tv series/album) especially when you have a slow connection. So I propose an --order-by flag with two options type and order where the type can be any file property.
For example:
`rclone --order-by=name,ascending copy remote:somewhere/ here/` or 
`rclone --order-by=size,descending copy remote:somewhereelse/ alsohere/`. 
This might take longer because I think you'd have to first build the full list of files then sort it for most remotes, but for certain types of content this is preferable to the random order that rclone currently uses.

This flag would also be nice for the listing and checksum commands.

**Comment by ncw** [comment]
Yes this would imply building a complete map of transfers first which would potentially use a lot more memory.

**Comment by brandur** [comment]
This is a tough one. I see the motivation behind leaving it unsorted, but speaking personally for my use cases, I will _always_ prefer my output to be sorted, and the additional memory overhead is ~_never_ going to be a problem. It's hard to say, but I suspect that I'm in the user majority rather than the minority.

It's possible to do the Unixy thing and pipe out to `cut` and `sort`, but these commands just have so many gotchas (e.g. say your filenames have spaces) that it gets really old fast.

It'd be nice to at least have the option to alias my own "rclone ls" to include an `--order-by=name` or `--sort` parameter.

**Comment by ncw** [comment]
With rclone's new sync method it will order the transfes by name on a per directory basis - is that helpful?

so when transfering any given directory, it will start the transfers in alphabetical order for that directory.  Rclone may be looking at up to `--checkers` directories at once though.

**Comment by azureblaze** [comment]
@ncw That's definitely very helpful, does this also apply to copy?

**Comment by eventer102** [comment]
I am eagerly hoping this implementation to be included with copy option.

If you have slow connection, you would desperately need to prioritize the rclone copy command upon scheduling overnight.
I use a crontab scheduler; However, when rclone with copy option breaks due to power failure, it simply copies the files at random. This has been a pain for so long for me.

Any work round on this issue or any plan to include the prioritized rclone copy option please.

Thanks.

**Comment by ncw** [comment]
If you want a completely deterministic copy you can use `--transfers 1`.  Otherwise rclone will be working its way through many directories at once and the copies can come out of order.  However this is much improved in recent rclones - the old sync method used to copy stuff at random.

An `--order-by` flag is still possible though so I'll leave this issue open!

**Comment by mehrdadn** [comment]
Hi! I would like to +1 the request for an `--order-by` flag. I would simply leave note in the documentation to document the performance implications, but otherwise it can be very useful.

**Comment by ncw** [comment]
I'm going to have a go at implementing this for sync/copy/move, but with a best efforts `--order-by`.  So rclone will transfer the files smallest first (let's say) but without building an entire transfer map first.  rclone has a buffer of 10,000 files by default so provided you are transferring less than 10,000 files rclone will do them mostly in the order you specified other than when the transfer queue was empty and it wanted something to be getting on with.

I can implement this quite easily using a priority queue or sorted slice and it won't use any more memory than rclone does at the moment.

**Comment by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [comment]
+1 for: --order-by=moddate,descending

**Comment by ncw** [comment]
I have implemented this here - testers appreciated!

https://beta.rclone.org/branch/v1.50.2-084-g7d79ab7b-fix-1205-order-by-beta/ (uploaded in 15-30 mins)

Here are the docs

### --order-by string ###

The `--order-by` flag controls the order in which files in the backlog
are processed in `rclone sync`, `rclone copy` and `rclone move`.

The order by string is constructed like this.  The first part
describes what aspect is being measured:

- `size` - order by the size of the files
- `name` - order by the full path of the files
- `modtime` - order by the modification date of the files

This can have a modifier appended with a comma:

- `ascending` or `asc` - order so that the smallest (or oldest) is processed first
- `descending` or `desc` - order so that the largest (or newest) is processed first

If no modifier is supplied then the order is `ascending`.

For example

- `--order-by size,desc` - send the largest files first
- `--order-by modtime,ascending` - send the oldest files first
- `--order-by name` - send the files with alphabetically by path first

If the `--order-by` flag is not supplied or it is supplied with an
empty string then the default ordering will be used which is as
scanned.  With `--checkers 1` this is mostly alphabetical, however
with the default `--checkers 8` it is somewhat random.

**Comment by domdevitto** [comment]
Hi Nick,
Not seeing this branch function correctly (on a big sync or copy), specifically with:

rclone-v1.50.2-084-g7d79ab7b-fix-1205-order-by-beta-osx-amd64/rclone copy /path/wherever gdrive:wherever --fast-list --transfers=22 --checkers=44 --tpslimit=90 --drive-chunk-size=1M --verbose --verbose --order-by size,ascending

Is sending many larger files before smaller files - and (in my case at least), looks like it's not reordering the transfers at all ?

**Comment by ncw** [comment]
> Is sending many larger files before smaller files - and (in my case at least), looks like it's not reordering the transfers at all ?

How many files are you transferring?  I expect the a few to slip through at the start - approx `--transfers` before the queue has built up.

**Comment by domdevitto** [comment]
> > Is sending many larger files before smaller files - and (in my case at least), looks like it's not reordering the transfers at all ?
> 
> How many files are you transferring? I expect the a few to slip through at the start - approx `--transfers` before the queue has built up.

No, transferring lots of files (65,558 in fact).  I'll see if I can build a smaller test case ! :-) 

Dom

**Comment by domdevitto** [comment]
> > Is sending many larger files before smaller files - and (in my case at least), looks like it's not reordering the transfers at all ?
> 
> How many files are you transferring? I expect the a few to slip through at the start - approx `--transfers` before the queue has built up.

I think I found the 'issue' - --max-backlog needs to be high enough to cover all the files - would that make sense?  (IMHO It's worth documenting this if that's right....)

When it's set high enough (default 1000) --order-by  seems to work lovely [at least for 'size']  :-)  - thankyou!

**Comment by ncw** [comment]
> I think I found the 'issue' - --max-backlog needs to be high enough to cover all the files - would that make sense? (IMHO It's worth documenting this if that's right....)

Yes that's right - if you want a perfect ordering then max-backlog needs to be bigger than the number of files that need transferring.

I wrote this in the docs - does that look OK? Or does that need more explanation?

#### Limitations

The `--order-by` flag does not do a separate pass over the data.  This
means that is may transfer some files out of the order specified if

- there are no files in the backlog or the source has not been fully scanned yet
- there are more than [--max-backlog](#max-backlog-n) files in the backlog

Rclone will do its best to transfer the best file it has so in
practice this should not cause a problem.  Think of `--order-by` as
being more of a best efforts flag rather than a perfect ordering.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51

**Comment by kedare** [comment]
It looks like order-by has no effect on the `ls` command ?

**Comment by ncw** [comment]
`--order-by` is just for the order that transfers are done. `ls` is unaffected.
