### ISSUE TITLE
Decrypting an encrypted path/hash

### ISSUE THREAD

**Issue by EnorMOZ** [rclone/rclone#1238]
As per forum post [https://forum.rclone.org/t/decrypting-an-encrypted-path/1331/6] to be able to decrypt an actual hash/path when using ls or any other means. 

Similar to --crypt-show-mapping but the reverse.

**Comment by ncw** [comment]
You can use --crypt-show-mapping for this by listing all the files and grepping for the encrypted path - would that work for you?

**Comment by seuffert** [comment]
the reverse wouldn't need to make any requests to the backend, would it (good for BIG libraries)? just decrypt the name

**Comment by ncw** [comment]
Neither would the forward...

I could do this with an extra command, something like

```
rclone cryptname encrypt crypt: plaintext
rclone cryptname decrypt crypt: ciphertext
```

I'm just not sure it is worth the effort since this isn't an often used option and there is a (kludgey) work-around.

I'd be prepared to be convinced otherwise though!

**Comment by sataris** [comment]
I would also like something like this. 

My use case 
Namely I have several files in my drive trash (thanks to ---drive-use-trash). 

Since these files all have encrypted filenames, I'd like to be able to decrypt the filenames without having to mount the trash folder itself as a mount. 

I'd prefer to just pass the encrypted file/folder name and have it tell me what it decrypts to.

Sidenote: if there's another way of doing this, I'm all ears!

**Comment by ncw** [comment]
@ishuah is just about to land a `--reverse` flag to the `cryptdecode` command which will do what you want so watch this space!

**Comment by ishuah** [comment]
@sataris here's a beta version (https://beta.rclone.org/v1.39-023-g0a7731cf/) that decrypts filenames

**Comment by animosity22** [comment]
This looks solved. Closing out.
