### ISSUE TITLE
Need AutoUpdate System.

### ISSUE THREAD

**Issue by niranjanshr13** [rclone/rclone#1259]
When new update arrives. We could just rclone -U; similar to youtube-dl -U to update. Many distribution doesn't have a package for it, so I was thinking creating a self-contain update feature.

**Comment by ncw** [comment]
This would be nice!

You can see if there is a new version with `rclone version --check`

**Comment by animosity22** [comment]
I think we have a one liner at this point to update and if you wanted to update, it's pretty straight forward these days.

Since no one has jumped on this in 3 years, I'm going to say it is stale and we can always open something back up if there is an urge to implement it.

Let me know if you think something else.

Thanks.
