### ISSUE TITLE
Feature Request: dedupe --dedupe-mode largest/smallest

### ISSUE THREAD

**Issue by EnorMOZ** [rclone/rclone#1269]
Have the ability for dedupe to resolve conflicts based on size. 
`  1:  20763388765 bytes, 2014-06-02 01:28:01.000000000, md5sum edde20da54035785c98d722a9785484f
    2:   5865405209 bytes, 2017-03-17 20:59:40.823000000, md5sum 088561d011ed0ab4f857e5e6ad108842`

**Comment by ncw** [comment]
What would you want - biggest / smallest?

**Comment by DTrace001** [comment]
In my case the biggest but figured others may want smallest (shrug)

**Comment by hombit** [comment]
It is a good idea to have a size related strategy. Often wrong duplicate has zero size, I have a lot of them are produced by official Mac client.

**Comment by chemputer** [comment]
I noticed there's a largest now implemented, but not smallest. I thought at first it was sorted by size, so I thought "first" would do, but that doesn't appear to be the case.

I definitely would like a smallest option, perhaps with a percentage difference to keep the larger one, like if file A is 1% the size of file B, they probably aren't the same... I don't want my video file to be deleted instead of a text file that accidentally has the same name and extension. 

If I get some time over the next couple days I'll take a look at the biggest code and see what I might be able to do myself.

**Comment by ncw** [comment]
> If I get some time over the next couple days I'll take a look at the biggest code and see what I might be able to do myself.

Adding smallest would be quite easy I think.

**Comment by seuffert** [comment]
rclone has gotten support for this (beside other modes)
```
* --dedupe-mode largest - removes identical files then keeps the largest one.
* --dedupe-mode smallest - removes identical files then keeps the smallest one.
```
i think this can be closed? @ncw

**Comment by trysten** [comment]
yeah, this can be closed
finished with: 81002747c5b0b2eab37178afc1338e8dba47c2f3
