### ISSUE TITLE
ACD HTTP 409 NAME_ALREADY_EXISTS

### ISSUE THREAD

**Issue by diamondsw** [rclone/rclone#1293]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac OS X 10.12.4, 64-bit
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync dir amazon:/Backup/dir
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
I run things through a custom script so I don't readily have logs. Probably not required - see description.

This is similar to, but different from #742. HTTP 409 errors can also happen when case is the only thing that differs between the local system and ACD, i.e. there are no local case sensitivity issues such as in that bug. I commonly run into this fixing bad capitalization in filenames, which subsequently fails to backup (and prevents deletions due to "I/O Errors" until I manually fix it). It would be quite preferable if rclone could at least detect that this is a capitalization conflict issue and not flag it as an I/O error; it would be even better if its "sync" option could properly fix the issue, either by renaming the Amazon end to match (efficient) or by deleting the "old" files and uploading "new" files. Either way, the result of a sync should be that the datasets are in sync.

**Comment by ncw** [comment]
The easiest fix for this would be for rclone to take a --lower-case flag (say) so it lowercased all file names in and out.

Do do it properly would be ok if the files were always in the same directory, so if you had

/path/to/file
/path/to/FILE

that would be possible, but

/path/to/file
/path/TO/FILE

would be quite hard.

Any of those options useful?

**Comment by jkoopmann** [comment]
I agree some sort of improvement would be great. Currently I automatically upload iOS camera roll fotos to my server and back these up with rclone. For whatever reason the camera seems to create tons of files that only differ in JPG and jpg resulting in an unpleasant amount of errors (and files not being backed up). I could try to change the file names but I am afraid the sync-software would not like that (the one from iOS to my server).

I would be happy with a "--skip" option in this case so that this does not result in errors from the cronjob. Better would be to create the file an Amazon with a different name or suffix etc. Not sure how this could be done though and yes clearly during restore this would create new challenges.

**Comment by animosity22** [comment]
RIP ACD. You'll be remembered.
