### ISSUE TITLE
Simplenote integration?

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#1294]
This is a feature request.

Would be great to have Simplenote (simperium API 2) integration.  These are basically text files, and rclone would be a terrific "backup" mechanism.  Not sure how well it would work for writing to the Simplenote service, but reading from it would be very easy, I would think.

**Comment by ncw** [comment]
The API looks quite capable.  I don't see any documentation on what an object is though - can it store arbitrary data?

**Comment by dogear42** [comment]
Simperium can store arbitrary data, yes.

However, Simplenote (the first app that used Simperium) has a note repository that uses a standard JSON format that looks like: 
{
    tags, ["tag1, "tag2"],
    deleted: false,
    shareURL: "",
    publishURL: "",
    content: "some big long string with line feeds\n in it",
    systemTags: [],
    modificationDate: 1490233933
}

The "content" property has the actual text content in it.  The note also has a hash "key" for accessing it.  That is what most programs use for the "filename".  (However, for backup/syncing purposes, we could potentially just dump the whole json blob into a file instead of just the content property.)

There is also a separate "tags" repository, so not sure how (or if) dealing with that is important.  Each entry in the tags repo is just a single word string.  The key is the same string, instead of a hash.

**Comment by ivandeex** [comment]
Requested 4 years ago by a now deleted account.
No comments, no +1's
