### ISSUE TITLE
rclone SFTP in Android termux failing

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#1313]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.36-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Android 5.0, 32 bit
Termux 0.48

> Which cloud storage system are you using? (eg Google Drive)
SFTP

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync localpath remote:/remotepath --checksum --exclude 'long list of excudes' --delete-excluded`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
`2017/04/06 17:06:22 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["go/bin/rclone" "sync" "storage/shared" "laptopcrypt:/" "-vv" "--checksum" "--exclude" "/{.HiddenCabinet,AndroIRC,Android,DCIM,Download,Fonts,Notifications,OpenKeychain,Pictures,Ringtones,Yota,rdtmp}/**" "--delete-excluded"]`
`2017/04/06 17:06:22 Failed to create file system for "laptopcrypt:/": failed to make remote "laptop:/Users/MYNAME/backup" to wrap: couldn't connect ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain`

This is very similar to these two issues:
- https://github.com/ncw/rclone/issues/1218
- https://github.com/ncw/rclone/issues/1279

Note that I tried the same thing without using the crypto remote, just using a bare SFTP remote.  Same error.

I tried this without storing a password and with storing a password.  Same error.

I checked:
`$ env | grep ssh`
And, I did NOT see anything, especially NOT like this: `SSH_AUTH_SOCK=/tmp/ssh-Sj7JaoojWnEb/agent.3807`

I tried running:
`$ eval "$(ssh-agent -s)"`
And I got something like:
`Agent pid 6997`

I'm not very knowledgable about SSH, so not sure what to do with this.

Thanks!

**Comment by kubark42** [comment]
@dogear42, what happens if you try to ssh directly into the server. Does it work?

**Comment by dogear42** [comment]
@kubark42 

Yeah, it prompts me for password.  I enter it.  Logs in no problem.

Note that I did login the first time manually so that I could answer YES to the question about adding the server to my known hosts file.

**Comment by dogear42** [comment]
@kubark42 

I ran it with and without -i, and didn't see it either time.  The environment variable is not reported at all.

**Comment by kubark42** [comment]
If it's prompting for a password even when you directly ssh, then the SSH key is not working. You'll want to get that resolved first.

**Comment by dogear42** [comment]
I'm not using a key.  You mean this only works with keys and not with passwords?  I wanted it to prompt me for a password.  I don't want to setup keys yet.

**Comment by kubark42** [comment]
Currently, it only works with keys.

Certainly, it would be nice to be able to support passwords because then `rclone` could be bundled into applications which can upload without having to have an SSH key installed on the system. There was some discussion in https://github.com/ncw/rclone/issues/1218 about using a password in general, but I don't think there was a conclusion there about whether it was something likely to be on the roadmap.

**Comment by dogear42** [comment]
Does it indicate on the documentation that it only works with keys?  That wasn't obvious to me.

The documentation says:
SSH password, leave blank to use ssh-agent
y) Yes type in my own password
g) Generate random password
n) No leave this optional password blank
y/g/n> n

Which made me assume I _could_ set a password, if I wanted, or if I didn't, that it would prompt me.  I mean, I know how to spell assume, but still.  :)

It also says this, but I have no idea what this means:
"This will guide you through an interactive setup process. You will need your account number (a short hex number) and key (a long hex number) which you can get from the SFTP control panel."

I have no "control panel" for my SFTP that I'm aware of (MacOS).

**Comment by kubark42** [comment]
Oh, I might be completely wrong, then. I thought you were meaning that you were expecting a password prompt when you started the `rclone` process. I don't know about entering the password during the config.

**Comment by dogear42** [comment]
I tried both setting the password and not.  I got the same error with both.

I'll try using the keys.

**Comment by dogear42** [comment]
I setup keys.  I no longer get prompted for a password to manually login over ssh.

However, I still cannot use SFTP:

go/bin/rclone sync storage/shared laptopcrypt:/ -vv --exclude '/{.HiddenCabinet,AndroIRC,Android,DCIM,Download,Fonts,Notifications,OpenKeychain,Pictures,Ringtones,Yota,rdtmp}/**' --delete-excluded
2017/04/07 00:17:02 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["go/bin/rclone" "sync" "storage/shared" "laptopcrypt:/" "-vv" "--exclude" "/{.HiddenCabinet,AndroIRC,Android,DCIM,Download,Fonts,Notifications,OpenKeychain,Pictures,Ringtones,Yota,rdtmp}/**" "--delete-excluded"]
2017/04/07 00:17:04 Failed to create file system for "laptopcrypt:/": failed to make remote "laptop:/Users/MYNAME/Google Drive/backup" to wrap: couldn't connect ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by ncw** [comment]
@dogear42 did you set up a password for ssh when you did the `rclone config` originally?  If so then it should have used that rather than an agent.

I just tried this beta https://pub.rclone.org/v1.36-22-g06ea13a-ssh-agent%CE%B2/ with termux on my nexus 6 using sftp with a password and it worked fine.

Can you try that?

**Comment by dogear42** [comment]
I guess another point to make is that I'm also using a crypt remote with this sftp remote.

I downloaded the latest, edited the remote to ensure I had the password typed in correctly, and I get this:

2017/04/12 03:00:00 Failed to create file system for "laptopcrypt:/": failed to make remote "laptop:/Users/MYNAME/backup" to wrap: couldn't connect ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

I already setup keys, too.  When I manually login over ssh, I don't even get prompted for a password.

So, I'm not sure what the problem is here.  It appears to not attempt _any_ methods of authentication.

**Comment by ncw** [comment]
I suggest you try the latest rclone which is packaged with termux and if there is still a problem please re-open.
