### ISSUE TITLE
ReadFileHandle.Read - unexpected EOF

### ISSUE THREAD

**Issue by kelek-** [rclone/rclone#1413]
Hello,
as acd_cli is currently disabled, but I still want to watch my media from ACD using emby and a mount from my ACD to my linux server I tried replacing acd_cli with rclone.
Mounting itself works out, however it really takes a while until the mount is done - I assume its due to slow Amazon routes?

Furthermore I realized a lot of these errors:
`2017/05/16 18:38:39 ERROR : series/file.mkv: ReadFileHandle.Read error: low level retry 1/10: unexpected EOF
`
Is this due to an error from Amazon or is this something rclone could take care of?

I'm running a stable jessie system using rclone 1.36.
I'm mounting ACD with:

rclone mount acd:Storage /mnt/acd/ --max-read-ahead=256M --allow-other --uid 108 --gid 113 --umask 000

I read using --buffer-size and --acd-templink-threshold could possibly speedup things, but I'm actually not sure.

Is there any specific version I should use to help debugging?

Thanks in advance!

Regards

**Comment by ncw** [comment]
> 2017/05/16 18:38:39 ERROR : series/file.mkv: ReadFileHandle.Read error: low level retry 1/10: unexpected EOF

rclone will retry those errors as the `retry 1/10` bit indicates.  That is probably what is causing the slow start if you are getting a lot of them.

`Unexpected EOF` is caused by the stream from amazon dropping unexpectedly for some reason.  It is worth doing the simple things like rebooting your router to see if you see any improvements.

Using `--buffer-size 128M` (say) will help a lot with this - it allows rclone to read ahead in the stream so it will have time to remake the connection if it drops before you notice.

I'm not sure about `--acd-templink-threshold` - I don't think it will help, but it doesn't hurt to try!

**Comment by animosity22** [comment]
ACD is dead.
