### ISSUE TITLE
rclone in loop if filename starts with http: or rcf: or any other unknown error 

### ISSUE THREAD

**Issue by Pythic** [rclone/rclone#1492]
I have to backup a large amount Rackspace containers (600+ each with millions of files) . Somehow (dont ask me why) some filenames start with http:/ or rcf:/ . rclone seems to not copy those files to the local FS (but it states "Copied new"). When this happens rclone never finishes. 
I also have seen the same behaviour if for some reason swift returns a file that has a "Unknown of IO Error type of response"
I'm using last beta from 6/20/2017

**Comment by ncw** [comment]
If a file is called "http://example.com" in the swift container, then rclone will download it to a directory called "http:" and the file called "example.com".

On subsequent syncs rclone will be looking to see if an object called "http:/example.com" (note 1 slash this time) exists, so it will forever copy these objects.

The problem is that "http://example.com" isn't a valid file name, whereas it is a perfectly valid object name.

Is that the problem you are seeing?

**Comment by Pythic** [comment]
Yes that is basically what I see. I was also unable to exclude these filenames using rclone copy .

I've worked around the problem using the "mount" option and using unison to manage the syncing and such. 

Is it a bug? or foo you cannot fix due to the nature of buckets and cloud storage?

**Comment by animosity22** [comment]
This was solved by the linked issue.
