### ISSUE TITLE
Cannot "exclude" socket file in rclone sync?

### ISSUE THREAD

**Issue by 01100001** [rclone/rclone#1537]
- rclone v1.36
- Ubuntu Server 16.04, 64-bit
- Backblaze B2

The rclone command (includes those I've also tried):

```
rclone sync ~/files b2remote:files --transfers=64 --delete-after --exclude=".scgi_local"

rclone sync ~/files b2remote:files --transfers=64 --delete-after --exclude=".scgi_local/**"

rclone sync ~/files b2remote:files --transfers=64 --delete-after --exclude="\.scgi\_local"

rclone sync ~/files b2remote:files --transfers=64 --delete-after --exclude="*.scgi_local"

rclone sync ~/files b2remote:files --transfers=64 --delete-after --exclude=".scgi_local" --exclude="**/.scgi_local"
```

Now `.scgi_local` is a socket file, i.e. not a normal file. (Permissions on the file: `srwxrwx---`) And this is the output I get when I run any of the above commands:

    2017/07/17 02:31:49 NOTICE: .scgi_local: Can't transfer non file/directory

Why am I getting the NOTICE when I am specifically telling rclone to exclude the file? I understand that it's not an ERROR, but still. (BTW exclude works just fine with normal files & directories.) How else should it be done?

**Comment by ncw** [comment]
Rclone will be excluding the file, but the notice is happening at a lower layer before the filtering.

I'll have a think on how to do this better.

**Comment by 01100001** [comment]
Oh, okay.

**Comment by 0x3333** [comment]
What needs to be done to fix this issue? I'm willing to help. Thanks.

**Comment by ncw** [comment]
@0x3333 thanks for your kind offer :-)

What is needed is a new option for the local backend, probably similar to this one

https://github.com/rclone/rclone/blob/bde0334bd8e2c16d9fbc49758cd9374f1d741bd2/backend/local/local.go#L66-L72

I just had a look to see what rsync does, and it skips fifos and sockets by default

```
       --devices
              This  option causes rsync to transfer character and block device
              files to the remote system to recreate these devices.  This  op‐
              tion  has no effect if the receiving rsync is not run as the su‐
              per-user (see also the --super and --fake-super options).

       --specials
              This option causes rsync to transfer special files such as named
              sockets and fifos.
```

So that is probably what rclone should do - skip devices and sockets. We have no way of implementing `--devices` and `--sockets` at the moment.

Alternatively we could implement a flag `--local-no-specials` or something like that to do the same.

What do you think?

**Comment by 0x3333** [comment]
My pleasure! 😃 

Currently, sockets, devices, etc are already skipped, but they got logged(`Storable` function on `local.go`) :

https://github.com/rclone/rclone/blob/da5cbc194a6fa337e0ae162da5c89605f8347232/backend/local/local.go#L803-L805

I believe we should keep default behavior, skipping those devices/sockets, just omit the logging line, they cannot be transferred anyways.

**Comment by ncw** [comment]
> I believe we should keep default behavior, skipping those devices/sockets, just omit the logging line, they cannot be transferred anyways.

If you run rsync not as root you get this

```
$ rsync -a /dev/null copy
skipping non-regular file "null"
$
```

Whereas as root

```
$ sudo rsync -a /dev/null copy
$
```

So I'd say rclone matches rsync's behaviour at the moment.

Perhaps downgrading the `Logf` (which is NOTICE and shown by default) to an `Infof` (INFO shown with -v) might be the thing?

**Comment by 0x3333** [comment]
I don't know, I think I need more time to think about it. Downgrading the Logf I don't believe is the right path. Maybe this behavior is the right one, I'm not sure.

Let me think about it and let you know...

**Comment by benz2012** [comment]
I agree that there is no need to change the default log behavior, but just as Nick suggested, this is a perfect opportunity to add a flag that mimics the `--skip-links` flag.

I am hesitant to make another flag, however, since these will both be performing a similar behavior. Also, `--skip-links` is poorly named, as skipping links is a file scanning behavior, but the flag changes a logging behavior.

Ideally, we would rename `--skip-links` to make it apparent that we are affecting logging behavior. One idea would be `--log-ignore-links`. Then we would add a new flag, related to this issue, named `--log-ignore-sockets-devices-pipes`.

You might start to see where this would spiral out of control (or is this a slippery slope fallacy?). This raises the philosophical question of "Should we allow global flags to adjust logging behavior?". And it brings us back to [the comment above](https://github.com/rclone/rclone/issues/1537#issuecomment-591550823) where it was questioned if this feature should even exist.

Ideally, a user should rely on logging levels to _adjust logging behavior_. Otherwise, you might as well implement a more custom interface, to eliminate the need for many global arguments.

**Would anyone be in favor of `--log-ignore` as a string parameter that takes an enumeration of _features_ that one might want to ignore in logs?**

For example, `--log-demote="skip-links,skip-non-file-directory"`

I am also in favor of making no changes. But if we close this issue with no changes made, the question still stands about adjustments to logging behavior. This topic was not raised on the `--skip-links` [issue/feature](https://github.com/rclone/rclone/issues/1480) so maybe I am overthinking it.

**Comment by ncw** [comment]
> I agree that there is no need to change the default log behavior, but just as Nick suggested, this is a perfect opportunity to add a flag that mimics the `--skip-links` flag.
> 
> I am hesitant to make another flag

Yes me too :-)

> however, since these will both be performing a similar behavior. Also, `--skip-links` is poorly named, as skipping links is a file scanning behavior, but the flag changes a logging behavior.

Agreed!

> Ideally, we would rename `--skip-links` to make it apparent that we are affecting logging behavior. One idea would be `--log-ignore-links`. Then we would add a new flag, related to this issue, named `--log-ignore-sockets-devices-pipes`.

We can deprecate flags in rclone - they can be hidden from the docs and the help but carry on working, so if we do want to rename the flag it isn't a big problem.

> You might start to see where this would spiral out of control (or is this a slippery slope fallacy?). This raises the philosophical question of "Should we allow global flags to adjust logging behavior?". And it brings us back to [the comment above](https://github.com/rclone/rclone/issues/1537#issuecomment-591550823) where it was questioned if this feature should even exist.
> 
> Ideally, a user should rely on logging levels to _adjust logging behavior_. Otherwise, you might as well implement a more custom interface, to eliminate the need for many global arguments.

Yes

> **Would anyone be in favor of `--log-ignore` as a string parameter that takes an enumeration of _features_ that one might want to ignore in logs?**
> 
> For example, `--log-demote="skip-links,skip-non-file-directory"`
> 
> I am also in favor of making no changes. But if we close this issue with no changes made, the question still stands about adjustments to logging behavior. This topic was not raised on the `--skip-links` [issue/feature](https://github.com/rclone/rclone/issues/1480) so maybe I am overthinking it.

Being #lazydev I'd propose `--log-ignore REGEXP` which would kill all of the logs which matched the REGEXP. Logs in rclone aren't tagged at the moment so it would be really hard to do classes of logs.

The original posters issue was that it is impossible to exclude the sockets from a scan as `--include` and `--exclude` work at a level above the directory listings. I could maybe get the local backend to follow the filters (by passing them in as List options maybe) which would at least give the users a way to work around the problem. That would fix the original issue.

**Comment by benz2012** [comment]
Ahh right, I got completely sidetracked from the original issue. (My own intentions were to find a way to ignore those log lines)

**Comment by ivandeex** [comment]
@benz2012 
Please submit whatever you have as a _Draft PR_.
Having more eyes on the code is always good.

**Comment by ivandeex** [comment]
Closing after 8 months of inactivity
