### ISSUE TITLE
Sharefile Storage Support Option

### ISSUE THREAD

**Issue by NicholasBoccio** [rclone/rclone#1543]
Sharefile has options for WebDAV and FTP

Here is the API documentation: https://api.sharefile.com/rest/
A description: https://www.citrix.com/file-sharing/file-storage.html

**Comment by ncw** [comment]
You could try [the latest beta](https://beta.rclone.org) which has FTP support?

**Comment by NicholasBoccio** [comment]
Thanks Nick. I did try that, but couldn't get the FTP with Sharefile to work. I will try again, maybe some coffee will help

**Comment by ncw** [comment]
@NicholasBoccio if you can't get the FTP to work with Sharefile then make an issue and I'll see if I can fix it. Is there a free account available?

**Comment by NicholasBoccio** [comment]
How can I securely provide you credentials?

**Comment by ncw** [comment]
@NicholasBoccio you can email me at nick@craig-wood.com.  If you want to PGP it you'll find my key in the keyservers.

**Comment by ncw** [comment]
@NicholasBoccio make sure you put "rclone issue 1543" in the title - I get a lot of email about rclone!

**Comment by benyanke** [comment]
Hello,

We use sharefile extensively as well - has there been any updates with this?

**Comment by ncw** [comment]
There is the [FTP](https://rclone.org/ftp/) option and there is also now a [WebDAV](https://rclone.org/webdav/) option which appears to be [supported by sharefile](https://support.citrix.com/article/CTX207863) - can you try those @benyanke ?

**Comment by benyanke** [comment]
I certainly will!

**Comment by joshzitting** [comment]
Any progress on this? I would love to hear how well it works?

**Comment by bobdroog** [comment]
Over the past few years we have been using ShareFile by Citrix (https://www.citrix.com/lp/sharefile/) as well. As of lately they have changed pricing on unlimited storage to $10/mo/user. We'd wondered if Citrix would ever make a Linux tool that we could use to sync our encrypted backups—so I called them. They said that they will "most likely never make one" as they are more focused on the Windows tools and products they offer. We have tested everything they support (eg. their windows sync tool and drive mapper, ftp, ftps, webdav, and their SF API v3).

I'd like to note that our account file max size limit is set to 100GB files (for some it's 10GB but you can get this changed by contacting them). All accounts come with unlimited API hits.

After testing all of these ways we've learned a lot about limitations and complications. Using certain services, files disappear after upload and takes a while before it shows up. Everything is middle-ware/proxy and loses data on uploaded files.

Here are a few results of what we found most successful:
- QNAP App (max 10GB files) https://appcenter.qnap.com/eng/qpkg/overview/HybridBackup
- FTP/FTPS (max ??GB files) https://support.citrix.com/article/CTX207859
- WebDAV (max 2GB files) https://support.citrix.com/article/CTX207863
- Citrix SF v3 API (max size set by account limitation 10GB or 100GB files)
https://api.sharefile.com/rest/index/start.aspx
- Web App (https://yourname.sharefile.com) uses the API 
(max size set by account limitation 10GB or 100GB files)

On top of all this, you have 18 hours to finish each file upload before it times out and disappears (through any of these services).

Our tests have shown that FTP is the worst. Any file size would fail randomly and/or not show up in your account. Download works great, though.

WebDAV is really slow to connect to, but seems to work OK with files under 2GB. We tested this with rclone and all files would upload twice as the first one couldn't get confirmed in time because it takes a bit before the file shows up in your account. The larger the file, the longer it takes before it can be confirmed in your account.

This is where we dropped all services and focused on the direct SF API they provide (see the ShareFile REST URL above). We created a Windows CLI tool (using https://github.com/citrix/ShareFile-NET) to upload files manually through this API—and this worked greatly! We tried small, medium, and large files—all the way up to 100GB. All files were delivered directly into the account and could be confirmed. Therefore, the API supports the largest file uploads at greatest speeds while avoiding their midway proxy.

After this successful test, @D3lta made a Linux tool using NodeJS and these have the same results as the Windows CLI tool above, hooray! However, this would require a lot of additional development for it to become a functional sync tool.

With all of this being said, we'd **LOVE** to see rclone become integrated with Citrix ShareFile's SF v3 API.

**Comment by ncw** [comment]
@bobdroog thank you very much for your testing - very interesting.

> With all of this being said, we'd **LOVE** to see rclone become integrated with Citrix ShareFile's SF v3 API.

It looks like from the above a native sharefile backend would be the best performance solution.

Is there any way of getting a free account on a sharefile?

**Comment by bobdroog** [comment]
Hi @ncw - Yes, integrating rclone with their REST API is definitely the best way to go for best performance and support for large file sizes.

They offer a 30-day trial, would that be enough time?
https://www.sharefile.com/trial

ShareFile API
https://api.sharefile.com/rest/index/start.aspx

**Comment by ncw** [comment]
> They offer a 30-day trial, would that be enough time?
> https://www.sharefile.com/trial

To keep a backend working I run daily integration tests, so I'd need permanent access to an account.

**Comment by bobdroog** [comment]
> To keep a backend working I run daily integration tests, so I'd need permanent access to an account.

Let me see what I can do. Will report back!

**Comment by bobdroog** [comment]
@ncw - I called them, they said they no longer have a team that would help with these kind of requests.

The only two ways right now to get an account is to purchase one or become a Citrix SaaS referral partner. I have applied to become one (through my business) and have been approved. 

I just applied for the ShareFile demo account/license a few moments ago.
> Please complete the form to receive your ShareFile account for 1 year. Your Advocate ID can be found in the welcome email you received with this link. Please allow 3 business days for processing.

> We have received your request. Please allow 3 business days for processing.

Will report back when I get a response from them.

**Comment by bobdroog** [comment]
Hey @ncw you've got mail!

**Comment by ncw** [comment]
Here is a first beta of the backend

https://beta.rclone.org/branch/v1.49.0-012-g86bdb60e-sharefile-beta/ (uploaded in 15-30 mins)

I think it is feature complete.  It passes the backend integration tests, but it probably has bugs so testing appreciated!

**Comment by bobdroog** [comment]
@ncw - You are the best! @D3lta and I will start testing right now.

**Comment by ncw** [comment]
> @ncw - You are the best! @D3lta and I will start testing right now.

Excellent :-)  Can you email me at nick@craig-wood.com - I've lost your email address!

**Comment by ncw** [comment]
Here is the next beta!  It supports
- multipart uploads
- streaming uploads
- choosing the root, eg `--sharefile-root-folder-id top`

It should be complete now and it passes all the integration tests.

https://beta.rclone.org/branch/v1.49.0-012-gfe64f0ef-sharefile-beta/ (uploaded in 15-30 mins)

**Comment by bobdroog** [comment]
This is fantastic! Thank you so much for being on top of it! We will start testing it with larger files (up to 100GB) now.

**Comment by bobdroog** [comment]
Thank you @ncw! We will continue to test and report any found issues for improvement.

**Comment by Danelem** [comment]
Just asking before doing more research about it.

I noticed that when getting a file from the remote to my local computer, it takes sometimes one minute before the actual download starts. When adding the --progress flag, I can see that rclone sees the files, but is not downloading them. After some time (between 30 and 90 seconds), it starts downloading the file normally.

I don't see any log message about this. Is this happening with someone else?

I want to try with a different account, to see if it's related to this, or if they throttle the download for some reason.

Upload works normally.

**Comment by ncw** [comment]
@Danelem I managed to see this once for a file I hadn't downloaded for a while then the next time it was quick - as if the file was being fetched from cold storage or something like that.
