### ISSUE TITLE
check/cryptcheck results

### ISSUE THREAD

**Issue by qweasdzxc787** [rclone/rclone#1572]
Would be great if check/cryptcheck would print out the list of files that differ at the end when the results are printed, even to a separate file through a command line option so the results could be very useful. Right now it takes a lot of work to reparse all the results to pull out a list of files. IMO it should be a notice level message so even if you have verbosity turned down you would see this list.

**Comment by ncw** [comment]
I've been wondering whether check should output its results to stdout instead of the log - I think that would make more sense.

It could output a sort of diff `+` for files in source but not in dest, `-` for files in dest and not in source

So

+ potato
- sausage

that sort of thing.

**Comment by jahio** [comment]
Stumbled on this issue this afternoon while looking for something else and the following concept popped into my head. I'm offering it here in hopes that it might spark an even better idea and feature amongst the `rclone` development team.

My biggest "thing" with `cryptcheck` (never used `check` but I assume they're basically the same minus the crypt to get a checksum) is that it can tell me _that_ something changed, but not _what_ changed, _in what way_ it's different, and even if it did there's no way to **easily** automate the output of that data in a _machine-readable_ yet (hopefully) human-friendly format.

Ideally, I'd have some way to tell it, "when you run, if you find something's off at the remote, put info about it in a log file or on the screen".

Now, if something is different between my source and the remote - encrypted or not - I want to know specifically _what exact file_ isn't right on the remote (my use case is `sync`, unsure about other use cases). Furthermore, I want to know the critical data _about_ that file, but obviously not its contents.

To me, I'd want to know at minimum:

+ Name of the file that failed the check on the remote;
+ Its size in bytes (future refinement: output in kb, mb, gb based on user args/env vars?)
  + At my source (what I'm using `sync` _on_); and
  + At the remote (where it's sync'd _to_)
+ The file's checksum:
  + At my source
  + At the remote
  + And the way in which the checksum was computed at each (e.g. `sha1` or `md5`)
+ And the file's last modified time (mtime)
  + At my source
  + At the remote
  + Perhaps in seconds since the UNIX epoch in UTC (I forget, is UNIX epoch already UTC?)
   so I can easily compare the two visually

The first problem would be, does the user want it at `STDOUT` or perhaps the output should go in a specified file? If you've got two or three file differences `STDOUT` is fine, but what if there are _thousands_?

`RCLONE_LOG_CHECK_FAILURES="STDOUT|<path>"`

+ If it's not `STDOUT` (which is obvious what to do then), try to write output to location
   specified in the value (if any); so `RCLONE_LOG_CHECK_FAILURES="/$PWD/failfiles.json"`
   for example
+ From the path name, try to infer the file type the user wants. If ending in `.json`, render JSON
   output like the sample I have below. If `.csv`, do the same for CSV. Anything else, or missing
   an extension, make it a plain text list.
+ Allow `RCLONE_LOG_CHECK_FAILURES_FORMAT="text|json|csv"` to override that extension
   so the user can manually specify the kind of output they want (what they'll script against)

Some examples of what's in my head for the output types: 

`text` would just be a plain-text default that _only lists the filenames_ with the name of the
remote that was checked against:

```
crypt-someremote:/db/abc.sqlite
crypt-someremote:/www/img/big.svg
crypt-someremote:/redis/important.rdb
```

> Sometimes you don't care what's at the remote, if it ain't what's local it's wrong, so redo
> the sync operation. This is enough for that.

`json` I could see this one going two different ways:

+ If the type/extension is `json` (spelled out), _human-friendly_ with whitespace; or
+ if the type/extension is just `jsn` or `js`, same thing but with whitespace removed.

An example of human-friendly JSON output might be...

```json
{
  "files":
  [ 
    {
      "/db/abc.sqlite": 
      { 
        "crypt-someremote:/": 
        { 
          "checksum-value": "...", 
          "checksum-type":  "md5",
          "size":           "2938228281818",
          "last_modified":  "<unix epoch int utc>"
        },
        "/path/on/system:":
        {
          "checksum-value": "...",
          "checksum-type":  "md5",
          "size":           "2938228281333",
          "last_modified":  "<unix epoch int utc>"
        }
      }
    },
    {
      "/www/img/big.svg":
      {
        "crypt-someremote:/":
        {
          "checksum-value": "...", 
          "checksum-type":  "sha1",
          "size":           "867530982182",
          "last_modified":  "<unix epoch int utc>"
        },
        "/path/on/system":
        {
          "checksum-value": "...", 
          "checksum-type":  "sha1",
          "size":           "86753098112",
          "last_modified":  "<unix epoch int utc>"
        }
      }
    },
    {
      "/redis/important.rdb":
      {
        "crypt-someremote:/":
        {
          "checksum-value": "...", 
          "checksum-type":  "md5",
          "size":           "1355255553326867530982182",
          "last_modified":  "<unix epoch int utc>"
        },
        "/path/on/system":
        {
          "checksum-value": "...", 
          "checksum-type":  "md5",
          "size":           "1355255553326867440292182",
          "last_modified":  "<unix epoch int utc>"
        }
      }
    }
  ]
}
```

`csv` We're all pretty sure what CSV is, but one note: if doing CSV output, _maybe_ it should default
to `CRLF` line endings so that it can be imported into Excel and other Windows-world tools? That's
of course if going to a file, if to `STDOUT` that's irrelevant. Just a thought to increase the total number
of things `rclone` can interop with.

From a scripting perspective, this would be really useful since we could save that output to a file or trap it based on some regex parsing from STDOUT (maybe insert a separator of like 4 blank new lines or something?), read that data, then do other things with those files with our programming/scripting language of choice.

A feature like this could be _hella_ useful in a DevOps/automation context. Food for thought! 😃

**Comment by ncw** [comment]
@jahio - thanks for your ideas

I think the idea of `--csv` or `--json` output is a good one.

A good start on this would be designing the output for the normal case.

I'll just note this

> Ideally, I'd have some way to tell it, "when you run, if you find something's off at the remote, put info about it in a log file or on the screen".

If you use the `-v` flag you'll get the files which are different in the log file, but as the OP noted this is difficult to parse

**Comment by jahio** [comment]
Thanks for the positive feedback, @ncw! Happy to have moved the project forward in some small way. If I were more Go-savvy I'd take a crack at this, but alas I just don't have the experience to contribute anything that would be _useful_ at this point (and not a lot of free time to learn right now). If that changes and this is still open, I'll see what I can do about lending you hand here.

> A good start on this would be designing the output for the normal case.

Now _this_ I might be able to do. What kind of format do you want this in? I'm not well versed enough in Go to give you a code sample with variables, etc., but is there another format I could give this to you in? Maybe (if it's not a bad practice) something like `<%= erb_templates_in_ruby =>` I could quickly grok?

Thanks again for your response, and for a great tool! I have it running right now as I type this, in fact. 😃

**Comment by ncw** [comment]
> What kind of format do you want this in?

Something easy for humans to read, but parsable with a bash script

It should show something like

filename, status

Where status can be
  * missing in remote
  * missing in local
  * sizes differ %d vs %d
  * hashes differ %s vs %s
  * error reading

Ideas appreciated!

**Comment by ivandeex** [comment]
Related to https://github.com/rclone/rclone/issues/157

**Comment by ncw** [comment]
`rclone cryptcheck` (and `rclone check`) now have these flags

```
      --combined string         Make a combined report of changes to this file
      --differ string           Report all non-matching files to this file
      --error string            Report all files with errors (hashing or reading) to this file
      --match string            Report all matching files to this file
      --missing-on-dst string   Report all files missing from the destination to this file
      --missing-on-src string   Report all files missing from the source to this file
```

Which I think satisfies this issue.
