### ISSUE TITLE
Highly destructive actions require confirmation

### ISSUE THREAD

**Issue by lucasgonze** [rclone/rclone#1574]
#1573 See https://forum.rclone.org/t/unexpected-deletions-in-gdrive/3421 for user-level discussion. This issue is about rclone itself.

A new user just getting to know rclone may naturally explore the sync command. A typical such user will try out the arguments, using trial and error until they are just right.

For example, they may do this:
rclone sync to from

And of course that won't work. The order of the arguments is:
rclone sync from to

However, there is no second chance. The first command will have wiped out the "from" directory. 

- The deletion is permanent. There is no undo or trash can. 
- The deletion is recursive. If you are looking to sync from the root of your remote directory, everything is gone.
- The deletion is massive. Thousands or tens of thousands of files can disappear.
- The deletion includes git history, so no restore will be possible.

Suggested fix: 

1. A prompt should ask the user to confirm they want to delete the target permanently 
2. A -f flag should suppress the prompt
3. Consider an undo feature

**Comment by lucasgonze** [comment]
Let me also add a personal note.  Are you actually not aware that extreme data destruction requires at least a trivial amount of caution? How is it physically possible to be that out of it? 

Does rclone create any kind of log, at least? Is there a record of the remote URLs nuked?

**Comment by 9182bfe2d3832daf3774c86a85e5a305** [comment]
I can't tell if it's you that had the issue, but https://support.google.com/drive/contact/missing_items might be of help, if you're on gsuite you can even roll back deletions yourself if they're less than 30 days old.

**Comment by lucasgonze** [comment]
To roll back deletions you have to be an enterprise customer. I started up a trial subscription. However the restore feature has not worked. It is possible that if I can get a URL to one of the deleted items it would help. That's why ask I ask about a log.

**Comment by 9182bfe2d3832daf3774c86a85e5a305** [comment]
You can't get url logs unless you turn on --dump-headers I believe, rclone doesn't log anything without that I know of being explicitly told to. Are you sure it  wouldn't be in your browser history though?

**Comment by ncw** [comment]
@lucasgonze I'm very sorry to hear about your problems with rclone.

The sync command is dangerous - note the bold **important** [in the docs](https://rclone.org/commands/rclone_sync/)

> **Important:** Since this can cause data loss, test first with the --dry-run flag to see exactly what would be copied and deleted.

`rsync` which `rclone` is modeled on has the same behavior and `rsync` is the reason rclone works like it does.

> Consider an undo feature

rclone has several features which can help here, one of which is `--backup-dir` which stores any deleted files in a directory of your choice.

There is also a `--drive-use-trash` feature which stores deleted items in the trash.

I don't think either of those would have helped in your case though.

When you did

> rclone sync to from

Was `to` empty at that point? I could put in a test for that.

**Comment by leonelwilliams** [comment]
Have you tried [this method](https://support.google.com/a/answer/6052340?hl=en) which appears to be available to all tiers?

**Comment by 9182bfe2d3832daf3774c86a85e5a305** [comment]
That method is unfortunately GSuite only, it's on the GSuite admin help section and the instruction require logging in to an admin panel.

**Comment by leonelwilliams** [comment]
Ah! I must have missed that he wasn't a G Suite customer - my mistake.

**Comment by Qwatuz** [comment]
@ncw what are your thoughts on having `--drive-use-trash` as default for sync commands? Or using it as default for any rclone command that has the capability to delete files, e.g move, sync.

I think having a trash bin on google drive and not using it is such a shame - it's a great safety net!

**Comment by 9182bfe2d3832daf3774c86a85e5a305** [comment]
I'm not sure it's a great idea to use `--drive-use-trash=true` by default, because you don't gain any space by moving things to the trash in gdrive. Personally on all environments where I use rclone I export the enviroment variable `RCLONE_DRIVE_USE_TRASH=true` which makes deletion operations pretty safe, but for those with limited storage this might be undesirable.

**Comment by Qwatuz** [comment]
The reason for using drive trash is to be a safety net. Lots of cloud services are unlimited so this is not a problem. If people are limited, they could easily turn off trash.

**Comment by lucasgonze** [comment]
Compare the downside of not using drive trash to the downside of using it.

Downside of using it by default: user has to empty trash sooner than expected 

Downside of not using by default: massive accidental irrevocable data loss for newbies

**Comment by Qwatuz** [comment]
> Downside of using it by default: user has to empty trash sooner than expected

No. The trash is unlimited, just like your google drive.

There is literally no downside to using the trash as default that I can think of.

**Comment by 9182bfe2d3832daf3774c86a85e5a305** [comment]
>No. The trash is unlimited, just like your google drive.

The vast majority of users don't have unlimited google drive space.

**Comment by lucasgonze** [comment]
If Trash is not unlimited, the user can either empty it or can set the flag to not use it. Either way this is not a big problem compared to accidental permanent deletion.

**Comment by breunigs** [comment]
I did not see this mentioned yet: "warn on first use". This way rclone can be backwards compatible (default "already warned" to true, explicitly set it to false when creating a new config file).

**Comment by calisro** [comment]
My opinion is that the only way here is to either leave it as is or have a 'warn on first use'.  Personally, I doubt a 'warning' will prevent anything.  While **I can sympathize** with people losing their data, it is a matter of reading the documentation before using commands.  There are many linux commands that can wreck systems.  dd, cp, rm, etc.  Even 'cat' can be dangerous or 'echo' when you sudo echo/cat > /dev/sda.  

Again, just my opinion.

**Comment by sbarrie1980** [comment]
Just stopping by to say that this bug (yes it's a bug, no well-designed software would permanently destroy entire folders recursively, especially end-user software) caused me to lose my whole home folder simply by running `rclone sync GDrive:documents .` from ~. But I'm sure you'll just see this as another dumb person who didn't spend two hours reading the manual, the technical documentation, and going through all the flags, but instead expected the program to have sane defaults. Yeah, how absurd it is to assume that a backup tool would treat user data a bit more carefully.

**Comment by dr-mcgillicuddy** [comment]
Anything destructive should have a y/n by default. Period.
I don’t know how this is still an issue at version 1.51

The default methodology should be the safest operation, and only with good reason should safeguards against data loss be removed.

**Comment by sbarrie1980** [comment]
> Anything destructive should have a y/n by default. Period.
> I don’t know how this is still an issue at version 1.51. This has been open for almost 3 years.
> 
> The default methodology should be the safest operation, and only with good reason should safeguards against data loss be removed.

It's still an issue because it's only a problem for inexperienced users, which the developers of this program don't care about. Hence the downvotes.

**Comment by lucasgonze** [comment]
One possible fix is to consider rclone a highly destructive program -
well-intentioned malware - and seek to get it shut down through abuse@
channels.

**Comment by dr-mcgillicuddy** [comment]
> it's only a problem for inexperienced users
Quite the opposite.

The more one uses rclone, the more one is likely to encounter this issue.

Moreover, the more complex one’s usage, the longer command line input is required—because rclone does not allow a user to define default flags. They must be entered at run, which is fine and not an issue in and of itself; it simply compounds this one...

That is to say, the more advanced one’s usage is, the longer the command line input is likely to be, and by definition, the longer the input, the more likely mistakes will occur.

By not asking for confirmation, rclone by definition assumes that users want to be as destructive as possible, all the time. Which is an odd and inconsistent assumption to make for a utility designed around cloud storage...

**Comment by animosity22** [comment]
> One possible fix is to consider rclone a highly destructive program - well-intentioned malware - and seek to get it shut down through abuse@ channels.

It's probably best to figure out constructive things to add to the conversation as there are many tools that delete, format, and "rm -rf *" has been around for my lifetime in the Unix/Linux world. 

There have been a few suggestions in terms of aborting if the numbers are greater than X and a few of those would be great to discuss and see if we can get added.

I had a sysadmin perform 4 clicks and delete a running VM last week so there is only so much one can do as well.

**Comment by dr-mcgillicuddy** [comment]
>there are many tools that delete, format, and "rm -rf *" has been around for my lifetime in the Unix/Linux world.


True, but rm is *only* destructive, and there is no other reason to call that particular utility. It also obeys permissions, which rclone purge doesn’t do for many buckets, (not rclone’s fault).

However most buckets will also ask for confirmation when deleting through a web interface, and most (all?) desktop environments will do the same when using FUSE mounts

Rclone’s CLI stands alone in being destructive by default, with no safeguards of any kind (permissions, prompts, ability to abort, etc.)

> I had a sysadmin perform 4 clicks and delete a running VM last week so there is only so much one can do as well.

Hopefully he had used rclone to copy an image if it to the cloud :)

**Comment by calisro** [comment]
> `However most buckets will also ask for confirmation when deleting through a web interface`

That's not quite correct.  Most buckets/remotes rely on their trash feature instead.  Google drive is a good example.  When something is deleted, it moves it to the trash without confirmation.  This is also the same behavior that rclone uses for the remotes unless that is specifically disabled.  If I delete a file on drive, it trashes it.

> most (all?) desktop environments will do the same when using FUSE mounts

This also isn't correct.  When a fuse mount is mounted, it behaves in the **same way** as a regular file system unless mounted with special flags such as 'read only'.  In a command line interface, that means that a 'rm' or a file or 'rm -rf' on a directory deletes the objects on linux.  Windows will warn.  This is operating system specific.

> Rclone’s CLI stands alone in being destructive by default, with no safeguards of any kind (permissions, prompts, ability to abort, etc.)

rclone defers that to the remote.  Most remotes have their own safeguards.  

I think this issue is more centered around concerns with the 'local' filesystem and perhaps that is the best place to concentrate a discussion rather than broadening the scope to all remote types.

**Comment by animosity22** [comment]
> True, but rm is _only_ destructive, and there is no other reason to call that particular utility. It also obeys permissions, which rclone purge doesn’t do for many buckets, (not rclone’s fault).

That was just an example of a command as I'm sure I can list many, many commands that are destructive as I've seen people corrupt a disk with a bad fdisk command on the wrong volume. I've run a dd before on my Mac and typed the wrong /dev/disk and wiped my system. There are countless ways to do things.

I'm more on the realm with @calisro and the focus should be on local as people 'tend' to destroy / remove / delete things locally so a little protection might help.

On any Linux system I ever use, the first thing I do is remove all the "-i" aliases so I can freely delete and copy things without being bothered. The point there is I made the choice to do that as it was a layer of protection I removed.

**Comment by ncw** [comment]
OK here is a practical suggestion...

I don't want to break backwards compatibility with the 1000s of scripts rclone is running.

However those probably all have a config file....

Perhaps if `rclone config` is run without a config file it could ask the user whether they want to engage interactive mode for deletes by default saying it is recommended for beginners.

There is an interactive mode PR https://github.com/rclone/rclone/pull/4083 which needs a bit more work.

Rclone could store whether the user wants interactive mode by default in the profile section of the config file (which I haven't built yet).

What do you think? That should keep backwards compatibility but protect new users provided they run `rclone config` which all the instructions tell them to do.

**Comment by calisro** [comment]
Should we then also have a short flag (-F?  -y?, etc )  to not prompt that interactive question if an advanced user is deliberately using rclone without a config? Unfortunately this change will impact anyone using rclone solely for local operations.  At least that is likely a smaller use case than actual remotes.

**Comment by ncw** [comment]
> I think its a good proposal. Should we then also have a short flag (-F? -y?, etc ) to not prompt that interactive question if an advanced user is deliberately using rclone without a config? Unfortunately this change will impact anyone using rclone solely for local operations. At least that is likely a smaller use case than actual remotes.

I was thinking we only ask the user when they are using `rclone config` - an advanced user using rclone without a config file won't be asked the question at all.

**Comment by islandcmd** [comment]
i'm the one who posted #4298 a few days ago and was linked to this discussion.

i tried to use rclone to back up my latop and ended up losing everything. i was informed that i got the source and destinations paths the wrong way round when trying to back up, which is a simple mistake anyone can make, even after reading all the docs.

why does such a simple mistake destroy all day permanently? it shouldn't. many people have lost their data because of this. and i don't think it's useful to unsympathetically tell people they should have backed up their data when they're using a back up tool. that's the whole point of rclone.

**Comment by calisro** [comment]
> I was thinking we only ask the user when they are using rclone config - an advanced user using rclone without a config file won't be asked the question at all.

I see!  Yea that's better.  I did a search through the forums and issues for people who have done this and each of them had just created a config file and was using a remote.   If they could have set that at the beginning of creating their config they may not have clobbered their remotes/locals.  @islandcmd 's issue also would have been prevented.

An additional check for "is the source location empty" might be beneficial as well.  I can't think of a good use case to sync an empty remote to any other remote. :)

> i don't think it's useful to unsympathetically tell people they should have backed up their data
No one is being unsympathetic. We've all been in situations like this where we did something and the hairs stood up on our arms as we realize what just happened.

**Comment by ncw** [comment]
In https://github.com/rclone/rclone/pull/4083 I'm just about to merge a PR which
- implements `-i` / `--interactive`
- promotes its use **everwhere** in the docs where `rclone sync` is mentioned

I'd appreciate it if you'd take a look at it (the docs especially) @calisro and @animosity22 

There will be a beta here in 15-30 mins if anyone wants to give it a go and give feedback

https://beta.rclone.org/branch/v1.52.0-034-g839baf96-test-beta/


Here is me testing it out by getting the source and destination the wrong way round on the rclone source code

```
$ rclone sync -i /tmp/source/ .
rclone: delete "vendor/github.com/pengsrc/go-shared/log/event.go"?
y) Yes, this is OK (default)
n) No, skip this
s) Skip all delete operations with no more questions
!) Do all delete operations with no more questions
q) Exit rclone now.
y/n/s/!/q> q
2020/06/05 17:15:14 NOTICE: Quitting rclone now
```

This I see as the first step. Once we have this merged then I can implement a beginner mode in `rclone config` which forces `-i` on.

**Comment by ncw** [comment]
I've merged the `-i` PR which I think is a good first step...

**Comment by ivandeex** [comment]
This will be fixed by config profiles like
```
[:default:]
interactive=true
```

**Comment by ivandeex** [comment]
@ncw 
Request for comments:

In addition to single `--interactive` flag introduce a multi-variant flag (a concrete name is TBD): `--confirmation`. Possible states:
- `off` (`false`) or `batch` - destructive operations proceed automatically
- `on` (`true`) or `interactive` - destructive operations require `y/n` on terminal, or abort if stdin is not a tty
- `auto` - same as `on` if stdin is tty, `off` otherwise

Then we can:
- make `auto` the default
- make `--interactive` a shortcut for `--confirmation on`
- introduce flag `--batch` or `--force` for use in rclone shell wrappers and pipelines (a shortcut for `--confirmation off`)
- optionally: interactive mode will fallback to `--dry-run` instead of just aborting, if stdin is not a tty or when user answered `no` (or add a new confirmation variant for that)
- optionally: when _install.sh_ finds no existing _rclone.conf_, create a brand new one with profile section 
```
[:default]
confirmations=on
```

Does this strike balance between batch and interactive usage?
Is forum or new issue a better place to discuss the idea?
What do you think?

**Comment by mrsilva** [comment]
I can't understand some of the unfortunate comments above, rclone is well documented and it will do what you tell it to do.

Having said that I do believe rclone could be improved with a 'delete all' protection flag. Something like:

**--delete-protection**

Which when used together with the **sync** command would only protect local files from total destruction:

IF remote root folder doesn't exist OR is empty, DON'T touch local files

Thanks

**Comment by ivandeex** [comment]
Closed after 1 year of total inactivity.
