### ISSUE TITLE
--size-only switch does not work

### ISSUE THREAD

**Issue by marinaz28** [rclone/rclone#1610]
Looks like "--size-only" flag does not work, at least "sometimes". You can see test run below. Source is Amason Cloud Drive, destination - Hubic. Win32 version 1.37 (same with 1.36). You can see, that file "kaka.xml" not copied. Same result is with 'copy' and 'copyto' commands. 

>rclone.exe version
rclone v1.37

>rclone.exe lsl HuBiC:default\test1
     3589 2017-08-18 11:03:58.301000000 kaka.xml
     3988 2017-08-18 11:03:59.498000000 kaka2.xml

>rclone.exe lsl ACD:\test2 
    10768 2017-08-18 10:23:21.407000000 kaka.xml
     3988 2017-08-18 10:23:16.099000000 kaka2.xml
    10768 2017-08-18 10:23:17.955000000 kaka3.xml

>rclone.exe sync ACD:\test2 HuBiC:default\test1 -u --no-check-certificate --delete-excluded --size-only --log-level DEBUG --log-file log004.log

>rclone.exe lsl HuBiC:default\test1
     3589 2017-08-18 11:03:58.301000000 kaka.xml
     3988 2017-08-18 11:03:59.498000000 kaka2.xml
    10768 2017-08-18 10:23:17.955000000 kaka3.xml

------- log file of sync operation here:
2017/08/18 11:18:09 DEBUG : rclone: Version "v1.37" starting with parameters ["rclone.exe" "sync" "ACD:\\test2" "HuBiC:default\\test1" "-u" "--no-check-certificate" "--delete-excluded" "--size-only" "--log-level" "DEBUG" "--log-file" "log004.log"]
2017/08/18 11:18:20 DEBUG : Hubic: Got swift credentials (expiry 2017-08-18 12:22:16 +0200 +0200 in 2h3m55.9931257s)
2017/08/18 11:18:24 INFO  : amazon drive root 'test2': Modify window not supported
2017/08/18 11:18:27 INFO  : Hubic Swift container default path test1/: Waiting for checks to finish
2017/08/18 11:18:27 DEBUG : kaka.xml: Destination is newer than source, skipping
2017/08/18 11:18:29 DEBUG : kaka2.xml: Destination is newer than source, skipping
2017/08/18 11:18:30 INFO  : Hubic Swift container default path test1/: Waiting for transfers to finish
2017/08/18 11:18:41 INFO  : kaka3.xml: Copied (new)
2017/08/18 11:18:41 INFO  : Waiting for deletions to finish
2017/08/18 11:18:41 INFO  : 
Transferred:   10.516 kBytes (211 Bytes/s)
Errors:                 0
Checks:                 2
Transferred:            1
Elapsed time:       50.9s

2017/08/18 11:18:42 DEBUG : Go routines at exit 12
2017/08/18 11:18:42 DEBUG : rclone: Version "v1.37" finishing with parameters ["rclone.exe" "sync" "ACD:\\test2" "HuBiC:default\\test1" "-u" "--no-check-certificate" "--delete-excluded" "--size-only" "--log-level" "DEBUG" "--log-file" "log004.log"]

**Comment by breunigs** [comment]
You specified `-u`, which is `--update` which says "Skip files that are newer on the destination". This explains why rclone skipped `kaka.xml`. To get what you want, it's probably enough to remove `-u` from your command.

It does seem a bit like these two settings should exclude each other. I started off with making a table for, which feature has which implicated. But there are a lot of flags and they behave slightly different depending on circumstances. The algorithm works roughly like below. It's pseudo code to give you an idea. An exclamation mark means a decision has been reached, otherwise read on:
```
destination missing?
  copy!

# at this point we might need to overwrite
if --ignore-existing
  skip!

if --ignore-times
  overwrite!

if --update and…
  …destination newer? 
    skip!
  …destination older?
    overwrite!
  …roughly the same mod time?
    same size?
      yes: skip!
      no: overwrite!

if --size-only and…
  same size?
    yes: skip!
    no: overwrite!

same size?
  yes:
    continue below
  no and --ignore-size:
    continue below
  no:
    overwrite!

if --checksum and…
  checksums different:
    overwrite!
  checksums match:
    skip! # this actually logs "sizes match", even with --ignore-size!
  no hash in common:
    skip! # this actually logs "sizes match", even with --ignore-size!

remotes support mod time?
  no: skip!

same mod time?
  yes: skip!

checksums different?
  overwrite!
no hash in common?
  overwrite!

# (special handling when just the mod time is different)

skip!
```

Even I am surprised by this immense level of configuration options. Some observations:
* `--ignore-times` kind of works as a "copy everything" mechanism, which is a bit surprising. It also makes a lot of other options obsolete.
* `--update` trumps `--size-only` and ignores `--check-sum`. A bit less "powerful" than ignore times though.
* when two remotes have no hashes in common and mod time cannot be checked:
** and `--checksum` is given: the files will be considered equal
** it is not given: the files will be considered different
** a bit surprising that setting `--checksum` makes it more lenient if the checksum is missing!

I wonder if this can be improved, so that the configuration would be more straight forward without losing any settings. I guess we could at least warn or fail if `--update` and `--ignore-times` and some "lower" parameter are given. Keeping backwards compatibility will make any changes quite challenging though…

**Comment by animosity22** [comment]
This looks to be answered. If you have any new questions, please feel free to post on the forums.
