### ISSUE TITLE
Verify password

### ISSUE THREAD

**Issue by PaulWoitaschek** [rclone/rclone#1615]
How is it possible to verify an encrypted volume? I backed up my data and now I want to check if the password I wrote down works for the files I encrypted (in case of a data loss).

**Comment by naeloob** [comment]
Just create a new Crypt remote with that password.
If you can see the directories with rclone lsd NewCrypRemote: it's fine.

**Comment by PaulWoitaschek** [comment]
It would be great if in setup, the script would ask for the password after entering for confirmation.

**Comment by breunigs** [comment]
I guess this case is an oversight, since rclone already requires the password twice in some places. Would you like to provide a patch?

**Comment by PaulWoitaschek** [comment]
I couldn't verify the password.

I added a new crypt remote

* n
* pwtest
* 5
* remote:gdrive
* 2
* y
* entered password twice
* n
* y

Now I can see that remote in the list, but when I type

`rclone lsd pwtest`

It shows the error:
> 2017/09/10 17:52:55 Failed to create file system for "pwtest:": failed to make remote "remote:gdrive" to wrap: didn't find section in config file

Does that mean that I entered the wrong password?

**Comment by ncw** [comment]
It means you entered the wrong remote, `remote:gdrive`.  Put in the path to your actual encrypted files

**Comment by PaulWoitaschek** [comment]
Where can I find the path of my encrypted files? I only have the decrypted files in on my computer.

**Comment by qaskai** [comment]
Hi, I’d like to make a patch for this problem. I’m new to open source and rclone, so if I run into any problems I won’t be able to deal with on my own, should I ask for help here or create a topic on the forum?

**Comment by ishuah** [comment]
Hi @qaskai 
Thanks for choosing to contribute to rclone!
If you have any questions or points you need clarification on you can post them here.
cc @ncw

**Comment by qaskai** [comment]
Hi guys,
Firstly, I'd like to apologize for taking so long - due to an unexpected event I wasn't able to begin the work until today.
Now, I'm not really sure I understand the issue. At first I thought the job was to add a verification - typing the password two times - in the setup of an encrypted remote. Since that is the current behavior, I reason that the problem lies elsewhere. 
Should I add a new option in rclone config script that will enable users to check passwords for remotes (rclone config --> type number of new check password function --> choose the encrypted remote for which the check will be preformed --> type password --> output OK/wrong)? Or maybe should every operation on encrypted remotes require typing out it's password?
These are just my ideas for password check, please let me know what this issue required originally. If someone could provide an example of current and desired behavior of the script with regard to this problem, I'll be really grateful!
Thanks, qaskai

**Comment by ncw** [comment]
@qaskai wrote:
> Now, I'm not really sure I understand the issue. At first I thought the job was to add a verification - typing the password two times - in the setup of an encrypted remote. Since that is the current behavior, I reason that the problem lies elsewhere.

I think there is some confusion on this issue!  I think that @breunigs thought that adding a verification was sufficient, however as you pointed out there is one already.

@naeloob 's suggestion is the right one to really check your password can decrypt the data.

So I'm not sure exactly what we are doing on this issue. It is possible to verify that a password typed in matches that in the config file - we could do that in the config setup somewhere, but I think it is of limited interest.

**Comment by PaulWoitaschek** [comment]
I thought about a verification command where you can put in your target and password and an optional amount of files to verify and it just checks if it can decrypt all files.
(maybe with an optional parameter to specify how many files there are to check)

I don't really get how rclone works but I assume the encryption is per-file based, so that's what my suggestion is built upon.

**Comment by ivandeex** [comment]
Closing after 3+ years of inactivity
