### ISSUE TITLE
Instructions are unclear: '--files-from'

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#1620]
&nbsp;&nbsp;&nbsp;&nbsp;It seems to me that the instructions for the `--files-from` command (if 'command' is the word I want) are rather unclear (and this counts as at least something like a bug). Does a file cited by `--files-from` have to include items that are only individual files, or (1) do wildcards work? (2) What about specifying a folder - would that work?

From my experience, the answers to both 1 and 2 are: no. It seems to me that those answers are both somewhat unexpected and also unhelpful. They are unhelpful, in that why can one net specify folders or at least wildcards?

Or, hold on, am I after `--include-from`? I find all of this very unclear, and I am unsure that the fault is wholly mine, though I do understand and appreciate that this is all gratis software . .

**Comment by ncw** [comment]
Yes [--files-from](https://rclone.org/filtering/#files-from-read-list-of-source-file-names) is just a list of file names.

If you want to include wildcard then you want --include-from.  Note that you need `dir/**` to include a directory and everything under it.

I'd appreciate feedback on the docs so if you have an idea how they can be improved then send me a PR or jot them down in this issue and I'll patch them in to the docs.

**Comment by ncw** [comment]
PS you aren't the first person to find the filtering complicated - it **is** complicated, but very powerful!

**Comment by CottonEaster** [comment]
Thanks for your messages.

&nbsp;&nbsp;&nbsp;&nbsp;Well, the goal is to make the explanations as simple as possible and no simpler, i.e. to explain - rather than distort or skirt - the complex functionality, _but_ in as clear a way as possible.

&nbsp;&nbsp;&nbsp;&nbsp;To that end, here is some suggested text.


========= Start of suggested text ========= 

**Notes**

- *Wildcards*. A file used with the `--files-from` option _**cannot** include wildcards_. If you need to use wildcards in specifying which files to operate upon, then `--include-from` may be the option to use.

- *Folders*. A file used with the `--files-from` option _**can** include folders_, _so long as_ those folders are listed with the format `<folder>/**`, e.g. `home/jane/documents/**`. (See also the point immediately below, on paths.)

- *Paths*. Paths within the `--files-from` file will be interpreted (whether they are for files or folders) as _starting with the root specified_ in the command (that command being the rclone command through which one is invoking the  `--files-from` option). This interpretation of paths is standard within rclone.

========= End of suggested text ========= 

It's a bit verbose, but I like to think it errs on the side of clarity.

**Comment by trvsysadmin** [comment]
This issue saved my life! I didn't know about the `/**` bit for folders. Here's my 2 cents on the Path portion text a little bit. Hope its helpful.

========= Start of suggested text =========

_Paths_. Paths within the `--files-from` file will be interpreted (whether they are for files or folders) as starting with the root specified in the command (that command being the rclone command through which one is invoking the `--files-from` option. This interpretation of paths is standard within rclone. For example:

`rclone copy --files-from sourcefiles.txt remote:root/path/foo/bar/{Lines Inside sourcefiles.txt Goes Here} ./dst/`

This is important because if your `src root` looks like `remote:root/`, rclone will reconstruct `/path/foo/bar/` within `dst` which might not be desirable if you have a complex directory structure in `src`.

**Comment by trvsysadmin** [comment]
Just read this again and tested. For _Folders_ `--files-from` doesn't work for me with `/*` or `/**` . However, `--include-from` works as mentioned by @ncw .

**Comment by ncw** [comment]
I think the `--files-from` point is covered in the docs now: https://rclone.org/filtering/#files-from-read-list-of-source-file-names
