### ISSUE TITLE
--b2-versions doesn't work for crypt backed by B2

### ISSUE THREAD

**Issue by jikamens** [rclone/rclone#1627]
Hidden file versions are not listed when I do `rclone ls --b2-versions` on a crypt bucket that is backed by a B2 bucket. This is highly inconvenient, to say the least. :-/

**Comment by jikamens** [comment]
Does `rclone cleanup` on a B2-backed crypt bucket even work? Not sure.

**Comment by ncw** [comment]
I'm not 100% sure how to fix this! Perhaps by getting the crypt remote to recognise the suffixes added for the versions.

> Does rclone cleanup on a B2-backed crypt bucket even work? Not sure.

I'm guessing yes as the crypt remote wraps the cleanup call.  If it doesn't, please make another issue!

**Comment by keithgh1** [comment]
Info from dupe #1632 

When you have B2 "lifecycle settings" set to include versioning, and you upload a new file in the same directory, with the same filename, then the B2 server has more than one version of the file with different timestamps. 

The documented behavior is here

https://www.backblaze.com/b2/docs/file_versions.html

and

https://www.backblaze.com/b2/docs/lifecycle_rules.html (describes which versions to keep etc)

Due to the filenames being encrypted locally by rclone prior to uploading, these additional versions now available on the server causes the associated filenames to be a mix of ciphertext and a plaintext date/time stamp.

When rclone attempts to decrypt this now-modified filename, the decryption fails and rclone throws an error (visible with more verbose debugging enabled) saying that the file has an "invalid filename" and skips processing this file.

Ideally, rclone could identify when a B2 encrypted remote, using filename encryption, with B2 versioning enabled server-side, sees an "invalid filename", could have an additional decryption attempt, by properly parsing the now-modified filename into two parts. The first part, the original encrypted filename, could run through the decryption process normally. The second part, the date/time stamp, would be appended onto the original plaintext filename (result of part1 decryption)

This would allow rclone filename encryption and B2 versioning to work together.

This issue is being filed per ncw. Some discussion is in this thread https://forum.rclone.org/t/backblaze-b2-humming-along-as-a-replacement-for-acd/2580/25

**Comment by normsland** [comment]
Would be great to get this implemented as b2 does not support server side move or copy. So we can't use the --backup-dir switch.

**Comment by cowwoc** [comment]
This feature, or lack thereof, is a very very big deal to me (the practical implication is data loss in case I want to recover an older version of my data).

Can we expect a fix in the short-term? Or should I consider drastic steps like disabling encryption?

Also, does this really affect *all* crypt configuratons? Or does it only affect filename encryption?

I would be okay losing filename encryption as a workaround so long as the actual contents are encrypted and I get versioning. Does that work?

**Comment by cowwoc** [comment]
I just tested it. It looks like versioning works fine if filename encryption is disabled.

**Comment by ncw** [comment]
> I just tested it. It looks like versioning works fine if filename encryption is disabled.

Yes that is a reasonable work-around I think.

**Comment by keithgh1** [comment]
Yes, the filename encryption is exactly the problem that this bug covers. See my previous message above. I did describe a potential fix above --- whether that's the most prudent one, I have no idea.

Thanks

**Comment by cowwoc** [comment]
@ncw You added a note on the website saying that the recommended workaround is `--backup-dir` but above @normsland wrote that:

> So we can't use the --backup-dir switch.

So I'm a bit confused :)

**Comment by ncw** [comment]
> @ncw You added a note on the website saying that the recommended workaround is `--backup-dir` but above @normsland wrote that:
> 
> > So we can't use the --backup-dir switch.
> 
> So I'm a bit confused :)

b2 does support --backup-dir now from rclone v1.48 since b2 added the capability for server side copies.

**Comment by jikamens** [comment]
Please fix this. :-(

**Comment by steakhutzeee** [comment]
Hi, i have a couple of questions:

rclone cleanup command will not work with --backup-dir, cleaning it, right?
I suppose it only works with "original" b2 old versions of files.

And also, if a bucket is only destined to work with crypt, at this time it's useless to use the "lifecycle settings" for that bucket because using crypt they are usless and i need to use --backup-dir instead.

Correct me if i am wrong.

Thanks in advance!

**Comment by ivandeex** [comment]
Unfortunately the patch #4024, which could resolve this, was abandoned by maintainers :-(
