### ISSUE TITLE
Remote metadata caching

### ISSUE THREAD

**Issue by ameir** [rclone/rclone#180]
I just started playing with rclone, and use the Amazon Cloud Drive (ACD) backend.  I have a lot of files stored (full system backups), and attempted to use it to do a diff-sync to ACD.  As expected, the process of comparing local and remote files is very time-consuming.  If I repeat this process, I expect that this will take even longer, since more files would be on ACD to compare.

I have tried the following projects, and one thing it does that I think is clever is maintain a local cache of remote file metadata in sqlite:
https://github.com/alex-phillips/clouddrive-node
https://github.com/alex-phillips/clouddrive-php

When remote files change outside of rclone, you can manually perform a sync of the remote metadata.  This substantially speeds up the comparison process.

Is this something you've considered?  It'd provide orders of magnitudes of speed improvement in many circumstances.

Thanks for the great project!

**Comment by ameir** [comment]
It looks like something similar has been proposed in https://github.com/ncw/rclone/issues/157, albeit as flat files.

**Comment by ncw** [comment]
I've thought about metadata caches, but I've been reluctant to add them because of the problems of keeping them up to date. I could see it maybe as an optional flag.  However my preference is to try to make the sync as fast as possible without.

You should find a no changes sync doesn't take very long.  ACD returns all the metadata as part of the directory listings so no extra transactions are required, just one per directory.

Did you measure how long a no changes sync takes?  It would be interesting to compare that to the time that `rclone size` takes - I think they should be about the same.

FYI here is my acd

```
$ rclone size acd:
Total objects: 5582
Total size: 9.908G (10639075938 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       13.5s
```

So it is scanning about 400 files / second for me.  That will vary of course but it varies as number of directories mostly, so directories with more files in will scan quicker.

One avenue of making ACD faster would be to try to get it to return all the files in one transaction, rather than having to read each directory one at a time.  This might be possible with the changes API, or by better use of the list

**Comment by ameir** [comment]
Thanks for the prompt response.  I just ran the same command as you, and ended up with:

```
time rclone size acd:
...
2015/11/07 03:48:13 Amazon cloud drive root '': List failed: HTTP code 502: "502 Bad Gateway", reponse body: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>We're sorry!</title>
</head>

<body style="padding: 4em; color: black; background-color: white; font-family: Verdana,Arial,Helvetica,sans-serif;">

<h2>We're sorry!</h2>
<p>
An error occurred when we tried to process your request.
Rest assured, we're already working on the problem and expect to resolve it shortly.
</p>

<h2>Désolés!</h2>
<p>
Une erreur s'est produite lorsque nous avons tenté de traiter votre requête.
Soyez assuré que nous travaillons déjà à la résolution du problème que nous pensons trouver très rapidement.
</p>

</body>
</html>

Total objects: 305826
Total size: 59.589G (63983594427 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 3
Checks:                 0
Transferred:            0
Elapsed time:    53m48.3s


real	53m48.353s
user	4m10.100s
sys	0m58.095s
```

Although it failed here due to the 502 on ACD's end, last I recall, it took about 80 minutes or so to begin a sync.  This is most unfortunate when it finally begins, and then I realize I need to add an exclude or other filter.

I think a local cache is great, so long as users know that any external modifications will require a re-sync of metadata.  Although, if you could find a magical way to shorten the file listing time, that'd be a huge win.  Or both? :)

**Comment by ivandeex** [comment]
Blocks on #1066 (capabilities inventory)

**Comment by animosity22** [comment]
Since ACD is dead and this issue is for the enhancement at a larger scale.

https://github.com/rclone/rclone/issues/5123
