### ISSUE TITLE
Increase test coverage and rewrite some tests

### ISSUE THREAD

**Issue by kubatasiemski** [rclone/rclone#1934]
Hi,
I removed template because is is unnecessary. I am little dissatisfied with my tests to touch command. I would like to rewrite it. I should split it (current it is one long function), add some comments and make true unit tests and check all cases.

I would also like to write tests to other commands.
Please let me know if you have any additional ideas or some part of rclone needs tests.

**Comment by ncw** [comment]
>  I am little dissatisfied with my tests to touch command. I would like to rewrite it. I should split it (current it is one long function), add some comments and make true unit tests and check all cases.

If you want to do that, then you'll probably want to use the tests framework. ...

In the test file put

```
func TestMkdir(t *testing.T) {
        r := fstest.NewRun(t)
        defer r.Finalise()
        fstest.TestMkdir(t, r.Fremote)
}
```

And in each test put

```
        r := fstest.NewRun(t)
        defer r.Finalise()
```

This creates a new remote on the fly for you (in fact it creates two, one local one and one remote one)

The `r` object then has lots of useful methods for putting objects, reading them etc.

See `fs/operations_test.go` for lots of examples.

> I would also like to write tests to other commands.
Please let me know if you have any additional ideas or some part of rclone needs tests.

rclone is reasonably well tested with both unit tests and integration tests (with the actual cloud providers).  Any test which uses the `fstest` framework takes a `-remote` parameter which can be used to test it against a cloud provider.

Here is [the current test run](https://pub.rclone.org/integration-tests/current-test.txt) - you can see that the `cmd/` are lacking tests.  These are because I try to keep them as simple as possible and just call something in `fs/operations.go` which is tested.  Take a look through `cmd` and see if you think we missed anything?

So speaking of `lsf` what we could do is factor the listing code with format into fs/operations.go and test it in there.  I'd suggeest the `ListFormatted` function takes a pointer to a `ListFormat` structure - that will make it easy to test, and then `lsf` itself's job is just to decode command line flags into a ListFormat structure which probably doesn't need unit testing.

**Comment by kubatasiemski** [comment]
Earlier I didn't know how important are functions in operations.go for commands. So my opinion about tests was wrong. Thank @ncw for information about tests framework and for documentation to lsf.
