### ISSUE TITLE
Not saving team drive

### ISSUE THREAD

**Issue by ColeMundus** [rclone/rclone#1942]
I am using rclone `v1.39` with Google Drive. 

When I edit a remote, I get the first three prompts, then a confirmation then the option to refresh the token and change the team drive. When I set the team drive, it does not save. 

![Team Drive](https://i.imgur.com/gioQL6h.png)

**Comment by mightyfree** [comment]
Same issue here. Current workaround is to delete the existing remote and create a new one.

Can replicate by creating a Google Drive remote and setting up as Team Drive. The remote works until editing to change team drive. The new setting does not apply, in fact it reverts back to My Drive location instead of previous Team Drive.

**Comment by ncw** [comment]
This is probably a consequence of 02ffd435724e344692aa4a3a36f9a0147fba888f

Thanks for finding a work-around @mightyfree

**Comment by animosity22** [comment]
This looks to be an old problem long solved. Closing out.
