### ISSUE TITLE
Consider supporting compression for crypt remotes

### ISSUE THREAD

**Issue by jikamens** [rclone/rclone#2098]
It's relatively common to compress plaintext data before encrypting it.

This is because you can't really compress it after encrypting it because good compression randomizes the data from the point of view of the compression algorithm and makes it compress very poorly.

Furthermore, since the data is randomized by compression, it can't be de-duplicated by the server, so even if the storage remote backing the crypt remote supports de-duplication, you still end up paying to store every encrypted byte.

It therefore might be useful if the crypt remote type supported (optional) compression which could potentially provide savings in terms of storage cost, upload and download bandwidth, and upload and download time.

If anybody ever ends up acting on this feature request, two additional things t consider:

1) Make sure a mix of compressed and uncompressed encrypted files is supported -- i.e., indicate in the header of the uploaded file whether it is compressed or uncompressed and react appropriately when downloading -- so that there is a backward-compatible path to enabling compression without having to re-upload all the files in the remote;

2) Dynamically determine while uploading whether individual files should be compressed or whether they're already compressed so additional compression won't help. For example, I played around with this a bit and found that a good algorithm is something like this:

* Read and compress the first 10MB of the file (big enough chunk to get a good idea whether compression will be useful on the entire file).
* If the file size is less than 10MB, then:
  * If the compressed blob is smaller than the uncompressed data, then upload the file compressed.
  * Else upload the file uncompressed.
* Else if the compressed 10MB blob is 25% or more smaller than the uncompressed blob, then upload the file compressed.
* Else upload the file uncompressed.

**Comment by ncw** [comment]
I think I'd implement this as a layer over the encrypted remote and I'd encrypt in chunks and save in many different files.  Rclone relies on being able to seek to individual points in the file which you'd lose if you just compressed the file.

**Comment by jikamens** [comment]
That's going to cause problems for things like file versioning on B2.

Also, it's probably going to cause problems similar to #1627, so you'd want to make sure to fix #1627 as well as avoid a similar situation here.

**Comment by id01** [comment]
I think doing something similar to dictzip (https://github.com/dictzip/dictzip-go) would allow for more seekable gzip compression without needing to handle multiple files; there are tools for other compression algorithms (like pixz) that take advantage of compression blocks to provide seekable compression as well. Might want to do something similar.

**Comment by ncw** [comment]
> I think doing something similar to dictzip (https://github.com/dictzip/dictzip-go) would allow for more seekable gzip compression without needing to handle multiple files; there are tools for other compression algorithms (like pixz for xz) that take advantage of the same block mechanism to provide seekable compression as well. Might want to do something similar.

Is there a description of how dictzip works somewhere?  The interface for dictzip doesn't look very useful - it only seems to be able to compress to a file.

> Edit: There's a MIT-licensed one here - https://github.com/rasky/multigz
> Maybe it can be used for a "press" remote.
> 
> Edit 2: On write, should the multigz library be used, I believe it would be possible to continuously read chunks of 64kb from the compressed data and record each of their locations in Writer.Header.Extra as uint16s; however, a custom implementation with zlib (just some metadata followed by a bunch of flushed blocks with checksums) will be more space and power efficient, and have no block length restriction, with the cost of being less standard.

multigz looks interesting....

**Comment by id01** [comment]
I looked more into the multigz source. The Offset struct has two variables - "Block", which seems like the start of the block in the compressed data, and "Off", which seems like the offset from the start of the block (I'm unsure of whether it is for compressed or uncompressed data). I'm not exactly sure how the blocking mechanism works, or if it's even possible to write a fixed number of blocks, as the blocks seem to be of variable sizes based on "Off".

I believe a possible implementation could be structured like this:
On write, we have the following cases:

- If the file is compressible, we append a ".raw" to the file name.
- If the file is smaller than 0.99972GB, we append a ".1gz" (mode 1, small files) to the file name. We then use multigz.Writer to compress the file in chunks, stopping at intervals of 65519 bytes (Worst case scenario <= 65535 bytes). Every stop, we can record the size of the compressed block by appending offset.Block-offsetPrevious.Block (2 bytes, unsigned), and the value of Off (2 bytes, unsigned), into a byte array, which we then assign to the extra data field through the writer. We can recover the value of Block of any block by finding the sum of all the sizes of the previous blocks. This way, we can support up to (65535/4)*65519 bytes (about 0.99973GB) with this format.
- If the file is larger than 0.99974GB but smaller than 204.75GB, we append a ".2gz" (mode 2, large files) to the file name. We then use multigz.Writer to compress the file into chunks, stopping at intervals of 16774139 bytes (Worse case scenario <= 16MB), and use 24-bit unsigned integers as the block size instead of 16-bit ones. This way, we can support up to (65535/5)*16774139 bytes (about 204.76GB)
- If the file is larger than 204.75GB but smaller than 42.66TB, we append a ".3gz" (mode 3, gigantic files) to the file name. Here, we do the same thing as before, but use chunks of a bit less than 4GB, as 32-bit unsigned integers as the block size.
- If the file is larger than 42.66TB, give off an error.

On read, if the file is compressed, we read the first 65KB of a file (let's hope the rest of the gzip header is <1KB), skip 10 bytes in the GZIP header (https://www.forensicswiki.org/wiki/Gzip#Header_checksum, https://jvns.ca/blog/2013/10/23/day-15-how-gzip-works/) to get to xlen (a uint16). We get this, then parse the next xlen bytes (based on the mode specified in the filename) to get our offsets. We use these offsets to find the blocks we need, then create a temporary file of the size of the compressed file. We fill this file with 0's, then write the header and needed blocks in place. We can then open the file using multigz and seek to the blocks we need.

**Comment by ncw** [comment]
> I looked more into the multigz source. The Offset struct has two variables - "Block", which seems like the start of the block in the compressed data, and "Off", which seems like the offset from the start of the block (I'm unsure of whether it is for compressed or uncompressed data). I'm not exactly sure how the blocking mechanism works, or if it's even possible to write a fixed number of blocks, as the blocks seem to be of variable sizes based on "Off".

Interesting analysis - thank you!

Do you want to write a proof of concept compressor?

For this to work with rclone the interfaces would need to be something like

```go
// Compress a file
func CompressFile(in io.Reader, size int64, out io.Writer) error

// Decompress a file (this could be io.ReadSeeker also)
func DecompressFile(in io.Reader, size int64) (FileHandle, decompressedSize int64, error)

// Where FileHandle satisfies io.ReadSeeker
```

**Comment by id01** [comment]
Got a functional prototype. It's a bit non-standard because it stores data in trailing garbage, but it was the most efficient solution I found. I tested seeking over a SSHFS and it does conserve data, though more measuring may be necessary.

[https://github.com/id01/rclone-mgz](Prototype Here)

**Comment by id01** [comment]
Okay, the code looks pretty good right now.

Some additional modifications/features:
* Removed the multigz dependency
* Added xz as another compression option if the binary is available on the system
* Multithreaded compression with a configurable number of threads
* Works with standard compression tools (even with gz-over-xz)
* Function that determines compressibility of file (and provides file extension accordingly)

I may add a faster algorithm in the future, but I don't really think it's necessary

@ncw, might want to [check it out](https://github.com/id01/rclone-compression)

**Comment by ncw** [comment]
> I haven't programmed in Go before, but I'm writing the POC code right now.

:-)

> I've finished writing a working prototype of the CompressFile function, but am a little held up on DecompressFile; should the `in io.Reader` be an `io.ReadSeeker`? Because otherwise I can't seek in the input without loading everything into memory or a tempfile.

In general streams from rclone are not seekable...  However the crypt backend does provide seekable streams.

it would be a bit of work, but all rclone streams could be made seekable.

> Edit 3: Done! This now makes completely gzip-compatible files. They're smaller too!

Great!

> Okay, the code looks pretty good right now.
> 
> Some additional modifications/features:
> 
> * Removed the multigz dependency
> * Added xz and lz4 as additional compression options if the binaries are available on the system

Are these standard gzip files with xz and lz4?

Shelling out to binaries won't work very well for rclone which is a cross platform program.   I think there are some libraries you could use.

Note that Klaus Post is the master of compression for go and this package contains assembly optimized compression routines

https://github.com/klauspost/compress

> * Multithreaded compression with a configurable number of threads
> * Works with standard compression tools (even with gz-over-xz or lz4)
> * Function that determines compressibility of file (and provides file extension accordingly)
> * Made configuration more... configurable
> 
> @ncw, might want to [check it out](https://github.com/id01/rclone-compression)
> 
> Might end up making a remote for this based on crypt.

This would probably be most useful to rclone users as an overlay backend which could be layered on top of crypt or any other backend.

**Comment by id01** [comment]
> > I've finished writing a working prototype of the CompressFile function, but am a little held up on DecompressFile; should the `in io.Reader` be an `io.ReadSeeker`? Because otherwise I can't seek in the input without loading everything into memory or a tempfile.
> 
> In general streams from rclone are not seekable... However the crypt backend does provide seekable streams.

Huh, I thought that having to load everything into memory or a seekable location to get to it sort of defeats the purpose of seekable files. I may be able to do some hacks with tempfiles to convert the io.Reader into a seekable file, but it'd probably just be easier to use a non-seekable file and stream the whole thing to disk first. Of course, if we're worried about the CPU bottleneck, it might still be beneficial to provide indexing in larger chunks for slower algorithms to be loaded into tempfiles on demand, though compression tends to be the much slower function, and we're running it across the entire file each time.

Also, compression only works before encrypting data; all strongly encrypted data is incompressible.

> > Okay, the code looks pretty good right now.
> > Some additional modifications/features:
> > 
> > * Removed the multigz dependency
> > * Added xz and lz4 as additional compression options if the binaries are available on the system
> 
> Are these standard gzip files with xz and lz4?

The xz.gz and lz4.gz files are xz and lz4 files in a layer of gzip-store to allow for metadata storage. They can be decompressed by using gunzip followed by the xz/lz4 commands.

> Shelling out to binaries won't work very well for rclone which is a cross platform program. I think there are some libraries you could use.
> 
> Note that Klaus Post is the master of compression for go and this package contains assembly optimized compression routines
> 
> https://github.com/klauspost/compress

Yeah; I was a bit afraid of integrating actual code licensed under the BSD licence, as I saw this project was MIT-licensed and I read that they aren't compatible. I can switch to the go libraries for the respective algorithms; they are probably faster too.

> This would probably be most useful to rclone users as an overlay backend which could be layered on top of crypt or any other backend.

Yeah; I was thinking of a service < crypt < press < cache setup.

**Comment by id01** [comment]
I added integrated lz4 support via this library: [https://github.com/pierrec/lz4](https://github.com/pierrec/lz4)

I also fixed a few crashes for larger files and added a caching mechanism to prevent duplicate reads of blocks.

I did some benchmarks for the compression routines, shown below:
```
Testing setup:
Original file on SSD
Compressed files on Ramdisk
Decompressed file on a hard drive
File used: 10172235776 byte (9.5GB) Windows SSD vdi
Cores used: 6 desktop Ryzen cores

gz-min:
compression: 94.674s, 5396065286 byte (5.0GB) output (~0.53 compression ratio)
decompression: 272.045s

gz-min-klauspost:
compression: 100.397s, 5456325901 byte (5.1GB) output (~0.53 compression ratio)
decompression: (not attempted)

gz-max:
compression: 448.84s, 5011936755 bytes (4.7GB) output (~0.49 compression ratio)
decompression: 267.067s

lz4-pierrec-256KB:
compression: 150.820s, 5991830418 byte (5.6GB) output (~0.58 compression ratio)
decompression: (not attempted)

lz4-pierrec-128KB:
compression: 180.268s, 6023779791 byte (5.6GB) output (~0.58 compression ratio)
decompression: (not attempted)

lz4-utils-256KB:
compression: 29.610s, 6093377810 byte (5.7GB) output (~0.60 compression ratio)
decompression: 151.547s

xz-utils-1MB:
compression: 549.19s, 4192593215 byte (3.9GB) output (~0.41 compression ratio)
decompression: 549.81s
```

This was the opposite of what I expected; the klauspost compression library seems to be slightly slower and produce slightly larger files, so I switched back to using go's default compression library. Also, the integrated lz4 compression (using pierrec's library) has worse performance than using gzip-min, along with worse compression ratios, likely due to optimization, which defeats the purpose of using it over gzip in the first place. That was the only, and most popular, go lz4 library I could find for go. Similarly, the [only xz library I could find for go](https://github.com/ulikunitz/xz) also says it won't be able to match the performance of the native utility. However, lz4-utils and xz-utils still do what they say on the tin - provide speed and much better compression ratios.

Because of this, it looks like lz4 and xz are best done via binaries - maybe a way to configure the path to xz/lz4 binaries in different operating systems (or maybe even just using $PATH) would be okay? This would just throw an error upon setup if the command doesn't exist, and the default gzip algorithm won't be affected.

**Comment by id01** [comment]
I created both a cgo and a binary lz4 integration, and a binary xz integration in the poc.

Meanwhile, I'm having some trouble integrating the code into rclone; it would be nice if someone else could do this.

**Comment by ncw** [comment]
> I created both a cgo and a binary lz4 integration, and a binary xz integration in the poc.
> 
> Meanwhile, I'm having some trouble integrating the code into rclone; it would be nice if someone else could do this.

What do you need help with?

**Comment by tatsujin1** [comment]
This is great work! :+1: 
Any idea how difficult it would be to integrate zstd as well?
Seeing as zstd is arguably the spiritual successor to lz4 it feels a pity to not add it. It's also quite flexible because of its wide range in compression levels.

I found these go packages:
* https://github.com/DataDog/zstd (cgo)
* https://github.com/mvdan/zstd (pure Go, although I'm unsure about the "Wuff" stuff)

I haven't used any of them. :)

**Comment by id01** [comment]
> > I created both a cgo and a binary lz4 integration, and a binary xz integration in the poc.
> > Meanwhile, I'm having some trouble integrating the code into rclone; it would be nice if someone else could do this.
> 
> What do you need help with?

I believe I've implemented most of it, but there are some functions that are giving me trouble:
 * The ComputeHash function, for example, is implemented in the crypt remote by encrypting the entire file again, however, compression is slow and different implementations may give different results that are both compatible with the decompressor. This will make this function very slow and may cause verification problems.
 * The Open function. I'm not really sure how to get a ReadSeeker to feed into the decompression function so that the entire file does not have to be read into memory. With some time, I may be able to make a workaround for this, but some type of reflection may be a simpler and cleaner solution.
 * The Update function. Through reading the crypt remote, I'm not really sure what this function does.
Also, do I just test by building rclone and trying out the new remote, or is there some sort of testing scripts (sorry; I'm not really familiar with the Go ecosystem yet)?

**Comment by id01** [comment]
I've been quite held up by school lately, but recently had the time to come back to this project after thinking about it some. After reading some more of the crypt code, I've managed to get the "press" remote to work with the crypt remote through some reflection and adaptation. There are some bugs and missing features, but the basic compressing/decompressing of directories works.

**Comment by ncw** [comment]
> I've been quite held up by school lately, but recently had the time to come back to this project after thinking about it some. After reading some more of the crypt code, I've managed to get the "press" remote to work with the crypt remote through some reflection and adaptation. There are some bugs and missing features, but the basic compressing/decompressing of directories works.

Nice one :-)  Can you link your branch?

**Comment by id01** [comment]
Link here: https://github.com/id01/rclone/tree/add_compression

List of things that work:
Directory uploads/downloads

List of things that don't work:
File uploads/downloads
Update() and ComputeHash() functions

List of things that need improvement:
- Making a good implementation of LZ4 that doesn't use C or shell out to binaries
- Making compression algs more modular instead of putting all in one behemoth file
- Reducing overhead

List of things that were changed:
- Heuristic function. Caused too many integration issues. Now everything is compressed.
- Added size to filename.

**Comment by ncw** [comment]
> Link here: https://github.com/id01/rclone/tree/add_compression

I had a look through [the code](https://github.com/id01/rclone/commit/901d8141e6e6b2016aebc6e11bfb6da69ebd408f) and put some Go style notes on.

So what next? Debugging?

**Comment by id01** [comment]
@ncw thanks for the notes! :) I've factored them (except for writing a wrapper instead of the cast) into the code.

Did a bit of debugging today, and I'm pretty sure there are still some bugs in it, but the latest version on GitHub now passes all sync and operation tests when run over crypt.

Some code cleanup (and rewriting some comments) might still be necessary. Also, I haven't implemented ComputeHash() yet; it's still just a panic stating it's not implemented. Is this necessary for a remote that doesn't support hashes? If it's required, I'll need to store the hash somewhere in the file to prevent the hashing from being awfully slow.

**Comment by ncw** [comment]
> @ncw thanks for the notes! :) I've factored them (except for writing a wrapper instead of the cast) into the code.

:-)

> Did a bit of debugging today, and I'm pretty sure there are still some bugs in it, but the latest version on GitHub now passes all sync and operation tests when run over crypt.

That is very good.
 
> Some code cleanup (and rewriting some comments) might still be necessary. Also, I haven't implemented ComputeHash() yet; it's still just a panic stating it's not implemented. Is this necessary for a remote that doesn't support hashes? If it's required, I'll need to store the hash somewhere in the file to prevent the hashing from being awfully slow.

I don't think you need to implement the `ComputeHash` function at all - just remove it. It is a specific function for crypt to make [rclone cryptcheck](https://rclone.org/commands/rclone_cryptcheck/) work.

**Comment by id01** [comment]
I pushed of my final modifications without testing yesterday, so the code didn't compile...

Fixed those today, along with a few other bugs. Also got rid of the filesizes stored in file names as a side effect and removed ComputeHash.

Pretty satisfied with my current implementation compared to before. I'll add documentation and other stuff and maybe send a PR soon.

**Comment by id01** [comment]
@ncw When doing the full integration test, I'm getting an error on the ObjectCheckWrap test saying that the compression remote doesn't support Mime types, as it is a wrapper remote. However, as we're uploading/downloading compressed data, the mime type given by any storage server will always be application/archivetype, so I've left this one out. Crypt seems to get around this somehow without implementing MimeTyper; how is this?

**Comment by ncw** [comment]
> When doing the full integration test, I'm getting an error on the ObjectCheckWrap test saying that the compression remote doesn't support Mime types, as it is a wrapper remote. However, as we're uploading/downloading compressed data, the mime type given by any storage server will always be application/archivetype, so I've left this one out. Crypt seems to get around this somehow without implementing MimeTyper; how is this?

Check out this bit of code

https://github.com/ncw/rclone/blob/99bc013c0a23d9dd5062600429a1488ae00cd277/backend/crypt/crypt_test.go#L48
