### ISSUE TITLE
Mount: Windows mount produces four instances of "new folder" when requested to make one in explorer.

### ISSUE THREAD

**Issue by danielloader** [rclone/rclone#2187]
#### What is the problem you are having with rclone?
Creation of 4 instances of a new folder.
https://i.imgur.com/jgFnwdX.png

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.40-028-ga8267d16
- os/arch: windows/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win 10 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`mount media: y: --config "C:\Users\spicypixel\rclone.conf"  --dir-cache-time=1m  --cache-chunk-size=32M --cache-info-age=672h --buffer-size=16M --rc --cache-tmp-upload-path="C:\Users\spicypixel\AppData\Local\Temp\rclone\cache-upload" -v`

**Comment by ncw** [comment]
What did you do to create the new folders?  How can I reproduce the problem?

Thanks

**Comment by daniel-loader** [comment]
Right clicked in an empty folder in Windows Explorer, clicked New > Folder, like a regular filesystem.

It then hesitates a little and comes back with the ones in the screenshot above.

**Comment by ncw** [comment]
I tried to replicate this with Windows server 2016 but it resolutely only makes one folder!

Can you run with `-vv --log-file mount.log` and make the new folder then stop the mount and attach the log here?  That should hopefully give a bit more idea as to what is going on.

**Comment by daniel-loader** [comment]
Will do as soon as I get a chance. Thanks!

**Comment by daniel-loader** [comment]
https://pastebin.com/raw/hXhpGNg7
https://imgur.com/uK44ry5

Hope it helps!

**Comment by ncw** [comment]
Thank you for that - nice video :-)

Everything looks normal in the log... I wonder if the `New Folder` is just taking too long to appear.

Can you try this for me?
  * Try the same experiment but with the underlying remote `gdrive` without the cache
  * Try the same experiment just with `rclone mount c:\path\to\localdir Q:`

Thanks!

**Comment by christoefar** [comment]
I would just like to confirm this behaviour on my server. I can provide my details/logs if you would like.

**Comment by ncw** [comment]
@christoefar are you using cache?  Can you try the experiments In the comment just above your first comment?

**Comment by christoefar** [comment]
@daniel-loader I notice you have passed the location of the conf file like I do. Is this because you are running it as a windows service using NSSM?

I ask because my command will run fine until I run it as service at which point I get the problem.

I have run the tests and attached the log files, 

**Problem Command & Log**

Log: [https://pastebin.com/ivEJ2Mj9](https://pastebin.com/ivEJ2Mj9)
You can see in this log the references to all 4 of the files.

Steps:

1. Mount
2. Create new folder (which produces 4 new folders).
3. Unmount

**Try the same experiment but with the underlying remote gdrive without the cache**

- This works correctly.
- Log [https://pastebin.com/zZ99ZzWR](https://pastebin.com/zZ99ZzWR)

**Try the same experiment just with rclone mount c:\path\to\localdir Q:**

- This works correctly.
- Log [https://pastebin.com/wPur6r3p](https://pastebin.com/wPur6r3p)

**Comment by daniel-loader** [comment]
Can confirm using the cache and nssm for service. Seems suspect then if it's not possible to recreate it when you run it manually.

**Comment by ncw** [comment]
@christoefar thanks for the logs.  As far as I can see everything looks normal in the problem case.  rclone doesn't report any errors, none of the FUSE calls return errors (except for the initial query to see if the directory is there before creating it).

The difference seems to be that in the problem case, things run the same until the OS decides to do this quite a few times

```
2018/07/05 13:11:20 DEBUG : /New folder: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/07/05 13:11:20 DEBUG : /New folder: >Getattr: errc=0
2018/07/05 13:11:20 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/07/05 13:11:20 DEBUG : /: >Getattr: errc=0
```

So that is as if it is looking for the directory.  Rclone returned `errc=0` so it found it, but we don't know exactly what rclone returned at that point.

I made a test binary which will print exactly what rclone returns in those Getattr calls.  Could you repeat your first two tests with this and we'll see exactly what the problem is hopefully.  Thank you :-)

https://beta.rclone.org/branch/v1.42-026-g6f86549c-fix-2187/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
Note there is more discussion of this here: https://github.com/rclone/rclone/issues/3216

The conclusion seems to be that it is running on the SYSTEM account which is the problem.

**Comment by ivandeex** [comment]
@danielloader @christopherchild This problem is reported against obsolete rclone version. Can you reproduce it with rclone 1.54?

**Comment by ivandeex** [comment]
Closing stale requests
