### ISSUE TITLE
[Feature Request] Delayed upload for –vfs-cache-mode

### ISSUE THREAD

**Issue by ErAzOr2k** [rclone/rclone#2327]
Hi,

I’d like to request a parameter for vfs-cache-mode, where I can set a delay (s, m, h, d, …), which uploads new or modified files after the defined time.

Right now, rclone will just upload the file instantly.

We already have something similar with --cache-tmp-upload-path and --cache-tmp-wait-time.

[Forum Thread](https://forum.rclone.org/t/feature-request-dalayed-upload-with-vfs-cache-mode-writes/5760)

**Comment by ncw** [comment]
Nice idea!

**Comment by KimchaC** [comment]
Are there any plans to implement this?

I use radarr and sonarr, which moves completed files from the main thread. So currently it locks up for several minutes and crashes since it is waiting for the upload to finish.

I tried to switch over to vfs, which is much quicker than the cache option, but I can't use it due to this.

**Comment by darthShadow** [comment]
@KimchaC Just FYI, I use Sonarr/Radarr myself and it doesn't actually crash while the file is being uploaded, it just hangs the main thread till the upload is finished, after which it resumes operations.

**Comment by KimchaC** [comment]
Yeah most of the time it resumes, but I had some instances where it didn't. But even without it crashing I think the experience is not great.

The biggest issue is that you have to wait for the uploads to finish, which means the files are not available for watching right away. And if you download a few movies at once, it can easily make Radarr unavailable for 30-60min.

With the  --cache-tmp-wait-time option the Radarr copy finishes in a few seconds and the file is immediately available in plex. After a while it is uploaded to the cloud and continues to be available. The experience is really great.

That being said, for now there is a workaround: Animosity22 came up with a workflow using mergerfs that works really well:
https://github.com/animosity22/homescripts

It even allows you to hardlink instead of copying files in Radarr/Sonarr, which is even quicker and doesn't use additional disk space.

It's a bit more effort to setup, but I am really happy with it so far.

**Comment by Nottt** [comment]
Would a bounty of $40 help with this?

Also it'd be nice if we could have a flag to cache the writes on RAM till they are uploaded, I have servers with very reliable energy power, fast pipes and 50GB+ of RAM to use to cache stuff. 

It would make writing on the mount faster than writing to my SSDs, a dream coming true!

Could be a flag like `--cache-location ram` and `--max--ram 80%`  I would prefer rclone to handle this than creating a ram disk and let rclone use it with `--cache-dir` because then it could start writing to disk once ram usage is over >% you set

**Comment by ncw** [comment]
This should probably be included in: https://github.com/rclone/rclone/issues/3186 which is basically the same issue but with a setting for upload delay.

**Comment by daniele-spl** [comment]
Are there any news here?
I also would need the delay upload feature. Is it possible to get a beta with this feature soon?

**Comment by michael-newsrx** [comment]
any updates for vfs upload delay? trying to use rsync into an s3 backed folder results in lots of server side copy files, renames, and deletes back to back

**Comment by darthShadow** [comment]
@michael-newsrx This has been available in the stable releases for more than a year now with the `--vfs-write-back` flag. Please try it out and open a new issue if you are facing any problems with it.

Closing this thread.
