### ISSUE TITLE
CVE-2018-12907

### ISSUE THREAD

**Issue by eclipseo** [rclone/rclone#2376]
As a package maintainer, I've just received an alert for this CVE that affects rclone. Since I haven't found any bug related to it, I'm creating one.

http://cve.circl.lu/cve/CVE-2018-12907

Summary:
In Rclone 1.42, use of "rclone sync" to migrate  data between two Google Cloud Storage buckets might allow attackers to  trigger the transmission of any URL's content to Google, because there  is no validation of a URL field received from the Google Cloud Storage  API server, aka a "RESTLESS" issue.

Reference:
http://openwall.com/lists/oss-security/2018/06/27/3
https://www.danieldent.com/blog/restless-vulnerability-non-browser-cross-domain-http-request-attacks/

**Comment by ncw** [comment]
The fundamental issue is that REST services often send URLs in responses which rclone follows without validation.

The sending of new URLs for resources is common practice in REST protocols.

As rclone uses HTTPS to access nearly all the cloud providers (Se Non HTTPS providers below), and checks certificates (unless you provide the `--no-check-certificate` flag)  in order to access this vulnerability you would either need to break SSL or compromise a cloud provider.

Assuming you've done that, you can send URLs to rclone which it might either request data from, or send data to. 

**However**, unlike a browser, the credentials for each fetch belong to each cloud provider backend - rclone will never mix up credentials between cloud providers no matter now compromised the URL.

There are several cases to consider, URLs which are used for upload, URLs which are used for downloads and redirects

## Download URLs

Let's say you are copying from compromised `Cloud Provider A`

`A` sends a malicious URL to download a file from.

Rclone will download that URL, but using the credentials of `Cloud Provider A`.

This has the consequences of:
  * Leaking the credentials for the compromised `Cloud Provider A`
  * Possibly downloading a publicly accessible file
    * This could conceivably be a locally accessible web server with no credentials

## Upload URLs

Let's say you are copying to compromised `Cloud Provider A`

`A` sends a malicious URL to upload a file to.

Rclone will upload to that URL (POST or PUT) using the credentials of `Cloud Provider A`.

This has the consequences of:
  * Leaking the credentials for the compromised `Cloud Provider A`
  * Leaking the data to a third party server
    * However `Cloud Provider A` is compromised so likely the attacker has access to your data anyway

## Redirects

Rclone starts downloading a URL and gets a redirect.  This is covered by Download URL above.

## Non HTTPS providers

Non HTTPS providers are:

  * [ftp](https://rclone.org/ftp/) which doens't send URLs
  * [sftp](https://rclone.org/sftp/) which doesn't send URLs and is protected by SSH
  * [http](https://rclone.org/http/) which does send URLs, however rclone will only follow links in the same domain.  Note this is often used with `https`.
  * [webdav](https://rclone.org/webdav/) which does send URLs.  This is almost always used with https.

The `http` backend could be vulnerable to redirects so the redirect handler for the `http` backend should check the URLs remain in the same domain. **FIXME** make issue

The `webdav` backend requires a bit more thought **FIXME** make issue

## Whitelist

To get rid of this problem completely appears to require some kind of whitelist for the URLs that the cloud provider returns. This is very cloud provider dependent.

CORS as a mechanism won't work, because if the cloud provider is compromised then presumably you can adjust the CORS headers too.

Rclone uses 3rd party SDKs to access a number of the cloud providers, google cloud storage included and the protection would have to be implemented in those libraries.

## Conclusions

The bar to accessing this vulnerability is very high.  To access this vulnerability you would have to:

  * Compromise a cloud provider or break SSL/TLS
  * Convince a user to do a cloud to cloud copy with rclone

The potential rewards are (from the Download URLs case - the Upload URLs case can be ignored I think):

  * Exfiltrating a file from a non-internet connected web server (one the client has access to but isn't internet connected) with no-credentials

There is likely some work to do on the `http` and `webdav` backends.

(Note that I'll edit this comment to keep it as the definitive statement as more facts emerge.)

**Comment by kuraga** [comment]
Hm... As I understand, we're talking about applying of MITM attack. In that case not only URLs issues exist but whole traffic could be compromised. So, what we're talking about?!

That's my thoughts but [here](https://github.com/google/google-api-python-client/issues/534) say the same...

**Comment by ncw** [comment]
@kuraga to exploit this you need to
  * MITM https traffic **or**
  * compromise a cloud provider

I'm assuming the first isn't possible, so it is the second the compromise a cloud provider which is a potential problem.

I think that the potential rewards are quite low and the barrier to entry very high, but there are cases where bad things could happen even without an https compromise.  I think the same logic applies to the issue you linked also.

**Comment by ivandeex** [comment]
Firefox and some Android apps maintain their own OS-independent lists of trusted root authorities as a measure against MITM. Docker's registry handling also provides an option [ExclusiveRootPools](https://godoc.org/github.com/docker/go-connections/tlsconfig#SystemCertPool) to lock API client into talking with chosen servers only.

When configured with a sandbox [CertPool](https://golang.org/pkg/crypto/x509/#CertPool) they optionally [append OS-standard pool](https://forfuncsake.github.io/post/2017/08/trust-extra-ca-cert-in-go-app) and set an option in [tls.Config](https://golang.org/pkg/crypto/tls/#Config).

White list of allowed domain wildcards might be a way too.

**Comment by ivandeex** [comment]
@eclipseo @kuraga This problem is reported against obsolete rclone version. Can you reproduce it with rclone 1.54?

**Comment by ivandeex** [comment]
Closing stale requests
