### ISSUE TITLE
[Feature request] Openstack swift container quotas when mounting

### ISSUE THREAD

**Issue by sekurilabs** [rclone/rclone#2408]
Hi,
It would be a nice option for rclone when mounting to set mounted drive size based on container byte quotas (X-Meta-Quota-Bytes). If there is no quotas then it defaults on the some predefined size. Svfs project had this included (as well as mounting whole Account), which I guess should not be a problem to integrate into rclone. Check svfs fs.go and it's swift library:
[https://github.com/ovh/svfs](https://github.com/ovh/svfs)

**Comment by ncw** [comment]
Nice idea!  Fancy having a go at implementing it?  The code would have go go here

https://github.com/ncw/rclone/blob/473e3c3eb8dc297db210d89a24bff274ce319c72/backend/swift/swift.go#L532

**Comment by netinfinity** [comment]
I'm currently working on it :)

Thanks!

**Comment by ncw** [comment]
What needs to be done is fill in the `Total` field in the `fs.Usage` struct here:

https://github.com/ncw/rclone/blob/dd670ad1db64eddb16b52ee876f076c6965a7e45/backend/swift/swift.go#L531-L547

In order to read the `Container` metadata you'd need to call `f.c.Container(f.container)` (if `f.container != "") ([docs on Container() call](https://godoc.org/github.com/ncw/swift#Connection.Container))

And you'd call the [Account method](https://godoc.org/github.com/ncw/swift#Connection.Account) to read the account metadata.

**Comment by netinfinity** [comment]
Great, thanks for the help :) How do I call this from (https://github.com/ncw/rclone/blob/master/cmd/mount/fs.go)[rclone/blob/master/cmd/mount/fs.go] later to get the usage data so I can create a mount with correct data?

**Comment by netinfinity** [comment]
Shouldn't we add :
`	if info.Total, err = getInt64FromHeader(resp, "X-Container-Bytes-Used"); err != nil {
		return
	}`
into this:
https://github.com/ncw/rclone/blob/f72eade70721a1c3b0a3ce75abc28d0f7950e66b/vendor/github.com/ncw/swift/swift.go#L1258-L1280

to get meta quota bytes?

**Comment by ncw** [comment]
> How do I call this from https://github.com/ncw/rclone/blob/master/cmd/mount/fs.go later to get the usage data so I can create a mount with correct data?

You don't need to.  The VFS layer will call the About function when you do something like `df` and it will cache the result afterwards.

> Shouldn't we add :
if info.Total, err = getInt64FromHeader(resp, "X-Container-Meta-Quota-Bytes"); err != nil { return }
into this:

Interesting idea. Unfortunately that info doesn't come back in the [list containers call](https://developer.openstack.org/api-ref/object-store/#show-account-details-and-list-containers) and I want to keep the `Container` struct consistent between the two.

So I think copy the implementation of `getInt64FromHeader` from the swift library into the swift backend (no copyright problems since I wrote it!) and call it there.

**Comment by netinfinity** [comment]
I think we have a bit of misunderstanding about fs.go. You have this lines in cmd/mount/fs.go:

https://github.com/ncw/rclone/blob/f72eade70721a1c3b0a3ce75abc28d0f7950e66b/cmd/mount/fs.go#L53-L76

Where reported size is static and hard coded to 1PB. I want to make a call to swift and ask about container meta quota bytes and if this metadata information exist, then change the reported fs size according to container quota. So if I limit my container to 20GB, when I mount it I want it to show 20GB mount size when I do for example df. Later on I would like to expand this to other backends that support quotas or give the quota information. This can be really helpful with the devs that use rclone in their projects or as part of their projects.

**Comment by ncw** [comment]
Note the `total, used, free := f.VFS.Statfs()` call.  This will eventuall call the `About` method on the swift backend.

The `total` is then used to override `resp.Blocks` from its default 1PB value.

So the result is dynamically calculated.  Try it on google drive to see.

```
$ rclone mount drive: /mnt/tmp/ &
$ df -h /mnt/tmp/
Filesystem      Size  Used Avail Use% Mounted on
drive:           17G  7.5G  1.4G  85% /mnt/tmp
```

**Comment by netinfinity** [comment]
That is what I'm trying to get with swift and containers that have quota. Can we repeat the steps needed to be done so I can make this happen? It would help a lot, since we are considering to use rclone in my company in production environment (with swift). We would also promote rclone to our partners.

Thanks!

**Comment by ncw** [comment]
If you look in my comment above starting "What needs to be done is fill in the Total field in the fs.Usage struct here:" that outlines the basics of what needs to be done.

Let me know if you need more help than that.

**Comment by ivandeex** [comment]
Closing after 2 years of inactivity

**Comment by puck** [comment]
Just adding a note for other people that might look through old tickets. This feature request has been implemented:

https://github.com/rclone/rclone/blob/8ed55c61e1a66bed00502361609a5a605f707da0/backend/swift/swift.go#L916

(Tested using v1.71)
