### ISSUE TITLE
WebDAV - Enable RFC4437 - Follow Redirect Reference Resource

### ISSUE THREAD

**Issue by jessiebryan** [rclone/rclone#2635]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

#### What problem are you are trying to solve?
I am unable to copy files from a WebDAV server which is returning 302 response followed by a Location header. The WebDAV server (Apache-Coyote/1.1) has RFC4437 enabled which describes the WebDAV behavior. In my example, the location is an AWS S3 bucket (not another location on the WebDAV server).

#### How do you think rclone should be changed to solve that?
When the endpoint returns 302 Found, rclone cannot actually "retrieve" the file without following the 302 to the new location.

**Comment by ncw** [comment]
This might be relevant: This was put in in 1550f70865245f917c63330039b18876bb214c8f to work-around a bug/feature in the go library which turns the PROPFIND requests into GET requests on redirect.  However that is only for PROPFIND requests - I would expect GET requests to be working properly.

Can you send me a debug log of a failed attempt with `-vv --dump bodies` please?  Ideally do something simple like `rclone -vv --retries 1 --dump bodies cat webdav:path/to/file` and send the complete log - thanks! (Feel free to edit the log for privacy).

**Comment by jessiebryan** [comment]
> Can you send me a debug log of a failed attempt with `-vv --dump bodies` please? Ideally do something simple like `rclone -vv --retries 1 --dump bodies cat webdav:path/to/file` and send the complete log - thanks! (Feel free to edit the log for privacy).

Attached - and after reviewing, I did see a server side error shown on line 2531 "X-Amz-Algorithm"

[rclone-webDAV-debug-bodies.txt](https://github.com/ncw/rclone/files/2465684/rclone-webDAV-debug-bodies.txt)

**Comment by ncw** [comment]
That got as far as the GET and it looks like you are right this error is the problem:

> Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified

You can see from the dump that the redirect worked OK, but s3 is moaning because it received an `Authorization:` header **and** an authorization signature in the query string of the URL.

I've had to work around this issue for ACD in #1501

I can use exactly the same work-around as in 6448c445f5f2b9f8ceeb809f80e0d0bb36280fb9 which is a little untidy in my opinion!

Or maybe something more general purpose like dropping the `Authorization:` header if it is redirected to a different domain.

There are undoubtedly WebDAV systems which will redirect to the same domain and expect the `Authorization:` header to be in place, so I don't think I can strip it for all redirects.

There is some discussion of this in [the relevant go issue](https://github.com/golang/go/issues/4800)

In fact reading that thread it seems that go1.8 does the correct thing

https://go-review.googlesource.com/c/go/+/28930

> Copy all of the original request's headers on redirect, unless they're
sensitive. Only send sensitive ones to the same origin, or subdomains
thereof.

So I need to remove the work-around I put in for this issue and use go1.8

I've had a go at doing this here - can you let me know if it works for you?

https://beta.rclone.org/branch/v1.43-138-gf7f8c295-fix-2635-redirect-beta/ (uploaded in 15-30 mins)

**Comment by jessiebryan** [comment]
> I've had a go at doing this here - can you let me know if it works for you?
> 
> https://beta.rclone.org/branch/v1.43-138-gf7f8c295-fix-2635-redirect-beta/ (uploaded in 15-30 mins)

Thanks for the explanation and research into this! 
Any chance you can provide a Linux binary? Looks like OSX and Windows only.

**Comment by jessiebryan** [comment]
> Any chance you can provide a Linux binary? Looks like OSX and Windows only.

Although we're using Linux, I was able to download your OSX binary and run it on an iMac. I am now able to copy files from the remote WebDAV server --> AWS!

**Comment by ncw** [comment]
The linux build failed - I've given it a kick - hopefully it will work this time!  Check the above URL in about 25 mins.

**Comment by jessiebryan** [comment]
> The linux build failed - I've given it a kick - hopefully it will work this time! Check the above URL in about 25 mins.
> 
> https://travis-ci.org/ncw/rclone/builds/440111570

No luck finding a Linux binary - build issues?

**Comment by ncw** [comment]
OK fixed the build!

Check out

https://beta.rclone.org/v1.43-150-g249a523d-beta/ (uploaded in 15-30 mins)

Thanks

**Comment by jessiebryan** [comment]
> OK fixed the build!

Thank You!! I have deployed binary and things are working perfectly now, thank you!
