### ISSUE TITLE
Rclone config create automation for google drive

### ISSUE THREAD

**Issue by zenjabba** [rclone/rclone#2644]
rclone config create doesn't allow for fully automated configuration (excluding the goole api auth which the user needs to log into the correct google drive account).

Currently this is what rclone currently presents with the following commandline

rclone config create sourcedrive drive --config=test-rclone.conf --drive-client-id=X --drive-client-secret=X

`2018/10/12 04:30:52 NOTICE: Config file "test-rclone.conf" not found - using defaults
Remote config
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...`

What I would like to see is with the following commandline

`# rclone config create sourcedrive drive --config=test-rclone.conf --drive-client-id=X --drive-client-secret=X --headless-setup` and it presents this following screen

```
go to the following link: https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=930690570454-ra711ct2peggpt0g98h09l56m0qt99td.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=1c9a152ad22e7f5db484662e16130543
Log in and authorize rclone for access
Enter verification code>
```

**Comment by zenjabba** [comment]
Ok, I'm ready for this :)

**Comment by InBrewJ** [comment]
You don't need to launch the interactive google api auth screen if you create a service account for google drive on the Google Cloud Platform

**Comment by InBrewJ** [comment]
Fair enough! I've realised after struggling even with a service account I can't get the command line config to work without firing up a web server...

I'm running this (option 1):

`rclone config create arupiot-auto drive \
drive-client-id "" \
drive-client-secret "" \
drive-scope drive.readonly \
drive-root-folder-id ""  \
drive-service-account-file path_to_my_json \
config_automatic no`

I've also tried this (option 2):

`rclone config create arupiot-auto drive \
--drive-service-account-file=/home/jib/Projects/media_warrior/GCP/media-warrior-07dec249ae7a.json \
--drive-client-id="" \
--drive-client-secret="" \
--drive-scope=drive.readonly \
--drive-root-folder-id="" `

If I run `rclone config` interactively the use the service account json file to browser window fires up asking for auth. My use case needs a service account because we need permissions/integration with more GCP services.

Thank you!

**Comment by InBrewJ** [comment]
I've just found the (probably) obvious workaround of using `#!/usr/bin/expect -f`

...it's not ideal

**Comment by zenjabba** [comment]
I'll wait till it's officially supported. I hate updating and debugging scripts more than I need too.

**Comment by dernat71** [comment]
Hi team! Any update on this? It would be **awesome** for fully automated processes (I think about CICD here).

Thanks a lot for all the work put into `rclone`. All heroes don't wear capes ;-)

**Comment by techsk8** [comment]
Any news on this?

**Comment by ncw** [comment]
If you use a service account you can make it fully automated, no user interaction required.

If you don't use a service account, you will need to do oauth through the browser. There is no getting round this.

Either way can be fully automated...

Run through the config manually with `rclone config -vv`

Before every prompt you will see a debug like this

```
2022/08/13 23:29:14 DEBUG : sldkfjsldf: config: reading config parameter "config_is_local"
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
```

You can put the answer to that on the `rclone config create` command line, so `config_is_local=true` 

In that way you can answer all the interactive questions and set client_id client_secret etc.

I'm going to close this as I think rclone now offers all the tools to do this.

**Comment by 88lex** [comment]
> If you use a service account you can make it fully automated, no user interaction required.

Specific example for those who may look in the future:

`rclone config update drivename type drive scope drive team_drive 0AH123456789PVA service_account_file /opt/sa/1.json`

For automated/non-interactive creation of Google shared drive remotes the above command works both to create new remotes and to update existing remotes. You can use it in scripts or in a terminal. I tend to use `update` rather than `create`, but either is fine.

The above does not address the exact mydrive auth question that OP was asking, but does work for shared/team drives.

NOTE: `rclone config update` works for "creating" MyDrive remotes as well. BUT the files sent to MyDrive using a service account are owned by the service account, which has a 15GB quota. Not especially practical for most use-cases.
