### ISSUE TITLE
rclone union mount allow more than one writeable remote

### ISSUE THREAD

**Issue by iamjrock** [rclone/rclone#2737]
#### Output of `rclone version`
v1.44, however this is a request for a new feature.

#### Describe the issue
This feature request has been discussed at length [here](https://forum.rclone.org/t/advantage-of-new-union-remote/7049).

rclone _union_ mounts currently have the restriction that only the last remote can be written to (all other remotes are read-only).  If we can remove this restriction then many rclone users who currently deploy unionfs or mergerfs could instead consolidate down to just using an rclone union mount.  This is especially helpful for Windows/OSX users as there are no readily available union filesystem solutions like unionfs/mergerfs for these operating systems.

Whilst removing the read-only restriction would accommodate many scenarios, the very common use case that we would like to achieve is:

-  location-0 is a local temporary folder and has the highest read priority. location-1 is a cloud remote with most of our storage.
- New files: When our local apps create new files, they are written to location-0 without any latency.
- Moved/Renamed files:
-- If the original file exists only on location-0: just mv within location-0
-- If the original file exists only on location-1: just move (server-side) the file in location-1
-- If the original filename exists in both locations: mv the file in both locations (server-side mv for location-1).
- Updated files: If the file is opened and saved, or replaced with a file of a larger/smaller size (same filename):
-- If the original file exists only in location-0: just overwrite the original file in location-0
-- If the original file exists only in location-1: leave the old file in location-1 and write the new file to location-0
-- If the original file exists in both locations:  leave the old file in location-1 and overwrite the old file with the new file in location-0.
- Deleted files: Delete from both locations.

This would then be cleaned up periodically with the following commands:

- rclone move any file from location-0 to location-1 that is not identical (filename, subfolder, size) in both locations; then
- delete any remaining files left over in location-0 (these are probably files that have the same filename and size in both remotes).

This periodic cleanup could be managed separately from this feature request, or included as union mount functionality.

The rclone forum thread also discusses various rclone.conf schemes that might be used to define the behaviour.

**Comment by iamjrock** [comment]
>  I'd rather avoid situations where I end up with duplicate files

@BinsonBuzz, yes one of my earlier passes at this had that deletion, but I changed it after a comment from @ncw.  It's a tradeoff:
- Cleaner: Deleting from location-1 in these situations is "cleaner" and means no need to handle the overwrite of old versions in location-0 during the periodic ove operation; vs
- Safer: Not deleting is "safer" in that the old file is still in location-1 until it is explicitly replaced later.  Like having a Trash can...

>including identical ones

I see your point, but I guess I was thinking:
- Less bandwidth is used if identical files are automatically excluded from the move; and
- In my setup I can't always use an --exclude as I often don't know the name of the files in advance of the move.

**Comment by xiaolei0125** [comment]
@iamjrock  Is there any new progress about unionfs?

**Comment by iamjrock** [comment]
@xiaolei0125, nothing from my end.  Sadly I haven't been able to help with rclone in the past few months.  However I can see above that last week @ncw moved this enhancement request into the v1.48 milestone, so fingers crossed for v1.48!

**Comment by thestigma** [comment]
Just want to note my own interest in this. As a Windows user with few alternatives union seems like a fantastic tool but is a little too limited to be practical currently. Very much hoping we see progress on this soon.

**Comment by Inrego** [comment]
Indeed, same here. Windows user who doesn't really have any alternatives for this functionality.

**Comment by thestigma** [comment]
On NCW's request:
I will go through all the material tomorrow and make another post trying to refine all the previously discussed ideas + my own into a concrete "implementation recipe".
**NO promises or time-frame at this point**, so keep your expectations in check, but NCW has agreed to at least re-visit the topic.

[quote="thestigma, post:1, topic:11744"]
I think the existing issue and accompanying thread covered pretty much everything, but just as a short recap of what I think are the most critical missing features:

* Instead of all inner remotes being read-only, they should all be writable but with the outer having write priority. (maybe have an option to mirror-write to all also, but this can be done with scripts so it's less critical)
* Logic for deleting, moving, renaming ect. to work on all of the inner remotes also. Basically any operation on a file should apply to any drive that has that file - not just limited to the outer one.
* Ability to set options-pr-remote (such as filter, or fast-list) and not just the end-point. Maybe this could be set directly into the Union remote config? If possible I think this would be a really clean way of doing it and you could likely keep full backwards compatibility with previous configuration formatting given that is currently so simple. This would be real useful for advanced setups, but depending on how much restructuring it would require I'd consider it a secondary priority compared to the two points above.
[/quote]

**Comment by thestigma** [comment]
Sorry for it taking this long, but here is my attempt at a structured implementation guide to make the coding job easier by providing a reference and rough task-list. This will inevitably recap a lot of already covered ground, but the idea here is to cover more the how (implementation) rather than what (functionality). I will also try to expand a bit on the existing ideas to try to keep the system as flexible as possible so it can be useful for more than the most typical use-case most of us are looking for.

This is roughly ordered by priority so we can cover the most critical and easy parts first, and polish up the rest later.

**About configuration:**
NCW has suggested that because the configuration formatting is actually some of the harder stuff to implement - that we for now just drop the whole config into a JSON. While that will be a little more unwieldy to configure it will let us get straight to solving the actual problems and we can worry about integrating the configuration better later. this should also allow us to keep easy backwards compatibility. Therefore I won't be going much into those specifics here. It can be quick and dirty and we don't need to commit to anything long-term as when that part is more closely integrated later it can just supplement, not replace the old JSON blob.

**About built-in syncing:**
I will not be including automatic syncing functionality here. This can already be done pretty easily by simple scripts, so it's a low-priority convenience thing and not an essential part of Union functionality itself. Besides it would need to be very configurable on it's own to fit everyone's diverse needs - which would mean a lot of work. This can be handled later on if needed.

---------------------------

**Problem 1**: Currently only 1 remote can write, and which one is predefined by the priority-ordering. We only have 2 levels, full and read-only. We should try to remove all of these limitations to create a high amount of flexibility.

I would recommend we create 3 hierarchical access-levels (emulating common conventions).
Each remote in the Union should be separately configurable regardless of it's place in the priority-order. Default to READ if not otherwise specified for safety-reasons.

-------------------------
**Level 1 - READ (only)**

> - On any Read: read from **highest priority remote** that has at least this access level. (same as current implementation).

**Level 2 - EDIT** (expands level 1)
(NOTE: potentially misleading name as it may imply write? A more accurate name might be ORGANIZE? or STRUCTURE? Up to you Nick...)

> - Everything from READ, and...
> - On any Move, Delete, Rename - perform this operation on **all remotes** of at least this access level.

Optimization note: Instead of listing for the file and performing Move, Delete or Rename on it if it exists - it may be faster to just blindly send the commands and just ignore/suppress and errors coming from a file not existing. 1 operation is better than 2 - and you can't really do anything wrong with a file that doesn't exist anyway...

**Level 3 - WRITE** (expands level 2)

> - Everything READ and EDIT, and...
> - On any Write - perform this operation on **all remotes** of at least this access level.

Optimization note: Can we detect if the source and all write remotes are on the same local volume or remote? If so it would be optimal do a quick "path-renaming move" / server-side move rather than the usual copy-then-delete in those cases. For example if you drop some files from your local D: drive into your mount which has a local remote on D: for your writes - then we want to avoid files being copied there. Obviously faster and less wear if we can just do a move. Same would apply on 2 union members on the same cloud drive.

------------------------
This should allow for very flexible configurations tailored to your spesific need. A couple of illustrative examples:
- A typical setup many of us want would involve a single (local) WRITE, and the rest of the remotes set to EDIT. All your new files goes to your local remote for later uploading by some script, but you are still able to edit, move and delete files everywhere and have them stay consistent.
- All remotes set to WRITE would basically create a pseudo RAID-1 mirrored volume.
- You don't necessarily need to have the WRITE remote also have the highest priority for reads. Maybe you want to want to read relatively static files from SSD for speed, but have your daily writes go on a HDD to prevent wear-out or whatever.

----------------

**Problem 2:** Consider this a "stretch-goal" - but a very apparently limitation is that you can currently only set flags/options at the endpoint. This makes it very hard to run separate settings for the different Union-remotes, like perhaps filtering. It also looks like many (or all?)  of the backend-flags do not actually forward "through" the union. For example I don't think --fast-list propogates, and you can't try to poll a union even if all remotes in it support polling.

Ideal solution: Specify flags pr. union-member in the configuration.
**Polling specifically may require some special considerations** because it's not stateless like most settings and needs to actively be running as a service, so that probably needs to be attached to an endpoint? (to the best of my understanding). If it is possible for Union to forward this to all union-members that supports it that may be ideal. If it can do that for all flags in general, then even better (overload any already existing flags from the Union config if applied at the end-point).

It does seem possible to work around this problem in a limited way already. You can mount all your union members and then union those mounts together. That allows you to set an individual config pr. Union member in the mounting script. This is a very cumbersome workaround... but it does work (with some caveats).

-------------------

Please tell me if I missed anything important, but I think this sums of the most important points from the (slightly messy) forum thread when excluding syncing functionality and the specifics of configuration formatting.

I am sure I will be updating this a few times to patch holes in the spec :)

**Comment by irneb** [comment]
I'm just wondering it this isn't re-inventing the wheel somewhat? A lot of the discussions happening seem to be exactly what projects like [https://github.com/trapexit/mergerfs](url) implements. There was quite a lot of discussions around how to decide which individual store would get the next write and how to handle duplicates and multiple versions. In the end there's pretty much options for nearly all possibilities. It could become extremely complex if going down this same rabbit hole.

Don't get me wrong, I think it would be great to have all this direct in rclone. It's just for the time being I go ahead and combine rclone with mergerfs and get the best of both as is.

**Comment by Inrego** [comment]
@irneb that's all good and dandy, because you have the option of using mergerfs.
Windows users can't use it, and there are no alternatives.

**Comment by irneb** [comment]
There are alternatives like https://github.com/Smurf-IV/Liquesce . Not "as" far reaching, but does provide similar features. If you're willing to go with non-open source then https://stablebit.com/DrivePool is also not "bad".

**Comment by Inrego** [comment]
Huh. I did my best trying to find alternatives, without luck. Neither of these are mentioned anywhere else where rclone users are trying to achieve this.
However, I reinstalled my server with Ubuntu so I'm not going to test them. But I think this information might be useful for others.

**Comment by iamjrock** [comment]
A fair question re mergerfs.  Personally I would still like to see an rclone solution because:

1) I have not tried Liquesce but it is a single contributor repo with its last commit being 2 years ago, not something that I would bet on.

2) I have tried Drivepool with Rclone about a year ago and found the combination extremely unreliable.  I forget the exact issues but if you google for Drivebit Rclone you will find various issues reported.

3) Let's not forget that OSX also lacks a true union drive solution (not just Windows).  OSX has union mounts in name but if you drill in you will find it insufficient for most use cases.

So to my mind, linux is still the only platform with a stable, proven, rclone-friendly union mount capability.

**Comment by irneb** [comment]
I agree, those things are really only well implemented on Linux (and perhaps BSD). The alternatives are "ok-ish". I've used Liquesce before, it's reasonably decent, it doesn't have all the options though - effectively the exact same thing as MHDDFS (basically just mounts more than one drive to a single mount point and all writes scatter randomly across all of them). I only came across Liquesce because I had extreme need of this in Windows, just could not use Linuix in that particular case, but had to be able to merge several disks into one (no raid, no spanned NTFS, had to be individual disks capable of being plugged in and moved without losing their data). I.e. I searched for Windows UnionFS ... it wasn't for rclone though.

For OSX I'm unsure what to do. Perhaps it might be possible to port mergerfs to that since it is at least partly based on BSD. Though I've not personally had any need of that, so didn't search in depth for this.

As to issues with such union mounts and rclone, I've used rsync on a Liquesce mount before (for backup purposes, both as a destination and as a source drive) and it ran pretty well, didn't see any issues. Since rclone basically uses rsync, I can't see that it would have much problems.

For anyone going with one of these or (preferably) mergerfs / aufs on a Linux, the principle follows like this:

1. Make a folder for each of your cloud stores.
2. Make a folder for the combined store (on Liquesce this becomes a drive letter) 
3. Set the Union mounter to map those individual folders to the combined one
4. Set rclone to sync those individual folders to each cloud store separately - best to have a script so it runs either on some double click or a timed event.
5. Place all your files in the combined folder and let the union mount handle how they get split to the other folders. Also get all your files from there as it shows all of them combined.6.

**Comment by irneb** [comment]
If rclone is going to have this, I would recommend you look at how mergerfs handles the various options though. Perhaps some of that code can be re-used, or perhaps it may suggest how things could be done. It's also very well tested already and extremely stable. So it could benefit rclone to not have to re-invent wheels.

**Comment by trapexit** [comment]
The reason mergerfs doesn't work on OSX is because there are very few people who are looking to use their Mac as a data store. It's a desktop OS. There has been some interest but I don't have a Mac and no one has stepped up to port it. There are enough differences between FUSE implementations and general OS behaviors to make it more than a quick thing.

Trying to make rclone present different backends as a POSIX filesystem is extremely non-trivial. They aren't designed for that. Also, a unionfs has to do more than make it look like a couple directories are really one. And a union of a posix filesystem is not the same as the union of a bunch of cloud services (all with slightly different features and APIs).

**Comment by thestigma** [comment]
I agree that Union should largely seek to emulate mergerFS in terms of the basic functionality. There has been a long long thread on this already, and the proposals here including my own basically sum up the main points of that consensus. Having it be part of rclone also offers up some unique possibilities in terms of integration. Also - as has been stated many times - it would be massively helpful to have a robust option outside of Linux. There exist options that simply "merge folders" but Union needs to do more than just this and I don't know of any proper replacement for mergerFS on Windows at least.

NCW has indicated he may take a look at this topic for one of the next two versions.

The best stop-gap solution so far has been to run mergerFS on windows via WSL2 (Linux-on-Windows). That is actually quite workable and practical due to the very tight integration and easy file-sharing, so running your whole rclone backend from the Linux environment does work. it's not exactly user-friendly though, and it leaves no room to optimize or add specifically rclone-related features as mergerFS is meant for generic use and not cloud. It works pretty well, but it's ultimately just a convoluted workaround.

**Comment by Max-Sum** [comment]
I have implemented a multiwrite union on [](https://github.com/Max-Sum/rclone/tree/multiwrite_union). It is inspired by the policy design of mergerfs. Could anyone help me to merge back?

**Comment by thestigma** [comment]
@ncw Likely wants to be informed on this. He can probably help you out on the specifics of merging back too I bet.

**Comment by buengese** [comment]
@Max-Sum this looks very good. Could open a pull request with this? This seems to check pretty much all the boxes and also supersedes my work on mirror backend I think (which is great because i never seem to find the time to finish it).

**Comment by ncw** [comment]
> @Max-Sum this looks very good. Could open a pull request with this?

Seconded!

> This seems to check pretty much all the boxes and also supersedes my work on mirror backend I think (which is great because i never seem to find the time to finish it).

@buengese would you like to review the pull request when it comes in?

**Comment by thestigma** [comment]
I will be very happy to help betatest this if you need some lab-rats. (and probably others here as well)
Just give me a holler and I'll come running ^_^

**Comment by iamjrock** [comment]
@Max-Sum, just wanted to say.....wow (!) and thank you for your work on this.  Count me in as an enthusiastic tester as well!

**Comment by Dibbyo456** [comment]
I believe this issue can be closed now because Rclone now supports multiple writable backend.

**Comment by ncw** [comment]
Well spotted @Dibbyo456 :-) Yes this is supported now, so will close.

Thanks @Max-Sum for your great work :-)
