### ISSUE TITLE
ncdu ignores exclude's

### ISSUE THREAD

**Issue by timwsuqld** [rclone/rclone#2933]
#### What is the problem you are having with rclone?

rclone ncdu ignores --exclude flags

#### What is your rclone version (output from `rclone version`)

```
$ rclone version
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian Linux 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
rclone ncdu --exclude "{Google Photos,Photos}" drive:/
rclone ncdu --exclude "Google Photos" --exclude "Photos" drive:/
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

ncdu output still fetchs data for GOogle Photos and Photos folders. (One is a special Google Drive folder, the other is a folder I just want to exclude.

**Comment by ncw** [comment]
You need to use the `/**` to exclude a directory and its contents.

So this should work

    rclone ncdu --exclude "/Google Photos/**" --exclude "/Photos/**" drive:/

I've rooted the excludes since I assume you don't want to exclude any directory called "Photos"

Note also that using the `--fast-list` flag will make listings much faster.  This will include everything but you might find that

    rclone ncdu --fast-list drive:

is faster than the one with the excludes.
