### ISSUE TITLE
[remote] put all files into "archives" to circumvent filelimits

### ISSUE THREAD

**Issue by fionera** [rclone/rclone#3084]
#### What is your current rclone version (output from `rclone version`)?
v1.46.0

#### What problem are you are trying to solve?
Bypass the filelimit on some remotes

#### How do you think rclone should be changed to solve that?
Implement a remote which puts all files into one/multiple tar files on the other end

**Comment by calisro** [comment]
You can kind of do this now using 

 tar cf - profiles.xml | rclone rcat test.tar

ls -ltra
-rw-rw-r--  1 xx xx 10240 Apr  1 17:14 test.tar

tar -xvf test.tar
profiles.xml

**Comment by Nanodragon999** [comment]
Yes, but i think Fionera meant to make a fuse mount that work with tar archive.
a bit like fusezip works but for tar, and implemented in rclone as a remote.

**Comment by calisro** [comment]
I'd think that would be rather slow on cloud storage due to the fact that each tar would need to have an index to scan for the contents of the tar or spanned tars. Or it would need to have a local database to maintain which would tie it to a single host. It would essentially have to scan many tar archives to even list contents.  And to extract contents of a file from the tar it would need to download the entire tar or chunk it which would mean lots of waste because each file would then need to be contained in a chunk.

To write to a tar, it would need to transfer the entire tar.

Would you see this working differently?

**Comment by fionera** [comment]
Yeah for that tar isnt the best option. I didnt know that the header of a tar isnt at the beginning. So a file format is needed that supports splitting and has its table of content at the beginning. Also it should have support for removing files (in gdrive you could patch the file content explicitly)

**Comment by ealgase** [comment]
If you're worried about rate limits for Google Drive, you may want to use your own API key.

**Comment by fionera** [comment]
its not for the ratelimit but for example a filelimit. As example you could technically store up to 2 Exabytes in a single Teamdrive, you have a filelimit of 400k File

**Comment by Cnly** [comment]
Another similar issue: https://github.com/ncw/rclone/issues/675.

**Comment by ncw** [comment]
I think, unfortunately, this idea is a non starter.

Very few of the cloud providers allow you to update parts of a file once it has been uploaded.  Google drive doesn't (see [api](https://developers.google.com/drive/api/v3/reference/files/update)) you can only update the whole file or nothing.

So upload a read only archive of files would be possible, but I'm not sure how useful that would be.

**Comment by fionera** [comment]
indeed. I actually started a different approach in adding a remote that automatically switches between write remotes to failover to the next one, when the first one returns a "tooMuchFiles" error

**Comment by ncw** [comment]
> indeed. I actually started a different approach in adding a remote that automatically switches between write remotes to failover to the next one, when the first one returns a "tooMuchFiles" error

A sort of RAID0 ?  A bit like the union remote?

**Comment by fionera** [comment]
kinda but instead of writing always to all remotes it only switches when needed...

**Comment by ncw** [comment]
> kinda but instead of writing always to all remotes it only switches when needed...

That is what I meant - RAID-0 only writes your data to one disk, it just presents the union of the disks as one big disk.

**Comment by fionera** [comment]
raid 0 scrambles the data across all disks so the random access is faster :P but yeah thats what it does

**Comment by thestigma** [comment]
The idea may have some merit and I've thought about this before - but I think it would probably be best used to selectively zip down files based on size rather than applying it across everything.

For example - based on a few parameters
-enablezipping
-sizecutoff
-minfiles
-maxsize

If enablezipping = true
do a check before any copy/move/sync
check how many files are below sizecutoff
if more than minfiles - zip these (split into multiple if needed to keep below maxsize), ignore those original transfers and add the new zip instead to the queue

Some sort register would need to keep track of what files reside where though. But at least the files would be recoverable manually if that register was lost.
Also, you have to do the whole process in reverse to make it transparent to user

pros:
- less files in general on cloud
- probably quite significant performance benefits when dealing with may small files, which is already a known weak-point of any cloud services due to the latency on requests.

cons:
- Slightly worse performance on selectively retrieving one single small file, especially if maxsize set very large. This seems like a small price to pay though.
- If making a change to a file on a zip then the entire zip has to re-downloaded to add the change, then reuploaded. Howeverm assuming a reasonable maxsize it shouldn't be a big deal.
- Slightly more CPU load I guess
- Dev-work...

All in all - I think there would be a lot to gain from it for "general use" storage, because in very small files are not at all uncommon. Right now I have about 220.000 files 16KB or less on my C: (and probably far far more under 100KB). It would take something like 122hrs to transfer those despite the trivial size of about 700MB. If split into 10MB zips the transfer time would be no issue (even if no compression used) - and retrieving any particular file (or uploading after editng) should also be fairly trivial.

**Comment by animosity22** [comment]
This looks to be answered. If you have further questions, please just make a post on the forums. Thanks!
