### ISSUE TITLE
File/foldername encryption ONLY

### ISSUE THREAD

**Issue by CHRONiCiTY** [rclone/rclone#3085]
#### What is your current rclone version (output from `rclone version`)?
1.45 & 1.46

#### What problem are you are trying to solve?
I would like to use file and foldername obfuscation on my files but I have no interest in actually encrypting the files themselves.

#### How do you think rclone should be changed to solve that?
Put this as an option in the crypt remote or create a new remote called "Obfuscate" for example.
Would be awesome if you could also then use this to obfuscate files and folders that had already been uploaded to a remote since it would basically just be a matter of 'moveto' (on the hosts that support that command).

**Comment by thestigma** [comment]
I am 99% certain that what you are asking for already exists (at least since 1.47 or 1.48, im not sure about earlier versions since I didn't use them).

During the normal Crypt setup you can choose to leave files as-is, encrypt them, or just obfuscate the name. For directories you can choose to do nothing or encrypt (but I guess there is no real difference between encrypting or obfuscating a directory).

I'm sure you can solve this simply by downloading the newest version and checking the config options.

**Comment by ncw** [comment]
Actually there is a pull request in progress implementing this: #2981
