### ISSUE TITLE
as rclone user i want to have an ability to watch and copy files only on write, so my rsync copy command doesn't scan the entire dir tree

### ISSUE THREAD

**Issue by gmdjango** [rclone/rclone#3137]
#### What is your current rclone version (output from `rclone version`)?
1.47

#### What problem are you are trying to solve?
currently i can only rclone copy ~/Dropbox Dropbox-account: -P and this scans the entire Dropbox

#### How do you think rclone should be changed to solve that?
add a daemon that watches writes to the dir tree recursively and run rclone on those events only so it will be 
rclone daemon &;
and then on each write there will be
rclone copy ~/Dropbox/path/to/file Dropbox/path/to/file

Here is one way to watch the writes on a dir: https://stackoverflow.com/questions/8699293/how-to-monitor-a-complete-directory-tree-for-changes-in-linux

Also we need to account for the opposite direction, not sure how.. probably Dropbox recent api or something like that, and run that every minute or so

**Comment by chiraag-nataraj** [comment]
Why not use inotify-type watchers and call `rclone` through that? One that comes to mind would be `systemd`'s `path` units, but there are other shell-based tools if you don't like (or use) `systemd`.

**Comment by danielloader** [comment]
@chiraag-nataraj got an example of using systemd path units for an inotify service for uploading?

**Comment by chiraag-nataraj** [comment]
I used to use the following to do auto-commits:
`autocommit@.path`:
```
[Unit]
Description=Autocommit for %I

[Path]
PathModified=%I
```
`autocommit@.service`
```
[Unit]
Description=Autocommit service for %I

[Service]
Type=oneshot
ExecStart=/usr/bin/env autocommit.sh %I
```
`autocommit.sh`
```
#!/bin/bash

cd $1
git add -A
git commit -a -m "Autocommit"
```
So I could start it with `systemctl --user start autocommit@$(systemd-escape /home/chiraag/.config)` and have it automatically commit any changes I make in that directory. Unfortunately, it's not recursive, so I ended up switching to `entr`, which _can_ do recursive tracking.

So I guess my modification to the above statement is that `systemd.path` is useful when looking at individual files/folders without recursion and `entr` is useful when looking at a whole _tree_ of files and folders.

As an example with `entr`:
`git-autocommit@.service`:
```
[Unit]
Description=Git autocommit for %I

[Service]
Type=simple
ExecStart=/usr/bin/env git-autocommit.sh %I
```
`git-autocommit.sh`:
```
#!/bin/bash

DIR="$1"

cd "$DIR"
while true
do
    find -iname "*" | entr -pd git add -A
    git commit -a -m "Autocommit"
done
```
For what it's worth, I ended up stopping it because it was generating too many commits haha. But yeah, this mechanism definitely worked while I used it.

**Comment by ncw** [comment]
> currently i can only rclone copy ~/Dropbox Dropbox-account: -P and this scans the entire Dropbox

What you can do is use `--max-age 1d` and `--no-traverse` - between them these will only upload stuff that is younger than one day and it won't traverse the remote dropbox.

You'll still want to do a full sync occasionally, but the above should be very quick.

**Comment by animosity22** [comment]
This looks to be answered. If you still have a question, please just ask on the forums and we can help out.
