### ISSUE TITLE
Readdir \\?\T:\: The system cannot find the path specified.

### ISSUE THREAD

**Issue by touhoku-japan** [rclone/rclone#3310]
#### What is the problem you are having with rclone?
2019/06/30 06:48:30 ERROR : : error reading source directory: failed to read directory "": Readdir \\?\T:\: The system cannot find the path specified.

#### What is your rclone version (output from `rclone version`)
beta-latest

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows10 Pro 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy t:\ remote:T

#### comment
I use this.
https://github.com/feo-cz/win-sshfs/releases

but rclone output it

2019/06/30 06:48:30 ERROR : : error reading source directory: failed to read directory "": Readdir \\?\T:\: The system cannot find the path specified.

**Comment by ncw** [comment]
So this is a problem with rclone reading an sshfs directory - is that right?

What happens if you do `rclone lsf -vv T:\` does that work? how about `rclone lsf -vv C:\` ?

Note that rclone has an [sftp backend](https://rclone.org/sftp/) which works with nearly every ssh server - maybe that would be a good workaround?

**Comment by animosity22** [comment]
This looks to be stale. If you have a question on how to use, please visit the forums and we are happy to help.
