### ISSUE TITLE
Tagging like on S3 and Ceph RGW

### ISSUE THREAD

**Issue by lz006** [rclone/rclone#3390]
Hi I know this topic has been discussed already but it would be really helpful if this feature could be implemented some day. Reason is that objects in S3 or Ceph RGW can be tagged by using curl for example. These tags were organized by the object storage and there is no need to find a way to make tags compatible to metadata from a common filesystem of an OS like mac or linux because they only live in object store but can be useful in case searching or categorization.

Mentioned discussion:
https://github.com/rclone/rclone/issues/1523

Please let me know your thoughts. thanks

**Comment by ncw** [comment]
So if we added a `--s3-tag` flag which only applied when uploading objects, would that be OK?

[The docs state](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) that you can provide a x-amz-tagging header when uploading the object - that would be easy to do.

**Comment by ncw** [comment]
This is supported by the SDK so would be a fairly easy change if you wanted to have a go?

**Comment by lz006** [comment]
yeah that would be awsome!

On 30 July 2019 21:51:25 CEST, Nick Craig-Wood <notifications@github.com> wrote:
>This is supported by the SDK so would be a fairly easy change if you
>wanted to have a go?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rclone/rclone/issues/3390#issuecomment-516569955

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ncw** [comment]
> yeah that would be awsome!

Would you like to help implement this?  I can give some pointers if so

**Comment by lz006** [comment]
yes I'll give it a try, pointers would be welcome

**Comment by ncw** [comment]
First thing is to make a new option like this one, called `tag`.  It should be an advanced option as I don't think people will normally want to configure it.

https://github.com/rclone/rclone/blob/5be968c0cacb0fa13b338ec2208d6c2f2f583540/backend/s3/s3.go#L705-L708

That needs to go in here too

https://github.com/rclone/rclone/blob/5be968c0cacb0fa13b338ec2208d6c2f2f583540/backend/s3/s3.go#L770

Next use that option here

https://github.com/rclone/rclone/blob/5be968c0cacb0fa13b338ec2208d6c2f2f583540/backend/s3/s3.go#L1871

With something like
```go
		if o.fs.opt.Tag != "" {
			req.Tagging = &o.fs.opt.StorageTag
		}
```

And the identical code here

https://github.com/rclone/rclone/blob/5be968c0cacb0fa13b338ec2208d6c2f2f583540/backend/s3/s3.go#L1898

That should put the tags on and should be OK for the first iteration!

Note the input format is URL encoded so "name=value&name1=value1".  This should really have special characters escaped too but that can be for the next revision!

This probably isn't a great input format. How about "name=value,name1=value1" in CSV encoding or maybe a JSON blob?

Do you think the parameter should be called `tagging` instead of `tag` - that would line up with what AWS call it better and gets across the idea that you could put multiple tags in.

**Comment by ncw** [comment]
This should be supported now like this

    --header-upload "x-amz-tagging: foo=bar&hello=world"

See #4303 for more info
