### ISSUE TITLE
Dropbox disallowed filenames cause retries

### ISSUE THREAD

**Issue by litemotiv** [rclone/rclone#3569]
I'm not sure if this qualifies as a bug but this might be something that could be tweaked for better default performance:

```
2019/09/24 00:35:44 NOTICE: multisite/wp-content/themes/wobb/resources/js/assets/.DS_Store: File name disallowed - not uploading                                                                        
2019/09/24 00:35:44 ERROR : multisite/wp-content/themes/wobb/resources/js/assets/.DS_Store: corrupted on transfer: sizes differ 6148 vs 0 

2019/09/24 00:36:31 ERROR : Dropbox root 'capstone/vm2': not deleting files as there were IO errors                                                                                                     
2019/09/24 00:36:31 ERROR : Dropbox root 'capstone/vm2': not deleting directories as there were IO errors                                                                                              
2019/09/24 00:36:31 ERROR : Attempt 1/3 failed with 2 errors and: corrupted on transfer: sizes differ 6148 vs 0  
```

When a file is blocked by Dropbox it would be preferreable if it isn't added to the retry queue since it will be blocked again. Perhaps it would be possible to drop these kinds of blocked transfers? The main reason would be that if there are a lot of blocked files, it could potentially keep rclone retrying for hours or days while it would always produce the same result.

Cheers,
-lite

**Comment by ncw** [comment]
I think this is a bug...

rclone knows which files are disallowed but it tells the sync routine that it uploaded them correctly, however the sync routine checks the upload and finds that they are not uploaded properly.

I think a better approach would be to return a `NoRetryError` with the text "File name disallowed - not uploading". This will error the sync which is correct since not everything got uploaded but it will not do retries.

What do you think?

**Comment by litemotiv** [comment]
Sounds perfect to me Nick 👍
