### ISSUE TITLE
Messy progress output - whitespace not cleared during updates.

### ISSUE THREAD

**Issue by mb300sd** [rclone/rclone#3574]
#### What is the problem you are having with rclone?

The old text is not cleared from whitespace during progress output

#### What is your rclone version (output from `rclone version`)

rclone v1.49.3
- os/arch: windows/amd64
- go version: go1.12.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows Server 2019 x64

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy or rclone sync

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Filenames are private, but image showing the issue is attached.

![](https://i.imgur.com/XH9b7bD.png)

**Comment by ncw** [comment]
I think this is very likely the same issue as #3500 and #2623 which is a bug in windows 10 which is fixed in Windows 10 1903

I see you are using Windows Server 2019 - maybe it has the same issue?

Any chance you could try this beta and see if it has the same problem? This uses a different library for doing the windows console things so may work better/differently!

https://beta.rclone.org/branch/v1.49.3-104-g3bddeed5-fix-config-beta/

**Comment by ncw** [comment]
PS I presume you are using the `-P` or `--progress` flag?

**Comment by mb300sd** [comment]
Yeah, using -P flag. Server 2019 is 1809, so very likely the same bug. MS needs to release a hotfix for the LTSC rather than just fixing it in a new build. :(

**Comment by ncw** [comment]
Any chance you could try the beta I posted above?

**Comment by mb300sd** [comment]
Beta works well!

**Comment by ncw** [comment]
> Beta works well!

Thanks for testing :-)

I think I'll swap over to using that library.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50
