### ISSUE TITLE
build: rpm's are broken in v1.49.4 release

### ISSUE THREAD

**Issue by holckj** [rclone/rclone#3580]
#### What is the problem you are having with rclone?

I can't install the rpm

#### What is your rclone version (output from `rclone version`)

1.49.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux (Centos), 64 bit

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

$ rpm -U rclone-v1.49.4-linux-amd64.rpm 
this results in the message:
package rclone-1.49.4-.x86_64 is intended for a  operating system 

$ rpm -U rclone-v1.49.3-linux-amd64.rpm
works fine

$ rpm -U rclone-beta-latest-linux-amd64.rpm 
doesn't work:
package rclone-1.49.4.152.gb9bd15a8.beta-.x86_64 is intended for a  operating system

**Comment by ncw** [comment]
This turns out to be because
- I'm using the master branch instead of the latest release of nfpm
- The master branch is broken

I've reported the master branch breakage upstream: https://github.com/goreleaser/nfpm/issues/71

I've fixed the CI to use the correct version of nfpm here - can you have a go with this?

https://beta.rclone.org/branch/v1.49.4-154-g18e137d6-fix-3580-rpm-beta/ (uploaded in 15-30 mins)

If that works then I'll think about whether to update the v1.49.4 release or produce a v1.49.5 release

**Comment by ncw** [comment]
I tested the rpm on centos7 and it worked fine for me so ive merged this to master.

I'll hold off on rebuilding v1.49.4/.5 until I hear from you

**Comment by holckj** [comment]
Your new beta (rclone-v1.49.4-154-g18e137d6-fix-3580-rpm-beta-linux-amd64.rpm) works fine for me. Thanks for your quick answer and fix :-)

**Comment by ncw** [comment]
Great, thanks for testing :-)

I'll push that out in a 1.49.5 release in the next 1 or 2 days.

**Comment by ncw** [comment]
I've released a v1.49.5 which you can find at [in the normal place](https://rclone.org/downloads/) which fixes this.

Release announcement: https://forum.rclone.org/t/rclone-1-49-5-release/12166
