### ISSUE TITLE
Rclone mount will incorrectly handle data when used with borgbackup

### ISSUE THREAD

**Issue by Cubox** [rclone/rclone#3641]
#### What is the problem you are having with rclone?

borgbackup will fail when writing files to rclone mount'd filesystem

#### What is your rclone version (output from `rclone version`)

v1.49.5-236-g2e505430-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

FreeBSD 12.0-STABLE amd64

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -vv --config /home/cubox/.rclone.conf --vfs-cache-mode full --cache-dir /tmp/rclone mount Gdrive:Onyx/Borg /gdrive | tee output.log`

For borg:
```
<root@Onyx>-<~> λ borg init /gdrive -e repokey-blake2
Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /gdrive

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).
<root@Onyx>-<~> λ borg create -p -e /root/.cache -C zlib,6 -v /gdrive::Onyx-2019-10-19T00:53 /usr/home /etc /root /www/cubox /www/fbh /usr/local/etc
Creating archive at "/gdrive::Onyx-2019-10-19T00:53"
Local Exceptionents   0%
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 573, in do_create
    create_inner(archive, cache)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 538, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/local/lib/python3.7/site-packages/borg/archive.py", line 515, in save
    self.repository.commit()
  File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 442, in commit
    self.compact_segments()
  File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 789, in compact_segments
    assert segments[segment] == 0, 'Corrupted segment reference count - corrupted index or hints'
AssertionError: Corrupted segment reference count - corrupted index or hints

Platform: FreeBSD Onyx 12.0-STABLE FreeBSD 12.0-STABLE r347964 GENERIC amd64
Borg: 1.1.10  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 67820  CWD: /root
sys.argv: ['/usr/local/bin/borg', 'create', '-p', '-e', '/root/.cache', '-C', 'zlib,6', '-v', '/gdrive::Onyx-2019-10-19T00:53', '/usr/home', '/etc', '/root', '/www/cubox', '/www/fbh', '/usr/local/etc']
SSH_ORIGINAL_COMMAND: None

```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

[output.log](https://github.com/rclone/rclone/files/3747361/output.log)

The log is quite big, but I hope this helps

Issue opened with borgbackup https://github.com/borgbackup/borg/issues/4795

**Comment by ivandeex** [comment]
One possible reason for this (but investigation of your borg issue can find a different cause) is that borg repository locks will not be exclusive on rclone mounts.
Borg backup requires atomic mkdir (i.e. creating directory should fail if it exists already), as stated in docs https://borgbackup.readthedocs.io/en/stable/usage/general.html#file-systems
Contrary to that mkdir im rclone is non-atomic by design ie. all rclone backends are required to return success if directory already exists even if underlying storage would return error, eg. see code comment here https://github.com/rclone/rclone/blob/master/backend/mailru/mailru.go#L1084
As a result lock attempts from parallel borg processes will always succeed leading to corrupted repository.

A fix will require a new mount flag that adds an extra check for pre-existing directory in the vfs rclone layer. Again, investigation of https://github.com/borgbackup/borg/issues/4795 can find another cause.

**Comment by Cubox-** [comment]
I asked the borgbackup guys if mkdir being non-atomic was an issue, and it's not the case in this situation. Only if multiples backups are created on the same repo at the same time.

**Comment by ncw** [comment]
I had a go at replicating this using the rclone checkout as data to be backed up.

Run mount in one window

```
rclone mount --vfs-cache-mode full TestDrive:borg /mnt/tmp/ -vv --rc 2>&1 | tee borgmount.log
```

And then do the backup in another

```
export BORG_PASSPHRASE=potato
borg init /mnt/tmp -e repokey-blake2
borg create -p -e /tmp/borgcache3 -C zlib,6 -v /mnt/tmp::backup3 /home/ncw/go/src/github.com/rclone/rclone/
```

That did not tickle the bug and worked fine.  I was trying with `borg 1.1.9` from the ubuntu repo which isn't quite the latest.  I also tried with the latest `1.1.10` release with the same results.

Can you reproduce this on a set of data I have access to?

All tests done with 

```
$ rclone version
rclone v1.49.5-244-g18c029e0-beta
- os/arch: linux/amd64
- go version: go1.13.1
```

**Comment by Cubox-** [comment]
@ncw I don't think the rclone checkout data is big enough/close enough to my scenario to trigger the bug.

Since I'm trying to backup my /home, /etc /root /www directories, there will be both files in sizes up to 1G, and directories with a lot of small files (nodejs cache files comes to mind). In total, more than 20G of data is being used.
I'm really not sure how I can provide data you can access to match that. (All directories being backed up contains sensitive data in various forms).

**Comment by ncw** [comment]
What you could do is [run this program](https://github.com/ncw/make_test_files) and tell me the parameters that cause a problem.

It creates exactly the same files for the same parameters.

**Comment by Cubox-** [comment]
Sorry for the delayed response. I totally forgot to reply.
I managed to make borg get an error:
```
<root@Onyx>-</gdrive> λ borg create /gdrive::TEST /home/cubox/rclonetests/dir
Enter passphrase for key /gdrive:
Data integrity error: Invalid segment entry header [segment 42, offset 457649781]: unpack requires a buffer of 41 bytes
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 573, in do_create
    create_inner(archive, cache)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 536, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 650, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 650, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 650, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 8 more times]
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 624, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/local/lib/python3.7/site-packages/borg/archive.py", line 1063, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/local/lib/python3.7/site-packages/borg/archive.py", line 995, in chunk_file
    from_chunk, part_number = self.write_part_file(item, from_chunk, part_number)
  File "/usr/local/lib/python3.7/site-packages/borg/archive.py", line 973, in write_part_file
    self.write_checkpoint()
  File "/usr/local/lib/python3.7/site-packages/borg/archive.py", line 478, in write_checkpoint
    self.cache.chunk_decref(self.id, self.stats)
  File "/usr/local/lib/python3.7/site-packages/borg/cache.py", line 925, in chunk_decref
    self.repository.delete(id, wait=wait)
  File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 1125, in delete
    size = self.io.read(segment, offset, id, read_data=False)
  File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 1440, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 1452, in _read
    segment, offset, err)) from None
borg.helpers.IntegrityError: Data integrity error: Invalid segment entry header [segment 42, offset 457649781]: unpack requires a buffer of 41 bytes
```
The data being:
`./make_test_files -v -max-size 100000000 dir`

I went a bit on the heavy side, I'll try with a smaller max.

**Comment by Cubox-** [comment]
Smaller dataset won't trigger the bug

**Comment by Cubox-** [comment]
Given that borgbackup needs to edit files in a non-sequential manner, vfs cache mode off would not work at all. A cache is needed for borgbackup.
To be fair, this issue has made me have to abandon using rclone with borgbackups and use another method. I am still grateful for ncw's work on this, and if he tells me he thinks he fixed the issue, I would be happy to try again with an updated code.

For anyone wondering what I do now instead, I am using a NAS my company owns, where I tell borgbackup to ssh there and use a static binary I pushed.

**Comment by dragetd** [comment]
I have been experimenting with this as well.

borg seeks through the segment files and sometimes updates them at the end. By default segment files are 512MB in size. This can cause simple updates that change a segment file to cause rclone download the huge files which again causes huge delays.

Reducing the segmeint-size is easily possible and improves the responsiveness (i.e. borg create calls not haging for *hours*), tho it is still very sluggish. Did not investigate this any further.

The locking was another thing I suspected to be an issue. But I am not sure how exactly I could debug this.

Would a script or Docker container that recreates the issue, help?

**Comment by ncw** [comment]
@dragetd I'm currently re-working the VFS layer to make it have delayed uploads which will probably help with excess uploading and downloading.

In general changing existing objects is not very cloud storage friendly - nearly all the rclone backends have immutable objects (with the exception of local and sftp).

So tweaking down the segment size sounds like an excellent idea if that is something borg does.

It would be nice to make a recipe for [the rclone wiki](https://github.com/ncw/rclone/wiki) of the recommended settings for rclone and borg.

> Would a script or Docker container that recreates the issue, help?

That would be super helpful thank you :-)

**Comment by dragetd** [comment]
I have been working on a Dockerfile that automatically creates a borg archive, rclone mount, starts and runs things with logging etc.

But so far things seem to work nicely with the latest beta (v1.52.0). For performance reasons, a few tweaks are a good idea:
- using the chunker remote with e.g. 32M chunks for quicker reading (tho not sure if that really helps)
- using --vfs-caching with tuned parameters
- reducing borg segment sizes to e.g. 64M

So far it works. Slow (because borg is doing a lot of filesystem operations which cause a lot of API calls), but no errors.

I think #4104 might have been a reason for some of the issues. Thank you very much for fixing this!

I will try to move my (secondary) actual Backup-scripts towards a rclone mount and see if things break.

@Cubox- Try the latest beta - maybe you can confirm that things seem to work nicer than before!

**Comment by Cubox-** [comment]
I have tried with the latest beta, but I'm getting
`2020/05/11 01:04:48 Fatal error: failed to umount FUSE fs: fuse: malformed message
`
just from a borg init. Sigh

**Comment by dragetd** [comment]
@Cubox- 
I am using https://beta.rclone.org/v1.51.0-327-g4006345c-beta/ on amd64 on a 5.4 kernel. Borg 1.1.11.

My remote is a google drive or a wasabi S3 bucket (tested both).

```
> rclone mount -v --dir-cache-time 5m --vfs-read-chunk-size 8M --vfs-read-chunk-size 100M --vfs-cache-mode writes --vfs-cache-max-size 4G --vfs-cache-max-age 6h drive-1:backup /mnt/temp
> # (different shell)

> borg init -e repokey /mnt/temp/test.borg
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: 
Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /mnt/temp/test.borg

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

# Recuding the segment size from 512mb to 100mb. Improves the 'reaction time' of borg when saving or trying to cancel a backup.
# My educated guess for a recommodation to not skrew things up:  `32MB <= (100MB per expected TB total repo size) <= 512MB`
# If you have fast upload (>=50Mbit), the segment size can be left larger
> sed -i "s/max_segment_size = 524288000/max_segment_size = 104857600/" /mnt/temp/test.borg/config

> borg create --progress --stats -C zstd /mnt/temp/test.borg::test1 /usr/src
Enter passphrase for key /mnt/temp/test.borg:
…
------------------------------------------------------------------------------                                                                                                     
Archive name: test1
Archive fingerprint: beeaaa3993ba8ba4e1bfd423941a2aafd4ee3fd6d8f511b1003aaaa05dda2b3c
Time (start): Sun, 2020-05-17 19:26:10
Time (end):   Sun, 2020-05-17 19:28:06
Duration: 1 minutes 55.85 seconds
Number of files: 137000
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                1.81 GB            431.30 MB            231.50 MB
All archives:                1.81 GB            431.30 MB            231.50 MB

                       Unique chunks         Total chunks
Chunk index:                   66626               131642
------------------------------------------------------------------------------
```

Unmounted, mounted again and tried an extract, worked without issues. Extracting took ~50 seconds.

Maybe you could post your versions and also try running rclone mount with `-vv` and post the output you get when trying borg init.

All my tests work fine so far!

**Comment by segator** [comment]
I think delayed upload is the way to go, if we can set something like wait for 1minute (since last write) before upload then we are fine

**Comment by darthShadow** [comment]
@segator This option is already available with the VFS rewrite from version 1.53 onwards, specifically the `--vfs-write-back` option

**Comment by segator** [comment]
seems to work but i notice lot of downloading of chunks as borg is modifying his block files instead of appending new files.
I supose a combination of cache backend and VFS could works, so I supose should be fine to use VFS in  cache write mode + cache backend  as persistent cache, right?

**Comment by juliandddd** [comment]
Just chiming in to see what the latest is on this issue before I start a borg + rclone mount with vfs cache mode full backup strategy

**Comment by segator** [comment]
@juliandddd Using it since dicember without any problem adding rclone cache feature.
in my case even better because I use it in multiple machines pushing the backup to same repository via rclone mount(to get beneficial of deduplication), the only thing is that I need to clean cache every time I execute borg on another machine.

**Comment by hrv231** [comment]
> Just chiming in to see what the latest is on this issue before I start a borg + rclone mount with vfs cache mode full backup strategy

I'm doing that, I have on my unraid rclone running with mount to Google Drive, I use this rclone mount for my borg backup repository.
I found this thread looking for other people's config, same as [this one](https://github.com/borgbackup/borg/issues/4795) from borgbackup.
In my case, it is working perfectly, no problems so far, I have rclone mount with this config:
`rclone mount --cache-dir /mnt/disks/ud1/RClone_Caching_Folder/ --vfs-cache-mode full --max-read-ahead 1024k --allow-other encrypted: /mnt/disks/secure &`
and then I point my borg repository inside the _/mnt/disks/secure_ folder, so far running _borg create_ works with no issues.
This is what I run if it helps
`borg create --compression none --one-file-system --read-special --files-cache mtime,size --debug --show-rc --progress /ua_nvme1/testrepo::testrepo-{now} /mnt/user/repo1`

rclone v1.55.0
borg 1.1.15

What @dragetd  explains about reducing the segment size of borgbackup is something I need to try, that way the download from the cloud (in this case with rclone mount) would not take so long, because that's exactly what it is happening to me, and I'm backing up about 500GB.

The work from RClone developers and Borg developers is amazing, I definitely need to donate something to those guys!

Great work and thank you @ncw!

**Comment by dragetd** [comment]
@hrv231 You can change the segment size in the repo config even after repo creation. New data is always written into new segments (borg does not reuse segments) and these will have the smaller size. But because of the deduplicating nature or borg, most of the data will be still in the lower segments which will keep their size.

One could try to recreate the repository (https://borgbackup.readthedocs.io/en/stable/usage/recreate.html) if one wants to re-write the old segments (to new segment files) in-place.

The config also has a setting for files per directory. I suspect (did not check) that some remotes might be more resource-intensive to use with larger directories. I do not have any benchmarks to back those claims, would be interesting if someone measured this.
If desired, one could reduce the 1000 files per directory default of borg to something less. But of course this will create more sub-directories, especially if your backup grows and gets older. So I recommend not to reduce this number too much or just leave it at default.


Another update I have: I do not recommend write-caching (-vfs-cache-mode full). I managed to break the connection in a way that rclone managed to write part of the indexes without the segments, which borg does not like at all. One can repair the repository and recover the previous data, but via a rclone mount this is painfully slow and not guaranteed to fix things.

I switched to only read-caching for the vfs options. Some operations become more sluggish, but I think it is more robust.

**Comment by ncw** [comment]
> Another update I have: I do not recommend write-caching (-vfs-cache-mode full). I managed to break the connection in a way that rclone managed to write part of the indexes without the segments, which borg does not like at all. One can repair the repository and recover the previous data, but via a rclone mount this is painfully slow and not guaranteed to fix things.

That is probably an rclone bug... If you can give instructions on how to reproduce then you can open a [new issue](https://github.com/rclone/rclone/issues/new/choose) about it. It would be worth trying [the latest beta](https://beta.rclone.org/) too.

**Comment by dragetd** [comment]
A while (months) ago I tried writing some test-scripts that would torture rclone and borg to share it with you. That was when I 'discovered' that the latest rclone mount works very well (back when we had that renaming bug).

From then on, I have been using borg on rclone mount without issues (and with the cache). It was just a one-time thing where I had some connection issues and other things happening. I cannot really reproduce it by any scripts or anything. I just switched to read-only cache back then, to be on the safe site. Because 'repair' on that repository took… days.

So I cannot really share any more insights, sorry.

**Comment by ncw** [comment]
@dragetd thanks for trying! We do keep fixing corner cases in the VFS (filesystems are hard!) so :crossed_fingers: you won't see it again.

**Comment by hrv231** [comment]
I have some questions now that I have read the docs more; and finished with my Borg config.

If I'm using _--vfs-cache-mode writes_ or the _--cache-dir_, what good is to add _--cache-writes_?
I have seen some people using something like this:
`rclone mount --cache-dir /mnt/disks/ud1/RClone_Caching_Folder/ --vfs-cache-mode writes --fast-list --cache-writes --allow-other`

FYI, _--write-back-cache_ There is not too much documentation about this flag.

_--vfs-read-ahead_ bytes ahead
The docs explains how to use _vfs-read-ahead_ when _cache-mode_ is _full_, but it doesn't tell me if I can use it when the cache-mode is _writes_, or if it is not needed with this mode.

Does it make sense to add _buffer-size_ to something big like 1G if I have a lot of RAM on my system?
--buffer-size 1024M
Does it improve something if I use it with my rclone mount?

Is _--buffer-size_ or _--vfs-read-ahead_ only use for _cache-mode full_?

What I'm looking for with all my questions is to optimize my rclone mount and provide more stability.

This is what I'm running now:
`rclone mount encrypted: /mnt/disks/secure --cache-dir /mnt/disks/ud1/RClone_Caching_Folder/ --vfs-cache-mode writes --max-read-ahead 102400k --fast-list --log-level DEBUG --log-file /mnt/disks/ua_nvme1/rclonelogfile.log --allow-other --vfs-write-back 15s &`

**Comment by hrv231** [comment]
> @hrv231 You can change the segment size in the repo config even after repo creation. New data is always written into new segments (borg does not reuse segments) and these will have the smaller size. But because of the deduplicating nature or borg, most of the data will be still in the lower segments which will keep their size.
> Another update I have: I do not recommend write-caching (-vfs-cache-mode full). I managed to break the connection in a way that rclone managed to write part of the indexes without the segments, which borg does not like at all. One can repair the repository and recover the previous data, but via a rclone mount this is painfully slow and not guaranteed to fix things.
> I switched to only read-caching for the vfs options. Some operations become more sluggish, but I think it is more robust.

Thank you @dragetd

**Comment by dimitarvp** [comment]
> You can change the segment size in the repo config even after repo creation

@dragetd You can?! So what happens if I get to my Borg repo `config` file, change the `max_segment_size`, then call `borg create` and then `borg prune`? Will all existing segments be broken apart on smaller files, or only from the last snapshot and on?

(Sorry for off-topic, I know this is `rclone`-s issue tracker but I really can't find a good help article on Borg about how to tweak various parameters of a Borg repo after creation.)

**Comment by dragetd** [comment]
Borg does not change old segments, this is only valid for new segments. There is 'recreate', but this is very slow and needs extra space.

Again, I recommend not using write caching. :)

**Comment by eike-fokken** [comment]
@dragetd Could you share your precise command line for both rclone and borg? I would probably like to copy it.

**Comment by anaxonda** [comment]
Could anyone explain why I am unable to run borg commands as root with an rclone mounted drive?

I have a google drive folder mounted with this command:
`rclone mount -v --dir-cache-time 5m --vfs-read-chunk-size 8M --vfs-read-chunk-size 100M --vfs-cache-mode writes --vfs-cache-max-size 4G --vfs-cache-max-age 6h gdrive:/ /home/user/gdrive/`

Running borg create with sudo gives `PermissionError: [Errno 13] Permission denied: '/home/user/gdrive/backups/mainbackup_gdrive.borg'`.

Running borg create as non-root works, but I would like to be able to run as root to backup root directories.

**Comment by ncw** [comment]
@anaxonda add `--allow-other` to your `rclone mount` command. (Check it is allowed in `/etc/fuse.conf` first)

**Comment by edsonsbj** [comment]
> Alguém poderia explicar por que eu sou incapaz de executar comandos borg como root com uma unidade montada rclone?
> 
> Eu tenho uma pasta do Google Drive montada com este comando: `rclone mount -v --dir-cache-time 5m --vfs-read-chunk-size 8M --vfs-read-chunk-size 100M --vfs-cache-mode writes --vfs-cache-max-size 4G --vfs-cache-max-age 6h gdrive:/ /home/user/gdrive/`
> 
> Correr borg criar com sudo dá.`PermissionError: [Errno 13] Permission denied: '/home/user/gdrive/backups/mainbackup_gdrive.borg'`
> 
> Executando borg create como não-root funciona, mas eu gostaria de ser capaz de executar como root para backup de diretórios raiz.

you need to add the --allow-other flag in your rclone mount command

**Comment by darthShadow** [comment]
Closing as answered.
