### ISSUE TITLE
rclone config wipes entire .config/rclone directory (including old files)

### ISSUE THREAD

**Issue by jeff-geoff** [rclone/rclone#3759]
#### What is the problem you are having with rclone?
I moved my rclone.conf to rclone.conf.old
re-ran rclone config,
and it deleted rclone.conf.old in addition to creating a new rclone.conf

#### What is your rclone version (output from `rclone version`)
rclone v1.50.2
- os/arch: darwin/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOS 10.15

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone config

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

N/A

**Comment by ncw** [comment]
Rclone usually keeps a a backup of the previous config as `rclone.conf.old` which explains what you saw.

I'm sorry about that...

What do you think rclone should do? We should probably document the `rclone.conf.old` name somewhere at minimum.

**Comment by jeff-geoff** [comment]
Well, the behavior I experienced may have been slightly different than expected behavior, then.

To explain in more detail--
I copied my rclone.conf to a .old (manually), deleted the original rclone.conf (also manually).  At this point the directory *only* contained a .old.

Then I ran rclone config again, intending to end up with a new .conf, and the .old I had created manually--However, I did not end up with a backup of the previous config at all.  Either my own moved copy, nor a .old created by rclone config as you describe.

I ended up with only the new rclone.conf, and the .old I had manually created was wiped; the directory contained only one file and it was the new rclone.conf.

My assumption is that rclone config is overwriting the entire directory, but I have not checked the repo to confirm this.

Because that is not expected behavior generally speaking (I would not expect anything to nuke another file without at least a warning), I can't imagine many people would even check the docs to see if rclone wanted to do this.

I think my assumption was that rclone config simply modified/updated rclone.conf in place, not that it replaced the .conf with a freshly written .conf
If I moved the contents of rclone.conf to another file in the same directory I could preserve my old configuration, then.

If that's not possible, I would suggest either having rclone config enumerate the .old files (rclone.conf.old.2, rclone.conf.old.3, rclone.conf.old.4, etc.)
or
simply prompt the user before changes are made, which is probably easier to add.

e.g. What would you like rclone to do with its current config file?
1. provide a path to which we should move the current .conf
2. to nuke the current .conf file and completely replace it leaving no backup of the current version

**Comment by eharris** [comment]
It seems to me that rclone shouldn't step on a backup file if it didn't create or put it there itself.  So when it renames the current conf to .old, it should do so without clobbering an already existing file.

If rclone wants to keep a temporary backup of the config file while it's in the process of modifying it, it seems like using the facilities provided by io/ioutil would be more appropriate and safer: https://golang.org/pkg/io/ioutil/#TempFile

**Comment by ivandeex** [comment]
I suggest describing this behaviour in the docs.

**Comment by ncw** [comment]
I think we have documented the way it works now which is good.

Can we improve that is what this issue is about I guess?

The code in question is here

https://github.com/rclone/rclone/blob/f4c787ab74c1efe0eb242b3e867cc20b9ddb61c9/fs/config/configfile/configfile.go#L157-L165

instead of using `rclone.conf.old` we could use the temporary name we've already generated so `rclone.conf.XXXXXX` (`f.Name()`) and add a suffix `.old` - this would mean there was never a collision between what we are doing and user stored files. Or we could generate a new temporary name which is guaranteed not to exist.

What do you think?

PS saving files reliably is hard :-)

**Comment by albertony** [comment]
> PS saving files reliably is hard :-)

Agreed! :) But I think doing something along the lines you suggest would be a nice improvement.

> instead of using rclone.conf.old we could use the temporary name we've already generated so rclone.conf.XXXXXX (f.Name()) and add a suffix .old - this would mean there was never a collision between what we are doing and user stored files.

That would be a good fix, for sure. However in theory there could be a collision, as I understand it: The temporary name created with os.CreateTemp, i.e. `rclone.conf.XXXXXX` from your example, is guaranteed to be unique, but when appending .old to that then there are no guarantees that `rclone.conf.XXXXXX.old` does not already exist. I would say the probability is very low, close to zero, though.

> Or we could generate a new temporary name which is guaranteed not to exist.

That would be the ideal solution. Slightly slower (new random number + extra stat/exsits-check, possible loop), but I guess negligible in this case? Maybe we should just go for this, to fix it once and for all (yeah right, I wish...).

The only downside I can think of (with either of the two approaches), is that if for whatever reason rclone fails to delete the `.old` files then it would keep filling the directory with new files on each update instead of removing/overwriting the single file as it does today. Unlikely, and minimal problem.

Then we should also do your suggestion regarding symlinks at the same time, probably:

> However, what rclone could do is detect if the config file is a symlink and then read the link and use that path as the path to the config file. That would work with rclone and have the nice properties we need and work around this issue too.

You mean rclone should consider the directory of the path pointed to by the symlink, write updated config file directly in that directory, and also create temp files in that directory while doing so? Is this safe to do, or could it lead to permission issues do you think? I mean, can user have (write) access to symlink and symlinked file but not permissions to create additional files in that path?
