### ISSUE TITLE
Could not remove MinAge filter when using 'rclone rc'

### ISSUE THREAD

**Issue by meh-mah** [rclone/rclone#3783]
#### Problem statement:
I am trying to set and reset the MinAge through the options/set command as follow:
```rclone rc options/set --json '{"filter":{"MinAge":<age in nano sec>}}' --rc-addr=<ip:port> --rc-user=<user> --rc-pass=<pass>```
No problem to set the MinAge. But could not remove such filter and ensure there is no MinAge limit. I mean when you run rclone rcd there is no filter regarding the min age. And the MinAge is 9223372036854776000 by default.

#### rclone version
rclone v1.49.1
- os/arch: windows/amd64
- go version: go1.12.3

#### OS
Multiple OS and versions

####  Storage
Swift

#### The command  trying to run
`rclone rc options/set --json '{"filter":{"MinAge": 9223372036854775807}}"`

#### log

ERROR : rc: "options/set": error: failed to write options from block "filter": Reshape failed to Unmarshal: json: cannot unmarshal number 9223372036854776000 into Go struct field Opt.MinAge of type fs.Duration

**Comment by ncw** [comment]
Sorry for the delay responding!

I think the problem is that the JSON decoding is doing a round trip through floating point numbers and 2^^63-1 is larger than the largest integer a float64 can hold.  The number you entered gets rounded to a number slightly bigger than an `int64` and there is no way of entering the exact number 2^^63-1.

This could be solved by adding a JSON Marshal and Unmarshal to the fs.Duration type.

This could also take other values like "off" (as a string).

What do you think?  Do you want to have a go at implementing it?

**Comment by KDreynolds** [comment]
I can take a stab at this one.

**Comment by ncw** [comment]
@KDreynolds great - thank you :-) Let me know if you need help.
