### ISSUE TITLE
Google team disk  200,000 files

### ISSUE THREAD

**Issue by Songxwn** [rclone/rclone#3827]
The Google team disk is limited to 200,000 files. I hope that the upload can be combined and uploaded. Bypass this restriction

**Comment by ncw** [comment]
What is your use case for rclone?

**Comment by Songxwn** [comment]
backup file.
Too many small files, more than 400,000

**Comment by mxdpeep** [comment]
Google Shared Drive can contain a maximum of 400,000 files and folders

if you have more files, compress it before syncing or sync to non-shared folder, aka User folder

**Comment by ncw** [comment]
If you are using rclone for backup then you could use [restic](https://restic.org) with it which can backup to google drive via rclone.  That packs small files together so you'll remain below the files limit.

For example my laptop has this many files

```
Total objects: 1264815
Total size: 203.586 GBytes (218598737207 Bytes)
```

which restic backs up to this many files.  This includes incremental backups which is why the total is bigger.

```
$ rclone size remote:backup
Total objects: 72353
Total size: 324.240 GBytes (348150534919 Bytes)
```

**Comment by Songxwn** [comment]
> 如果您使用rclone进行备份，则可以使用[restic](https://restic.org)，它可以通过rclone备份到Google驱动器。它将小文件打包在一起，因此您将保持在文件限制以下。
> 
> 例如我的笔记本电脑有这么多文件
> 
> ```
> Total objects: 1264815
> Total size: 203.586 GBytes (218598737207 Bytes)
> ```
> 
> Restic备份到这么多文件。这包括增量备份，这就是为什么总量更大的原因。
> 
> ```
> $ rclone size remote:backup
> Total objects: 72353
> Total size: 324.240 GBytes (348150534919 Bytes)
> ```
Thank you very much, I will try
