### ISSUE TITLE
Standardize with rsync path declarations

### ISSUE THREAD

**Issue by InAnimaTe** [rclone/rclone#383]
As I use rclone more and more, I've noticed the requirement around source directory copying...and frankly, it really should be changed to resemble how rsync actually works.

This means that `copy supercooldir hubic_remote:cake` should copy the directory `supercooldir` into the `cake` bucket, not the contents. However, `copy supercooldir/ hubic_remote:cake` should actually copy the contents of `supercooldir` into the `cake` bucket.

From the rsync man page: 

> A trailing / on a source name means "copy the contents of this directory". Without a trailing slash it means "copy the directory". 

I'm not sure if there's been any discussion on this already so forgive me if this has already been proposed.

**Comment by ncw** [comment]
Sorry I missed this ticket!

Yes there has been some discussion on this.

I'm of the opinion that rsync's way of doing it, while clever, is extremely error prone and a mis-feature.

If you type

    rsync -av --delete /path/to/my/files dest:/path/to/backup

Then one say with a bit of command line completion help, type

    rsync -av --delete /path/to/my/files/ dest:/path/to/backup

Then you just deleted all the files in your backup and re-uploaded them :-(

I made rclone so that the trailing slash is irrelevant like it is in the rest of the unix world and it always refers to the directory contents.

I did write this in the docs to address this point for new users

> If you are familiar with `rsync`, rclone always works as if you had
> written a trailing / - meaning "copy the contents of this directory".
> This applies to all commands and whether you are talking about the
> source or destination.

I think, practically speaking, it is too late to change it, even if I wanted to :-(

**Comment by jody-frankowski** [comment]
> I made rclone so that the trailing slash is irrelevant like it is in the rest of the unix world and it always refers to the directory contents.

Isn't it the exact contrary?
`cp -r directory dest` will copy the directory itself, not just its content.

IMHO it would be better if it was that way in rclone. As for copying only the content of the directory you could either implement rsync's trailing slashway , or the '*' wildcard if you think it is too much error prone (or maybe both).

**Comment by ncw** [comment]
@jody-frankowski I'm going to fix this with two new commands `cp` and `mv` which will work exactly like their unix counterparts unlike `copy` and `move`

**Comment by jody-frankowski** [comment]
@ncw Awesome, thanks.
But don't you think that from the user point of view it will start to get confusing?
There would be 5 somewhat similar commands: `copy` `move` `sync` `cp` `mv`

I still think having one (and only one) command named `copy` or `cp` that would copy the directory itself, but could copy the files with a `*` wildcard would be better. At least less confusing for the users.

Another solution would be having only one command (`sync` or `rsync`) that would behave like `cp` with no flags, like `mv` with the `--remove-source-files` flag, and like `rsync` itself with some additional flags. However imho it would be harder for users that have no knowledge of how rsync works.

**Comment by 19wolf** [comment]
So I'm having some trouble with this. I'm using a Backblaze bucket "b2:mybucket" and I ran `rclone sync /data/Media/Photos/2018/ b2:mybucket` and ended up with my bucket containing ex "March" "April" "May" instead of "2018" with subdirs "March" "April" "May". How do I make it do what I want, without copying over my whole Photos directory? I'm trying to back up my photos by most recent to least recent, but eventually I'll have 2010-2018 with subdirs for each month therein.

**Comment by sedlund** [comment]
what is the equivalent for 

`rsync b2:mybucket/data/myfile* .`

in rclone?

I've tried copy, copyto, sync, --include, --exclude, --filter etc...

It just seems there are way too many options to do something that should be trivial.

**Comment by ncw** [comment]
> what is the equivalent for
> 
> `rsync b2:mybucket/data/myfile* .`
> 
> in rclone?

    rclone copy b2:mybucket . --include "myfile*"

Should do it.

**Comment by sedlund** [comment]
>> rclone copy b2:mybucket . --include "myfile*"
>Should do it.

Thanks @ncw this does copy the file,  but this also copies all the directories underneath that path without the files.

```
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5

```

```
--- start filters ---
--- File filter rules ---
+ (^|/)myfile[^/]*$
- ^.*$
--- Directory filter rules ---
+ ^.*$
- ^.*$
--- end filters ---
2019/03/11 17:34:25 NOTICE: myfile_superneat: Not copying as --dry-run
2019/03/11 17:34:26 NOTICE: blah: Not making directory as dry run is set
2019/03/11 17:34:26 NOTICE: blah2: Not making directory as dry run is set
etc...
```

**Comment by ncw** [comment]
> Thanks @ncw this does copy the file, but this also copies all the directories underneath that path without the files.

You want `--include /myfile*` then to just copy files in the root - hopefully that will work :-)

**Comment by animosity22** [comment]
@InAnimaTe  - Is this still an open item or can it be closed out?

**Comment by InAnimaTe** [comment]
I haven't used rclone in 3 years so probably something that can be closed.
