### ISSUE TITLE
--no-gzip-encoding flag not honored on Google Drive

### ISSUE THREAD

**Issue by Dibbyo456** [rclone/rclone#3872]
Rclone adds `Accept-Encoding: gzip` header on requests even when the `--no-gzip-encoding` flag is present.

```
2020/01/12 21:10:55 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "about" "gdrive2:" "--log-file=rclone2.log" "--fast-list" "-vv" "--dump=headers" "--no-gzip-encoding"]
2020/01/12 21:10:55 DEBUG : Using config file from "C:\\Users\\HARRY\\.config\\rclone\\rclone.conf"
2020/01/12 21:10:55 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/01/12 21:10:55 DEBUG : HTTP REQUEST (req 0xc0001f0d00)
2020/01/12 21:10:55 DEBUG : GET /drive/v3/about?alt=json&fields=storageQuota&prettyPrint=false HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.50.2
Authorization: XXXX
X-Goog-Api-Client: gl-go/1.11.0 gdcl/20190802
Accept-Encoding: gzip
2020/01/12 21:10:55 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/01/12 21:10:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/01/12 21:10:56 DEBUG : HTTP RESPONSE (req 0xc0001f0d00)
```

**Comment by Yexiaoxing** [comment]
The debugging information is not accurate. 

In https://github.com/rclone/rclone/blob/master/fs/fshttp/http.go#L333, the request is dumped using `httputil.DumpRequestOut`. This method will generate a new `http.Transport` to mock and dump the request, but not using our customized Transport. By default, `http.Transport` enables Gzip compression, and that's the reason why `Accept-Encoding: gzip` is appended in the headers.

One possible solution (actually a trick) is to explicitly add `Accept-Encoding` header to the request before dumping, and restore the header afterward.

**Comment by ncw** [comment]
Doing a test with a compressible file (1GB of zeros) I can see that the flag is working...

No flag

```
$ rclone copyto -v --multi-thread-streams 0 TestDrive:1GB-zeros  /tmp/1GB-zeros3
2020/01/13 07:41:35 INFO  : 1GB-zeros: Copied (new)
2020/01/13 07:41:35 INFO  : 
Transferred:   	        1G / 1 GBytes, 100%, 204.697 MBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:          5s
```

With flag

```
$ rclone copyto --stats 10s -v --multi-thread-streams 0 TestDrive:1GB-zeros  /tmp/1GB-zeros4 --no-gzip-encoding
2020/01/13 08:17:26 INFO  : 
Transferred:   	   31.996M / 1 GBytes, 3%, 3.310 MBytes/s, ETA 4m59s
Transferred:            0 / 1, 0%
Elapsed time:        9.6s
```

@Yexiaoxing - you are right.  I checked the standard library code and that is exactly what it does!

> One possible solution (actually a trick) is to explicitly add `Accept-Encoding` header to the request before dumping, and restore the header afterward.

I think that would be worth doing if we could get the transport to calculate it for us.  Do you know if there is a way of doing that @Yexiaoxing ?  Otherwise I think we are heading into trouble with debugging tools not showing us the truth!

Perhaps a note in the docs might be appropriate that using `--dump header`

- will automatically decompress data
- may not show `Accept-Encoding` headers properly

**Comment by Yexiaoxing** [comment]
> I think that would be worth doing if we could get the transport to calculate it for us. Do you know if there is a way of doing that @Yexiaoxing ? Otherwise I think we are heading into trouble with debugging tools not showing us the truth!

I also tried it. Thanks to the Golang feature, the extra headers set by the transport during the round trip are inaccessible by outer codepath... 

The standard library does not allow us to use a customized transport. 

Also there are actually two headers affected, another is Connection-Close or something else if I remember it wrong.

There might be some possible solutions.

1. Copy the `DumpRequestOut` function and use our transport. A bit difficult but may worth since it is the reality.
2. Mock the two headers. Simple but may be broken again in the future if upstream changes the algorithm.
3. Do nothing. Print a warning at the beginning. Most simple one.

Funny fact: I digger into the source code trying to understand why the property was lost, spending hours before I discover the fact. I was also surprised by that there is no body talking about this missing feature in the internet.

**Comment by ncw** [comment]
Thanks for the investigation @Yexiaoxing 

I think that this is a minor problem in the scale of things (no-one has complained about it in the 7 year history of rclone), so probably just a note in the docs is my favourite approach.

Something like

> Note that the `Accept-Encoding` as shown may not be correct in the request and the response may not show `Content-Encoding` if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
