### ISSUE TITLE
No count of deleted files in summary output

### ISSUE THREAD

**Issue by perception101** [rclone/rclone#390]
rclone version,

```
$ rclone -V
rclone v1.28
```

OS version

```
$ uname -a
CYGWIN_NT-10.0 Neptune 2.4.1(0.293/5/3) 2016-01-24 11:26 x86_64 Cygwin
```

I run rclone from the Cygwin command line, but it's the standard Windows version of rclone.  Windows 10, 64bit.

I'm using Google Drive.

This is the command in question.

```
rclone sync `cygpath -w -a /cygdrive/d/Users/Tony/Pictures/` googledrive:\\Backups\\Pictures`
```

The command works fine, and it deletes the files on the remote.  What it doesn't do, is report anything in the summary for deleted files.  There are over 65,000 objects, so I've not included a full log.

So I get,

```
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:             62838
Transferred:            0
Elapsed time:     7m39.1s
```

What I'd like is a 'Deleted:    xxxx' entry?

**Comment by klauspost** [comment]
Could easily be added as part of #389

**Comment by ivandeex** [comment]
@ncw 
This has probably been fixed by:
- https://github.com/rclone/rclone/pull/389#issuecomment-413928369
- https://github.com/rclone/rclone/issues/2347#issuecomment-414679743
- https://github.com/rclone/rclone/commit/b6db90cc322c1187da7afb108a6171163ad1d85d
- https://github.com/rclone/rclone/commit/80a3db34a884c0ca070abd5820481d7dee810156
- https://github.com/rclone/rclone/commit/6390dec7dbca8bcbcf1cb0a0da7f22e42007c502

**Comment by ncw** [comment]
Yes, I agree this has been fixed already.
