### ISSUE TITLE
Webgui rclone gets disconnected as I leave command line

### ISSUE THREAD

**Issue by Merlincool** [rclone/rclone#3910]
#### Output of `rclone version`

rclone v1.50.2-194-gbfd9f321-beta
- os/arch: linux/amd64
- go version: go1.13.6

#### Describe the issue

As soon as I leave command line,rclone gets disconnected. Is there a way to keep rclone browser continuously on so I can browse when and where needed. I don't want to open my headless server terminal and drop down rclone browser commands always to keep browsing rclone. Is there a way so I can keep my browser alive even when I leave command line and close terminal.

Instead of attaching screen and keeping rclone browser alive. Is there a way without it?

I am new to linux but I am fascinated to use rclone.

Also one more thing, I do not see any option that will transload files from vps to google drive using browser, I am missing something. There are lot of options in backend but I haven't touch anything.

**Comment by Yexiaoxing** [comment]
That's how Linux works :)
You can use `screen` or `tmux` to make it running under their control, or you may write a systemd (or any other init you are using) service to run in the background. If you are only running it once, try `nohup`.

This seems to be a usage question rather than issues. You may raise it in our forum next time: https://forum.rclone.org/.

**Comment by ncw** [comment]
This is really a question [the rclone forum](https://forum.rclone.org/) - @Yexiaoxing 's advice looks good to me though.
