### ISSUE TITLE
Sanitizing --filter-from input?

### ISSUE THREAD

**Issue by o0-o** [rclone/rclone#4050]
I have a quick question that I need to ask before I deploy this at work.

Are files passed to `--filter-from` thoroughly sanitized or is there a potential for arbitrary execution there?

If so, please disregard, otherwise, I am requesting it as a feature.

**Comment by ncw** [comment]
Rclone is written in Go which is a [memory safe language](https://en.wikipedia.org/wiki/Memory_safety) so I'd say the chance for arbitrary execution is very very low. Go doesn't have buffer overruns or dangling pointers or heap free problems so much of the attach surface for a C program isn't present.

> Are files passed to `--filter-from` thoroughly sanitized or is there a potential for arbitrary execution there?

The contents of the files are parsed by rclone. Irregular input will cause rclone to return an error, or at worst crash in a controlled way, it should never (due to the protections of the go language) do arbitrary execution.

I guess the question you are asking is, "is it safe to pass untrused data to --filter-from". I haven't fuzzed `--filter-from` so it might crash rclone, but I'm pretty sure that would be the worst outcome.

Does that help?

**Comment by o0-o** [comment]
Thanks, that's good to know.

Yes, my concern is untrusted data passed to `--filter-from`. I am not really concerned with a sophisticated attack on system memory or similar (although good to know that should not be possible). I mainly just need to know that it's not possible to arbitrarily pass arguments to rclone or break out into the shell via a malicious `--filter-from` file.

**Comment by ncw** [comment]
I think you are good to go then :-)

(With the usual caveat about software being complicated, security being doubly so and rclone not guaranteeing anything!)

I'll close this now.
