### ISSUE TITLE
Leave root - rclone move

### ISSUE THREAD

**Issue by agneevX** [rclone/rclone#4312]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.52.0
- os/arch: linux/arm
- go version: go1.14.3
```
#### What problem are you trying to solve?
Preserve root folder when using `rclone move`.

#### How do you think rclone should be changed to solve that?
A parameter, `--leave-root`.

##### [Discussion on the forum](https://forum.rclone.org/t/leave-root-with-rclone-move/16951)

**Comment by calisro** [comment]
My personal opinion is that if it can be done using filters, i'd rather see less flags.  In this case filters would work and I think its an edge case to leave the root as part of a move since typically a move involves moving the folder and not its entire contents.

**Comment by agneevX** [comment]
The docs should be at least updated to reflect this _hack_.

**Comment by calisro** [comment]
I don't believe this is a hack.  This is how the command was intended to function along with filtering.  

https://rclone.org/commands/rclone_move/#synopsis

> If no filters are in use and if possible this will server side move source:path into dest:path. After this source:path will no longer exist.

What do you think @ncw ?

**Comment by ncw** [comment]
If you want to preserve the root then you could

1. move all the files individually which is what the `--filter` trick does.
2. move them using DirMove (so renaming the directory) and then recreating the folder. This will be faster and you can do it with `rclone mkdir`
3. move them by using DirMove/Move on the contents of the folder. This will be faster than the `--filter` trick but a lot more code.

You could also do `--disable DirMove` instead of `--include *`

A slight annoyance is the `move` command isn't consistent. It may or may not leave the root depending on stuff...

I'm pretty sure this has come up before in the issues, but I can't find the issue.

If we were going to code anything then I'd prefer option 2 of the above which would only be a few lines of code.
