### ISSUE TITLE
Is there any way to skip verification code process[Gdrive Auth]?

### ISSUE THREAD

**Issue by 0-0eth0** [rclone/rclone#4413]
Hi there RCLONE team,
Thanks for this great project, i just wanted to get rid of that verification code part while authorize from google drive, let me know if there is any way to do it? i want to auth multiple gdrive accounts but its hard for my team team to share verification codes.
i just expect one link where user click on allow access without verification code process. 

Regards,
Jinay

**Comment by animosity22** [comment]
This is a great forum question as it's not really an issue.

You can use service accounts if that fits your needs as that helps to streamline that part if you are sharing things.

Otherwise, no, that's a Google thing, not a rclone item as you have to auth with a user account.

Feel free to follow up or ask on the forums:

https://forum.rclone.org

Thanks!
