### ISSUE TITLE
Google Shared Drive - Sync a specifc folder in a specific shared drive by ID

### ISSUE THREAD

**Issue by TaylorDale** [rclone/rclone#4419]
Context: I'm trying to sync a folder in a shared drive (Both ID's are known, and the use case changes between different folders and different shared drives). I want to only have one remote to access all of the shared drives because I'd otherwise manually have to create a list of shared drives and maintain it as it changes. I'd rather not use the named folders because I already have the ID's which is much more reliable than names which are subject to change.

So dynamic multi-shared drive support seems to be fine, and since using ID to select a file/folder isn't supported, my approach has been I can do this with the --drive-team-drive param to select the shared drive, and --drive-root-folder-id to set the desired folder as root for the sync. However since I'm impersonating a user, drive-root-folder-id gets ignored with

2020/07/08 03:18:49 NOTICE: Google drive root '': Ignoring cached root_folder_id when using --drive-impersonate

Is there any way for me to remedy this/An alternative way for me to sync when I know the specific ID's of the desired shared drive and the folder?

**Comment by ncw** [comment]
You can use the  --drive-team-drive param to set the root folder ID in the team drive - no need for --drive-root-folder-id.

**Comment by TaylorDale** [comment]
No luck.

`rclone lsd crossdrive: --drive-team-drive 1-1XXXXXXXXbYTGK
2020/07/08 12:22:52 ERROR : : error listing: couldn't list directory: googleapi: Error 404: Shared drive not found: 1-1-1XXXXXXXXbYTGK, notFound
2020/07/08 12:22:52 Failed to lsd with 2 errors: last error was: couldn't list directory: googleapi: Error 404: Shared drive not found: 1-1XXXXXXXXbYTGK, notFound`

**Comment by ncw** [comment]
I just checked the source - sorry that won't work because we need the root team drive ID as part of the listing call.

So you want to use

- `team_drive` to set the team drive root
- `root_folder_id` to set a specific directory with that team drive and
- `impersonate` - to set a specific user

This is all consequences from one lousy decision by me to cache the root folder id in `root_folder_id` automatically. This was a mistake because users set that field too. I've been trying to get myself out of that mess, but I'm not sure it is working!

This is also related to #4051 which is the exact opposite of your problem namely `root_folder_id` overriding `team_drive`.

> Since ba7c2ac, accessing a Google Drive remote adds a root_folder_id to the config file. Thereafter, thanks to 473a437 , the --drive-team-drive flag (or equivalent environment variable) is ignored on that remote.

I could do a work-around flag, say `--drive_root_id` which if set overrides the now problematic `--drive_root_folder_id`. That would leave
- `root_id` - user set ID of the root folder
- `root_folder_id` - cached root folder ID

Or I could cache the `root_folder_id` in a different variable, say `cached_root_folder_id` which could have a bit more cleverness in it (eg have a hash of the `impersonate` and `team_drive` variables), and issue a NOTICE if users are using `team_drive` or `impersonate` and if `root_folder_id` is set that they need to check it. This is closer to what I should have done originally and isn't too noisy.

What a mess!

Any thoughts?
If

**Comment by TaylorDale** [comment]
Thanks for following that up, personally I'd like to see some sort of indication in the naming that `root_folder_id` is actually a cached value and is subject to change as you say in the latter half. I wasn't expecting this behaviour and worked it out from my error messages, fairly simple but an upfront indication would be great. However that may be a more major change than the other option. I feel it's a much more sustainable/clean way of doing it however - especially with hashing it to the user's current settings to ensure it's only applied when it makes sense. 

Appreciate your work on this, we make extensive use of Rclone for many of our jobs.

**Comment by ncw** [comment]
Ok here is my plan

- revert root_folder_id to be entirely user configured
- introduce root_folder_id_cache which rclone manages. This will associate root_folder_id s with a hash of the Options struct.

That is what I should have done originally. To fix up the mess with rclone having cached values in root_folder_id I need to warn the user

- if root_folder_id is set in the config file (and isn't appDataFolder or root)
- and team_drive or impersonate is in use (config file, flags, env)
- tell the user to check the root_folder_id and remove if not in use with link to a wiki page with more explanation

This will leave no way to get rid of the warning in your (somewhat unusual) case. Is that acceptable?

**Comment by TaylorDale** [comment]
That sounds like a great solution to me, not worried about warnings as we're using this as part of a bigger program in remote control mode for reliably downloading a large folder of which we've already stored the ID of in a database. Cheers again.

**Comment by ncw** [comment]
I'm going to re-open this until I've made that change.

**Comment by ncw** [comment]
I've had a go at fixing this here

[v1.52.2-249-ga26ef2e3-fix-4419-drive-root-folder-id-beta](https://beta.rclone.org/branch/v1.52.2-249-ga26ef2e3-fix-4419-drive-root-folder-id-beta/) on branch [fix-4419-drive-root-folder-id](https://github.com/rclone/rclone/tree/fix-4419-drive-root-folder-id) (uploaded in 15-30 mins)

This removes all the caching of root_folder_id and just gives the user a hint in the debug messages that setting it would speed things up.

Testing much appreciated @TaylorDale

**Comment by ScuttleSE** [comment]
I encountered this issue today too. I have a folder shared on a GApp-user. It is shared among a number of users. I am using drive impersonate and service accounts to copy files to this drive, which doesn't work in the current version of rclone since I'm using root_folder_id to define the remote, while using drive_impersonate.

The beta seems to work fine.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53 or v1.52.3 whichever comes first

**Comment by systemmonkey42** [comment]
I've done a quick test of the beta and it seems to be working for me.

Thanks

**Comment by ncw** [comment]
Thanks for testing @systemmonkey42

**Comment by TaylorDale** [comment]
I've just got some time to test this out today, it's working great by the looks of it, am about to do some synchronising but LS is working just fine. 

Cheers
