### ISSUE TITLE
`rclone mount` configured by env variables uses invalid VFS cache dir on Windows

### ISSUE THREAD

**Issue by nthuemmel** [rclone/rclone#4544]
#### What is the problem you are having with rclone?

Using `rclone mount` with a non-persistent configuration (all settings given by environment variables) & VFS caching enabled attempts to use a VFS cache dir with illegal characters (`:`) on Windows.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.52.3
- os/arch: windows/amd64
- go version: go1.14.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows Server Core 2019 LTSC (64-bit) Docker Container (but I suspect the problem appears on all Windows versions)

####  Which cloud storage system are you using? (eg Google Drive)

Seafile (But I suspect the problem appears with all backends)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```powershell
$Env:RCLONE_SEAFILE_URL="https://example.com"
$Env:RCLONE_SEAFILE_USER="me@example.com"
$Env:RCLONE_SEAFILE_PASS="mypassword"
$Env:RCLONE_SEAFILE_LIBRARY="mylibrary"
rclone mount :seafile: R: --vfs-cache-mode writes
```

#### A log from the command

As soon as attempting to write a file to the mounted drive:

```
2020/08/30 23:33:45 ERROR : IO error: open RW handle failed to make cache directory: make cache directory failed: mkdir C:\Users\ContainerAdministrator\AppData\Local\rclone\vfs\:seafile: The filename, directory name, or volume label syntax is incorrect.
```

#### Workaround

Create a temporary config.

```powershell
rclone config create seafile seafile
rclone mount seafile: R: --vfs-cache-mode writes
```

Using `--cache-dir` does not help, since rclone always appends `vfs\:seafile` to the custom directory path.

**Comment by darthShadow** [comment]
Does this work as a workaround (from the example in the docs @ https://rclone.org/docs/#config-file):

```
$Env:RCLONE_CONFIG_MYSEAFILE_TYPE="seafile"
$Env:RCLONE_CONFIG_MYSEAFILE_USER="me@example.com"
$Env:RCLONE_CONFIG_MYSEAFILE_PASS="mypassword"
$Env:RCLONE_CONFIG_MYSEAFILE_LIBRARY="mylibrary"
rclone mount myseafile: R: --vfs-cache-mode writes
```

**Comment by ncw** [comment]
Ah, this is unfortunate!  @darthShadow 's workaround should get you going though while we work on a fix.

**Comment by nthuemmel** [comment]
Thanks! I have tested the workaround @darthShadow, and it works very well.

**Comment by ncw** [comment]
If someone wants to have a go at a fix, it should be easy

The problem lines are here

https://github.com/rclone/rclone/blob/bfcd4113c31bbde4ffd3bfa9fc0c1de228f9e6c0/vfs/vfscache/cache.go#L84-L86

`fremote.Name` returns the name of the remote

Probably what we need to do is get `fremote.Name()` into a variable then do something similar to this

https://github.com/rclone/rclone/blob/bfcd4113c31bbde4ffd3bfa9fc0c1de228f9e6c0/vfs/vfscache/cache.go#L82

Though it might be better to substitute the `:` with a character that can't appear in remote names but can appear in Windows file names rather than removing it, say `=`
