### ISSUE TITLE
Exit code 141 when pipeline doesn't consume all output

### ISSUE THREAD

**Issue by lverns** [rclone/rclone#4575]
#### What is the problem you are having with rclone?

When using bash with `set -o pipefail`, and piping the output of `lsf`, I frequently find the command exiting with status code 141.

It seems to only occur if the last command in the pipeline doesn't consume all the output. For example `| head -1` almost always triggers the failure state, but `| tail -1` does not, but `| sort -r | head -1` does trigger the failure state. 

#### What is your rclone version (output from `rclone version`)

```
rclone v1.53.0
- os/arch: linux/amd64
- go version: go1.15
```
Also occurs with
```
rclone v1.54.0-beta.4765.233bed6a7
- os/arch: linux/amd64
- go version: go1.15
```

#### Which OS you are using and how many bits?

Fedora 32, 64 bit

####  Which cloud storage system are you using?

SFTP

#### The command you were trying to run

`rclone -vv --ignore-times --ignore-size --config rclone.conf lsf --format tp remote:/ | head -1`

Note that if I drop the `| head -1` this returns 1273 lines.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

(some contents redacted)

```
2020/09/08 16:44:42 DEBUG : rclone: Version "v1.54.0-beta.4765.233bed6a7" starting with parameters ["rclone" "-vv" "--ignore-times" "--ignore-size" "--config" "rclone.conf" "lsf" "--format" "tp" "remote:/"]
2020/09/08 16:44:42 DEBUG : Using config file from "/home/user/rclone.conf"
2020/09/08 16:44:42 DEBUG : Creating backend with remote "remote:/"
2020/09/08 16:44:42 DEBUG : sftp://user@example.com:22//: New connection 192.168.50.224:53142-><redacted>:22 to "<redacted> SFTP"
2019-12-20 17:34:16;file20191220.csv
```

**Comment by lverns** [comment]
Oh! I just found an easier set of steps for reproduction:
```commandline
$ set -o pipefail
$ mkdir dir
$ for A in {0..1300}; do touch dir/$A; done
$ rclone ls dir | head -1
        0 0
$ echo $?
141
```

**Comment by ncw** [comment]
Exit code 141 (> 128) means that rclone exited with a signal. 141-128 = 13, signal 13 is (no surprise) SIGPIPE.

You need more than the pipe size of data to see this effect, which is why you need that many directory entries.

So what is happening here is that when `head` closes the input pipe, rclone gets a SIGPIPE signal and quits as head is finished with it.

I note also that `ls` behaves the same on your test directory

```
$ ls -l dir | head -1 ; echo $?
total 0
141
```

So I think that is is probably correct behavior.

If I modify rclone like this so it outputs "hello" infinitely and ignores SIGPIPE

```diff
@@ -513,8 +515,12 @@ func AddBackendFlags() {
 // Main runs rclone interpreting flags and commands out of os.Args
 func Main() {
 	rand.Seed(time.Now().Unix())
+	signal.Ignore(syscall.SIGPIPE)
 	setupRootCommand(Root)
 	AddBackendFlags()
+	for {
+		fmt.Println("hello")
+	}
 	if err := Root.Execute(); err != nil {
 		log.Fatalf("Fatal error: %v", err)
 	}
```

The rclone never exits here because it is still outputing data (or more likely blocked because the pipe buffer is full).

```
$ rclone ls dir | head -1
hello
(prompt not returned)
```

So I don't think rclone can ignore SIGPIPE. It could catch it and then exit with exit code 0, but I'm not a fan of that either as returning a 0 exit code when an error happened is bad....

There is a discussion of how to adapt your shell script to this here: https://stackoverflow.com/q/22464786/164234

**Comment by lverns** [comment]
Thanks for the thorough write up. While I'm still a little surprised, this is clearly standard behavior.
