### ISSUE TITLE
Copy the contents of the shortcut when server side copying (google drive)

### ISSUE THREAD

**Issue by rick65134** [rclone/rclone#4604]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.53.1
- os/arch: windows/amd64
- go version: go1.15

#### What problem are you are trying to solve?
Copy the contents of the shortcut when server side copying (google drive)

#### How do you think rclone should be changed to solve that?
Adding a flag to change this default action of copy to copy the contents of the shortcut.
And for the circular things, maybe we can combine such flag with a number to limit the tracking depth of shortcuts or the default depth of 1?
See more discussions on https://forum.rclone.org/t/copy-the-contents-of-the-shortcut-when-server-side-copying-google-drive/19094 .

Thanks!

**Comment by vaccarieli** [comment]
What is the new flag to copy contentes out of the shortcuts ?

**Comment by vaccarieli** [comment]
Is there a feature for this already in the Beta Version ?

**Comment by LaazV** [comment]
There's one weird thing with this. When copying shortcuts, rclone counts as if copying the file (if the file is 10gb, but it's just a shortcut, it creates a new shortcut, but it counts as if it's transfered 10gb).

It would be amazing to be able to actually copy the file and not the shortcut. I'm trying to copy a bunch of files that are linked with shortcuts to another drive which I do not own, and I can't do that. I have to copy them by hand, more than 2 thousand files.

**Comment by ncw** [comment]
This probably wouldn't be too hard if you wanted to have a go @LaazV ?

**Comment by ItoshikiMonset** [comment]
This will be great. I have the same problem when doing server side copy, whenever is a folder it copies the folder and its content but when it's a file it just copy the shortcut. I try put all the shortcut files in a folder and well, it didn't work. I know that's how it should work according the documentation, but it you can make it to copy files instead of shorcuts will be really good!

**Comment by abhiraj2** [comment]
doesn't this already happen, I can recount multiple times when I've only had a shortcut to the files and files on another drive but was able to copy the files completely.

**Comment by ncw** [comment]
@abhiraj2 this is talking specifically about server side copies - I expect you were doing a non server side copy.

**Comment by abhiraj2** [comment]
Correct, I used it for non-server side copy
How would one go about implementing it for server side copies?

**Comment by ncw** [comment]
> Correct, I used it for non-server side copy How would one go about implementing it for server side copies?

It would need a feature flag `--drive-copy-shortcut-contents` (say)  and a bit of code modification. Instead of calling `shortcutID(srcObj.id)` this bit of code would call `actualID(srcObj.id)` if the flag was set. I think that is enough.

https://github.com/rclone/rclone/blob/c26dc69e1b42e2b4ca1f845cb9682bc432366bf4/backend/drive/drive.go#L2377-L2378

**Comment by abhiraj2** [comment]
Alright I'll give it a go

**Comment by ncw** [comment]
Thanks to @abhiraj2 this is merged to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.58
