### ISSUE TITLE
Request add support for Gofile.io

### ISSUE THREAD

**Issue by JuanJ67m** [rclone/rclone#4632]
Gofile.io have "unlimited" upload capacity and such feature deserve a support by RClone.

https://gofile.io/welcome

**Comment by lasombra** [comment]
@ncw I would be interested to give this a try, but I haven't developed in Go besides the official tutorial. Would that work out for you?

**Comment by animosity22** [comment]
I can assure you I cannot develop much at all so that would be fine.

@ncw is a superb explainer and helper in terms of helping you along if you want to pick it up and have a go at it.

**Comment by buengese** [comment]
I think that might have to wait a little longer. The api on their page seems to be very early and incomplete and doesn't quite provide the minimum feature-set we usually want to have for rclone. (e.g. right now there seems to be no support for folders at all).

(Also unlimited storage for free kinda is an unusual business model... I can't see that site living for long)

**Comment by lasombra** [comment]
@buengese that's true and one of the reasons I jumped in. Although it's very incipient, it could help serve as an entry-level implementation or would you recommend something else?

**Comment by hereisderek** [comment]
folder support seems to have been added, anyone interested in giving it a go now?

(and that it has survived two years now)

**Comment by rizkidewanto** [comment]
Any update on this? File storage seems promising, despite the "storage duration" limitations

**Comment by animosity22** [comment]
> Any update on this? File storage seems promising, despite the "storage duration" limitations

Unless you plan to:

1) submit a PR
2) have someone else that can do a PR
3) plan to sponsor it

It'll not have an update as it's in the new remote backlog with very little interest..

**Comment by JannickNijholt** [comment]
Seems interesting to add?

**Comment by samuelchristlie** [comment]
What's the status on this provider? Just recently came across this issue and noticed that @ncw has already started working on it. If help is still needed, I'm interested in contributing :)

**Comment by ncw** [comment]
@samuelchristlie it is in development. I will post a beta when it is ready for testing

**Comment by ncw** [comment]
Here is a beta for testing.

[v1.68.0-beta.8161.7194d828d.fix-4632-gofile](https://beta.rclone.org/branch/fix-4632-gofile/v1.68.0-beta.8161.7194d828d.fix-4632-gofile/) on branch [fix-4632-gofile](https://github.com/rclone/rclone/tree/fix-4632-gofile) 

Any testing much appreciated.

# Gofile docs (cut down)

The initial setup for Gofile involves logging in to the web interface
and going to the "My Profile" section. Copy the "Account API token"
for use in the config file.

## Configuration

Here is an example of how to make a remote called `remote`.  First run:

     rclone config

This will guide you through an interactive setup process:

```
No remotes found, make a new one?
n) New remote
s) Set configuration password
q) Quit config
n/s/q> n

Enter name for new remote.
name> remote

Option Storage.
Type of storage to configure.
Choose a number from below, or type in your own value.
XX / Gofile
   \ (gofile)
Storage> gofile

Option access_token.
API Access token
You can get this from the web control panel.
Enter a value. Press Enter to leave empty.
access_token> YOURACCESSTOKEN

Edit advanced config?
y) Yes
n) No (default)
y/n> n

Configuration complete.
Options:
- type: gofile
- access_token: YOURACCESSTOKEN
Keep this "remote" remote?
y) Yes this is OK (default)
e) Edit this remote
d) Delete this remote
y/e/d> y
```

Once configured you can then use `rclone` like this,

List directories and files in the top level of your Gofile

    rclone lsf remote:

To copy a local directory to an Gofile directory called backup

    rclone copy /home/source remote:backup

### Modification times and hashes

Gofile supports modification times with a resolution of 1 second.

Gofile supports MD5 hashes, so you can use the `--checksum` flag.

### Restricted filename characters

In addition to the [default restricted characters set](/overview/#restricted-characters)
the following characters are also replaced:

| Character | Value | Replacement |
| --------- |:-----:|:-----------:|
| !         | 0x21  | ！           |
| "         | 0x22  | ＂           |
| *         | 0x2A  | ＊           |
| :         | 0x3A  | ：           |
| <         | 0x3C  | ＜           |
| >         | 0x3E  | ＞           |
| ?         | 0x3F  | ？           |
| \         | 0x5C  | ＼           |
| \|        | 0x7C  | ｜           |


File names can also not start or end with the following characters.
These only get replaced if they are the first or last character in the
name:

| Character | Value | Replacement |
| --------- |:-----:|:-----------:|
| .         | 0x2E  | ．           |

Invalid UTF-8 bytes will also be [replaced](/overview/#invalid-utf8),
as they can't be used in JSON strings.

### Public Links

Gofile supports `rclone link` to make public links to files or
directories. If you specify a directory it will download as a `zip`
file. You can use the `--expire` flag to specify the time the link
should be valid. Note that `rclone link --unlink` removes all the
public links for a file.

### Root folder ID

You can set the `root_folder_id` for rclone.  This is the directory
(identified by its `Folder ID`) that rclone considers to be the root
of your Gofile drive.

Normally you will leave this blank and rclone will determine the
correct root to use itself and fill in the value in the config file.

However you can set this to restrict rclone to a specific folder
hierarchy.

In order to do this you will have to find the `Folder ID` of the
directory you wish rclone to display.

You can do this with rclone

```
$ rclone lsf -Fip --dirs-only remote:
d6341f53-ee65-4f29-9f59-d11e8070b2a0;Files/
f4f5c9b8-6ece-478b-b03e-4538edfe5a1c;Photos/
d50e356c-29ca-4b27-a3a7-494d91026e04;Videos/
```

The ID to use is the part before the `;` so you could set

```
root_folder_id = d6341f53-ee65-4f29-9f59-d11e8070b2a0
```

To restrict rclone to the `Files` directory.

**Comment by Elshepl** [comment]
Is this only for the paid plan, and is there any way to use it with the free version?

**Comment by Elshepl** [comment]
> Here is a beta for testing.
> 
> [v1.68.0-beta.8161.7194d828d.fix-4632-gofile](https://beta.rclone.org/branch/fix-4632-gofile/v1.68.0-beta.8161.7194d828d.fix-4632-gofile/) on branch [fix-4632-gofile](https://github.com/rclone/rclone/tree/fix-4632-gofile)
> 
> Any testing much appreciated.
> 
> # Gofile docs (cut down)
> The initial setup for Gofile involves logging in to the web interface and going to the "My Profile" section. Copy the "Account API token" for use in the config file.
> 
> ## Configuration
> Here is an example of how to make a remote called `remote`. First run:
> 
> ```
>  rclone config
> ```
> 
> This will guide you through an interactive setup process:
> 
> ```
> No remotes found, make a new one?
> n) New remote
> s) Set configuration password
> q) Quit config
> n/s/q> n
> 
> Enter name for new remote.
> name> remote
> 
> Option Storage.
> Type of storage to configure.
> Choose a number from below, or type in your own value.
> XX / Gofile
>    \ (gofile)
> Storage> gofile
> 
> Option access_token.
> API Access token
> You can get this from the web control panel.
> Enter a value. Press Enter to leave empty.
> access_token> YOURACCESSTOKEN
> 
> Edit advanced config?
> y) Yes
> n) No (default)
> y/n> n
> 
> Configuration complete.
> Options:
> - type: gofile
> - access_token: YOURACCESSTOKEN
> Keep this "remote" remote?
> y) Yes this is OK (default)
> e) Edit this remote
> d) Delete this remote
> y/e/d> y
> ```
> 
> Once configured you can then use `rclone` like this,
> 
> List directories and files in the top level of your Gofile
> 
> ```
> rclone lsf remote:
> ```
> 
> To copy a local directory to an Gofile directory called backup
> 
> ```
> rclone copy /home/source remote:backup
> ```
> 
> ### Modification times and hashes
> Gofile supports modification times with a resolution of 1 second.
> 
> Gofile supports MD5 hashes, so you can use the `--checksum` flag.
> 
> ### Restricted filename characters
> In addition to the [default restricted characters set](/overview/#restricted-characters) the following characters are also replaced:
> 
> Character	Value	Replacement
> !	0x21	！
> "	0x22	＂
> *	0x2A	＊
> :	0x3A	：
> <	0x3C	＜
> >	0x3E	＞
> ?	0x3F	？
> \	0x5C	＼
> |	0x7C	｜
> File names can also not start or end with the following characters. These only get replaced if they are the first or last character in the name:
> 
> Character	Value	Replacement
> .	0x2E	．
> Invalid UTF-8 bytes will also be [replaced](/overview/#invalid-utf8), as they can't be used in JSON strings.
> 
> ### Public Links
> Gofile supports `rclone link` to make public links to files or directories. If you specify a directory it will download as a `zip` file. You can use the `--expire` flag to specify the time the link should be valid. Note that `rclone link --unlink` removes all the public links for a file.
> 
> ### Root folder ID
> You can set the `root_folder_id` for rclone. This is the directory (identified by its `Folder ID`) that rclone considers to be the root of your Gofile drive.
> 
> Normally you will leave this blank and rclone will determine the correct root to use itself and fill in the value in the config file.
> 
> However you can set this to restrict rclone to a specific folder hierarchy.
> 
> In order to do this you will have to find the `Folder ID` of the directory you wish rclone to display.
> 
> You can do this with rclone
> 
> ```
> $ rclone lsf -Fip --dirs-only remote:
> d6341f53-ee65-4f29-9f59-d11e8070b2a0;Files/
> f4f5c9b8-6ece-478b-b03e-4538edfe5a1c;Photos/
> d50e356c-29ca-4b27-a3a7-494d91026e04;Videos/
> ```
> 
> The ID to use is the part before the `;` so you could set
> 
> ```
> root_folder_id = d6341f53-ee65-4f29-9f59-d11e8070b2a0
> ```
> 
> To restrict rclone to the `Files` directory.


Is this only for the paid plan, and is there any way to use it with the free version?

**Comment by ncw** [comment]
@Elshepl the API only works with premium accounts. I don't know whether there is any plans to change this but it would depend on Gofile changing their policy.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.68

Any testing before release much appreciated. Please make a new issue if you find a problem. Thank you :-)

**Comment by mateooo1** [comment]
The API does work in free accounts.

**Comment by realnc** [comment]
They claim the API works on free accounts, but is limited. They say:

> Premium Requirement: Most API endpoints require a premium account. Only basic operations like uploading, creating folders, and removing content are accessible with free accounts.

However, with rclone it just gives an error message:

```none
error listing: couldn't list files: Error "error-notPremium"
```
