### ISSUE TITLE
Examples section in include/exclude/filter documentation page

### ISSUE THREAD

**Issue by edwardxml** [rclone/rclone#4719]
#### What is your current rclone version (output from `rclone version`)?
1.53.2
#### What problem are you are trying to solve?
The filter - exclude - include documentation page https://rclone.org/filtering/ doesn't fully reflect the practical examples for commonly encountered requirements in the rclone forum. As a reference it is great and comprehensive but is not helpful to a beginner.
#### How do you think rclone should be changed to solve that?
I was thinking about adding a 'Practical examples' section at the bottom of the page in a simple requirement - solution format so that examples from the forum could be added without fuss and thinking about wording / tense / point of view etc.

My first example would be `--exclude /directory_to_exclude/**`

It is a common requirement to exclude one, or a few folders / pseudo folders but the syntax isn't obvious. The answer is in the existing reference, but I only found it after I got a solution to work. The rclone / go glob() syntax is different (arguably better) than the regex I am familiar with; my day to day globbing; restic, rsync etc..

Recently, problems with `-exclude "[{JP,KR,HK,CN,RU,PL,AU,GB,FR}]"` came up in 
https://forum.rclone.org/t/certain-exclusion-flags-seem-to-be-ignored/20049/2 which nicely illustrated lots of points in the existing documentation and I though would make a great example if there was a place to easily add it into the page. I am thinking there will be no shortage of real world filter examples to pull from the forum into documentation going forward.

My concerns are:-

1. The page is already long - Putting the section at the end might somewhat mitigate this. Having a separate practical example section might prevent incremental bloating of the reference section.
2. It is somewhat different to the other documentation so I don't want to just wade in.

Ed.

**Comment by edwardxml** [comment]
I have some sympathy with the issue and solution raised in https://github.com/rclone/rclone/issues/4713. It might be possible to take the existing ref material and put it into a slightly clearer order to also address my `--exclude /directory_to_exclude/**` example

**Comment by ncw** [comment]
I think examples would be a great idea.

The page is written in more mathematical style than most people are used to reading. That's my fault, it is how my brain works!

Having lots of examples always helps and we could put them at the end but put a link to them near the start as some people really like having examples. The examples should also show how you test filters to see if they are working with `rclone ls`.

The other thing that trips users up is the order that the patterns get applied, if you have more than one then they get matched one by one in order which seems straight forward to me, but I know that lots of users have had problems with that.

I think the [Patterns](https://rclone.org/filtering/#patterns) section could do with a bullet list of the different "glob operators" right at the start after the first paragraph.

I did have the idea of writing a web-app which would let you filter some examples using rclone filter syntax. This would be all in a single page - a bit like the many regexp simulators you see! That actually wouldn't be too hard since go can compile to wasm or javascript so we could run the actual filters code in a web page! This could have a permalink section so the examples could link to a live test.

**Comment by ncw** [comment]
I had a quick go at the web app which you can try here: https://filterdemo.rclone.org/ - feedback much appreciated!

**Comment by edwardxml** [comment]
more mathematical style

The page is first and foremost a definitive syntax so that seems entirely appropriate.

The web app is rather fun. Is it linked to a particular rclone or just go version? I had a fruitless experience with some Google NaCl code imposed a few years ago but WASM is new to me. The web page seems to have gained a double html dom entry somehow but my browsers don't care.

Will try to have a look at the filter page this weekend.

**Comment by ncw** [comment]
> The web app is rather fun. Is it linked to a particular rclone or just go version?

It is the relevant parts of the current beta compiled into a web app

> I had a fruitless experience with some Google NaCl code imposed a few years ago but WASM is new to me.

Yes WASM is what NaCL was aiming at, but supported by all the browsers.

> The web page seems to have gained a double html dom entry somehow but my browsers don't care.

Ooops, I've fixed that now.

> Will try to have a look at the filter page this weekend.

:-)

**Comment by edwardxml** [comment]
Hi @ncw 

I was just doing a bit more rclone filter delving. The existing documentation on `--filter` notes:

    A special rule called `!` can be used to clear the existing rules.

Is there a particular use case for this you had in mind or have come across. I was thinking about a situation where a filter was set with an exported bash variable and that needed to be replaced but it seemed a bit unexciting. Am I missing something really obvious again.
