### ISSUE TITLE
dropbox: support new oauth scheme

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4792]
Email received from dropbox:

----

We  released an update to our authorization model—you’ll want to review  your app’s (rclone) permission settings, and may need to update your  code for refresh tokens.

Action Required: Token and Permission Updates

The Dropbox API now supports OAuth scopes, PKCE, refresh tokens, and short-lived access tokens. We’re asking developers to review their app’s permission settings and ensure their apps support short-lived access tokens. Apps that require background access will need to update to use refresh tokens, which is made easier by using our updated SDKs.

Starting September 30th, 2021, the Dropbox OAuth flow will no longer return long-lived access tokens. It will instead return short-lived access tokens, and optionally return refresh tokens. Please be sure to review, test, and move to the new permission model before then.

For detailed instructions, please see:
- [Oauth Guide](https://www.dropbox.com/l/AADHH_cYgGKEfigPV-GaT0S3W7o2pNqTU9c)
- [Blog post - oauth scopes and enhance permissions](https://dropbox.tech/developers/now-available--scoped-apps-and-enhanced-permissions)
- [Blog post - Migrating app permissions and access tokens](https://dropbox.tech/developers/now-available--scoped-apps-and-enhanced-permissions)

----

The first of those blog posts seems to have most of the info needed

**Comment by Daddoon** [comment]
Here is the solution / workaround i have found.

If this does not change, it's just about a RClone config and behavior change in the future.

As stated on [this page of Dropbox API](https://www.dropbox.com/developers/documentation/http/documentation#file_properties-properties-remove), the **refresh_token** can be forced to be generated with the **access_token** if we register the OAUTH2 access with the **token_access_type=offline** parameter in the URI.

So what does it mean ?
- In your Dropbox App, set the Token as **short-lived** as this is the only solution in the future.
- Rebuild your Dropbox remote in RClone **except** that when RClone will open an URL in your browser in order to Add/Validate your new Dropbox App access at the end of the process, replace this:

```
https://www.dropbox.com/1/oauth2/authorize?client_id=<APPID>&redirect_uri=http%3A%2F%2Flocalhost%3A53682%2F&response_type=code&state=<SOMECODE>
```

By something like this:

```
https://www.dropbox.com/1/oauth2/authorize?client_id=<APPID>&redirect_uri=http%3A%2F%2Flocalhost%3A53682%2F&response_type=code&state=<SOMECODE>&token_access_type=offline
```

Note the **&token_access_type=offline** appended at the end of the URL.

And so validate your App workflow with this URL and not the one generated by RClone.

- The end ! With this params, Dropbox API will return the refresh_token in the request to RClone.

I just tested this by waiting 4 hours, and indeed, RClone does use the given refresh_token.

**Comment by okz** [comment]
Excelent work around Daddoon..  

They do suggest ```token_access_type=offline``` will continue to be supported, since that is how they support "offline" apps

**Comment by ncw** [comment]
@Daddon - thanks for your writeup - very useful.

A bit of experimentation shows that we get tokens which expire if we

- supply `token_access_type=offline` **OR**
- set the app config to `Access token expiration = short-lived`

So the minimum thing to do would be for me to flip the bit in the app config to `short-lived` tokens.

However I think the safe thing to do would be to add the `token_access_type` parameter so we can test this in the beta and the next version of rclone before flipping the bit.

I've made that change here - can you test it?

[v1.54.0-beta.4904.e092a853e.fix-4792-dropbox-token](https://beta.rclone.org/branch/fix-4792-dropbox-token/v1.54.0-beta.4904.e092a853e.fix-4792-dropbox-token/) on branch [fix-4792-dropbox-token](https://github.com/rclone/rclone/tree/fix-4792-dropbox-token) (uploaded in 15-30 mins)

Other questions

- Are we required to add scopes? Should we? The drive backend allows the user to [configure the scopes](https://rclone.org/drive/#drive-scope) which some users find useful.
- Rclone should probably be using PKCE being an open source app, but I haven't researched that more.

**Comment by Daddoon** [comment]
@ncw Beware for the behavior, i'm not sure that setting the app to short-lived is enough. I don't know where i have read this in the Dropbox doc or somewhere, but i think that i have also read that the Dropbox API **may** return a refresh_token, like if this behavior is not consistent depending the scenario / call.

I may be wrong. But however, from my own tests yesterday, i have set my Dropbox Apps to short-lived token, and first tried to reauthenticate in RClone: Dropbox API **did not** return a refresh_token on my side. Si it didn't work for a future authentication.

Only adding the **token_access_type=offline** dit the magic bit, where the refresh_token was returned.

I assume that the behavior is, in some kind, random or related to some apps things internally on Dropbox side (i don't know).

Better to be safe and consistent in my opinion, but maybe some additional feedback from people would be grateful, i'm just talking about what happened on my tests.

**Comment by Daddoon** [comment]
I have tested your fix on my machine, Windows 10 - 64 bits.

Everything worked like a charm out of the box, good job !

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

I think this should be sufficient for the moment so I'm going to close this now.

**Comment by immanuelfodor** [comment]
If somebody has an existing rclone config, what should be done? A user guide would be great to migrate existing setups.

**Comment by Daddoon** [comment]
It's like before, nothing changed from the interactive side of RClone.

But because the updated RClone now use a different authorization option when asking permission on Dropbox, you must remove/add again your remote configuration.

So register your remote as before with same options. When the authorization window will open, the right permission will be asked to Dropbox, and so everything will work out of the box (refresh_token and else), nothing to do on your side.

Of course, just remember to change your Dropbox app config and set your token types to "short-lived" !

**Comment by ncw** [comment]
@immanuelfodor wrote:
> If somebody has an existing rclone config, what should be done? A user guide would be great to migrate existing setups.

Run

    rclone config reconnect yourremotename:

To get a new token should be enough.

The old config will continue to work until September 2021 - not sure what will happen then.

**Comment by trompx** [comment]
Hello,
Thanks for testing and implementing the new features as Dropbox evolves.

As of today, I can still generate non expiring access token. That's what I did until now, but I'd prefer my solution to be future proof. 
I was planning to use rclone in a docker container running on aws fargate. It was nice being able to have a non expiring access token, so I could at runtime pass the access token as environement variable.
I can't manually log in to a browser to generate or link the dropbox account, I am not sure what I should/could do in my case to have an auto refreshing token ?

Any idea @ncw @Daddoon

**Comment by trompx** [comment]
Thanks for answering @ncw,
For now I have the following rclone.conf inside the docker container:
```js
[dropbox]
type = dropbox
token = {"access_token":"NONEXPIRINGACCESTOKEN","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
```
At runtime, I set the NONEXPIRINGACCESTOKEN to the env var pulled from aws secrets manager.

If I were to switch to short lived token, from what you say, that means that rclone will auto update the access_token when the expiry is reached? Will the expiry will be also set to a new value and should also be persisted.
I should for example **after each rclone run**, check the rclone.conf, extract the access_token and expiry date (renewed or not) and save it back to aws secrets managers?

**Comment by ncw** [comment]
> Thanks for answering @ncw, For now I have the following rclone.conf inside the docker container:
> 
> ```js
> [dropbox]
> type = dropbox
> token = {"access_token":"NONEXPIRINGACCESTOKEN","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
> ```
> 
> At runtime, I set the NONEXPIRINGACCESTOKEN to the env var pulled from aws secrets manager.
> 
> If I were to switch to short lived token, from what you say, that means that rclone will auto update the access_token when the expiry is reached?

Yes it will. There will be a new `refresh_token` in there too.

> Will the expiry date also be set to a new value and should also be persisted?

Yes and yes.

> I should for example **after each rclone run**, check the rclone.conf, extract the access_token and expiry date (renewed or not) and save it back to aws secrets managers?

You should really save the entire JSON blob which will have these things in at minimum.

```json
{
  "access_token": "XXX",
  "token_type": "bearer",
  "refresh_token": "XXX",
  "expiry": "2021-11-11T15:18:45.190106735Z"
}
```

**Comment by trompx** [comment]
@ncw do you want I create a new issue or you prefer to reopen this one?

**Comment by trompx** [comment]
For those having the same issue. The problem was a **permission problem** when running on Fargate. You have to make sure to **bind mount** the folder which holds the config and attributes the correct permission so rclone can actually write the new generated config file with the updated token and expiry.
Furthermore, I had to use the `rclone config dump | jq -r .dropbox.token` to get the updated token after the rclone command.

**Comment by izo-jshapiro** [comment]
@trompx We had a very similar situation to what you've described in your very helpful comments above. We ultimately found what we felt was a slightly cleaner approach. Describing it here in case it's helpful to others.

Key idea: rclone needs the dropbox token in a config file, but is smart enough to refresh a stale token and update the config file if there's a refresh token. Therefore, we can arrange for each running container instance to have a config file to based on the initial (long-ago-expired) token we got when setting up the task definitions for Fargate. We don't need a shared config file that gets mounted everywhere and is maintained with up-to-date tokens. As long as there's a refresh token in the config, rclone will refresh the access token and go about its business.

To avoid baking secrets into our container images, we created a docker image that overrides the entry point so that we can build a config file before executing rclone.

Our Dockerfile
```
FROM rclone/rclone:1


RUN mkdir -p /config/rclone

COPY startup.sh /usr/local/bin/startup.sh
RUN chmod a+x /usr/local/bin/startup.sh

# Override the default entry point to invoke our startup script
ENTRYPOINT ["/usr/local/bin/startup.sh"]
```

Our startup script
```
#!/usr/bin/env sh

cat <<EOT >> /config/rclone/rclone.conf
[dropbox]
type = dropbox
client_id = $DROPBOX_CLIENT_ID
client_secret = $DROPBOX_CLIENT_SECRET
token = $DROPBOX_TOKEN
EOT

/usr/local/bin/rclone "$@"
```
The env variables used by the script are stored in AWS Parameter Store and provided as secrets to the task definition.
