### ISSUE TITLE
--baseurl rclone serves /rclone/ instead of /rclone

### ISSUE THREAD

**Issue by montvid** [rclone/rclone#4814]
#### What is the problem you are having with rclone?

--baseurl "rclone" does not work with myaddress.com/rclone but works with myaddress.com/rclone/ . The same with 192.168.1.231:8080/rclone does not work but 192.168.1.231:8080/rclone/ does. How to make it work with "myaddress.com/rclone" only?

#### What is your rclone version (output from `rclone version`)

rclone v1.54.0-beta.4927.dfadd9896

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

LMDE 4 Linux

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone serve webdav /home/momo/ --addr 192.168.1.231:8080 --baseurl "rclone" --user ggg --pass lol --cert ~/cert1.pem --key ~/privkey1.pem

**Comment by montvid** [comment]
I see Nemo/Nautilus can't mount webdav because they are looking for /rclone and NOT /rclone/ no matter if i input /rclone/. It seems it is a bug on rclone's part.

**Comment by ncw** [comment]
I just had a look in the RFC. The root path is the root "collection"

https://tools.ietf.org/html/rfc4918#page-16

> There is a standing convention that when a collection is referred to
   by its name without a trailing slash, the server MAY handle the
   request as if the trailing slash were present.  In this case, it
   SHOULD return a Content-Location header in the response, pointing to
   the URL ending with the "/".  For example, if a client invokes a
   method on http://example.com/blah (no trailing slash), the server may
   respond as if the operation were invoked on http://example.com/blah/
   (trailing slash), and should return a Content-Location header with
   the value http://example.com/blah/.  Wherever a server produces a URL
   referring to a collection, the server SHOULD include the trailing
   slash.  In general, clients SHOULD use the trailing slash form of
   collection names.  If clients do not use the trailing slash form the
   client needs to be prepared to see a redirect response.

Which means I think that rclone is a standards compliant server - the RFC only says that "when a collection is referred to its name without a trailing slash, the server MAY handle the request as if the trailing slash were present".

So I'd say the bug is in the client here for ignoring the trailing slash in the URL!

There are two possible fixes for this

1. Redirecting "http://host/path/to/whatever" to "http://host/path/to/whatever/" if `whatever` doesn't exist as a file.
2. Redirecting only the root it it was specified without a `/`. This might not work for subdirectories though.

So can you try without --baseurl and see if the client can browse into subdirectories (and subsubdirs) OK? That will tell us if the simple fix (2) will work.

**Comment by montvid** [comment]
Yes the client can browse into subdirectories (and subsubdirs) OK. Rclone works fine without --baseurl specified. See dav://192.168.1.231:8080/ghgh/fghgfh works fine.

**Comment by montvid** [comment]
Just tried to resolve a simmilar bug I guess. Maybe it would be of interest to you https://redmine.lighttpd.net/boards/2/topics/9516?r=9526#message-9526

**Comment by ncw** [comment]
Interesting, that says it is a bug in GVFS

Anyway, can you try this version which does option 2) above with a 308 redirect which I think should work for you. Can you check it works and you can browse into subdirectories.

[v1.54.0-beta.4943.4165ccadb.fix-4814-http-redirect](https://beta.rclone.org/branch/fix-4814-http-redirect/v1.54.0-beta.4943.4165ccadb.fix-4814-http-redirect/) on branch [fix-4814-http-redirect](https://github.com/rclone/rclone/tree/fix-4814-http-redirect) (uploaded in 15-30 mins)

**Comment by montvid** [comment]
Thank you very much! It works on arm linux, amd64 freebsd and amd64 linux, vm64 windows 10 too. Maybe someone could file a gnome gvfs issue...

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

> Maybe someone could file a gnome gvfs issue...

That would be a good idea. I've got too much on my plate though so will you?
