### ISSUE TITLE
Add overall files per second rate limit

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#485]
rclone has adaptive rate limiting built in to the remotes, eg for google drive it starts off with a rate limit of one transaction every 10mS and backs off when it gets rate limited.

However it might nice if rclone could limit the number of files per second it uploads or downloads to avoid triggering the rate limiting code in the first place.

Make this a flag - say `--transfers-rate-limit` or `--transfers-per-second` or `--trlimit` and you'd give it a number (floating point) you wanted per second, or maybe a minimum time between transfers `--transfers-pacing` which you'd give in seconds.

**Comment by hashbackup** [comment]
I have a customer using Rclone with HashBackup to send a backup to G-Drive.  I read about the per-user rate limits, but the actual upload rate limits are much different.  For example:

- the files being uploaded are 100MB, and take 60 seconds to upload.  They're not a lot of small files.
- I'm using --retries 2 --low-level-retries 2, because HashBackup also does retries
- it seems there's no delay between low-level retries; maybe there should be
- in one case, a 100MB file was sent at 11:00:09; the next several attempts through 11:05:46 failed (over 5 minutes); at 11:05:52 a 20-byte file copy worked; at 11:05:54 it was throttled again, at 11:06:01 a 100MB file could be sent

When Backblaze B2 throttles with 429, it also returns a Retry-After header telling how long to delay.  Not sure if G-Drive does that, but I think the delays Rclone is using today are much too small, at least for uploads.

I have the detailed session logs if you need more info.  Thanks!

**Comment by kflu** [comment]
+1. I use rclone to backup a large directory to amazon cloud drive. Most of the times it goes through sub directories to figure out the ones need to upload, while most of those don't need to be uploaded, so **the number of requests per unit time** is really high and triggers 429. 

The consequence is that rclone will abort (due to number of retries limit) before it begins the actual uploads. My workaround is to boost up retries `--retries 999` but that's unreliable.

```
...
2016/10/17 11:04:13 amazon drive root 'foo': Reading "2008-00-00/"
2016/10/17 11:04:13 amazon drive root 'foo': Finished reading "2007-03-12/"
2016/10/17 11:04:13 amazon drive root 'foo': Reading "0000-00-00_2015-07-31/2007-06-10/"
2016/10/17 11:04:13 amazon drive root 'foo': Finished reading "0000-00-00/070225/"
2016/10/17 11:04:13 amazon drive root 'foo': Reading "0000-00-00_2015-07-31/0000-00-00/"
2016/10/17 11:04:13 pacer: Rate limited, sleeping for 632.969758ms (1 consecutive low level retries)
2016/10/17 11:04:13 pacer: low level retry 1/1 (error HTTP code 429: "429 Too Many Requests", reponse body: {"logref":"1b7f58ba-...","message":"System unavailable. Please back off for a while and try again later"})
2016/10/17 11:04:13 amazon drive root 'foo': Directory listing error for "0000-00-00_2015-07-31/2007-06-10/": HTTP code 429: "429 Too Many Requests", reponse body: {"logref":"1b7f58ba-...","message":"System unavailable. Please back off for a while and try again later"} - low level retry 1/10
2016/10/17 11:04:13 pacer: Resetting sleep to minimum 20ms on success
```

**Comment by ncw** [comment]
@kflu It looks like you've set `--low-level-retries` to 1?  If you leave it at the default of 10 then it will retry the directory listings and should complete successfully even in the presence of 429 errors.  429 errors are normal from Amazon Drive and rclone copes with them fine usually.

**Comment by kflu** [comment]
@ncw No I didn't set that. Is that the default value or could be set in a config file? How do I check?

**Comment by ncw** [comment]
@kflu If you run with -v it prints the command line args. You can't set it in the config file. It would be worth trying the latest beta if you haven't already at beta.rclone.org

**Comment by pjpalomaki** [comment]
@ncw Did you Implement this flag in a beta or something? I'm getting serious rate limiting, especially as I'm doing a huge server-side copy between two GDrives. I literally can't run Rclone longer than a minute, otherwise I get 24h ban. Also, what's weird is that the api console shows that I haven't gone over my **daily limit**, **per 100s** or **per 100s per user limit** but I'm still getting rate limited.. I have no Idea where/how google limits my transfers..

**Comment by ncw** [comment]
@pjpalomaki this isn't done yet, I'm afraid...  It sounds like google are being more aggressive about rate limiting certain things...

**Comment by pjpalomaki** [comment]
@ncw Ok thanks, I assume there's no deadline for something like this?

I'll keep an eye on the rate limiting, there seems to be some real inconsistencies between accounts etc (I've got about 5 drive accounts)..

**Comment by pjpalomaki** [comment]
Just on this, I'm getting more convinced that there's a separate quota for server-side copy apart from the quotas in the api console. Evert time I run rclone, even on transfers=1 checkers=1 etc. I'm still getting massive rate limiting within a minute and ban straight away. But if I straight away start copying normally between the same servers, I don't get rate limiting at all.. it's as if I hadn't done any of the server-side copying at all.

**Comment by breunigs** [comment]
Since 1.37 rclone has the the tpslimit and tpslimit-burst Flags, which control the amount of http transactions per second. See here for more details: https://github.com/ncw/rclone/commit/6f71260acf5235bd86b27ff664bd692d985e9a41

The ticket is specifically about *transfers* per second though, so it’s close but not quite the same.

**Comment by animosity22** [comment]
is there anything you still want to do for this @ncw?

**Comment by ncw** [comment]
@animosity22 The `--tpslimit` flag satisfies every use outlined here.

As @breunigs pointed out above it isn't quite the same thing as the files per second limit outlined here, however I think we can wait for an actual user requirement before implementing a files per second limit so I'll close this now.
