### ISSUE TITLE
New `--fix-case` flag to workaround case insensitive filesystem (macOS/Windows)

### ISSUE THREAD

**Issue by vicmarto** [rclone/rclone#4854]
When syncing to a case sensitive file system, it would be nice if rclone could rename files/directories to match the case on the source.

Currently this isn't possible - rclone views `HELLO.txt` and `hello.txt` on a case insensitive file system as being the same file and skips over them.

This could be controlled with a new flag `--fix-case` which would only be supported on backends which implemented the `Move` and maybe `MoveDir` optional methods.

`--fix-case` would likely rename the source to the same name as the destination if it was different. This would mean it would make the unicode normalisation the same also.

See the forum for more info: https://forum.rclone.org/t/force-rclone-to-respect-case/20794/5

**Comment by ncw** [comment]
To implement this it would need some code to check to see if the leaf of the destination is the same as that found and to `Move` it if not

https://github.com/rclone/rclone/blob/50cf97fc729ee305cb89260f2c7ed387cf12bac0/fs/sync/sync.go#L345

Might need to check all case insensitive file systems can actually rename `HELLO.txt` to `hello.txt`- this might need a new integration test.

**Comment by ivandeex** [comment]
The new flag should work in `copy`, `sync` and `dedupe`
- #1113
- #2430

**Comment by bdkjones** [comment]
This would be a good addition, but I think the original post mixed up the priority: the destination name should be changed to match the case of the source name, not the other way around. (The source filename should be the source-of-truth.)

Even though `FILE.txt` and `file.txt` are the same file on macOS, rclone should preserve the casing during syncs-otherwise, we're not really "cloning" the file because information is lost. That loss might seem trivial, but it's still a loss.

**Comment by HailAlistair** [comment]
I also have updated a bunch of files and folder cases. (I have capitalized a lot of stuff)
It would be great if rclone could fix the cases on the destination as well.

**Comment by EdgeRealm** [comment]
This addition would be useful. Any updates on this?

**Comment by nielash** [comment]
> This addition would be useful. Any updates on this?

Yes -- I've opened a PR 🙂 https://github.com/rclone/rclone/pull/7356
