### ISSUE TITLE
nfs,cifs: copy ACL for file from server1 to server2？

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4858]
@ncw @ivandeex

**Comment by ivandeex** [comment]
@zhucan
You repeatedly drop issue template from ALL your submitted issues. You put extra burden on rclone team. It is very hard to track issues that lack subject, problem description, searchable TEXT log and otherwise look like a spam. Please refrain from doing that in future. 

> @ncw @ivandeex

This is not a problem description but a spam in my and @ncw mailbox.

**Comment by ivandeex** [comment]
I remember ACL copy has already been mentioned elsewhere. Feel free to resubmit with all required data from bug/feature template. It's there for a purpose.

**Comment by zhucan** [comment]
@ivandeex  Thanks for your suggestions. ACL copy for object has already been mentioned. Not mentioned for file storage.
