### ISSUE TITLE
vfs cache write, need to delete cache before every restart

### ISSUE THREAD

**Issue by LeendertPlas** [rclone/rclone#4979]
When mounting a drive on windows with the vfs cache write option, the drive will only show up in explorer if the cache location is empty or non-existant. This means you would need to delete the entire cache everytime you encounter an error.

Is this a bug or is this working as intended?

**Comment by ivandeex** [comment]
Open task manager next time this happens and watch the outward traffic. I bet the mount is just waiting for the upload jobs to complete (those that were pending since last rclone restart).

Please note that your request lacks any details so I had to guess. A deeper analysis is impossible without it.

**Comment by ivandeex** [comment]
This question lacks details. Closing after a grace period.
