### ISSUE TITLE
Install script fails with "End-of-central-directory signature not found."

### ISSUE THREAD

**Issue by jkpe** [rclone/rclone#5145]
#### What is the problem you are having with rclone?
Running the install script results in an error

```
Archive:  rclone-current-osx-arm.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of rclone-current-osx-arm.zip or
        rclone-current-osx-arm.zip.zip, and cannot find rclone-current-osx-arm.zip.ZIP, period.
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

macOS Big Sur 11.2.3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

curl https://rclone.org/install.sh | sudo bash

or

curl https://rclone.org/install.sh | sudo bash -s beta

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
curl https://rclone.org/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4436  100  4436    0     0  27214      0 --:--:-- --:--:-- --:--:-- 27048
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     65      0 --:--:-- --:--:-- --:--:--    65
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Archive:  rclone-current-osx-arm.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of rclone-current-osx-arm.zip or
        rclone-current-osx-arm.zip.zip, and cannot find rclone-current-osx-arm.zip.ZIP, period.
```

**Comment by ivandeex** [comment]
If you look at the table in https://rclone.org/downloads/ and the listing in https://downloads.rclone.org/
You'll see that there is no such distribution file as rclone-current-osx-arm.zip
Our script has downloaded a "404 file not found" page instead of the real archive and obviously can't unpack it.
We'll look into the script, it must to detect this condition.
In the meantime I recommend you the following workaround: download rclone-current-osx-amd64.zip and try it.
I heard that MacOS can transparently run Intel executables on ARM machines.

**Comment by ivandeex** [comment]
If you look at the table in https://rclone.org/downloads/ and the listing in https://downloads.rclone.org/
You'll see that there is no such distribution file as `rclone-current-osx-arm.zip`
Our script has downloaded a `404 file not found` html page instead of the real archive and obviously can't unpack it.
We'll look into the script, it must detect such a condition.
In the meantime I recommend you the following workaround:
manually download `rclone-current-osx-amd64.zip` from https://downloads.rclone.org/ and install it manually.
I heard that MacOS can transparently run Intel executables on ARM machines.

**Comment by ncw** [comment]
> Our script has downloaded a `404 file not found` html page instead of the real archive and obviously can't unpack it.

Ooops

> We'll look into the script, it must detect such a condition.

I'm sure we can use the return codes of curl, can't we

**Comment by ivandeex** [comment]
> I'm sure we can use the return codes of curl, can't we

PR #5147

**Comment by ivandeex** [comment]
> for v1.55 we will support osx/arm

**Comment by ivandeex** [comment]
from https://github.com/rclone/rclone/pull/5147#discussion_r599020203

> for v1.55 we will support osx/arm
