### ISSUE TITLE
Google Drive Error 500 and Rate limited due to inaccessible shortcut

### ISSUE THREAD

**Issue by romspax** [rclone/rclone#5176]
#### What is the problem you are having with rclone?

When performing COPY command server-side I'm getting a lot of Error 500 messages. After digging around I stumbled on a shortcut in the folder structure to which the account, that I'm using to perform copy, does not have access to. 

#### What is your rclone version (output from `rclone version`)

v1.54.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10 / Mac BigSur

####  Which cloud storage system are you using? (e.g. Google Drive)

Google Drive
#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone --drive-impersonate account@domain.com copy "gdriveX:/" "SharedDriveX:/" --drive-server-side-across-configs --progress --create-empty-src-dirs --log-level DEBUG --log-file log.txt

**Comment by darthShadow** [comment]
Ok? And what is your question/problem here? That seems like expected behaviour.

**Comment by romspax** [comment]
Sorry, failed to mention the issue that this is causing:

I've spent more than 2 hours trying to figure out what the issue could be, error message mentions Rate limiting and Error 500, so naturally one would start with lowering tps rate, etc. So it would be nice if either (or both) the error message or the documentation would mention that inaccessible shortcuts can be causing rate limiting/error 500

**Comment by darthShadow** [comment]
I don't think we can do anything here. 500 errors can be caused due to numerous issues, most of which are internal to Google, and suggesting a single possibility is not the right solution.

Ideally, Google would provide more info in their error messages so this can be shown to the users too. You can place a request for that here: https://issuetracker.google.com/issues?q=componentid:191650%20status:open

Once they add the relevant info, feel free to open a new issue to request that message to be reflected in rclone too.
