### ISSUE TITLE
Windows "copy here" vfs cache: removed cache file as stale (remote deleted)

### ISSUE THREAD

**Issue by DEvmIb** [rclone/rclone#5181]
#### What is the problem you are having with rclone?

on windows  right click "copy here" on the same folder the copy is 0 bytes.
the original file gets also 0 bytes and will be uploaded.

#### What is your rclone version (output from `rclone version`)

v1.55.0-beta.5342.2ccf416e8

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

windows 10 64b

####  Which cloud storage system are you using? (e.g. Google Drive)

minio, webdav all the same problem

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

mount

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

[log.log](https://github.com/rclone/rclone/files/6229097/log.log)

**Comment by albertony** [comment]
Related:
- https://forum.rclone.org/t/copy-and-paste-a-file-in-same-directory-erases-original-file/23144
- https://github.com/rclone/rclone/issues/2187

**Comment by ncw** [comment]
I had a look through the log.

I made an edited version with a bit less stuff in here..

[issue-5181-edited.log](https://github.com/rclone/rclone/files/6235958/issue-5181-edited.log)

What appeared to happen is that somehow the original file got truncated to 0 length before the copy was even attempted.

The problem happened here

```
2021/03/30 14:36:25 DEBUG : /Textdokument (neu).txt: CreateEx: flags=0x502, mode=0700
2021/03/30 14:36:25 DEBUG : Textdokument (neu).txt: Open: flags=O_RDWR|O_CREATE|O_EXCL
2021/03/30 14:36:25 DEBUG : Textdokument (neu).txt: newRWFileHandle: 
2021/03/30 14:36:25 DEBUG : Textdokument (neu).txt(0xc000048200): openPending: 
2021/03/30 14:36:25 INFO  : Textdokument (neu).txt: vfs cache: removed cache file as stale (remote deleted)
2021/03/30 14:36:25 DEBUG : Textdokument (neu).txt: vfs cache: removed metadata from cache as stale (remote deleted)
2021/03/30 14:36:25 DEBUG : Textdokument (neu).txt: vfs cache: truncate to size=0
2021/03/30 14:36:25 DEBUG : : Added virtual directory entry vAddFile: "Textdokument (neu).txt"
2021/03/30 14:36:25 DEBUG : Textdokument (neu).txt(0xc000048200): >openPending: err=<nil>
2021/03/30 14:36:25 DEBUG : Textdokument (neu).txt: >newRWFileHandle: err=<nil>
2021/03/30 14:36:25 DEBUG : : Added virtual directory entry vAddFile: "Textdokument (neu).txt"
2021/03/30 14:36:25 DEBUG : Textdokument (neu).txt: >Open: fd=Textdokument (neu).txt (rw), err=<nil>
2021/03/30 14:36:25 DEBUG : /Textdokument (neu).txt: >CreateEx: errc=0, fh=0x1
```

Rclone truncated the file to 0 size because Exporer opened the file with `Create` with flags `O_RDWR|O_CREATE|O_EXCL`. However explorer didn't write to the file so there was no need to truncate it.

I've attempted to fix this here.

[v1.55.0-beta.5352.20e15e52a.fix-5181-vfs-explorer](https://beta.rclone.org/branch/fix-5181-vfs-explorer/v1.55.0-beta.5352.20e15e52a.fix-5181-vfs-explorer/) on branch [fix-5181-vfs-explorer](https://github.com/rclone/rclone/tree/fix-5181-vfs-explorer) (uploaded in 15-30 mins)

Can you give it a try?

**Comment by ivandeex** [comment]
I will try the fix with various VFS modes to see if it breaks something.

**Comment by albertony** [comment]
Great work.

Out of curiosity I did a quick investigation with SysInternals Process Monitor, tracing Windows API calls while performing a Ctrl+C/Ctrl+V in Windows Explorer.

Windows explorer opens the source file with disposition ("action to take on a file or device that exists or does not exist") `OPEN_EXISTING` first. Then, probably as a potential destination, tries to open it again with `CREATE_NEW`, which fails with `NAME COLLISION` as result. Then it tries with a new name, autogenerated suffix "- Copy" to basename, and succeeds with `CREATE_NEW` and ends up writing copied content to that.

I guess it matches the other findings, just wanted to mention it in case it adds some additional "confidence" to the solution (if that made any sense... :shrug: :smile:)

**Comment by sjluppino** [comment]
We hit this too, and have a deterministic repro + a root cause + a candidate fix — would appreciate maintainer input on the approach before opening a PR.

### Root cause

In `vfs/vfscache/item.go`, `Item._checkObject` treats a `nil` remote object as proof the object was deleted, and removes the clean local cache file:

```go
if o == nil {
    if item.info.Fingerprint != "" {
        if !item.info.Dirty {
            item._remove("stale (remote deleted)")
        } // ...
```

The problem is that `o` is `nil` in two very different situations:

1. the remote object was genuinely deleted, **and**
2. we simply couldn't *fetch* it — the backend was momentarily unreachable, or a stale/negative listing was returned (e.g. right after the cache is reloaded).

In case (2), a fully-cached, clean file is discarded, truncated to 0, and the next read returns `n=0, EOF` — a 0-byte file — even though the data is intact on the remote. It self-heals later (re-fetch / expiry), but the read window is wrong.

### Reproduction

Reliably triggered by making the backend briefly unreachable at the moment a cached item is re-checked after a mount/daemon restart. Two levels:

- **Unit (deterministic):** wrap the remote `Fs` so `NewObject` returns a transient (non-`ErrorObjectNotFound`) error, populate a clean cached item, then re-open with a `nil` object — the cache file is wrongly removed.
- **Integration:** write → cut the backend → restart the mount → restore → read, looped — ~1 in 5 iterations serves the file empty, with `vfs cache: removed cache file as stale (remote deleted)` in the log.

### Candidate fix — re-confirm before discarding

On `o == nil` for a clean cached item that has a fingerprint, re-check the remote and only treat it as deleted on a *confirmed* not-found:

```go
if o == nil && item.info.Fingerprint != "" {
    ctx := context.Background()
    if ci := fs.GetConfig(context.TODO()); ci.ConnectTimeout > 0 {
        var cancel context.CancelFunc
        ctx, cancel = context.WithTimeout(ctx, time.Duration(ci.ConnectTimeout))
        defer cancel()
    }
    var rerr error
    o, rerr = item.c.fremote.NewObject(ctx, item.name)
    switch {
    case errors.Is(rerr, fs.ErrorObjectNotFound):
        // confirmed deleted — remove as before (deletion-propagation preserved)
    case rerr != nil:
        // couldn't confirm (transient/unreachable) — keep the cached copy
    }
    // object found -> fall through to the normal fingerprint check
}
```

This preserves the intended deletion-propagation (the existing `TestItemReloadRemoteGone` stays green) and only changes the genuinely-ambiguous case. The lookup is bounded by `ConnectTimeout` since `_checkObject` runs under `item.mu`.

### Questions before opening a PR

1. Is discarding a clean cached file on an *unconfirmed* remote (case 2 above) an oversight, or intended ("the cache mirrors the remote; not-found is authoritative")?
2. Is re-confirming the right approach, or would you prefer threading a real `context` through `_checkObject` from the callers (for shutdown cancellation), or a different strategy entirely?
3. Any concern with the extra `NewObject` under `item.mu`? (The `o != nil` path already does remote I/O via `fs.Fingerprint` there.)

Happy to open a PR with the fix + a unit test once we know the direction you'd prefer.

**Comment by ncw** [comment]
@sjluppino 
> 1. Is discarding a clean cached file on an _unconfirmed_ remote (case 2 above) an oversight, or intended ("the cache mirrors the remote; not-found is authoritative")?

I don't think it is a bug. Clean cached items can be tossed at any any time. Could we handle it better - quite possibly :-)

> 3. Is re-confirming the right approach, or would you prefer threading a real `context` through `_checkObject` from the callers (for shutdown cancellation), or a different strategy entirely?

Re-confirming is an extra transaction which is a concern. However I don't think this is in a hot path so that probably isn't important.

> 5. Any concern with the extra `NewObject` under `item.mu`? (The `o != nil` path already does remote I/O via `fs.Fingerprint` there.)> > Happy to open a PR with the fix + a unit test once we know the direction you'd prefer.

Hmm... Doing IO while holding `item.mu` is asking for trouble but since we are doing IO anyway it is probably OK.

@sjluppino why don't you open a new issue with details on exactly the problem you are having and how to replicate it before making a PR.

**Comment by sjluppino** [comment]
Thanks @ncw — opened #9530 with the exact problem statement + a deterministic repro (and the proposed re-confirm direction), as you suggested. Happy to follow up there.
