### ISSUE TITLE
s3: Multipart files not checked or syncronized based on Checksum (ETag, additional headers)

### ISSUE THREAD

**Issue by robbat2** [rclone/rclone#523]
Multipart uploads to S3 do not have working checksum-based synchronization or validations. This can be implemented in two different ways:
1. Set additional headers of the known checksums of the file (as a bonus, you can set multiple different checksums on a single file
2. If the chunk size is consistent, the local ETag can be calculated for comparison. The chunk size can also be stored as a header, to ensure later calculations can be repeated, This is possible as documented here: http://www.perlmonks.org/?node_id=1140988

> What is your rclone version (eg output from `rclone -V`)
> rclone v1.29
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Gentoo Linux, 64-bit
> 
> Which cloud storage system are you using? (eg Google Drive)
> S3 (Ceph Hammer)
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> rclone  sync .  $REMOTE_NAME:$BUCKET_NAME/  --checksum
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
> 
> ```
> rclone  sync .  $REMOTE_NAME:$BUCKET_NAME/      --checksum --dump-headers --dump-bodies
> 2016/06/14 17:09:27 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2016/06/14 17:09:27 HTTP REQUEST
> 2016/06/14 17:09:27 HEAD /$BUCKET_NAME HTTP/1.1
> Host: objects-us-west-1.dream.io
> User-Agent: rclone/v1.29
> Authorization: AWS XXXXXX:Ke4mVHLXl4WUSPoyfVYZ6LoPFiM=
> Date: Wed, 15 Jun 2016 00:09:27 UTC
> 
> ```

2016/06/14 17:09:27 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/06/14 17:09:27 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/06/14 17:09:27 HTTP RESPONSE
2016/06/14 17:09:27 HTTP/1.1 200 OK
Date: Wed, 15 Jun 2016 00:09:27 GMT
X-Amz-Request-Id: tx000000000000001bbb918-0057609cb7-d8d7311-default
X-Rgw-Bytes-Used: 44040192
X-Rgw-Object-Count: 3
Content-Length: 0

2016/06/14 17:09:27 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/06/14 17:09:27 S3 bucket robjoh84-congress-test2: Building file list
2016/06/14 17:09:27 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/06/14 17:09:27 HTTP REQUEST
2016/06/14 17:09:27 GET /$BUCKET_NAME?delimiter=&max-keys=1024&prefix= HTTP/1.1
Host: objects-us-west-1.dream.io
User-Agent: rclone/v1.29
Authorization: AWS XXXXXXXX:lEMCCAZstZ5rJbzqUt25R59v5j8=
Date: Wed, 15 Jun 2016 00:09:27 UTC
Accept-Encoding: gzip

2016/06/14 17:09:27 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/06/14 17:09:27 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/06/14 17:09:27 HTTP RESPONSE
2016/06/14 17:09:27 HTTP/1.1 200 OK
Content-Length: 525
Content-Type: application/xml
Date: Wed, 15 Jun 2016 00:09:27 GMT
X-Amz-Request-Id: tx000000000000001bbb91b-0057609cb7-d8d7311-default

<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>$BUCKET_NAME</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1024</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>test.mem</Key><LastModified>2016-06-15T00:01:37.000Z</LastModified><ETag>&quot;4388daee7926e0b260eaf1bb51bdcb35-7&quot;</ETag><Size>33554432</Size><StorageClass>STANDARD</StorageClass><Owner><ID>robjoh84</ID><DisplayName>$UID</DisplayName></Owner></Contents></ListBucketResult>
2016/06/14 17:09:27 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/06/14 17:09:27 S3 bucket $BUCKET_NAME: Waiting for checks to finish
2016/06/14 17:09:27 Waiting for deletions to finish
2016/06/14 17:09:27 S3 bucket $BUCKET_NAME: Waiting for transfers to finish
2016/06/14 17:09:27 S3 bucket $BUCKET_NAME: Waiting for deletes to finish (during+after)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:       400ms

```
```

**Comment by ncw** [comment]
I prefer option 1 as there is already a precedent for that - that is how b2 does it.  That would also make `rclone md5sum` work and enable checksum based syncing for large files.  Option 2 only lets you calcuate the etag when you download the file which is useful, but not as useful for rclone.

Is there a de-facto standard for the name of the metadata - I try to keep rclone compatible with other tools if possible?

This could also be implemented for swift (&hubic) - I wonder if there is any standard metadata keys for that also?

**Comment by ncw** [comment]
I [asked on StackOverflow](http://stackoverflow.com/q/37844032/164234) a question about a standard metadata key for storing MD5SUMs.

**Comment by robbat2** [comment]
The closest I've seen to a standard name in S3 tools was `x-amz-meta-$HASHNAME`. I did want to mention that 
there is another strong advantage to the ETag method, notably parallel checksumming of large files (assuming you have enough disk IO to feed multiple threads of checksumming).

Maybe support both in headers...

**Comment by jamshid** [comment]
>  Option 2 only lets you calcuate the etag when you download the file which is useful, but not as useful for rclone.

I don't understand this. Using the S3 ETag seems like the better option since it does not require adding a custom header. The S3 ETag is returned in listings, so you don't even have to HEAD the object to validate its checksum against the local file. You certainly don't need to download the file, which would defeat the purpose of .

You don't need to store the chunk size in a separate header since the number of parts is included in the ETag. The format is "HEX MD5 OF EACH PART'S MD5 - NUMBER OF PARTS". The chunk size is simply the `file size / number of parts`. with the remainder being the last part.

**Comment by ncw** [comment]
@jamshid wrote
> I don't understand this. Using the S3 ETag seems like the better option since it does not require adding a custom header.

Having an actual MD5 of big files would enable cloud to cloud copies from drive to s3 with checking for example, and it would enable `rclone md5sum` to work, neither of which would work with Option 1.

**Comment by chris-redekop** [comment]
I drafted an implementation of #1 for S3.  During an update, it detects large files and attaches the MD5 hash as metadata; during a check, it falls back to checking the metadata when the ETag is not an MD5 hash.

I have a question about this implementation and S3-backed crypt remotes.   When `S3#Update` asks a crypt proxy for its hash, on line https://github.com/chris-redekop/rclone/commit/515def71e5742ac8b96a6490e6ff47832f67887d#diff-7db3cb93944d57b2ffc803281c906018R1009 , crypt returns "" (https://github.com/ncw/rclone/blob/master/crypt/crypt.go#L615 ).  This r esults in an empty hash being saved to the metadata, instead of the hash of the encrypted file.

To address this, *can* crypt remotes implement this Hash function by encrypting the proxied file and then calculating its MD5 hash?  *Should* they?  I think this would fix MD5 hashes for large encrypted files on S3, but I'm concerned about unintended consequences.

**Comment by chris-redekop** [comment]
I took a closer look support for `ObjectInfo#Hash` in `crypt::ObjectInfo`.  I think this would be a great feature, and I think it's doable; but it would need some rework in the hash handshake between file systems.  In particular, I think the handshake needs to broker

1. preferred vs. available hash algorithms,
1. which side of the handshake picks the preferred algorithm,
1. the hash calculation of *transformed* (e.g. encrypted, compressed #625, etc) streams *on-the-fly*.

In the meantime, I added ETag support to the S3 file system.  The change is up in #1863.

**Comment by ncw** [comment]
Sorry @chris-redekop I missed your comment from 25th October.

> I drafted an implementation of Option 1 for S3. During an update, it detects large files and attaches the MD5 hash as metadata; during a check, it falls back to checking the metadata when the ETag is not an MD5 hash.

That is pretty much exactly how the b2 large file hash works.  However it has the downside you've pointed out below which are in #1767

> To address this, can crypt remotes implement this Hash function by encrypting the proxied file and then calculating its MD5 hash? Should they? I think this would fix MD5 hashes for large encrypted files on S3, but I'm concerned about unintended consequences.

They could, but it is likely to mean the file is encrypted twice and possibly transferred twice so not ideal.  See #1767 for more discussion!

> I took a closer look support for ObjectInfo#Hash in crypt::ObjectInfo. I think this would be a great feature, and I think it's doable; but it would need some rework in the hash handshake between file systems. In particular, I think the handshake needs to broker

I'm not sure how you  would solve encrypting and transferring the data twice?

To solve the crypt hash problem, I was thinking of making a v2 crypt format which stores a blob of metadata in front of each file.  This would be hashes in all supported formats, and also the full name of the file.  This would mean that it was relatively cheap to look up the hash of an encrypted file.

**Comment by chris-redekop** [comment]
Thanks for the context.  #1767 does go over this issue in detail!  I'd like to talk through this "calculate the sum in advance" option a bit more, as it addresses my use case better than #1863: "as a backup operator, I want to (crypt) check the large files that rclone copies to S3".

> They could, but it is likely to mean the file is encrypted twice and possibly transferred twice so not ideal. See #1767 for more discussion!

I do see the need for double encryption--once to calculate the sum in advance and once to transfer the file encrypted.  (I don't see a need for a double transfer?)  The double encryption seems like a fair tradeoff to me, for four reasons:

1. My "S3 backup operator with large files" use case needs two encryptions either way:
   1. If we calculate in advance, we need once for the sum and once for the upload, like in #1767, or
   1. If we calculate later, we need once for the upload and once later for the crypt check.  (This assumes #1863, because S3 otherwise has no support for large-file MD5 sums.  See 3 below.)

1.  When I "calculate the sum in advance", I *never* have to crypt check my backup files.  (S3 assured during upload that they match.)  This means I avoid re-checking a remote FS to check newly backed-up files, which means I also avoid rechecking the previously backed-up files that I have already checked.  In this sense, "calculating the sum in advance" actually reduces the overall number of re-encryptions.

1. Other than the S3 ETag--which we know doesn't address all use cases--uploading the MD5 sum in advance is **the only way** to verify large files on S3.  There is no other way to confirm that the bytes **on S3's side** were, *e.g.*, not corrupted during transmission.  Note that uploading the MD5 sum later, as arbitrary metadata that S3 does not confirm, does not address this issue.  We need S3 to recognize and confirm the sum **on its side**; and uploading the MD5 sum in advance is currently the only way to achieve this.  (If S3 ever adds the ability to do this check *afterward*, all the better.)

1. This is [Amazon's recommended approach for ensuring data integrity](https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/).  It works transparently for multi-part upload, and Amazon's CLI does this by default.

> To solve the crypt hash problem, I was thinking of making a v2 crypt format which stores a blob of metadata in front of each file. This would be hashes in all supported formats, and also the full name of the file. This would mean that it was relatively cheap to look up the hash of an encrypted file.

I like this idea as an optimization.  I also think it would be fun to write an S3 crawler to upgrade v1 files to v2! :spider_web: 

Functionally, though, it does not address 3 above.  I think we need at least one *anchor* sum that is verified by S3 and and serves to "certify" the other sums in the v2 blob.  Otherwise, we can't be sure that the uploaded sums actually match the contents of the uploaded file.  For this reason, I still support calculating the sum in advance.

The unfortunate thing here--touched upon on #1767 --is that the APIs want the sum *before* the upload instead of *after*.  I don't see this as a reason to not implement the "calculate the sum in advance" functionality; if the APIs improve later, rclone can improve its "calculate the sum in advance" impl right along with them.  :smile:  

What do you think?  I prefer this solution as an alternative to #1863, and would be happy to switch over to this work.

**Comment by ncw** [comment]
I agree by and large with your points above.  I'll just call out some things

> I don't see a need for a double transfer?

Remember rclone supports remote -> remote transfers so it will involve a double transfer from the source.

> It works transparently for multi-part upload, and Amazon's CLI does this by default.

I've looked at the docs and Content-MD5 doesn't seem to be supported for multipart uploads.  It is supported for each chunk and the AWS Go SDK does that for me already.

> Functionally, though, it does not address 3 above. I think we need at least one anchor sum that is verified by S3 and and serves to "certify" the other sums in the v2 blob.

Yes that is mostly why I haven't done it....

> What do you think? I prefer this solution as an alternative to #1863, and would be happy to switch over to this work.

I think that it won't work with multipart files unfortunately :-( Here are the docs for [initiate](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html), [upload a part](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html) and [finalise](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html) - I'd appreciate a double check on that.

----

Rclone goes to some effort to check hash integrity. After uploading something, rclone will immediately [check the hash is correct](https://github.com/ncw/rclone/blob/master/fs/operations.go#L377-L382) (ie check the Etag returned by S3 matches that caculated locally) and delete the file if it isn't which has the same eventual result as sending it in the Content-MD5 header I think.

That scheme would work well with #1863 and I think it covers your requirements of having an object whose hash has been checked at the point of upload.

I think we would have to hide it behind a feature flag --s3-etag or something like that so we don't break backwards compatibility with other workflows.

Although we could always use this mechanism for uploads - it is just downloads that are potentially problematic.

In fact looking at the [s3manager code](https://github.com/aws/aws-sdk-go/blob/master/service/s3/s3manager/upload.go#L768-L790) it has all the info there (namely MD5SUMs) of all the parts so it would be really easy for it to check the etag returned there...

**Comment by ncw** [comment]
I had another idea about #1863  - in order to use etags for download we need to be sure rclone uploaded the file.  We can be reasonably certain about this as to whether the file has the "mtime" metadata or not.  Or we could explicitly add some metadata like "partsize" to say how bit the upload chunks were...

**Comment by chris-redekop** [comment]
> I had another idea about #1863 - in order to use etags for download we need to be sure rclone uploaded the file. We can be reasonably certain about this as to whether the file has the "mtime" metadata or not. Or we could explicitly add some metadata like "partsize" to say how bit the upload chunks were...

Great idea!  I really like the idea of an RCLONE_VERSION tag on objects, irrespective of #1863.  This would enable rclone to recognize previous versions of itself, as well as third-party uploaders.  I think this is a critical piece of info for evolving rclone's data schema (i.e. going from v1 to v2 of encrypted files, as you described).

We could also add specific metadata for #1863, but I think being able to track rclone's data schema makes this less pressing.

**Comment by chris-redekop** [comment]
> Remember rclone supports remote -> remote transfers so it will involve a double transfer from the source.

Ah, yes!  Right, so two *reads* might require two *transfers*.

> I've looked at the docs and Content-MD5 doesn't seem to be supported for multipart uploads. It is supported for each chunk and the AWS Go SDK does that for me already.
> I think that it won't work with multipart files unfortunately :-( Here are the docs for initiate, upload a part and finalise - I'd appreciate a double check on that.

Thanks the discussion--we're into good details.  I reread the docs, some of the code, and ran a few experiments.  Here are my findings.

1.  The AWS Go SDK supports Content-MD5 for *small* files with `s3manager`.
1.  The AWS Go SDK does **NOT** support Content-MD5 for *large* files with `s3manager`.  Even though [the general input struct](https://github.com/aws/aws-sdk-go/blob/a9ba0f983db388454795aa122bf6a94170465683/service/s3/s3manager/upload.go#L121) takes a `ContentMD5` value, `s3manager` [discards this](https://github.com/aws/aws-sdk-go/blob/a9ba0f983db388454795aa122bf6a94170465683/service/s3/s3manager/upload.go#L608) once it determines it is dealing with a large (i.e. multi-part) file.  ([The multi-part input struct](https://github.com/aws/aws-sdk-go/blob/a9ba0f983db388454795aa122bf6a94170465683/service/s3/api.go#L8204) does not have a ContentMD5 field.)   If I understand the code correctly, then `s3manager` is not doing any integrity checking for us.

1.  The AWS Go SDK does support Content-MD5 for large files with explicit multi-part uploads.  I originally thought `s3manager` could do MD5-sum checking for us, but now I think explicit multi-part uploads are the only way to verify integrity.  I threw up [a gist](https://gist.github.com/chris-redekop/cec6d06894267c3893d5381af1e1fd64/) to demonstrate this.  It can be made to pass or fail its integrity check on a large multi-part file.  I got this idea by rereading [the multi-part documentation that you sent to me](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html); it notes a Content-MD5 field.

> Rclone goes to some effort to check hash integrity. After uploading something, rclone will immediately check the hash is correct (ie check the Etag returned by S3 matches that caculated locally) and delete the file if it isn't which has the same eventual result as sending it in the Content-MD5 header I think.

Right, it's that check that I want to enhance, as it currently skips over all large S3 files.  Between two available levels of enhancement,
1. Check with S3's ETag (behind an option): this has the limitations that we discussed--mostly that AWS cautions against using it--but it suits my use case.
1. Check with Content-MD5: this is the AWS's recommendation for verifying integrity, but would require the most work.  rclone would need to partition and upload the file manually instead of using `s3manager`. 

I still prefer 2, but it's a bit more work than I thought.  1 works, too.  What do you think?

**Comment by ncw** [comment]
I'll try your test program tomorrow, I've only got a moment to comment now...

I note that if we want to fix s3manager we can send a PR to AWS.  They've taken lots of my PRs in the past and I've found the team there very responsive.

I was thinking about what you said about crypt being able to supply the hashes...  This would be useful in other places, `--track-renames` for instance doesn't work without a hash to work with.  Perhaps we should do that too, also behind an option.

**Comment by chris-redekop** [comment]
Ah, good idea re: submitting a PR to aws-go-sdk.  I'll take a closer look and see how that might work.

Re: trackng moves, yes, I see what you mean.  By making hashes available sooner, crypt remotes look more like unencrypted remotes.

**Comment by ncw** [comment]
I did a little test with rclone uploading an 11M file.

````
dd if=/dev/zero of=11M bs=1M count=11
rclone copy -vv --dump-bodies 11M s3:rclone 2>&1 | tee s3.log
tr -d '\000' < s3.log > s3-no-nulls.log
````

[s3-no-nulls.log](https://github.com/ncw/rclone/files/1527694/s3-no-nulls.log)

If you look at that log you can see
  * each chunk is uploaded with an `X-Amz-Content-Sha256` so each chunk is protected
  * to finish the upload, all md5sums of all the chunks are sent - here amazon checks the integrity of the entire upload
    * also here is enough info to calculate what the ETag should be.
```
<CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Part><ETag>&#34;5f363e0e58a95f06cbe9bbc662c5dfb6&#34;</ETag><PartNumber>1</PartNumber></Part>
<Part><ETag>&#34;5f363e0e58a95f06cbe9bbc662c5dfb6&#34;</ETag><PartNumber>2</PartNumber></Part>
<Part><ETag>&#34;b6d81b360a5672d80c27430f39153e2c&#34;</ETag><PartNumber>3</PartNumber></Part>
</CompleteMultipartUpload>
```

So I think s3manager and S3 are ensuring the integrity of large file uploads quite well.

**Comment by chris-redekop** [comment]
Yes, I see what you mean!  Thanks for finding this.

So Content-MD5 aside, the SDK is always SHA-256 hashing its chunked payload.  This addresses a big part of (the motivation behind) my use case; all that remains is, "as a backup operator, I want to (crypt) check the large files that rclone cop**ied** to S3 **some time in the past**"

I do want to address this use case, but now that (I realize that) my rcloned files have been verified :sweat_smile: I'm not in as big of a hurry.  Are you still interested in adding either MD5 or ETag support to S3 large files?  In the meantime, I'm going to take keep studying the ETag before I propose one or the other.

**Comment by chris-redekop** [comment]
Given what I found below, @ncw, I think calculating and specifying the MD5 ahead of the download is the best approach.  (I think the ETag is to fragile.)  What do you think?

1. [This API call](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListParts.html) initially looked promising, as a source of truth for the list of an object's parts. If I am reading the documentation correctly, however, it only applies to in-progress uploads (not completed uploads).  I do not see a way to discover upload IDs for completed uploads.
1. S3 changes the ETag of large objects when copied server-side between buckets, so any multi-part metadata that we upload with an object is of limited use--for ETag-checking local rclone uploads that have not been moved server-side--and is potentially misleading.

**Comment by ncw** [comment]
> Given what I found below, @ncw, I think calculating and specifying the MD5 ahead of the download is the best approach. (I think the ETag is too fragile.) What do you think?

I think that is probably the best approach and matches the approach taken by b2.  I agree with you that the ETag is probably too fragile.  I think the major pointer is that direction is that it isn't documented by AWS, so they can change it whenever they like...

I didn't know about Etag of large object copies.  Note that rclone does a server side copy when updating the modtime of a file so it is more common that you might think.

**Comment by chris-redekop** [comment]
Sounds good.  I'll close #1863, then, and prep my [original branch](https://github.com/chris-redekop/rclone/tree/issue523/large-file-hashes) for a PR.

**Comment by ncw** [comment]
That would be great :-)

I note in your branch you use `metaMD5Hash    = "Md5hash"` - I'd like to follow some standard here if there is one! Any thoughts?

**Comment by chris-redekop** [comment]
Leaving a note here: in it's [CLI/S3 FAQ](http://docs.aws.amazon.com/cli/latest/topic/s3-faq.html), AWS lists Signature Version 4's `x-amz-content-sha256` as a preferred alternative to `Content-MD5` when uploading files to S3.

**Comment by ncw** [comment]
We now

- Add metadata with a calculated MD5 hash on each large object
- Check the etag returned by s3 for multipart uploads where possible

I think this is sufficient to close this issue.
