### ISSUE TITLE
Rclone link to onedrive for business really slow.

### ISSUE THREAD

**Issue by ytrezq** [rclone/rclone#5246]
I don t if it s the intended behavior, but I do something like

    rclone link onedrive:path/to/some/file.sql
using my onedrive for business account where typical file size is 64Mib, the command takes about 30seconds to complete whereas I have a 10Gb/s connection.

This is annoying, because I m using rclone in a script in order to generate 30000 download link per day (one per file).

**Comment by Cnly** [comment]
I think there's probably some overhead coming from initialising the backend every time you invoke the command. One way of improving this may be letting rclone accept multiple files to link at a time (e.g. by accepting multiple paths or reading paths from a file).

**Comment by darthShadow** [comment]
If the backend initialization is the cause, then using the `operations/publiclink` rc command (https://rclone.org/rc/#operations-publiclink) should help solve the issue since any backend created via the rc commands is cached for some duration and at a sufficient frequency of requests, it should always be in the cache.

**Comment by ivandeex** [comment]
Regular cleanup of answered tickets
