### ISSUE TITLE
--dump should imply -vv

### ISSUE THREAD

**Issue by ytrezq** [rclone/rclone#5247]
The output is the same between `rclone --dump bodies link onedrive:list.txt` and `rclone link onedrive:list.txt`. I m meaning nothing is printed beside the download link.

**Comment by darthShadow** [comment]
You need to enable debug logging too.

**Comment by ytrezq** [comment]
@darthShadow how? This should be documented.

**Comment by darthShadow** [comment]
https://rclone.org/docs/#log-level-level

**Comment by Cnly** [comment]
Or should we make `--dump` imply `-vv`?

**Comment by ytrezq** [comment]
> Or should we make `--dump` imply `-vv`?

@Cnly yes, definitely.

**Comment by mrobgithub** [comment]
Before this change, adding the global flag "--dump filters" to a command would ALWAYS dump the filters regardless of what log level was set. With this change, there is no longer a way to "--dump filters" without getting tons of extra debug information. Is there anyway to either exclude "--dump filters" from this change or change the implementation to instead of globally changing the log level to instead treat all the DumpFlags like "filters" and always dump them regardless of the log level since they were explicitly asked for in the command.
