### ISSUE TITLE
azureblob: Support for OAuth / AzureAD auth (or maybe Azure CLI)

### ISSUE THREAD

**Issue by Centzilius** [rclone/rclone#5284]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.56.0-beta.5452.4401d180a
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-72-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.3
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?
I'm trying to access an azure blob storage account/container that has shared access keys disabled (and therefore uses Azure AD RBAC authorization) without resorting to a service principal or MSI.

#### How do you think rclone should be changed to solve that?
Implement OAuth authentication similar to what is done for onedrive. Extracting the credentials from the azure cli could also be an alternative.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Adding oauth is relatively straight forward as rclone has a solid framework for it now.

Can any azureblob use oauth or is some special config needed. (Just wondering if it is likely to work on my very simple Azure setup).

Can you point to any docs on this?

Would you like to implement this?

**Comment by Centzilius** [comment]
I'd have to look into Go some more to implement it my own but I'll try as soon as I have some time.
Regarding documentation that would probably be it but its basically creating a Azure AD application with the API scope of https://storage.azure.com/user_impersonation. If that also works with cross-tenant applications I'd need to test.

**Comment by ncw** [comment]
Is it the kind of thing I should create a global rclone Azure AD Application? Or do you think all users will want to create their own?

We'll need a `client_id` and a `client_secret`. We also need two endpoints and a list of scopes. And a redirect URL. Once we have that the oauth should just plug into rclone's framework. So implementing OAuth is very little programming and a lot of reading docs! I suppose the onedrive backend may be helpful here since it already accesses Microsoft OAuth.

Here is a simple example from the hubic backend

https://github.com/rclone/rclone/blob/ab7dfe0c874e707e83282fde2ce9ecd75efb4184/backend/hubic/hubic.go#L38-L48

https://github.com/rclone/rclone/blob/ab7dfe0c874e707e83282fde2ce9ecd75efb4184/backend/hubic/hubic.go#L58-L64

And that is just about it!

This looks like a good doc: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols

**Comment by ncw** [comment]
I'm going to close this as I think it is done. Please make a new issue with problems - thank you.
