### ISSUE TITLE
Typo in manpage

### ISSUE THREAD

**Issue by ioannis-vm** [rclone/rclone#5332]
Hello!
There is a typo in the manpage, on line 320.

> For example, if you have many files in /path/to/src but only a few of them change every day, you can  *to*  copy  all  the  files  which changed recently very efficiently like this:

I think the word *to* should be removed.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
Thanks for reporting.
Which version of rclone are you on?

I think this has already been fixed in latest version (1.55.1).. From the documentation of the copy command, which is manpages are generated from:

https://github.com/rclone/rclone/commit/756d47fb507df7c93bb66e665e3c34eb84c3fd4c#diff-f0496ff7f9edf8aabe97ac6d126019029da57e736cdb734a33adc61dcdb9a076

https://rclone.org/commands/rclone_copy/

**Comment by ncw** [comment]
Note that you can see the beta website at https://tip.rclone.org 

Looking at https://tip.rclone.org/commands/rclone_copy/ this has been fixed already so I'll close this now.

**Comment by ncw** [comment]
@ioannis-vm thanks for reporting this :-)
