### ISSUE TITLE
`--ignore-checksum` has no effect with sftp

### ISSUE THREAD

**Issue by ytrezq** [rclone/rclone#5366]
md5sum is called server side even if `--ignore-checksum` is passed to Rclone triggering high cpu usage when uploading directories.

**Comment by albertony** [comment]
The `--ignore-checksum` disables one use of checksums, namely for verifying transfers. But there are other uses, one is for comparing files to decide if a transfer is needed - adding `--size-only` will disable that.

The sftp backend has a dedicated option `--disable-hashcheck` to disable execution of md5sum/sha1sum entirely, so that is probably what you would want to set.

**Comment by ytrezq** [comment]
@albertony the problem of `size-only` is it also implies ignoring modification time.

**Comment by albertony** [comment]
I see.
And also what I said was wrong: Unless using `--checksum`, rclone will not consider the checksum for deciding if it needs transfer, only considers date and size. (These flags never stop confusing me).

I agree then, that when `--ignore-checksum` is given the hash calculation should not be performed..

Using `--disable-hashcheck` does prevent the md5sum from running?

**Comment by ytrezq** [comment]
@albertony it doesn’t work in beta versions

    Error: unknown flag: --disable-hashcheck

**Comment by albertony** [comment]
Sorry, it is called `--sftp-disable-hashcheck` (https://rclone.org/sftp/#sftp-disable-hashcheck)

**Comment by ytrezq** [comment]
@albertony it works, but the general doc is

**Comment by albertony** [comment]
> md5sum is called server side even if --ignore-checksum is passed 

Tried to reproduce this in debugger, but I do not see this happening. With `--ignore-checksum` rclone is not executing md5sum/sha1sum.

What version of rclone are you using?

Can you include a log from an upload where this happens, with rclone flag `-vv` specified?

**Comment by ivandeex** [comment]
@ytrezq 

Could you please fill in this
https://github.com/rclone/rclone/blob/master/.github/ISSUE_TEMPLATE/Bug.md
instead of playing jeopardy?



#### The associated forum post URL from `https://forum.rclone.org`



#### What is the problem you are having with rclone?



#### What is your rclone version (output from `rclone version`)



#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)



#### Which cloud storage system are you using? (e.g. Google Drive)



#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)



#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)





#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ytrezq** [comment]
> @ytrezq
> 
> Could you please fill in this
> https://github.com/rclone/rclone/blob/master/.github/ISSUE_TEMPLATE/Bug.md
> instead of playing jeopardy?
> 
> #### The associated forum post URL from `https://forum.rclone.org`
> #### What is the problem you are having with rclone?
> #### What is your rclone version (output from `rclone version`)
> #### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
> #### Which cloud storage system are you using? (e.g. Google Drive)
> #### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
> #### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
> #### How to use GitHub
> * Please use the +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
> * Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
> * Subscribe to receive notifications on status change and new comments.

@ivandeex 
Mostly irrelevant in that case. Especially for the type. No need to specify the storage type twice if it s sftp.
I already told the version and rather than specific cases outlined the underlying general issue.

**Comment by ytrezq** [comment]
> > md5sum is called server side even if --ignore-checksum is passed
> 
> Tried to reproduce this in debugger, but I do not see this happening. With `--ignore-checksum` rclone is not executing md5sum/sha1sum.
> 
> What version of rclone are you using?
> 
> Can you include a log from an upload where this happens, with rclone flag `-vv` specified?

I used it for resuming a large directory transfer with the sync command.

**Comment by ivandeex** [comment]
1. Copy-paste output from rclone version

2. The command you were trying to run (e.g. rclone md5sum remote:tmp)

3. Copy paste output from rclone config show config YourRemote: (replace passwords by xxx)

4. Copy paste log from the command with the -vv flag (e.g. output from rclone -vv md5sum remote:tmp)

**Comment by ivandeex** [comment]
I have gone through this ticket again.

> @albertony it works

I conclude that user solved their problem.

> but the general doc is misleading.

Yes. Feel free to send a patch.

> I already told the version

No, this whole thread does not have version numbers.

I am going to close this as it seems the is resolved.
Next time please fill in data for problem analysis.
