### ISSUE TITLE
"TLS segment is underaligned" when running any rclone command

### ISSUE THREAD

**Issue by ioogithub** [rclone/rclone#5546]
#### What is the problem you are having with rclone?
rclone binary broken, produces a TSL error with any command.

`/data/adb/modules/com.piyushgarg.rclone/rclone --version`
error: "/data/adb/modules/com.piyushgarg.rclone/rclone": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
Aborted

#### What is your rclone version (output from `rclone version`)
I think it is 1.53 or newer? (this is unconfirmed as I cannot run rclone --version) It is the version that is included with the latest version (version 1.8) of this project project:
(https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone) 

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Android 11, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
n/a

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
any command for example (rclone --version)

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
n/a

Note: There is a similar issue here however it is for a different version of Android and it was closed a year ago with an update to go, it seems that the issue is still active on Android 11:
https://github.com/rclone/rclone/issues/3515

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ioogithub** [comment]
I would like to try to update the binary manually however I don't see Android listed as as supported platform:

https://rclone.org/downloads/

**Comment by x0b** [comment]
Please use the forum for help & support, but since we're already here:
- [#3515](https://github.com/rclone/rclone/issues/3515) has been known and fixed for a while now by using newer toolchains.
- If possible, update your magisk module to 1.15. Because your old 1.8 module will probably might work with a new binary from the following bullet points...
- You can try downloading rclone `v1.56.0` [directly from the module repo](https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone/raw/master/common/binary/arm64/rclone).
- Or by downloading it directly from https://beta.rclone.org/v1.56.0/testbuilds/rclone-android-21-armv8a.gz (un-gz before use).

**Comment by ncw** [comment]
Thanks for the excellent advice @x0b 

I'm going to close this now as this is a fixed bug.
