### ISSUE TITLE
Windows has started thinking that rclone is ransomware

### ISSUE THREAD

**Issue by 13steinj** [rclone/rclone#5559]
#### The associated forum post URL from `https://forum.rclone.org`
NA

#### What is the problem you are having with rclone?

If you try downloading rclone 1.56 from rclone.org, it fails and is considered ransomware. Existing rclone is also considered ransomware. On the off-chance that rclone.org is compromised, I'm not gonna  re-enable it until I get some kind of a-ok from Nick or another maintainer. That said (id) for a false positive, this is a bad one to end up being. I'm sure there's some way to get added as trusted by Microsoft.

#### What is your rclone version (output from `rclone version`)

NA

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

NA but win10  pro 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)

NA

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

NA

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

![image](https://user-images.githubusercontent.com/10525230/131209156-131c2b1b-4678-48aa-8449-6d1a7a443964.png)
![image](https://user-images.githubusercontent.com/10525230/131209170-5d3f44ac-116b-4b82-89f7-98fc3779768e.png)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by 13steinj** [comment]
At minimum, a direct and clear link to the md5 checksums that exist on github should be placed in the same table.

**Comment by Masamune3210** [comment]
It's definitely not a virus or compromised. Windows Defender just has shit heuristics, and rclone is easily abused for malicious things

**Comment by albertony** [comment]
FYI: There is a thread about it in the forum (https://forum.rclone.org/t/rclone-1-5-6-windows-finds-trojan-win32-cryptinject-msr/26172).


> At minimum, a direct and clear link to the md5 checksums that exist on github should be placed in the same table on the site.

I agree.

Authenticode Code Signing the executable would also be nice, but don't think there are any free options for open source projects anymore, so would need to rely on donations. And also it adds complexity to the build/release process.

**Comment by Masamune3210** [comment]
Unfortunately as far as I know you are correct. There are no free signing mediums that are trusted enough by Defender to avoid being classified automatically as malicious. It's a common problem among the emulation open source community especially due to the frequent builds which cause mayhem with heuristic discovery

**Comment by ivandeex** [comment]
So let them think. We can't help it.
You can whitelist the C:\path\to\rclone.exe in Defender, like me.
Or use the fact that they blocked only one concrete rclone version 1.56.0, and just upgrade to latest beta.

**Comment by 13steinj** [comment]
> You can whitelist the C:\path\to\rclone.exe in Defender, like me.

I have 0 problem with whitelisting. But downloading itself is blocked. It is not resumable, and non actionable in Defender. Very7 odd catch 22.

> Or use the fact that they blocked only one concrete rclone version 1.56.0, and just upgrade to latest beta.

If they concretely blocked one rclone version, then some kind of false positive report should be sent. Either way, this is usually done heuristically. It is safe to assume that as the algorithm grows in the next year, more versions will also be blocked.

**Comment by x0b** [comment]
Update your signatures to >= `1.347.597` and try it again. I previously filed a dispute and Microsoft has now announced an update. 

![reply](https://user-images.githubusercontent.com/6282238/131243404-bda826b5-988c-43e2-b3ac-3aa82a6472f0.png)

I'm still receiving Smartscreen warnings, so I'm hoping that will also be resolved soon.

**Comment by ncw** [comment]
Thanks@x0b for doing that. How do you file a dispute BTW?

**Comment by x0b** [comment]
You can submit files for analysis over at the [Microsoft Security Intelligence portal](https://www.microsoft.com/en-us/wdsi). This is not just for malware - you can also file if you believe that a detection is incorrect:

<img src="https://user-images.githubusercontent.com/6282238/131246681-3a3d2f59-3c32-49be-86f6-c927bf62bea3.png" width="420" />

If Microsoft decides not to accept the initial submission, you then have the option to file a more detailed dispute.

**Comment by andrewww** [comment]
Hey, there,

I'm currently trapped between feeling like a jerk and feeling like I've been treated like a jerk.

I just posted on forum.rclone.org a new topic, which I called a Suspected Bug, because I was seeing a different kind of trojan than was previously reported:
![image](https://user-images.githubusercontent.com/1473025/132130215-662e3f0a-b8ac-484b-81c3-8ab39f561c54.png)

My only objective was to report this new information. But within minutes, there was a reply "this is not a bug and is reported here and here (links)", and the topic was closed before I could respond to say that I understand, I was just trying to post new information, and I know it's not a bug, per-se, but it is something that the devs have to deal with. So I posted a new topic again (that being literally the only way I could figure to post the information) trying to make these points as respectfully as I could. 

Now both posts have been deleted. I realize this is meta, but I wanted to report the information, and I needed to provide context, as I'm new to the rclone community.

**Comment by Masamune3210** [comment]
Read up in this issue to find the response to this. If you got rclone from the official website there is no malicious code in rclone. The virus detection in Defender is a bit trigger happy and regularly detects open source projects as malicious due to the fact that the heuristic engine doesn't see them a lot in the wild, therefore assuming by almost default that its a virus

**Comment by andrewww** [comment]
Thanks, @Masamune3210 . 

Is the information I posted helpful to the community, or does the kind of threat detected not matter?

**Comment by x0b** [comment]
@andrewww I haven't seen your forum post, so I can't know for sure why it was removed. That being said, I re-checked the v1.56.0 am64 binary with windows defender and cannot reproduce the detection. 

While such detections are generally useful to know about since we then may be able to convince the Antivirus vendor to unblock rclone, they are only a problem if they are widespread i.e they affect a significant number of people. Since this does (currently) not seem to be the case, no further action is warranted.

**Comment by ChrisKader** [comment]
> @andrewww I haven't seen your forum post, so I can't know for sure why it was removed. That being said, I re-checked the v1.56.0 am64 binary with windows defender and cannot reproduce the detection.
> 
> While such detections are generally useful to know about since we then may be able to convince the Antivirus vendor to unblock rclone, they are only a problem if they are widespread i.e they affect a significant number of people. Since this does not seem to be the case, no further action is warranted.

Can be reproduced in Edge by simply downloading the binary from the website and as if this comment, edge still flags the latest version but not the one prior.
