### ISSUE TITLE
bisync: add modtime support

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5679]
## What problem are you are trying to solve?

bisync delta engine and unit tests do not take backend time tolerance into account. this should be fixed.

### https://github.com/rclone/rclone/pull/5164#discussion_r634229878 (ivandeex)

the unit test runner is based on `mangleListing` which is a very far relative of [fstest.CompareItems](https://github.com/rclone/rclone/blob/v1.55.1/fstest/fstest.go#L356). It already has ability to ignore hashsums on demand. It still needs ability to compare times with per-backend tolerance or even ignore times if unsupported. Having that would let us run tests against backends without time support and probably lift the corresponding ban.

Tentatively this can be implemented as:
1. parse out the time filed and convert to `time.Time`
2. round time down to _doubled_ tolerance
3. put time field back into string
4. feed the result to `diff`.

Why not just parse and compare with tolerance?
Because `mangleResult` is two-fold. Besides comparing it can prepare a test state snapshot for storing in golden directory, which later can provide a **bigger picture** of what's going on.

### https://github.com/rclone/rclone/pull/5164#issuecomment-843151817 (ivandeex)

With a feature _must_ come a method of testing it.

Rclone has a comprehensive `fstest` framework dedicated to peculiarities of the plethora of supported cloud providers. Planning to work on this patch I had the heart to keep the project test engine's nature (while translating it from python to golang and refactoring it to work natively/unattended on Windows and with a wider set of backends) and propose it as a new kid on the set of rclone approaches (see my inline comment above), instead of rewriting it from the grounds up for `fstest`.

The bisync test suite **lacks** the ability to compare imprecise/absent timestamps as of the time of this writing (I hope I can say it, _absent_ timestamps should be "comparable" too). It works correctly mostly because it compares logs from a particular filesystem **with itself**. Unless this ward is fixed, we _can't run tests_ against backends without modtime and consequently can't declare them supported. I have an idea on how to fix that (see another inline comment), but the effort will need time.

## modtime in delta engine

Try to extend `operations.Equal` into `operations.Compare` with more returned conditions like `Newer, Older, ...` (related to #4810) for direct use in bisync delta engine

### https://github.com/rclone/rclone/pull/5164#issuecomment-842407758 (JWink3101)

The fact that this only supports a small subset of remotes is disappointing, esp. some popular ones not supporting mod time. Others, like S3, are way more performant if you disable it.

This is an issue with the overall algorithm of some sync tools but there is no reason you *need* modtime to decide what to sync. You may need it for *conflicts* but if you have past state, then you can tell if a changed file-size is a modification on one side only.

### https://github.com/rclone/rclone/pull/5164#issuecomment-842512914 (ivandeex)

> This is an issue with the overall algorithm of some sync tools but there is no reason you _need_ modtime to decide what to sync.

Theoretically, no. The bisync change detection in its current state is all about [bit masks](https://github.com/rclone/rclone/pull/5164/files#diff-25f7d45d3740899fdbbb93ff87a682943b7085b9c2f7f67b9cc58756c90e3630R31) (as opposed to "rclonic" [Equal](https://github.com/rclone/rclone/blob/v1.55.1/fs/operations/operations.go#L167)). But it needs more testing.

## How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
Related to this ticket (and also #5676), `--check-sync` should also support comparing `modtime` (and eventually, when [`checksum`](https://github.com/rclone/rclone/issues/5683) and [`size`](https://github.com/rclone/rclone/issues/5684) are supported, it should use the same sync key used for the bisync run.)

Currently, `--check-sync` only compares filenames, not `modtime`, `size`, or `hash`. It can detect whether a file from one Path is missing on the other, but not whether both Paths have different versions of a file. This can cause issues such as [this one](https://forum.rclone.org/t/bisync-missed-syncing-changed-file-no-error-no-warning/41174/2).

Alternatively, perhaps this would be better handled by outsourcing it to the more robust [`rclone check`](https://tip.rclone.org/bisync/#concurrent-modifications), rather than attempting to duplicate the same functionality in `--check-sync`.

Here's where the trouble is:

https://github.com/rclone/rclone/blob/94a320f23cd9e6ad27a03a2ac3c833f8871129f8/cmd/bisync/operations.go#L474-L479

https://github.com/rclone/rclone/blob/94a320f23cd9e6ad27a03a2ac3c833f8871129f8/cmd/bisync/listing.go#L53-L58
