### ISSUE TITLE
bisync: investigate chained operations

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5689]
### https://github.com/rclone/rclone/pull/5164#discussion_r688912759 (ncw) -> (ivandeex)

> Users will ask
> - can we have 3 paths?
> - what if I do `bisync A B` and seperately `bisync A C`

No we can't have more than two paths with `bisync`.
Need to experiment myself to see how the sum of `bisync A B` and `bisync A C` works.
Depending on the results will either update docs or submit a fix.

## How do you think rclone should be changed to solve that?

:thinking: :thinking: :thinking:

## How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
> can we have 3 paths?

No. It's not _trisync_ 😜 

> what if I do `bisync A B` and seperately `bisync A C`

I've tested this quite a bit, as it's one of my main use cases for bisync -- keeping my laptop and desktop both in sync with cloud storage. It is supported and works well, with the following important caveats:

- The trees for `B` and `C` should not overlap (documented [here](https://rclone.org/bisync/#lock-file))
- The two bisync runs should not be run _concurrently_, or it could create a race condition. (Similar to the [answer documented here](https://rclone.org/faq/#using-rclone-from-multiple-locations-at-the-same-time).)
- If you make non-identical edits to the same file on `B` and `C` without bisyncing with `A` in between, you will create a conflict, which bisync will resolve by renaming to `..Path1` and `..Path2` versions. This is [normal and expected](https://tip.rclone.org/bisync/#unusual-sync-checks) (because you've changed the file on both sides, and bisync has no way of knowing which you want to prevail).

For me, I just schedule one machine on the even hours and the other on the odds, and I've never had a problem. But in theory I could still run into trouble if either run were ever to take longer than an hour. A better solution, which we may want to consider for the future, would be extending the [lock file](https://rclone.org/bisync/#lock-file) functionality so that 1.) it can be stored on a non-local remote, and 2.) it locks out any other bisync run that attempts to bisync _either_ path (not just _both_.) i.e. `bisync A B` should lock out not only other `bisync A B` runs, but also any runs of `bisync A C`, `bisync A D`, etc. (including `bisync B A`, but not `bisync C D`)

Note that `--workdir ` is already customizable, but needs to be a local path (not a remote like Google Drive). If we change this, we'll need to make sure it's filtered out of the path being bisync'd, lest we accidentally sync it. We'll also need to think through what happens if the dir isn't accessible (probably it should fail [resiliently](https://tip.rclone.org/bisync/#resilient)). 

See related ticket: #5678 (I think this one can be closed in favor of that one, since the "investigate" part is done.)

**Comment by nielash** [comment]
Closing this in favor of #5678 (see explanation [here](https://github.com/rclone/rclone/issues/5689#issuecomment-1685612894).) If anyone disagrees, please feel free to reply / reopen.
