### ISSUE TITLE
bisync: implement `--track-renames`

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5690]
## What problem are you are trying to solve?

bisync does not honor `--track-renames` !

## How do you think rclone should be changed to solve that?

bisync should honor `--track-renames` ?

Also see https://github.com/cjnaz/rclonesync-V2/issues/71

## How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by f0k** [comment]
Hello, I'd just like to know what's the progress on this feature. Is anybody planning to work on this soon, or is it a low priority? Is there anything I can help with, without speaking Go? As far as I see, compared to a unidirectional sync, this would require keeping a full listing of the last known synced state, in order to figure out *where* a rename took place.

For context, my use case would be keeping a directory on my phone in sync with a NextCloud server, where files can be added, deleted and renamed/moved on both ends. My options seem to be a) finding a software solution that supports this, b) renting a (twice as expensive) server I can run Syncthing on, c) writing a Python script myself. Rclone seems to be close to a), hence I'm curious. By no means I intend to beg anyone to implement this feature sooner!

**Comment by nielash** [comment]
> Hello, I'd just like to know what's the progress on this feature. Is anybody planning to work on this soon, or is it a low priority?

@f0k I just submitted a [PR](https://github.com/rclone/rclone/pull/6971) that should significantly improve this (albeit in a [slightly different way](https://github.com/rclone/rclone/pull/6971/commits/6309fe0fb052deed5ef0c970e13ce49487ddb7c9).) Files and folders can now be renamed on both sides without needing to re-upload, or do a `--resync`, or end up with erroneous `..path1` and `..path2` versions. (However, the behavior is unchanged when a rename is on only one side.)

**Comment by f0k** [comment]
Nice! However, if I understand correctly, this does not help when a file is renamed only on one side and I would like the change to propagate to the other side without incurring a retransmission.

**Comment by nielash** [comment]
> Nice! However, if I understand correctly, this does not help when a file is renamed only on one side and I would like the change to propagate to the other side without incurring a retransmission.

You are correct.

As a note to anyone revisiting this later (possibly me), I think the technical limitation currently is that `--track-renames` doesn't work with `copy`, only `sync`. Whereas `bisync` uses `copy` to transfer the queued files to the opposite path, and then it does the queued deletes in a later step. Here's the line where it calls `CopyDir`:

https://github.com/rclone/rclone/blob/415f4b2b93cd39799818cc87349510d8f4f32fa1/cmd/bisync/queue.go#L26-L26

which then calls `runSyncCopyMove` with `fs.DeleteModeOff` hard-coded:

https://github.com/rclone/rclone/blob/415f4b2b93cd39799818cc87349510d8f4f32fa1/fs/sync/sync.go#L1141-L1144

`fs.DeleteModeOff` precludes `--track-renames`:

https://github.com/rclone/rclone/blob/415f4b2b93cd39799818cc87349510d8f4f32fa1/fs/sync/sync.go#L208-L211

I think it should be possible (and desirable) to support `--track-renames` for `bisync`, but it would take a bit of rethinking about how `bisync` queues work.
