### ISSUE TITLE
serve webdav symlink read-only write attempt -> http: superfluous response.WriteHeader 

### ISSUE THREAD

**Issue by cyayon** [rclone/rclone#5702]
Hello,

I have a rclone  serve webdav daemon which running with my uid (not root).
On my home directory (webdav served), i have a symlink to another read-only directory.

I am able to list and browse all directories, the read-only followed with symlink, and others.

When i try to write on the read-only directory multiple times (in fact it is macos which try to create .DS_Store files), the rclone daemon log multiple times : 
http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:74)

And then i am unable to list the read-only directory (before write attempt, i have no issue).

I am using the last 1.56.2 version of rclone on linux amd64.

thanks.

**Comment by ncw** [comment]
I tried to replicate this, but I haven't succeeded yet.

Please can you post the log from `rclone serve webdav -vv`

Thanks

**Comment by WeidiDeng** [comment]
I run into this problem before, after some messing with the golang webdav library and rclone, I believe I found the cause.

When creating webdav server, rclone delegate filesystem operations to vfs, [Mkdir](https://github.com/rclone/rclone/blob/master/cmd/serve/webdav/webdav.go#L254), [OpenFile](https://github.com/rclone/rclone/blob/master/cmd/serve/webdav/webdav.go#L254) etc.

The problem is when trying to create a file in a readonly-directory, vfs allocates a [file](https://github.com/rclone/rclone/blob/master/vfs/file.go#L659), (according to my test, first a vfs file node is allocated, and a write handle is returned). When vfs flushes the content via [openPending](https://github.com/rclone/rclone/blob/master/vfs/write.go#L59), which is in turn called by [Close](https://github.com/rclone/rclone/blob/master/vfs/write.go#L185) (debug.PrintStack output, I wonder why none of the write related method is called, but perhaps [resp.Body implemented ReadFrom](https://github.com/golang/net/blob/master/webdav/webdav.go#L271)), [rcat will fail](https://github.com/rclone/rclone/blob/master/vfs/write.go#L71), and [file handle object won't be set](https://github.com/rclone/rclone/blob/master/vfs/write.go#L203).

Now that's the first part, when browsing the webdav server, client will send PROPFIND request to fetch the directory listing, which calls [walkFS](https://github.com/golang/net/blob/master/webdav/file.go#L758), which in turn open file [read only](https://github.com/golang/net/blob/master/webdav/file.go#L775), however openRead requires a [validObject wait](https://github.com/rclone/rclone/blob/master/vfs/file.go#L511), this check will always fail because

1. The underlying fs.Object is nil, it's only set when [file handle is closed without error](https://github.com/rclone/rclone/blob/master/vfs/write.go#L203).
2. Time.Sleep won't help, writers are deleted when Close [returned](https://github.com/rclone/rclone/blob/master/vfs/write.go#L191).

**Comment by cyayon** [comment]
Does this patch included in the last nightly/beta build ?
If yes, which one please ?

**Comment by ncw** [comment]
@WeidiDeng - I think that looks like a good fix.

Do you want to submit a Pull request with that?

Can you try to make a test for it too? (Might be hard!)

**Comment by WeidiDeng** [comment]
> @WeidiDeng - I think that looks like a good fix.
> 
> Do you want to submit a Pull request with that?
> 
> Can you try to make a test for it too? (Might be hard!)

1. I already submit a [pr](https://github.com/rclone/rclone/pull/5800).
2. I don't know where to set up the test case, should it be in vfs or webdav?

**Comment by ncw** [comment]
@WeidiDeng 
> 1. I already submit a [pr](https://github.com/rclone/rclone/pull/5800).

Nice - missed that - sorry!

> 2. I don't know where to set up the test case, should it be in vfs or webdav?

I would say this should be a VFS test - that is where the fundamental issue is.

The test should go in here https://github.com/rclone/rclone/blob/master/vfs/write_test.go

I think what you'll have to do is create a read only directory on the underlying file system then run your test there.

**Comment by piyushgarg** [comment]
rclone v1.62.0-DEV
- os/version: darwin 13.2.1 (64 bit)
- os/kernel: 22.3.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.19.6
- go/linking: dynamic
- go/tags: none

The superfluous error is coming on mac while the same webdav is working fine on rclone linux build.

```
2023/02/24 15:10:38 http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:75)
2023/02/24 15:10:38 INFO  : /: PROPFIND from 192.168.0.24:64738
2023/02/24 15:10:51 DEBUG : /: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2023/02/24 15:10:51 DEBUG : /: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2023/02/24 15:10:51 DEBUG : /.DS_Store: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : .DS_Store: Open: flags=O_RDONLY
2023/02/24 15:10:51 DEBUG : .DS_Store: >Open: fd=<nil *ReadFileHandle>, err=can't open file - writer failed
2023/02/24 15:10:51 DEBUG : /.DS_Store: >OpenFile: fd=<nil *ReadFileHandle>, err=can't open file - writer failed
2023/02/24 15:10:51 http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:75)
2023/02/24 15:10:51 INFO  : /: PROPFIND from 192.168.0.24:64738
2023/02/24 15:10:51 DEBUG : /: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2023/02/24 15:10:51 DEBUG : /: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2023/02/24 15:10:51 DEBUG : /.DS_Store: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : .DS_Store: Open: flags=O_RDONLY
2023/02/24 15:10:51 DEBUG : .DS_Store: >Open: fd=<nil *ReadFileHandle>, err=can't open file - writer failed
2023/02/24 15:10:51 DEBUG : /.DS_Store: >OpenFile: fd=<nil *ReadFileHandle>, err=can't open file - writer failed
2023/02/24 15:10:51 http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:75)
2023/02/24 15:10:51 INFO  : /: PROPFIND from 192.168.0.24:64738
2023/02/24 15:10:51 DEBUG : /: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2023/02/24 15:10:51 DEBUG : /: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2023/02/24 15:10:51 DEBUG : /.DS_Store: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:10:51 DEBUG : .DS_Store: Open: flags=O_RDONLY
2023/02/24 15:10:51 DEBUG : .DS_Store: >Open: fd=<nil *ReadFileHandle>, err=can't open file - writer failed
2023/02/24 15:10:51 DEBUG : /.DS_Store: >OpenFile: fd=<nil *ReadFileHandle>, err=can't open file - writer failed
2023/02/24 15:10:51 http: superfluous response.WriteHeader call from golang.org/x/net/webdav.(*Handler).ServeHTTP (webdav.go:75)
2023/02/24 15:10:51 INFO  : /: PROPFIND from 192.168.0.24:64738
2023/02/24 15:36:02 DEBUG : /: OpenFile: flags=O_RDONLY, perm=----------
2023/02/24 15:36:02 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2023/02/24 15:36:02 INFO  : /: PROPFIND from 192.168.0.24:65019
```
