### ISSUE TITLE
documentation is missing typical rclone.conf examples for each provider

### ISSUE THREAD

**Issue by zoobab** [rclone/rclone#572]
Hi,

I am finding that the documentation talks about this interactive `rclone config` mode, but the most common way of configuring things is via a config file. It would be useful to provide typical config files for each provider, right now I am using rackspace with swift.

**Comment by ncw** [comment]
The reason why I haven't documented the config file is that the majority of the remotes can't be configured that way as they use oauth2 which requires rclone interacting with a web server.

`rclone config` for swift has the rackspace endpoints built in which should make configuring rackspace swift really easy.

The config file for rackspace should look like this

```
[rackspace]
type = swift
user = USER
key = KEY
auth = https://identity.api.rackspacecloud.com/v2.0
```

**Comment by edwardxml** [comment]
I will try to review this in the next few weeks. Ed.

**Comment by edwardxml** [comment]
I had originally thought of going through creating example rclone.conf sections for a range of backends and pasting them into backend hep topics. That is just something else to maintain in step when in reality any rclone user wanting an example rclone.conf section will just create one with rclone config.  Backend specific flags and advanced ones are already documented directly from backend code.

I suggest this issue is closed.

**Comment by ivandeex** [comment]
@albertony 

Do you think we need rclone.conf examples in backend docs?

**Comment by albertony** [comment]
Hm... I agree with @edwardxml. But perhaps we could add a short description of the general syntax? I did not find that anywhere.. I mean something describing: Text file, where remote names are withing [], followed by "key = value" lines, where you at least must have key "type" with value according to the backend id as returned by `rclone help backends`, and optionally other options as described for each backend, etc...

**Comment by ivandeex** [comment]
Or a link to https://en.wikipedia.org/wiki/INI_file#Format ?

**Comment by albertony** [comment]
Yes, sure, that is fine. So just describe how "sections" are "remote names" etc..

**Comment by jessuppi** [comment]
For future Googlers like myself, it seems the challenge is that Rclone supports simultaneous backup services (remotes) so the config file reflects that ability to have multiple sections in the INI format per-service.

Technical users who want to review everything first and don't really like using setup wizards may feel overwhelmed.

My project SlickStack is aiming to integrate Rclone using standardized config variables e.g.:

```
RCLONE_SERVICE="backblaze"
RCLONE_MODE="copy"
RCLONE_CLIENT_ID=""
RCLONE_CLIENT_SECRET=""
RCLONE_USER=""
RCLONE_PASSWORD=""
RCLONE_TOKEN=""
```

Ref: https://github.com/littlebizzy/slickstack/blob/master/modules/rclone/rclone-config.txt

Since we only plan to support a single Rclone destination (remote) per SlickStack server, I hope this can work, and our central configuration file `ss-config` can successfully generate the required config file for Rclone that way. However this approach has not been tested yet re: Oath concerns explained by @ncw 

...this approach also means changing to a different remote overwrites prior settings.
