### ISSUE TITLE
IAM Role for Service Account stopped working after v1.54.1

### ISSUE THREAD

**Issue by ThisIsQasim** [rclone/rclone#5762]
Follow up on #5414 and #5137 and I know @ncw has been looking to fix. I am able to successfully use IAM Role for Service Account (IRSA) on v1.54.0 but get access denied on v.1.54.1 so it looks like it broke somewhere between v1.54.0 and v1.54.1. Comparing the code it looks like there was a line to use the default AWS SDK credential provider chain which got removed. https://github.com/rclone/rclone/blob/7f5ee5d81f12045d1565fd5dc6596bc81d44d431/backend/s3/s3.go#L1564

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.57

**Comment by tcasteix** [comment]
Hello, 
I'm running the version 1.59.2 and tried to use the IAM role function (role attached to an AWS EC2 instance) in order to copy files to a AWS S3 bucket but I got an Access Denied, while with aws CLI it worked. I deduced it was not a policy bucket issue. 
my env_auth = true was set . I ran -vv --dump auth and saw the role that meant to be used. I do think it was not used properly by rclone.
I was able to list the content of my bucket but writing into it with env_auth = true.

**Comment by jwierzbo** [comment]
@tcasteix I've had same issue. To solve it I've had to add full access to my bucket:

```{
   "Version":"2012-10-17",
   "Statement":[
      {
         "Effect":"Allow",
         "Action": "s3:ListAllMyBuckets",
         "Resource":"*"
      },
      {
         "Effect":"Allow",
         "Action":"*",
         "Resource":"arn:aws:s3:::MY_BUCKET"
      },
      {
         "Effect":"Allow",
         "Action":"*",
         "Resource":"arn:aws:s3:::MY_BUCKET/*"
      }
   ]
}
```
