### ISSUE TITLE
quickxorhash optimization

### ISSUE THREAD

**Issue by isaacl** [rclone/rclone#5959]
Follow up from #5884

Perhaps we can borrow the extensive optimization ideas ideas from [this swift project](https://github.com/ranlor/QuickXorHash).

My understanding is this hash is the bottleneck in rdrive sync commands to onedrive – is that correct?

**Comment by ncw** [comment]
> My understanding is this hash is the bottleneck in rdrive sync commands to onedrive – is that correct?

You should also check out the `--cpuprofile` flag on rclone so you can measure exactly how much CPU the hashing takes when you are doing a real transfer.

**Comment by ncw** [comment]
I think you'll find the OneDrive syncing is bottlenecked on the onedrive api, but the profiles will say.

If you enable the `--rc` then you can see profiles - see the docs here: https://rclone.org/rc/#other-profiles-to-look-at

I don't think the slack chat is working at the moment. Happy to answer questions here.

**Comment by ncw** [comment]
[Posting on the rclone forum](https://forum.rclone.org/) is the best way to chat with knowlegeable users, and it make a nice searchable knowlegebase for the future.

> * when syncing TO the remote, how does rclone determine which files to check?

It checks all of them in the source path.

>   Could it track the last complete sync and filter based on mtime?

You can do this using --max-age which can take a date or a time specifier (eg `2h`). It is a popular way of speeding up syncs, though you want to use `rclone copy` rather than `rclone sync`.

> * Questions about a complicated oauth dance (federated account) to obtain cookies for using OneDrive webdav, whether that might run faster / be less quirky.

Probably best to make a topic in the forum about that and hopefully someone who knows more about it that me can answer!

I'm going to close this issue now since I think we've gone off topic, and I don't think optimizing quickxorhash will help you very much.
