### ISSUE TITLE
rclone package linux-arm-v7.deb, v1.58.0-beta.5887 and newer, not installable on raspian (rPi4), architecture missmatch

### ISSUE THREAD

**Issue by RichardBeisser** [rclone/rclone#5973]
RaspberryPi 4 has an arm-v7 architecture. Raspian is based on debian. so the right package for installation is linux-arm-v7.deb
when you try to install with
apt install linux-arm-v7.deb
v1.58.0-beta.5887 and newer, the package manager will fail.

the deb-package doesnt contain the information any more that the package is also for armhf.
so the package manager will stop installation:

Error while processing Archiv rclone-beta-latest-linux-arm-v7.deb (--unpack)
Package-Architecture (arm) doesnt match with system (armhf)
sub-process /usr/bin/dpkg returned an error code (1)

more details
https://forum.rclone.org/t/problem-with-option-netdev-in-fstab-rclone-v1-58-0-beta-5885/29007/3?u=blacksun

**Comment by ncw** [comment]
It looks like that due to an update of nfpm the .deb packages are being given the architecture `arm` rather than `armhf` like they used to be.

It looks like this is the relevant change

https://github.com/goreleaser/nfpm/issues/367

I've had a go at fixing this, can you check these out when they've built?

[v1.58.0-beta.5981.4dd448856.fix-5973-arm-deb](https://beta.rclone.org/branch/fix-5973-arm-deb/v1.58.0-beta.5981.4dd448856.fix-5973-arm-deb/) on branch [fix-5973-arm-deb](https://github.com/rclone/rclone/tree/fix-5973-arm-deb) (uploaded in 15-30 mins)

**Comment by RichardBeisser** [comment]
> [v1.58.0-beta.5981.4dd448856.fix-5973-arm-deb](https://beta.rclone.org/branch/fix-5973-arm-deb/v1.58.0-beta.5981.4dd448856.fix-5973-arm-deb/)

I tested it, this file works.
Now these changes have to build in nfpm. the official beta-files do not work

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.58

Thanks for testing :-)

**Comment by RichardBeisser** [comment]
> I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.58

I could install arm-v7.deb file from folder v1.58.0-beta.5988.3e125443a successfully.
First I tried the file from root folder rclone-beta-latest-linux-arm-v7.deb
This file was not instalable --> invalid header in archiv file
Only a temporarelly problem?

**Comment by ncw** [comment]
> Only a temporarelly problem?

A stale file had got in the cache somehow... If you try again it should be OK now.
