### ISSUE TITLE
Bisync should be considered experimental

### ISSUE THREAD

**Issue by asdffdsazqqq** [rclone/rclone#6082]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/bisync-should-be-considered-experimental/29879

#### What is your current rclone version (output from `rclone version`)?
not required

#### What problem are you are trying to solve?
Bisync should be considered experimental and the documentation to reflect that.

#### How do you think rclone should be changed to solve that?
1. https://rclone.org/commands/rclone_bisync/
--- should be labeled `experimental`
--- should have a scary warning, some suggestions are
"Warning, `rclone bisync is advanced command, that is considered experimental. Use at your own risk.
"Can delete files on BOTH the source and dest"
"Can result in the permanent loss of files on the source and dest"
"Important: Since this can cause data loss, test first with the --dry-run or the --interactive/-i flag."

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Feel free to submit a PR as that gets reviewed and you can make updates as agreed upon.

**Comment by Xelbayria** [comment]
I am aware that it's an experimental, so what's the state of `rclone bisync`?  is it in alpha or beta?

**Comment by asdffdsazqqq** [comment]
> I am aware that it's an experimental, so what's the state of `rclone bisync`? is it in alpha or beta?

the state is `unmaintained ` as per
https://forum.rclone.org/t/bisync-bugs-and-feature-requests/37636/3

**Comment by nielash** [comment]
> the state is unmaintained  as per
https://forum.rclone.org/t/bisync-bugs-and-feature-requests/37636/3

It is now `maintained` again, as I have volunteered to maintain it 😃

As for the original question, I agree Bisync should be considered "experimental", although I think "beta" is a better description for it. There are really two distinct risks here, and I think it's worth tracking them separately:

1. The risk that the code could have bugs -- both ones that we're [aware of](https://tip.rclone.org/bisync/#limitations) and not yet aware of, since it's relatively new ([Nov 2021](https://github.com/rclone/rclone/pull/5164#issuecomment-956454724)) and more real-world testing is needed
2. The risk inherent to using any kind of bi-directional sync tool, even one that is bug-free (ex. ability to delete files on both source and dest)

Risk 1 can be addressed over time as bugs get fixed and real-world use gives us more confidence about unknown unknowns. However, Risk 2 really can't ever be addressed, as it's just inherent to the command's nature. So, if Risk 2 justifies an "experimental" label, Bisync will stay experimental forever, no matter how mature and stable the code becomes over time.

Therefore, I would propose that we communicate Risk 1 by continuing to consider Bisync in "beta", and making that clearer in the docs ([it's there](https://tip.rclone.org/bisync/#supported-backends), but too easy to miss), until such time that we feel comfortable calling it "stable". I would also propose updating this language accordingly:
https://github.com/rclone/rclone/blob/156c372cd760460f419708c75506434c48decfc8/cmd/bisync/cmd.go#L152 

For Risk 2, I'd suggest we communicate it through big bold "**Important**" warnings, like other destructive commands such as [`purge`](https://rclone.org/commands/rclone_purge/) or [`dedupe`](https://rclone.org/commands/rclone_dedupe/). I like calling Bisync an "advanced" command, as that will always be true. But "experimental" implies that the experiment will be over at some point, and this one won't be.

I also think that if we add the `beta` label, we should establish some clear criteria it will have to meet to be considered "out of beta". Here's the checklist I'd probably propose, but I'd love some feedback on this:

- [ ] fix #5676 
- [ ] fix #5679 
- [ ] fix #5683 
- [ ] fix any major bugs discovered through real-world beta testing, over at least 2 release cycles

There are, of course, many other issues that should be addressed at some point, but I think we do have to draw the line somewhere, lest Bisync remain in `beta` forever. IMO, the `beta` label should be more about whether it's safe to use (as documented) in production, not whether it has lots of features.

**Comment by Xelbayria** [comment]
Hey, 
I agree with you regarding the "beta" and had no problem using `rclone bisync` for the last few months. It depends on how one person uses it and may have encountered a problem like 4 tasks from the task list above. I haven't encountered any of them yet. Everyone has their definition of what is the beta. The person who develops "beta" will decide whether it's in beta or experimental.

I used it for syncing data between 2 devices using the same app. The system I set up is risk-free, so I am not worried if something goes wrong. I noticed since the early usage of Bisync. The app cannot be opened at the same time on both devices. Otherwise, Bisync will create files with `..path1` and `..path2`. I've researched to check if there is a better _bisync_ software. It seems all have the same problem. You can say these software with _bisync_ are Work In Progress.

**Comment by nielash** [comment]
@Xelbayria Thank you for the feedback!

> I noticed since the early usage of Bisync. The app cannot be opened at the same time on both devices. Otherwise, Bisync will create files with `..path1` and `..path2`. I've researched to check if there is a better _bisync_ software. It seems all have the same problem.

This was also one of my biggest annoyances when I first started using bisync! I improved the behavior in `v1.64` so that it now checks first if the edits on both sides are identical, and skips the `..path1` / `..path2` renaming if so. I'd encourage you to check it out, if you haven't already!

Bisync DOES still rename them if they are NOT identical, as that is a true sync-conflict. For my future knowledge: what would you prefer to happen in that scenario? (i.e. same file edited on both sides since the last sync with non-identical edits)

**Comment by Xelbayria** [comment]
> Bisync DOES still rename them if they are NOT identical, as that is a true sync-conflict. For my future knowledge: what would you prefer to happen in that scenario? (i.e. same file edited on both sides since the last sync with non-identical edits)

That's a difficult question. The data from the app are contents that will keep changing. For example, the app is a video player that can play videos. It holds a record of what I watched. On Device#1, I watched Video#1. On Device#2, I watched Video#2.   What if I use the app on both devices on the same day (down to an hour)? The renaming happened. The contents in the file from both devices are not identical. I've seen some software forums discussing "merging". The method is not usable because it's not perfected. There are many reasons for that. The contents will be different in varying files. There are no rules or patterns. 

I've come up with 3 different methods. The above is for "merging". The other scenes would be "Selection" and "PathX, then PathX". 👈 has no name for that yet.

**Comment by nielash** [comment]
@Xelbayria Thanks! Makes sense. One thought I had recently is a new optional `--prefer` flag to auto-resolve such conflicts, with values like `newer | older | path1 | path2` (with `newer` and `older` requiring modtime support). The current behavior would remain the default, as it is the safest. There would maybe also need to be a setting to control what happens to the "loser" (whether it gets deleted or just renamed.)

I agree that "merging" would not be viable, for a number of reasons, but perhaps a `--prefer` option could be a good solution for you.
