### ISSUE TITLE
ncdu: show excludes

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#6087]
From https://github.com/rclone/rclone/issues/3369

```
ls x || exit 1
mkdir x/y -p
echo foo > x/bar
echo bar > x/y/z
rclone ncdu x --exclude '/y/**'
rm x -r
```

Expected: Directory `x/y` is shown on the listing with `<` at the beginning.

Actual: I see no exclusion, I hear no exclusion. It is as if dir `y` did not exist at all.

**Comment by ncw** [comment]
Yes we are deviating from `ncdu` here. `--excludes` are handled at a lower level so `rclone ncdu` never gets to see them.

I don't think this is at all easy to fix, so my preference would be to document the behaviour.

What do you think @albertony ?

**Comment by albertony** [comment]
> --excludes are handled at a lower level so rclone ncdu never gets to see them. (...) I don't think this is at all easy to fix.

I agree.

I've not used (rclone) ncdu all that much, but I guess with a large remote one would want to use filtering to reduce network traffic and increase "ui response time", and if we were to refactor exclude handling so that it is exposed to ncdu it would probably break that:

> Please note that even though you can't see the hidden files and directories, they are still there and they are still included in the directory sizes.
(https://linux.die.net/man/1/ncdu)

Perhaps possible to figure out something smart, e.g. separate between "low level excludes" (the rclone way) and "high level excludes" (the ncdu way), but I don't think its worth spending a lot of effort on.

> so my preference would be to document the behaviour.

Lets do that.
