### ISSUE TITLE
bisync flag "--create-empty-src-dirs" missing

### ISSUE THREAD

**Issue by FreyLuis** [rclone/rclone#6109]
The Flag "--create-empty-src-dirs", that is implemented in copy, sync, etc is missing for bisync.

**Comment by ncw** [comment]
What would you like bisync to do - sync empty directories? We could probably do with a better named flag.

**Comment by PandaSITT** [comment]
The "-scr-" might be unnessesarry,

**Comment by PandaSITT** [comment]
> What would you like bisync to do - sync empty directories?

Yes, the same thing that has allready been implemented for other commands. Maybe the "-scr-" doesn't fit anymore

**Comment by larnon** [comment]
I try to use rclone with Google Drive and Cryptomator to sync files between different devices(Windows, Linux, Android). Cryptomator creates many empty directories, and without such flag, rclone removes all those empty directories at remote. I would say this, and automatic resyncing after file operations are the 2 things mainly missing from otherwise an amazing tool.

**Comment by web2brain** [comment]
Cryptomator is my use case as well.
The workaround mentioned [here](https://rclone.org/bisync/#empty-directories) is not really suitable for calling bisync regularly with a cronjob...
