### ISSUE TITLE
Feature Request: Compression remote (Zip)

### ISSUE THREAD

**Issue by cccapon** [rclone/rclone#675]
A compression remote would be similar to the "crypt" (Encrypt/Decrypt) remote in that its destination is some other remote folder.  

It would use gzip/7zip/bzip to reduce the size of any file which can reasonably be compressed.  It would merely store files which do not benefit from compression.

Storing compressed files would mean the amount of cloud storage required is reduced.  

This leads to more available space to store more files before cap limits are reached.

Thanks.

**Comment by ncw** [comment]
Nice idea.

**Comment by pedrosimao** [comment]
I totally upvote it. By using 7zip, and choosing wisely what filetypes to compress (videos files, for example, are normally not worth compressing) we could significantly reduce the amount of data to upload/download during our backups/restores. Arq does it very well. I adopted rclone, instead of Arq, because I have more control. But this is something really missing in rclone.
Anyway, I don't want to compare commerical products with opensource ones. But rclone is much better than Arq for many things...

**Comment by chosn** [comment]
I would welcome a zip feature too.
I also had to make a decision between Arq and rclone. But rclone has too many advantages, so final decision was to use rclone. The only missing thing in rclone is the compression feature....
Would be great if it is added in the near future...

**Comment by Stele77** [comment]
Definitely a huge benefit. For storage space, but also in combination with encryption needed to better hide file contents from cloud storage provider. I am just a noob, but i did some research, and this could prevent them to flag files for DMCA by hash. 
Which is a huge privacy concern and PITA, because the big providers dont care if private copys of copyrighted material are legal like in my country or not.
But even more, after Snowden and in this times we live in it should be a top priority for every dev, especially in FOSS IMHO. 
And otherwise RClone is so perfect, even for CLI noobs (Or been 20 y out of training ;) )! So thanks you for your hard work, and for considering,
Greetings,
Steven

**Comment by kraduk** [comment]
The new facebook compression algorythm would be a nice option to as it offers better levels than lz4.

https://github.com/facebook/zstd

**Comment by Jefferderp** [comment]
+1 to that. BSD license, and even btrfs promises to implement this with the next Linux kernel version, very promising.

**Comment by hieu-n** [comment]
I'm switching to https://github.com/odeke-em/drive to rclone because rclone seems to be more lighter on resources and supports more cloud storage services. One thing I would miss from `odeke-em/drive` is the ability to do this:


```
tar czf - . | drive push -piped backup-$(date +"%m-%d-%Y-"%T"").tar.gz
# It pushes a tar.gz archive created on the fly. No archive file is made on the machine running the command, so it doesn't waste disk space.

```

**Comment by ncw** [comment]
@hieu-n check [rclone rcat](https://rclone.org/commands/rclone_rcat/).  I suggest you use [the latest beta](https://beta.rclone.org) which is just about to be released and has improved rcat.

**Comment by rmalayter** [comment]
Ideally this should be mike type aware and happen transparently fir supporting back ends (s3, Swift, etc.).
With most of the major cloud providers you can set a Content-Encoding header that gets reflected back retrieval download.

So you upload a gripped version of file.html to container/file.html (note the lack of a .gz extension) with a “Content-Encoding: gzip” header, and the file is compressed on disk and is always served with “Content-Encoding: gzip” to browsers or other tools.

This would basically make compression transparent.

**Comment by ShapeShifter499** [comment]
I would love to see this feature.   I originally was making use of duplicity and that has this feature, but I had to go abandon it because it took too much RAM when I tried to download the stuff I had uploaded. rclone does much better for RAM so far in my tests which is good since I'm running this on a Raspberry Pi 3B+

**Comment by Maxpain177** [comment]
+1

**Comment by mholt** [comment]
I'd be interested in an rclone command that can take a folder or archive file on one end, and spit out the opposite on the other end. For example: `folder source -> archive destination` creates an archive file, and `archive source -> folder destination` extracts it.

Incidentally, I just updated https://github.com/mholt/archiver over the last few weeks so that it can do this very task... it's agnostic of file system and is a perfect library companion for this sort of thing.

**Comment by ncw** [comment]
> I'd be interested in an rclone command that can take a folder or archive file on one end, and spit out the opposite on the other end. For example: `folder source -> archive destination` creates an archive file, and `archive source -> folder destination` extracts it.

Yes, I've had that idea too in the past - I think it is a good one!

So something like

    rclone zip /path/to/source/files remote:destination.zip

and

    rclone unzip remote:source.zip /path/to/destination/files


> Incidentally, I just updated https://github.com/mholt/archiver over the last few weeks so that it can do this very task... it's agnostic of file system and is a perfect library companion for this sort of thing.
> 

archiver looks like very nice tool :-)

So were you thinking of an `rclone archiver ...` command?

> (If this request is too different from the original post, let me know and I can open a new issue.)

I think this is a new issue - this issue is about a transparent compression and decompression overlay for any backend.

**Comment by mholt** [comment]
> I think this is a new issue - this issue is about a transparent compression and decompression overlay for any backend.

Gotcha, I'll open a new issue to propose it. Not a high priority for me personally, but something that would be cool nonetheless.

(The archiver package _also_ supports streaming compression -- without archival -- for a variety of formats, so that may still be useful if you wish.)

**Comment by ferferga** [comment]
Eagerly waiting for this, such a cool and useful idea! Thank you very much for your interest in working on it @id01 !

**Comment by ivandeex** [comment]
Everybody interested is welcome to test alpha _compress_ remote https://github.com/rclone/rclone/pull/4566

**Comment by cowwoc** [comment]
@ivandeex Very cool. How do we test this? Are there pre-built binaries for us to download?

**Comment by ivandeex** [comment]
@buengese I recall @ncw once noted in https://github.com/rclone/rclone/pull/4566#issuecomment-699516713 a way to produce branched betas. Is there one for _compress_?

**Comment by pedrosimao** [comment]
Great functionality! Should have been there since the beginning! I just wonder if we should not add LZ4 too, since compression and decompression times are much faster on multi-core processors (most of the desktops, for example).

**Comment by pedrosimao** [comment]
@ivandeex is this feature compatible with encryption?

**Comment by ivandeex** [comment]
> @ivandeex is this feature compatible with encryption?

It's in alpha yet.

**Comment by ivandeex** [comment]
> I just wonder if we should not add LZ4 too

The first release of compression remote will have only gzip (https://github.com/rclone/rclone/issues/992)

**Comment by buengese** [comment]
> @ivandeex Very cool. How do we test this? Are there pre-built binaries for us to download?
the current branch has no beta. If you are interested in testing it I can make one.

>Great functionality! Should have been there since the beginning! I just wonder if we should not add LZ4 too, since compression and decompression times are much faster on multi-core processors (most of the desktops, for example).
Previous attempts at implementing this had support for LZ4 but for the current it's not supported. The gzip implementation we use is multithreaded and can reach speeds >125mb/s even on low end hardware when using a low compression level therefore I don't really see a need for lz4.

**Comment by id01** [comment]
I'm surprised this remote ended up coming to fruition. Congrats/thanks @buengese !

Yeah, @pedrosimao  we used to have lz4 and lzma, but couldn't find (good enough) Golang implementations for them that didn't use cgo with the original code. If an extensibility update for this remote comes up I might be able to salvage some code from the first version of the library that uses external binaries for generic compression. Maybe put it in a separate library or something. However, what Buengese says is true - as seekable compression is necessarily parallelizable, even gzip can reach very high speeds, likely higher than bandwidth allows.

As for the reason to use gzipped gob in the original metadata file, that choice was made to reduce storage space used (as those who use this remote likely have concerns with reducing storage space); the metadata files index the real size of every chunk (256KB by default but adjustable) in an array, which may make pretty large metadata for larger files. I suggest compressing the json?

**Comment by buengese** [comment]
I'm sorry I had meant to post this [beta link](https://beta.rclone.org/branch/v1.52.3-336-g38784e1b-press-new-v2-beta/) here and kinda forget. So if anyone wants to test go ahead. But please use with caution even though it's almost ready for merge now there might still be bugs.

regarding the metadata file: we already increased the default block size to 1MiB based on the assumption that people using the compression remote probably store mostly large files and seeking is a relatively rare occurrence. This already reduces the size of the json file quite a bit I compressing it wouldn't be a problem but honestly, I don't see many situations where the size of the metadata files could become a problem.

**Comment by id01** [comment]
Six megabytes per terabyte does sound like a better storage usage, and I suppose adding 1-2MiB of data per seek is a reasonable bandwidth usage by today's standards, especially for large files. I think the original version had a default block size of 64KiB for gzip, so the metadata files used a lot more data.

**Comment by cowwoc** [comment]
@buengese Is this beta backwards compatible with existing data? Meaning, will existing uncompressed data co-exist with new compressed data we add to the same server? Also, is there a way to trigger compression of existing data?

**Comment by ivandeex** [comment]
@buengese Is _sgzip_ file format compatible with _gzip_ and common _pgzip_?

**Comment by buengese** [comment]
>@buengese Is sgzip file format compatible with gzip and common pgzip?
Yes sgzip is 100% standard gzip. Both pgunzip and gunzip will work. It's a fork of pgzip with added seeking functtionality, the changes are honestly very minor but I decided not upstream them because they are rather specific to this use case. I think I've elaborated on this in the pr.

>@buengese Is this beta backwards compatible with existing data? Meaning, will existing uncompressed data co-exist with new compressed data we add to the same server? Also, is there a way to trigger compression of existing data?
You should be using the compression backend and an uncompressed backend for the same path. If you wrap a backend with compression it should be empty or a subfolder. Compressing the existing data involves copying the existing data to the new compressed backend. e.g. `rclone copy uncrompressed-backend: compressed-backend:` obviously compressed backend shouldn't be a subfolder of compressed backend in this case.

**Comment by id01** [comment]
I think one thing that should be clarified is that seekable compression is a subset of gzip compression: `gunzip file.txt.gz` will produce the original data due to gzip specification, but gzipping it back won't generate the file structure or metadata needed. So don't add or replace gzip files manually - it's going to be really, really bad.

**Comment by cowwoc** [comment]
@buengese I can't figure out how to get this to work. I've got two remotes "local" and "local-cache" where "local-cache" is a cache wrapper on top of "local" and "local" is a local disk.

I tried creating a new compress remote that wraps "local" but every time I try writing to "local:g:\test" it writes to folder "g:" in the current working directory instead of treating "g:" as a drive letter. Is this a bug?

**Comment by buengese** [comment]
@cowwoc  You don't use drive letters through the local remote. What you'd do is create a local remote at G:\test and wrap that remote with compress.

**Comment by cowwoc** [comment]
@buengese It might help if you create a more detailed tutorial or screencast showing this because when I create a new local remote I am not prompted to enter a path so I am not sure how to do what you mention.

**Comment by buengese** [comment]
Ok I kinda misread what you wrote. What you did should indeed have worked as should have directly passing a local path when configuring the compress remote which is what I meant here. But it looks like neither is working for the windows build I linked here. Both ways are working fine on linux so this is fact a bug i missed. I'll look into it

**Comment by buengese** [comment]
Here is [new beta](https://beta.rclone.org/branch/v1.52.3-335-gc96c4cfc-press-new-v2-beta/) that should definitely work on windows.

**Comment by buengese** [comment]
This is now finally in master. Still somewhat experimental though.

**Comment by cowwoc** [comment]
@buengese Sorry for not replying earlier. I tried the new beta that you said should definitely work under Windows and I'm having the same problem. I run: `rclone sync source local-compressed:f:\backup\target` and files are getting backed up to `local/f:/backup/target` instead of `local:f:/backup/target`. Meaning, rclone is creating a sub-directory `local` relative to the current working directory instead of resolving this path on drive F:. Is this something you can fix?
