### ISSUE TITLE
Can't overwrite files on remotes mounted on Windows as SYSTEM user: Permission denied

### ISSUE THREAD

**Issue by ElDavoo** [rclone/rclone#6758]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-mount-running-as-windows-system-user-cannot-modify-overwrite-existing-file-from-local-command-line-or-remote-client-even-though-creating-a-new-file-works/34710

#### What is the problem you are having with rclone?

When mounting a remote as the SYSTEM user on Windows, overwriting a file will fail with "Permission denied", even with full VFS.

#### What is your rclone version (output from `rclone version`)

rclone v1.60.1
- os/version: Microsoft Windows 11 Pro 22H2 (64 bit)
- os/kernel: 10.0.22621.900 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.19.3
- go/linking: static
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 11, but should reproduce on any windows

#### Which cloud storage system are you using? (e.g. Google Drive)

OneDrive, Google

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone --config C:\Users\Davide\.config\rclone\rclone.conf mount msdev: P: --vfs-cache-mode full --vfs-read-chunk-size 1M --vfs-read-chunk-size-limit 16M --buffer-size 4M --vfs-cache-max-age 5m --cache-dir D:\rclonecachemsdev\  -v --network-mode --transfers 1 --bwlimit off

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

https://forum.rclone.org/uploads/short-url/7zeqQTaL5QPPNBdiCEpNdz8zSNR.log

----

Running as SYSTEM user is necessary when wanting to auto-start rclone as a service, with nssm. Otherwise, the network drive does not appear to either Administrator or the current user.  

As me and tangofan are having the same issue, I basically copied their forum post as it's very complete.

Everything works fine when mount is run with user permission (but then, the drive is not system-level and/or can't be started as a windows service)

Steps to reproduce:

1) On Windows, install rclone and winfsp to mount
2) mount a remote with rclone running it as the SYSTEM user
For example with `psexec.exe -s -i cmd /C "rclone --config ... `
3) Try to overwrite an existing file

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
This looks like a comment / doc fix.

Feel free to submit a PR to fix the docs if you'd like to make something more clear.

Click here:

https://github.com/rclone/rclone/blob/master/docs/content/commands/rclone_mount.md

Click on the pencil and you can submit an update.

**Comment by albertony** [comment]
@ElDavoo : I see the same, and I don't immediately understand why the default permissions is not enough when running as system user, because Everyone still have "Create files / write data" and "Create folders / append data". Forcing full access to everyone by adding `-o FileSecurity=D:P(A;;FA;;;WD)` makes writing work though, so you should be able to find a less dirty configuration by tweaking permissions as described here: https://rclone.org/commands/rclone_mount/#windows-filesystem-permissions.

**Comment by ElDavoo** [comment]
> This looks like a comment / doc fix.

To be honest, I feel like not letting people overwrite files is a deviation from what the normal behaviour for this software is - e.g. a software defect.  

Albertony's workaround (thanks for that!) can and should be published as a documentation update, but it really feels hacky (e.g. I can do `rclone mount a: ./a/`  on linux and it would work - i expect it to work the same way on windows without additional arguments)

**Comment by animosity22** [comment]
> on linux and it would work - i expect it to work the same way on windows without additional arguments

If I've learned anything over the years, I would not expect Linux and Windows to behave the same way.

Feel free to submit a change if that helps to ensure the documentation is better for Windows as that would help other folks :)

**Comment by albertony** [comment]
> To be honest, I feel like not letting people overwrite files is a deviation from what the normal behaviour for this software is - e.g. a software defect.

I see what you mean, but on the other side one might say running as system user, and combining with psexec, is not part of the normal use case. 

Also this permission stuff is quite complex, and on Windows it is highly based on the third party library WinFsp (this means to change how rclone mount behaves with regard to this may have to go through that external project in the end). So, as @animosity22 says, I don't think we can expect rclone to have identical behaviour on linux and windows.

In any case, it would be good to understand the issue: What permissions are wrong/missing, preventing windows write operation. Then we would could consider if its something we can/want to improve in code, or at least we would have the information required to write a good explanation in the documentation..

PS: A less dirty setting could be `-o FileSecurity=D:P(A;;FRFW;;;AU)`, which will set Read&Write permissions to "Authenticated Users", but prevent execute (then would have to add FX), delete and some more. Basically, with the FileSecurity SDDL string option, you can tweak the permissions however you want.

**Comment by ElDavoo** [comment]
> `-o FileSecurity=D:P(A;;FA;;;WD)`

is adding this to the docs a good idea? might it be a security risk?

**Comment by albertony** [comment]
Found a bit more explanation: It is the windows advanced permission `Write extended attributes` which makes the difference. It is mentioned in the docs already, related to the mapping of posix style permissions set by `--file-perms` and `--dir-perms`, though not specifically describing our case:

> Note that the mapping of permissions is not always trivial, and the result you see in Windows Explorer may not be exactly like you expected. For example, when setting a value that includes write access, this will be mapped to individual permissions "write attributes", "write data" and "append data", but not "write extended attributes". Windows will then show this as basic permission "Special" instead of "Write", because "Write" includes the "write extended attributes" permission.

By default when mounting; the owner gets the "Write extended attributes" permission (he basically gets full permissions, read, write, delete, but not execute - so not quite "Full control"), while the additional principals representing the posix "group" and "others" concepts does not get this permission (they get a bit less than the owner, basic read and write). When mounting as yourself you are able to write because you have the owner permissions. When mounting as system user you get the permissions set for the Everyone group, representing posix "others", and then you do not get "Write extended attributes" and are not able to write.

> is adding this to the docs a good idea? might it be a security risk?

I think its a good idea. I think the example `-o FileSecurity=D:P(A;;FRFW;;;WD)` should be recommended, as it closest matches the default Read&Write set for Everyone, with only the addition of the notorious "Write extended attributes". Then we could also mention that if execute is needed, `-o FileSecurity=D:P(A;;FRFWFX;;;WD)`, and if also delete is needed then full access permissions can be set with `-o FileSecurity=D:P(A;;FA;;;WD)`.
