### ISSUE TITLE
Add SFTP jump proxies support

### ISSUE THREAD

**Issue by bricewge** [rclone/rclone#6987]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/sftp-proxyjump-support/23881

#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.52.3
- os/arch: linux/amd64
- go version: go1.17.11
```

#### What problem are you are trying to solve?

Finding a replacement to [`sshfs`](https://github.com/libfuse/sshfs) which is now  orphaned and archived.

#### How do you think rclone should be changed to solve that?

Supporting SSH jump proxies in the SFTP backend. In OpenSSH this is done with [ProxyCommand](https://www.mankier.com/5/ssh_config#ProxyCommand) or [ProxyJump](https://www.mankier.com/5/ssh_config#ProxyJump) directives.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I found [an article explaining ProxyJump](https://medium.com/maverislabs/proxyjump-the-ssh-option-you-probably-never-heard-of-2d7e41d43464) - it is neat!

You could certainly do that by hand - so set up the SSH tunnel in advance and use SFTP to that.

So I guess we could imagine a list of intermediaries in the rclone.conf which rclone had to connect to first.

I wonder if we could make rclone use ssh for creating the connection rather than its internal ssh client. Then it would support ProxyJump and looking up in ~/.ssh/config

Using v1.55 syntax that could be something like this `:sftp,host=HOST,external` assuming that `external` meant use the external ssh. (There is probably a better name but it won't come to mind!).

Do you want to work on this @bricewge ? Or maybe your company would like to sponsor the feature?

**Comment by bricewge** [comment]
> I wonder if we could make rclone use ssh for creating the connection rather than its internal ssh client. Then it would support ProxyJump and looking up in ~/.ssh/config

This is how `sshfs` is doing it, this would make migrating to `rclone` straight forward. Also, it would avoid having to implement a parser for `ssh_config` ; there are already some go libraries for it, but they don't support all directives.

> Do you want to work on this @bricewge ? Or maybe your company would like to sponsor the feature?

Sorry I can't make the time to work on this feature request, even tho it would probably be fun to learn some Golang.

**Comment by redthing1** [comment]
I think that would be the best approach too.

**Comment by redthing1** [comment]
Looks like that patch solved this issue!

**Comment by ncw** [comment]
Yes I think #7012 is a good solution to this issue - use an external ssh binary with `--sftp-ssh`. I'll close this for now though if anyone wants to implement it in rclone itself then I'll re-open.

Note that this is in [the latest beta](https://beta.rclone.org/) and due for release in v1.64
