### ISSUE TITLE
rclone thinks a directory is new if it's a symbolic link to a known directory

### ISSUE THREAD

**Issue by glibg10b** [rclone/rclone#7030]
Let's say `rclone bisync a/ b/` works. Now, if I create a new symlink with `ln -s a c` and run `rclone bisync c/ b/`, it thinks c is a new directory.

**Comment by nielash** [comment]
The technical reason for this is that rclone sees `a` and `c` as different remotes (which happen to have identical contents). This is not unique to `bisync` -- we can also see that they are treated differently by `sync`:

```
% rclone sync a a
2023/08/19 02:13:20 ERROR : Fatal error received - not attempting retries
2023/08/19 02:13:20 Failed to sync: can't sync or move files on overlapping remotes (try excluding the destination with a filter rule)
%
```
```
% rclone sync a c
%
```

Because the canonical names are different, this causes bisync to name the listing files differently. For example, instead of overwriting `a..b.path1.lst`, it creates a new `c..b.path1.lst`.

In order for it to behave any other way, it would have to recognize that `c` points to `a`, and then use the `a..b` prefix for BOTH `rclone bisync a b` and `rclone bisync c b`. This would probably be possible, but I'm not sure if it's desirable, since it would be inconsistent with `sync`'s opinion that `a` and `a` overlap but `a` and `c` do not. (Alternatively, rclone as a whole could make the decision to _always_ rename `c` to be canonical `a` -- but this might have implications for other commands.)

`bisync` generally assumes that the same two paths will be bisync'd repeatedly. Can you say more about the use case that would require future bisync runs to sometimes be called as `rclone bisync a b` and other times as `rclone bisync c b`? (Using either one consistently should already work.)

**Comment by glibg10b** [comment]
@nielash I created a symbolic link to the directory to save typing (~/storage/shared/Documents/university/ vs ~/university). I suppose I could somehow change rclone's references to the former to point to the latter, though the only way I know how is by digging around in ~/.cache/rclone/

Thanks for your insight. Since I can't think of a use case either, I'm closing this issue
