### ISSUE TITLE
new feature: VFS auto normalization

### ISSUE THREAD

**Issue by kapitainsky** [rclone/rclone#7072]
Immediate goal of this enhancement is to fix macOS `rclone mount` which at the moment does not work properly regardless of mounting method used - macOSFUSE or FUSE-T. Optionally normalized VFS can bring other benefits as well e.g. some less common or future filesystems rclone users can work with and normalization constraints imposed.

The background issue and possible solutions have been discussed on the forum:

https://forum.rclone.org/t/possible-special-character-encoding-issue-on-macos/39048/30

At the moment many cloud storage destinations (and rclone virtual crypt remote) allow to store both NFC and NFD encoded files/directories names. Also rclone allows to upload/download both forms.

This in general works trouble free on Linux and Windows but breaks rclone mount functionality in macOS - depending on mount options either only NFC or only NFD content is visible/accessible - this is [unfortunate](https://eclecticlight.co/2021/05/08/explainer-unicode-normalization-and-apfs/) consequence of Apple design decision to be different than rest of the world and use exclusively NFD in their APIs. We won't change it.

Experimentation and testing, including [attempts](https://github.com/macos-fuse-t/fuse-t/issues/16) to improve situation with FUSE-T (it has now - since v1.0.20 - `-o nfc` option which should help with NFC path) lead me to believe that last missing part of the puzzle is rclone VFS lack of normalization.

I would like to propose to add optional normalization to VFS.

New option:

--vfs-normalize OFF/NFC/NFD - with OFF being default 

When set to NFC or NFD it would apply characters normalization to served content.

Edge case to watch is situation where two names differ only by normalization and coexist in the same folder e.g.:

```
$ rclone lsf crypt:TEST

CONFLICTéééFILE.txt
CONFLICTéééFILE.txt
```

one file is NFC and other is NFD. Only solution I see for such case is use only one name and log ERROR.

**Comment by ncw** [comment]
I think this should be achievable relatively easily.

All file / dir objects are ultimately made from the directory cache. So we only need to do the normalized comparison in the directory cache searching routine.

We actually do this already for case sensitive / insensitive file systems.

So first we look for an exact match which is a quick hash look up, and then we look for a case insensitive match which involves comparing every item.

https://github.com/rclone/rclone/blob/2c50f26c36e7b18e0fcfe18bc844a2141c9245af/vfs/dir.go#L710-L732

We could do something very similar for the normalization options too. I think we'd want to make a normalization function which does the (NFC, NFD) and/or (lower case) and just run through the loop once. We do exactly this in the sync routines so factoring this out would be sensible.

https://github.com/rclone/rclone/blob/2c50f26c36e7b18e0fcfe18bc844a2141c9245af/fs/march/march.go#L58-L71

> Edge case to watch is situation where two names differ only by normalization and coexist in the same folder

We currently just use the first one in the case vs CASE comparison. That is the easy thing to do. To detect a collision would require scanning the whole directory which would take on average twice as long.

Worth the extra CPU for an ERROR message?

> New option:
> 
> --vfs-normalize OFF/NFC/NFD - with OFF being default

Assuming we are only using the normalize option to find matching file names and not actually returning them to the OS then we can get away with using NFC only and this would match this flag which only does NFC normalization.

      --no-unicode-normalization   Don't normalize unicode characters in filenames

Once thing I am unclear on though - do you think we need to apply that normalization to the file names sent to the OS - is that your intention? So we  receive an NFC file name from Google Drive (say) and send the macOS kernel an NFD file name according to the flag? That will be a bit more work (but not much). I think this might be what the FUSE-T option `-o nfc` does though so maybe isn't necessary?

**Comment by kapitainsky** [comment]
> Once thing I am unclear on though - do you think we need to apply that normalization to the file names sent to the OS - is that your intention?

Yes this is the most important thing actually and whole purpose of this  - it is about sending to OS normalized names. Today we have a problem that remotes can contain both NFC and NFD names - it works on Linux but breaks macOS. 

> I think this might be what the FUSE-T option `-o nfc` does though so maybe isn't necessary?

This option converts names received from OS (macOS uses NFD) and makes sure that NFS mount receives NFC - so all NFS content is NFC. It also makes NFC content to work with macOS APIs.
It breaks when some content in remote is already NFD - files are not visible/directories are not browsable.

On macOS it happens for example when user uses `rclone copy/sync` - NFD names are saved in remote.

With `--vfs-normalize` to make macOS mount work we could either:

1. `--vfs-normalize NFD` - this is what macOS likes the most I think

2. `--vfs-normalize NFC` and use `-o nfc`

It is difficult to say which one will behave better on macOS - I think that both would work. But with NFC/NFD and macOS I have learnt that only testing can tell.

**Comment by kapitainsky** [comment]
The key purpose of this enhancement is to fix `rclone mount` on macOS. 

Today it simply does not work - does not matter with macFUSE or FUSE-T. And is unfixable by `-o modules=iconv,from_code=UTF-8,to_code=UTF-8` or `-o modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC` workaround. It only helps in some cases and creates new issues - like for example that files can not be open in Finder (macOS file browser)

**Comment by kapitainsky** [comment]
Cool. I am happy at all stages to test - I do not need binary build I can happily build myself from `git clone`.

I hoped that fuse-t can handle it fully but does not seem to be possible.

**Comment by kapitainsky** [comment]
Note:

With `--vfs-normalize` set to NFC or NFD `iconv` should not be applied:

https://github.com/rclone/rclone/blob/fcb912a664de2e4df0e71b63aa3a8a1f956dd495/cmd/cmount/mount.go#L120-L126

It is crude way to actually try to normalize - but it stopped working fully with advent of APFS FS few years ago and changes in normalization in all macOS. I actually suspect it never worked 100% before neither - but nowadays it is more apparent.

Still should be there for old Apple computers users - this is why  `--vfs-normalize`  should be optional

**Comment by kapitainsky** [comment]
Sorry to keep pestering... but can it be implemented one day?  I am not skilled enough in go to give it a go.  I do try to earn my karma points on the forum instead:) I do believe that it is missing piece of macOS `rclone mount` to work predictably and consistently.

**Comment by ncw** [comment]
> Sorry to keep pestering... but can it be implemented one day? I am not skilled enough in go to give it a go. I do try to earn my karma points on the forum instead:)

You have lots of karma indeed :-)

I put this on the 1.64 milestone which isn't a guarantee that it will make that release, but it will be on my radar at least!

**Comment by FurloSK** [comment]
Just dropping in to say that I would be extremely thankful for having this fixed at some point. It would save a lot of trouble for me and many users in Slovakia, Czech republic and other countries, where basically all words are accented, which makes using `rclone` very problematic.

**Comment by nielash** [comment]
I took a shot at fixing this: https://github.com/nielash/rclone/commit/af6c376ef102e56704a8bb6d81e53f3311474fd3 

It is the "smallest patch that could work" approach as ncw suggested. So, it does not add a new `--vfs-normalize` flag -- rather, it uses the existing `--no-unicode-normalization` (and note the double-negative -- `false` means normalize.) This seemed to be enough to fix it -- @kapitainsky I wonder if you agree?

> > Edge case to watch is situation where two names differ only by normalization and coexist in the same folder
> 
> We currently just use the first one in the case vs CASE comparison. That is the easy thing to do. To detect a collision would require scanning the whole directory which would take on average twice as long.
> 
> Worth the extra CPU for an ERROR message?

I attempted to split the difference on this by adding a new flag for this (disabled by default), `--vfs-block-norm-dupes` (better name suggestions welcome). ncw is right that there will be a performance hit, so I think most non-mac users will want to leave it off. However some mac users may want it, as otherwise the "edge case" @kapitainsky mentioned will have an odd effect: both versions of the file will be visible in the mount, and both will appear to be editable, however, editing either version will actually result in only the NFD version getting edited under the hood. So `--vfs-block-norm-dupes` prevents this confusion by detecting this scenario and hiding the duplicates + logging an error, similar to what `march` would do. Thoughts on this approach?

On a slightly-related note, it seems to me that there is something odd about how `lib/encoder` is behaving on mac. For example, if I mount a `crypt` remote with invalid UTF-8 paths and then run `rclone lsl` on the mount, I will get errors. However if I `rclone sync` that same remote to `local` and then `rclone lsl` the copied files, it works just fine. But then if I `rclone check` the same paths I synced, suddenly there are errors due to name encoding differences. Is it that the conversion only goes one way? Probably out of scope for this ticket, but thought I'd mention it.

**Comment by kapitainsky** [comment]
> I took a shot at fixing this: [nielash@af6c376](https://github.com/nielash/rclone/commit/af6c376ef102e56704a8bb6d81e53f3311474fd3)

This is a big one for us macOS users:)

As soon as I have a moment I will start testing it.

**Comment by kapitainsky** [comment]
OK I could not wait - I am very excited about this chance to fix this long standing issue:) - so I quickly tried with my test data (NFC/NFD mix usage) I used in the past. And hurrah! It works. Have not looked and "duplicates" yet. I am a bit swamped at the moment so it is only quick try - I will take for a proper ride later.

How exactly this patch work? Sorry I am not a programmer and struggle to understand exactly how it is achieved. I see that it ditches `iconv` conversions - this is nice - was doing it myself for long as it was maybe something working for HFS+ but definitely for APFS was only trouble. But on its own it was not enough.

**Comment by nielash** [comment]
> And hurrah! It works. Both in Finder and terminal using FUSE-T mount.

That is encouraging to hear! 😃 

> How exactly this patch work? Sorry I am not a programmer and struggle to understand exactly how it is achieved.

Basically it takes the existing `--vfs-case-insensitive` logic and extends it to apply to both case insensitivity and unicode normalization form. So, if mac references a file with its NFD name, rclone first looks to see if it has a file with that exact NFD name. If it does, great -- we're done. If it does not, instead of telling mac "sorry, I don't have that", it will look to see if it has a file that normalizes to the same NFC name as the one that mac is asking for. If it finds exactly one such file, it will consider this a match. If it finds more than one, it will error (this is possible for case sensitivity but should be pretty rare for NFC/NFD. For example, if mac asks for "hello" but rclone has both "HELLO" and "HeLlo".)

So the result is that if rclone gives mac an NFC file but mac converts it to NFD, rclone will not get confused and will be able to figure out which file mac is talking about.

The most important part is [here](https://github.com/nielash/rclone/blob/af6c376ef102e56704a8bb6d81e53f3311474fd3/vfs/dir.go#L809-L822). And this calls `operations.ApplyTransforms` to do the actual conversion:

https://github.com/rclone/rclone/blob/91b54aafccc3aed01a5389864e8ef3902286b406/fs/operations/check.go#L381-L390

This uses the [`norm`](https://pkg.go.dev/golang.org/x/text/unicode/norm) package from the Go standard library instead of Mac's `iconv` implementation, which is known to be buggy.

**Comment by kapitainsky** [comment]
Thank you for this explanation. When I digest it I will try to break it with my testing:) And of course I hope I will fail.

**Comment by nielash** [comment]
> At last we could have FUSE free mount life on macOS:)

That's the dream! 😆 

Aside from https://github.com/rclone/rclone/issues/7503#issuecomment-1910713905 which I posted a fix for, are there other `nfsmount` issues?

**Comment by kapitainsky** [comment]
> Aside from [#7503 (comment)](https://github.com/rclone/rclone/issues/7503#issuecomment-1910713905) which I posted a fix for, are there other `nfsmount` issues?

I have been using your fix few times and it serves its purpose - writing to NFS mount is possible.

One issue I noticed was `nfsmount` mount name. Firstly it can not be controlled with `--volname` and secondly it was rather random as I remember (definitely not using remote name).

**Comment by nielash** [comment]
Ok. That sounds fairly easy, I'll try to take a look.

**Comment by kapitainsky** [comment]
> It is the "smallest patch that could work" approach as ncw suggested. So, it does not add a new `--vfs-normalize` flag -- rather, it uses the existing `--no-unicode-normalization` (and note the double-negative -- `false` means normalize.) This seemed to be enough to fix it -- @kapitainsky I wonder if you agree?

Using below test set,

```
$ rclone tree crypt:NFC_NFD_testing
/
├── NFCéééFILE.txt
├── NFCééééDIR
│   ├── NFCéééFILE.txt
│   └── NFDééééFILE.txt
├── NFDééééDIR
│   ├── NFCéééFILE.txt
│   └── NFDééééFILE.txt
├── NFDééééFILE.txt
└── TEST_DUPES
    ├── CONFLICTéééDIR
    │   ├── CONFLICTéééFILE.txt
    │   └── CONFLICTéééFILE.txt
    ├── CONFLICTéééFILE.txt
    ├── CONFLICTéééDIR
    │   ├── CONFLICTéééFILE.txt
    │   └── CONFLICTéééFILE.txt
    └── CONFLICTéééFILE.txt

5 directories, 12 files
```
I can confirm that it works exactly like described including `--vfs-block-norm-dupes` flag behaviour.

I am impressed by simplicity of this solution - it gives me confidence that it actually work as intended. 
Myself I was thinking about some unnecessarily complex `--vfs-normalize OFF/NFC/NFD ` approach.

**Comment by kapitainsky** [comment]
> I attempted to split the difference on this by adding a new flag for this (disabled by default), `--vfs-block-norm-dupes` (better name suggestions welcome). ncw is right that there will be a performance hit, so I think most non-mac users will want to leave it off. However some mac users may want it, as otherwise the "edge case" @kapitainsky mentioned will have an odd effect: both versions of the file will be visible in the mount, and both will appear to be editable, however, editing either version will actually result in only the NFD version getting edited under the hood. So `--vfs-block-norm-dupes` prevents this confusion by detecting this scenario and hiding the duplicates + logging an error, similar to what `march` would do. Thoughts on this approach?

I think it is perfectly acceptable approach. Definitely it should be optional as normalisation cases are IMO very rare - it actually takes some effort to even create them:) But they are possible so for people who might have this issue this flag is a solution.

**Comment by kapitainsky** [comment]
> Aside from [#7503 (comment)](https://github.com/rclone/rclone/issues/7503#issuecomment-1910713905) which I posted a fix for, are there other `nfsmount` issues?

There is one more problem with `nfsmount`. When you unmount - share folder is gone - but `rclone nfsmount` process is still running and has to be CTRL-C

**Comment by nielash** [comment]
Thanks, I'll take a look.

**Comment by nielash** [comment]
One other thought just occurred to me -- I wonder if we should just return [here](https://github.com/nielash/rclone/blob/af6c376ef102e56704a8bb6d81e53f3311474fd3/vfs/dir.go#L819), at least when not using `--vfs-block-norm-dupes`. In other words, as soon as we find the first match, use it and move on instead of continuing to look for a possible second match. If all we care about is the first match, it would be a lot faster.

**Comment by kapitainsky** [comment]
> One other thought just occurred to me -- I wonder if we should just return [here](https://github.com/nielash/rclone/blob/af6c376ef102e56704a8bb6d81e53f3311474fd3/vfs/dir.go#L819), at least when not using `--vfs-block-norm-dupes`. In other words, as soon as we find the first match, use it and move on instead of continuing to look for a possible second match. If all we care about is the first match, it would be a lot faster.

I think yes - it would be even safer. Given that without `--vfs-block-norm-dupes` I can be editing wrong file on my mount... This way I think we would have dupe missing - which again I think is better.

**Comment by kapitainsky** [comment]
And one thought in my head too... Could we add this logic to [rclone dedupe](https://rclone.org/commands/rclone_dedupe/)? so I could validate my remote not only for exact duplicates but also for potential ones based on case and normalisation?

**Comment by nielash** [comment]
> I think yes - it would be even safer.

I think it would actually be a little less safe... as the purpose of looking for a second match is so that it can return an error if it finds one. But the question is... is that error actually useful, and if so, is it worth the CPU tradeoff? 

> And one thought in my head too... Could we add this logic to [rclone dedupe](https://rclone.org/commands/rclone_dedupe/)? so I could validate my remote not only for exact duplicates but also for potential ones based on case (`--by-case`)and normalisation (`--by-normalisation`)?

That's an interesting idea! I bet that would be possible. One other thought I had along these lines is whether something like an `rclone iconv` command might be a useful thing. For example, to convert any NFC filenames to NFD, or vice versa.

**Comment by kapitainsky** [comment]
> I think it would actually be a little less safe... as the purpose of looking for a second match is so that it can return an error if it finds one. But the question is... is that error actually useful, and if so, is it worth the CPU tradeoff?

Error is only useful when using `--vfs-block-norm-dupes`? Isn't it?

**Comment by kapitainsky** [comment]
> That's an interesting idea! I bet that would be possible. One other thought I had along these lines is whether something like an `rclone iconv` command might be a useful thing. For example, to convert any NFC filenames to NFD, or vice versa.

BIG yes - another nice to have feature:)

**Comment by nielash** [comment]
> Error is only useful when using `--vfs-block-norm-dupes`? Isn't it?

I tend to think that the type of user that would care about this error would be using `--vfs-block-norm-dupes` anyway, and the vast majority of users will not care about it and would rather have the performance boost. It is a very unlikely error to begin with -- you'd have to have multiple equal-folding filenames in the same directory to encounter it. And even if you did, "pick the first one and move on" might still be preferable to an error, for many users.

**Comment by kapitainsky** [comment]
Any rough idea what is performance impact? Because maybe we worry about non existing problem?

**Comment by nielash** [comment]
I suppose we could run some tests and find out. It would depend a lot on how many files you have -- with a small number you probably wouldn't notice it, but with a large number it could become noticeable. I worked on a unicode normalization issue for `bisync` recently and was surprised at how much of a bottleneck all the conversions turned out to be -- I ended up reworking the code because of it.

One thing that helps in this case though is that we only find ourselves in this loop if we already failed to find an exact match. For most users, this should be pretty rare -- it basically requires the sort of scenario like macOS where the OS is actively auto-converting filenames as opposed to merely enforcing case-insensitive uniqueness. And even then, we're just talking about the small subset of files that have special characters and came from some non-mac source.

**Comment by nielash** [comment]
Come to think of it, this is another good use case for `rclone convmv`... the more files that are already in the correct format, the fewer checks you have to do each time.

**Comment by kapitainsky** [comment]
Yes this is what I do with my rclone remotes data - at least for now before I store it in the cloud I convert all to NFD.

**Comment by nielash** [comment]
> I have been using them the last few days and this is day and night compared to what it was before in terms of macOS `rclone mount` compatibility.

Very glad to hear that 🙂 

Yes, I can submit PRs. I was planning to also look at some of the other `nfsmount` issues you mentioned (`--volname` and unmounting), but as they are less critical maybe it's best to submit the most important changes first and fix the rest later. What do you think?

> `rclone nfsmount` made to release in disastrous stage - effectively useless so compared to it your changes are gold.

🤣

**Comment by kapitainsky** [comment]
> Yes, I can submit PRs. I was planning to also look at some of the other `nfsmount` issues you mentioned (`--volname` and unmounting), but as they are less critical maybe it's best to submit the most important changes first and fix the rest later. What do you think?

IMO normalisation is fully working and is ready to be includes in rclone release.

nfsmount - I do appreciate good engineering so have to say that indeed maybe better to solve known issues.

Most importantly normalisation works perfectly with macFUSE/FUSE-T so it immediately solves old issue. nfsmount is very nice addition but not critical.

**Comment by nielash** [comment]
@kapitainsky I made a proof-of-concept for a `rclone convmv` command. Very much still a WIP, but if you are interested: https://github.com/nielash/rclone/commit/1d6be937035854dba5a8f58a320fb8b3826755a0 

Examples of what it does: [Link](https://github.com/nielash/rclone/blob/1d6be937035854dba5a8f58a320fb8b3826755a0/docs/content/commands/rclone_convmv.md?plain=1#L123-L183)

**Comment by kapitainsky** [comment]
> @kapitainsky I made a proof-of-concept for a `rclone convmv` command. Very much still a WIP, but if you are interested: [nielash@1d6be93](https://github.com/nielash/rclone/commit/1d6be937035854dba5a8f58a320fb8b3826755a0)
> 
> Examples of what it does: [Link](https://github.com/nielash/rclone/blob/1d6be937035854dba5a8f58a320fb8b3826755a0/docs/content/commands/rclone_convmv.md?plain=1#L123-L183)

I have managed to compile it and run few simple tests. All worked! I think that it is very cool small utility. When needed it is purely irreplaceable. Things like this make rclone truly pro utility. Thank you very much for doing it.
