### ISSUE TITLE
webdav: nextcloud: rclone incorrectly retries long server-side chunks merge operations before they complete

### ISSUE THREAD

**Issue by devnoname120** [rclone/rclone#7109]
#### What is the problem you are having with rclone?

Uploading very large files (e.g. 20 GB) always fails because rclone keeps restarting the transfer while the server is still under the process of merging the chunks together.

#### What is your rclone version?
```
❯ rclone --version
rclone v1.63.0
- os/version: darwin 13.3.1 (64 bit)
- os/kernel: 22.4.0 (arm64)
- os/type: darwin
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.20.5
- go/linking: dynamic
- go/tags: none
```

#### Which OS you are using and how many bits?

```
❯ neofetch
                    'c.          paul@Pauls-Air
                 ,xNMM.          --------------
               .OMMMMo           OS: macOS 13.3.1 22E261 arm64
               OMMM0,            Host: MacBookAir10,1
     .;loddo:' loolloddol;.      Kernel: 22.4.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 12 hours, 32 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 331 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: yabai
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal Font: MesloLGS-NF-Regular 13
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 2991MiB / 16384MiB
       .cooc,.    .,coo:.
```

#### Which cloud storage system are you using?

WebDAV (NextCloud)

#### The command you were trying to run?

```
rclone copy verybigfile.bin nextcloud:
```

#### A log from the command with the `-vv` flag

My NextCloud instance is running out of storage so unfortunately I'm not able to provide such a log. It has been a long-standing issue though.

@ncw I remember looking into it a very long time ago.
- For long operations, the HTTP `MOVE` request for merging chunks eventually times out (but the merge is actually still in progress).
- When trying to merge again then NextCloud returns a `LOCKED` error which I [tried to ignore](https://github.com/rclone/rclone/blob/2234feb23d1f9c50e94ad1c5b2d854282748cc03/backend/webdav/chunking.go#L30-L33).
- `rclone` seems to somehow figure out that the file isn't actually there, deletes the chunks, reuploads them, and tries to merge them again.
- Rinse and repeat.

There is [no API to check whether the `MOVE` operation is still in progress or not](https://github.com/nextcloud/server/issues/28395). The only way I know of is to check if it's still in progress is to [retry the `MOVE` until we don't receive a `LOCKED` error any longer](https://github.com/rclone/rclone/pull/6133#issuecomment-1184336893).

If I recall correctly, this workaround didn't work out: rclone eventually restarted the transfer anyway. Maybe rclone has some kind of mechanism to force retry "staled" transfers even if the backend asks it to wait?

👉 Would there be a way to work around this NextCloud limitation?

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
See the issue:

https://github.com/rclone/rclone/issues/7103

**Comment by devnoname120** [comment]
@animosity22 This is unrelated, please reopen.

**Comment by animosity22** [comment]
Try the beta.

**Comment by devnoname120** [comment]
@animosity22

1) I'm literally a participant in the issue #7103 that you mentioned.
2) I even contributed a pull request to fix issue #7103. See https://github.com/rclone/rclone/pull/7108
3) I'm the author of the entire chunks merging code of that rclone remote (see https://github.com/rclone/rclone/pull/6133).

I can guarantee you that #7103 is completely unrelated to this issue.

**Comment by animosity22** [comment]
Thank you for literally telling me. Appreciate it.

**Comment by ncw** [comment]
I expect rclone is timing out. This fails the transfer which deletes the uploaded file and tries again.

You can increase the timeout with `--timeout` - that might help.

Need to see a log to be certain though.

**Comment by devnoname120** [comment]
@ncw Will try in the coming days thanks.

**Comment by animosity22** [comment]
any updates @devnoname120 ?

**Comment by devnoname120** [comment]
@animosity22 Unfortunately my NextCloud instance is almost full and I don't have enough space to transfer large files to trigger the behavior (for now).

**Comment by Pogogo007** [comment]
i have tried multiple times with different timeout durations notably --timeout 60m0s and 100m5s but the issue seems to still show up

**Comment by devnoname120** [comment]
@Pogogo007 Thanks for testing. Could you also provide a log as @ncw requested? This will make tracking down the issue easier.

**Comment by Pogogo007** [comment]
[bug.log](https://github.com/rclone/rclone/files/12734558/bug.log)
Ignore the CloudFlare ratelimites. In the middle of the file is the issue that it spits out.

**Comment by ncw** [comment]
Ok, give this a go

[v1.65.0-beta.7393.5be640f6e.fix-7109-nextcloud](https://beta.rclone.org/branch/fix-7109-nextcloud/v1.65.0-beta.7393.5be640f6e.fix-7109-nextcloud/) on branch [fix-7109-nextcloud](https://github.com/rclone/rclone/tree/fix-7109-nextcloud) (uploaded in 15-30 mins)

It will retry the 423 errors after 1,2,4,8... seconds up to `--low-level-retries` times.

It will write a NOTICE log about it so you should see what is going on.

Let me know if that helps!

**Comment by jaimedelano** [comment]
Hi, Nick.
First of all, thanks for the amazing Rclone.
I think a loop is better than _--low-level-retries_.
Additionally, I suggest adding a new option/flag **nextcloud_merge_timeout** / **--nextcloud-merge-timeout**
Algorithm:
```
while elapsed_time < nextcloud_merge_timeout :
time = randint(10,30)
sleep(time) // Sleep random time (10 ~ 30 seconds)
check_if ( destination_file_exists && filesize_is_correct ) then_break
endwhile;
```

**Comment by Pogogo007** [comment]
Unfortunately it does not seem to help as after the timeout it just spews the same error and proceeds to retry
Keep in mind currently im am attempting to upload a 50GB file as such im assuming the merging process can take quite a while

**Comment by ncw** [comment]
@Pogogo007 you may need to increase `--low-level-retries` if it will take longer than 1024 seconds to merge the file.

Can you paste some logs?

**Comment by ncw** [comment]
@Pogogo007 do you have some logs you can share?

**Comment by Strongman8481** [comment]
> @Pogogo007 do you have some logs you can share?

I am running into this issue as it turns out. I opened a help request that I believe fits this exactly.  I have 2 files in the cache that are MD5 summed as being the same on the server/cache, but they will not clear from the cache because of this error.  I have attached logs using the 7109 beta binary.  [Help request I opened](https://forum.rclone.org/t/vfs-cache-not-clearing-for-webdav-mount/42548). Please let me know what I should try.  

I run rclone as a service, here is the config:

ExecStart=/usr/bin/rclone mount \
        --allow-non-empty \
        --config /home/meh/.config/rclone/rclone.conf \
        --log-level DEBUG --log-file "/home/rclone.log" \
        --allow-other \
[rclone7109.log](https://github.com/rclone/rclone/files/13192039/rclone7109.log)

        --cache-db-purge \
        --vfs-cache-mode full \
        --vfs-read-chunk-size 16M \
        nextcloud:/media /mnt/media/

`
2023/10/27 12:07:54 NOTICE: webdav root 'media': Sleeping for 1s to wait for chunks to be merged after 423 error
2023/10/27 12:07:55 DEBUG : pacer: low level retry 2/10 (error merging the uploaded chunks failed with 423 LOCKED. This usually happens when the chunks merging is still in progress on NextCloud, but it may also indicate a failed transfer: "media/download//complete//file2.1080p.TrueHD.Atmos.7.1.AVC./file2.1080p.TrueHD.Atmos.7.1.AVC..mkv" is locked, existing lock on file: exclusive: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked)
2023/10/27 12:07:55 DEBUG : pacer: Rate limited, increasing sleep to 40ms
2023/10/27 12:07:56 NOTICE: webdav root 'media': Sleeping for 2s to wait for chunks to be merged after 423 error
2023/10/27 12:07:58 DEBUG : pacer: low level retry 3/10 (error merging the uploaded chunks failed with 423 LOCKED. This usually happens when the chunks merging is still in progress on NextCloud, but it may also indicate a failed transfer: "media/download//complete//file2.1080p.TrueHD.Atmos.7.1.AVC./file2.1080p.TrueHD.Atmos.7.1.AVC..mkv" is locked, existing lock on file: exclusive: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked)
2023/10/27 12:07:58 DEBUG : pacer: Rate limited, increasing sleep to 80ms
2023/10/27 12:07:58 NOTICE: webdav root 'media': Sleeping for 4s to wait for chunks to be merged after 423 error
2023/10/27 12:07:59 DEBUG : vfs cache RemoveNotInUse (maxAge=3600000000000, emptyOnly=false): item download//complete//file2.1080p.TrueHD.Atmos.7.1.AVC./file2.1080p.TrueHD.Atmos.7.1.AVC..mkv not removed, freed 0 bytes
2023/10/27 12:07:59 DEBUG : vfs cache RemoveNotInUse (maxAge=3600000000000, emptyOnly=false): item download//complete//file1.1080p.TrueHD.Atmos.7.1.AVC./file1.1080p.TrueHD.Atmos.7.1.AVC..mkv not removed, freed 0 bytes
2023/10/27 12:07:59 INFO  : vfs cache: cleaned: objects 2 (was 2) in use 2, to upload 0, uploading 2, total size 67.422Gi (was 67.422Gi)
2023/10/27 12:08:01 DEBUG : /: Lookup: name="download"
2023/10/27 12:08:01 DEBUG : /: >Lookup: node=download/, err=<nil>
2023/10/27 12:08:01 DEBUG : download/: Attr: 
2023/10/27 12:08:01 DEBUG : download/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/10/27 12:08:01 DEBUG : download/: Lookup: name=""
2023/10/27 12:08:01 DEBUG : download/: >Lookup: node=download//, err=<nil>
2023/10/27 12:08:01 DEBUG : download//: Attr: 
2023/10/27 12:08:01 DEBUG : download//: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/10/27 12:08:01 DEBUG : download//: Lookup: name="complete"
2023/10/27 12:08:01 DEBUG : download//: >Lookup: node=download//complete/, err=<nil>
2023/10/27 12:08:01 DEBUG : download//complete/: Attr: 
2023/10/27 12:08:01 DEBUG : download//complete/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2023/10/27 12:08:01 DEBUG : : Statfs: 
2023/10/27 12:08:01 DEBUG : : >Statfs: stat={Blocks:277345007509 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2023/10/27 12:08:02 DEBUG : pacer: low level retry 4/10 (error merging the uploaded chunks failed with 423 LOCKED. This usually happens when the chunks merging is still in progress on NextCloud, but it may also indicate a failed transfer: "media/download//complete//file2.1080p.TrueHD.Atmos.7.1.AVC./file2.1080p.TrueHD.Atmos.7.1.AVC..mkv" is locked, existing lock on file: exclusive: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked)
2023/10/27 12:08:02 DEBUG : pacer: Rate limited, increasing sleep to 160ms
2023/10/27 12:08:03 NOTICE: webdav root 'media': Sleeping for 8s to wait for chunks to be merged after 423 error
2023/10/27 12:08:11 DEBUG : pacer: low level retry 5/10 (error merging the uploaded chunks failed with 423 LOCKED. This usually happens when the chunks merging is still in progress on NextCloud, but it may also indicate a failed transfer: "media/download//complete//file2.1080p.TrueHD.Atmos.7.1.AVC./file2.1080p.TrueHD.Atmos.7.1.AVC..mkv" is locked, existing lock on file: exclusive: OCA\DAV\Connector\Sabre\Exception\FileLocked: 423 Locked)
2023/10/27 12:08:11 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2023/10/27 12:08:11 NOTICE: webdav root 'media': Sleeping for 16s to wait for chunks to be merged after 423 error
`

**Comment by Strongman8481** [comment]
I wanted to report back that I continued to use the above bin file and a 51 GB file successfully uploaded. The week+ files that were sitting in the cache also cleared out on their own. I will plan to reload the stable binary and do another test just to prove that this fixed my issue. Happy to provide any further logs.

**Comment by ncw** [comment]
@Strongman8481 wrote
> I am running into this issue as it turns out. I opened a help request that I believe fits this exactly. I have 2 files in the cache that are MD5 summed as being the same on the server/cache, but they will not clear from the cache because of this error. I have attached logs using the 7109 beta binary. [Help request I opened](https://forum.rclone.org/t/vfs-cache-not-clearing-for-webdav-mount/42548). Please let me know what I should try.
> 
> [rclone7109.log](https://github.com/rclone/rclone/files/13192039/rclone7109.log)

Thanks for your logs - very useful.

It looks like the upload and merge worked OK but then nextcloud returned a file not found error which I don't understand.

Maybe the merge did complete properly and file not found is actually indicating success. This would fit in with what you are saying about the files MD5 sums being OK.

At the moment we retry the 404 errors - but you were just out of retries when that happened.

Can you try this

[v1.65.0-beta.7463.503dc9473.fix-7109-nextcloud](https://beta.rclone.org/branch/fix-7109-nextcloud/v1.65.0-beta.7463.503dc9473.fix-7109-nextcloud/) on branch [fix-7109-nextcloud](https://github.com/rclone/rclone/tree/fix-7109-nextcloud) (uploaded in 15-30 mins)

It

- increases base timeout to 5s so you should definitely have retries left
- it increases timeout for 404 errors to 10s

Let me know if you can upload big files - I'd like to see a log if possible.

Thank you!

**Comment by Strongman8481** [comment]
I put out another big file.  Something is going on. In two instances it seems the large file is uploaded, but still not getting cleared from the cache. This could be something happening in nextcloud.  The resulting log file was multiple gigs. Here is a trimmed down version.  Let me know if I trimmed too much or you have access downloading the file.  

[rclone log](https://drive.proton.me/urls/V025J2WMZC#OiGjuGqz14u8)

**Comment by ncw** [comment]
It appears from your logs that if we get a 404 after 423 errors then the upload is successfully.

This code implements that idea - can you give it a try?

[v1.65.0-beta.7469.8ffe3e462.fix-7109-nextcloud](https://beta.rclone.org/branch/fix-7109-nextcloud/v1.65.0-beta.7469.8ffe3e462.fix-7109-nextcloud/) on branch [fix-7109-nextcloud](https://github.com/rclone/rclone/tree/fix-7109-nextcloud) (uploaded in 15-30 mins)

**Comment by Strongman8481** [comment]
> It appears from your logs that if we get a 404 after 423 errors then the upload is successfully.
> 
> This code implements that idea - can you give it a try?
> 
> [v1.65.0-beta.7469.8ffe3e462.fix-7109-nextcloud](https://beta.rclone.org/branch/fix-7109-nextcloud/v1.65.0-beta.7469.8ffe3e462.fix-7109-nextcloud/) on branch [fix-7109-nextcloud](https://github.com/rclone/rclone/tree/fix-7109-nextcloud) (uploaded in 15-30 mins)

Here is the latest log. I added two files yesterday. A 53G file and a 24G file. Both seem to have uploaded successfully.  They are still hanging out in the cache but they are not uploading.  I don't fully understand why but it looks like progress!  Let me know if I trimmed too much from the debug log.

[debugTest2.log](https://github.com/rclone/rclone/files/13227511/debugTest2.log)

**Comment by johnsanc314** [comment]
Any idea when this fix is going to be merged into the official builds?
https://beta.rclone.org/branch/fix-7109-nextcloud/v1.65.0-beta.7469.8ffe3e462.fix-7109-nextcloud/

This solved the issue a few people were having with my Nextcloud instance trying to upload 25GB+ files.

**Comment by v3DJG6GL** [comment]
Hey @ncw
Do you have plans to include the fix in stable? It is almost impossible for me to use my WebDAV connected Nextcloud instance when dealing with large files, e.g. video files.

BTW: Thank you for this amazing tool!

**Comment by noigeaR** [comment]
Can we please get this fix merged into official builds?
Uploading large files is still broken in v1.68.0.
The [fix-7109-nextcloud](https://github.com/rclone/rclone/tree/fix-7109-nextcloud) branch reliably fixes the problem, but it is already over 800 commits behind master...

**Comment by ncw** [comment]
Thanks for testing. Sorry this PR slipped off my radar.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.69

**Comment by JulienFS** [comment]
For the record : 404 as success is dangerous. I'll try to fix this on nextcloud itself as I'm planning to add some reliable hashing mechanism. Note that since there's no reliable hash mechanism on nextcloud status code is the only thing that can guarantee a client that the file was properly uploaded. This kind of behavior is one of the many reasons why a file might silently be corrupted during the upload. For this reason I would strongly advise to enable this new behavior only if some sort of "I know what I'm doing" parameter is given.

**Comment by JulienFS** [comment]
I checked the logs on the nextcloud side. I have a lot of `- Part XX: Error executing "UploadPart"` errors when it happens. XX is the number of the part and interestingly its mostly multiples of 5.
The error involved is a `408 Request Timeout` on the S3 PUT method. I guess the multipart upload for S3 backend is pushing a bit too hard for the actual backend.

I think that on the NC side there's something related to file locking preventing the "normal" failure of the upload, which is fortunate since it prevents the abortion of the upload altogether.

The real fix would be to implement retries on 408 on the NC's S3 backend handler or some simultaneous part upload limiting configuration.

**Comment by JulienFS** [comment]
@ncw This needs to be reverted. The fix has to happen on Nextcloud. 423 + 404 is likely to happen if the multipart upload fails on NC and the abortMultipartUpload cleanup method is called. It gives too much room for a silently missing file. Please at least don't make if the default behavior.

**Comment by ncw** [comment]
@JulienFS I agree that is a horrible work around! However it does seem to fix things for users.

The workaround only kicks in if

1. We had a 423 error
2. We subsequently get a 404 error

How likely is it that this happens when it shouldn't? Have you actually seen it happen?

If the workaround does kick when it shouldn't then rclone will check the uploaded file to see it is the correct length and if not, upload it again.
