### ISSUE TITLE
S3 sync high memory usage (leads to OOM)

### ISSUE THREAD

**Issue by ahmedjafri** [rclone/rclone#7141]
#### What is the problem you are having with rclone?
rclone runs for about 20-40 minutes and then memory usage starts to climb up to 11-13 GB until it's killed by the kernel for taking too much memory. The machine this is running on has 16GB of memory. 

#### What is your rclone version (output from `rclone version`)
1.63.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)
S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
$ rclone --config ./rclone.conf -v --stats 5s --transfers 3 --dry-run --filter-from ./rclone-exclude.conf --rc --s3-upload-concurrency 1 --max-backlog=1000 sync /<redactedPath> remote:<redacted>/
```

rclone.conf
```
[remote]
access_key_id = <redacted>
secret_access_key = <redacted>
max_upload_parts = -3
endpoint =
region = us-east-2
type = s3
folder = /
bucket = <redacted>
storage_class = DEEP_ARCHIVE
fast_list = false
server_side_encryption =
chunk_size = 100M
```

rclone-exclude.conf 
```
- .zfs
- .zfs/**
- *.DS_Store
- /iocage/**
- /jails/**
- **/.recycle/**
- /ix-applications/**
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2023/07/15 20:23:32 NOTICE: Serving remote control on http://127.0.0.1:5572/
2023/07/15 20:23:32 NOTICE: s3: s3 provider "" not known - please set correctly
...
Transferred:        3.317 GiB / 263.962 GiB, 1%, 8.313 MiB/s, ETA 8h55m8s
Checks:              6365 / 6365, 100%
Transferred:           71 / 1082, 7%
Elapsed time:       2m0.3s
```

memory dump
```
      flat  flat%   sum%        cum   cum%
      11GB 99.92% 99.92%       11GB 99.92%  github.com/rclone/rclone/lib/pool.New.func1
         0     0% 99.92%       11GB 99.89%  github.com/rclone/rclone/backend/s3.(*Fs).Put
         0     0% 99.92%       11GB 99.89%  github.com/rclone/rclone/backend/s3.(*Object).Update
         0     0% 99.92%       11GB 99.89%  github.com/rclone/rclone/backend/s3.(*Object).uploadMultipart
         0     0% 99.92%       11GB 99.89%  github.com/rclone/rclone/fs/operations.Copy
         0     0% 99.92%       11GB 99.89%  github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove
         0     0% 99.92%       11GB 99.92%  github.com/rclone/rclone/lib/pool.(*Pool).Get
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ahmedjafri** [comment]
It looks like setting `max_upload_parts = 50000`  seems to have mitigated the problem. Running for an hour at `~ 300MB`

**Comment by ncw** [comment]
How many and how big are the files you are uploading?

I suspect you are uploading multiple files bigger than 10,000 * 5M = 50 GB

Since these files don't fit in the normal chunk size, rclone will be increasing the chunk size. However this means that the file gets its own memory pool to fit the new sized chunks. Potentially if you have a files which vary in size you'll get multiple memory pools leading to memory exhaustion.

This would be easy to confirm with a debug log with `-vv`. If you have one can you attach one? Or if you want to sent it to me confidentially then email it to nick@craig-wood.com with a link to this github issue in it.

There was an issue and/or a forum thread about this very recently but I can't find it at the moment.

> It looks like setting `max_upload_parts = 50000` seems to have mitigated the problem. Running for an hour at `~ 300MB`

You must be using a non AWS system as [10,000 is the maximum for AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html).

This fixes the problems provided your files are less than 50,000 * 5MB = 250 GB in size by making sure that all the buffers in use are the same size (5MB).

Assuming this is the problem, other workarounds are

Set `--s3-chunk-size 25M` - provided all your files are less than 10,000 * 25M = 250GB all files will use the same 5MB buffer.

You can also use these flags to help rclone return memory to the OS

      --s3-memory-pool-flush-time Duration   How often internal memory buffer pools will be flushed (default 1m0s)
      --s3-memory-pool-use-mmap              Whether to use mmap buffers in internal memory pool

You'd use `--s3-memory-pool-use-mmap` and `--s3-memory-pool-flush-time 1s`

However all of these are workarounds to the fact rclone is not doing a good job managing memory here!

Perhaps rclone should be using a scatter/gather memory allocator to synthetically make the bigger buffers from the smaller once. This would be the most efficient solution.

Another solution would be for rclone to only allocate buffer sizes in factors of 2 from the default. So allocate pools at 5MB, 10MB, 20MB, 40MB rather than lots of intermediate sizes which means rclone can't share the memory.

Or maybe rclone's memory allocator should be re-worked so that it can keep buffers of more than one size.

If you are working on behalf of a company you might be interested in taking out a [support contract](https://rclone.com/support) then I could do this work as part of it and it helps keep the rclone project sustainable.

**Comment by ncw** [comment]
This should fix the problem properly

[v1.64.0-beta.7247.5bd9e6527.multithread](https://beta.rclone.org/branch/multithread/v1.64.0-beta.7247.5bd9e6527.multithread/) on branch [multithread](https://github.com/rclone/rclone/tree/multithread) (uploaded in 15-30 mins)
