### ISSUE TITLE
webdav: nextcloud: new chunking code causing a panic

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#7168]
It was reported on the forum that rclone v1.63.1 is panicing in the Go http standard library

https://forum.rclone.org/t/panic-after-updating-to-v1-63-1/40226

With a bit of tracing the Go stdlib code I managed to work out that it is caused by the `nil, nil` return of this code

https://github.com/rclone/rclone/blob/70cbcef62409629fb970c730c8f28de672e8851e/backend/webdav/chunking.go#L122-L126

`GetBody` must not return a `nil` body with a `nil` error.

@devnoname120 do you have any ideas about this? I think this is probably a type which should say `err != nil` not `err == nil` but that means we've been taking the wrong branch all along so a bit of testing may be needed.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by devnoname120** [comment]
@ncw Sorry for the issue and thanks for the ping, I'll try to look into it this week.

From rough memory I remember that I specifically added and tested this retry mechanism because it was preventing me from uploading large files (50 GB) with a large number of chunks (~ 1000).

There was almost always at least a chunk that failed to upload and would trigger the restart of the entire transfer. So it definitely worked *at some point* because I personally needed this to work. I may have pushed the wrong commit or something at that time however, so I will investigate...

**Comment by ncw** [comment]
I'm pretty sure changing `err == nil` to `err != nil` will fix it but great if you can confirm.

**Comment by devnoname120** [comment]
@ncw Your suggestion looks good to me. It indeed looks like a mistake — maybe I botched up at some point when refactoring my pull request?

I opened a new pull request, it also fixes an additional segmentation violation: https://github.com/rclone/rclone/pull/7195

**Comment by devnoname120** [comment]
@ncw I'm not entirely sure how your release schedule works but do you plan to publish a new release in the near future? Imho those fixes are significant.

**Comment by ncw** [comment]
@devnoname120 check out the milestone :-) In about a week is the plan!

**Comment by cobordism** [comment]
I was about to report this bug too :)
glad to hear it is fixed in next update.
