### ISSUE TITLE
bisync: recover from exit without `--resync`

### ISSUE THREAD

**Issue by crocinsocks** [rclone/rclone#7470]
It would be great if bisync could recover from an exit (SIGINT, SIGTERM, SIGKILL) without the need of a `--resync`.

e.g. powercut, Ctrl+C, shutdown

This would save the extra work to get it to play nice with everyday usage. Currently, have to run a script to wait for sync(s) to finish then shutdown/restart/etc. In some cases there is nothing that can be done to prevent this such as as system crash or power cut resulting in `--resync` being required. Or sometimes you just want a quick restart due to a kernel/application update or other issue and instead you have to wait or accept the consequences. 

Thanks

**Comment by nielash** [comment]
Definitely agree this could and should be improved!

(For others reading this: [here's our previous discussion](https://github.com/rclone/rclone/issues/7332#issuecomment-1732881448) about it, with some good background info about why this is a particularly tough challenge for bisync.)

Some possible solution approaches include:

- "autosave" -- save progress state every X seconds (or after every X transfers) throughout a run, so in the event of a crash, the next run can resume from the last autosave. 
Pros: probably the most accurate method
Cons: may be complicated to build, may slow down the sync with lots of writes to disk, may not be practical with a non-local `--workdir` if that is eventually supported

- "replay queues" -- save the queue list at the beginning of each sync, and in the event of an interruption, the next run attempts to finish the prior run by "replaying" it, before starting the new run.
Pros: easier and less expensive than "autosave"
Cons: potentially not robust to changes that occurred after the interrupted run

- "graceful shutdown" -- upon receiving Ctrl+C, gracefully wrap up what we're doing at the earliest opportunity, cleaning up after ourselves to make things easy for next time.
Pros: relatively easy and clean
Cons: only works when we have some warning (won't help with powercut, sudden crash, etc.)

- "diff from last trusted listing" -- similar idea to https://github.com/rclone/rclone/pull/7410/commits/ef4b47a9824754824a05491c3d4c7a2ef97253d4, but revert the whole listing instead of individual files, and re-diff.
Pros: the easiest and perhaps most elegant option
Cons: there's [one particular edge case](https://github.com/rclone/rclone/issues/7332#:~:text=the%20one%20scenario,and%20move%20on.%22) it wouldn't handle as well as the others (not sure how important that is)

One question I have for you is: how important is it to handle the "crash" scenarios in addition to the ones where we have some warning? i.e. would a "graceful shutdown" option go far enough for you?

Another use case to keep in mind here is using a laptop while traveling, and losing internet or needing to close the laptop mid-sync...

**Comment by crocinsocks** [comment]
Great points personally I believe this would need to be a combination of 3 & 4 e.g. "graceful shutdown" & "diff from last trusted listing"

Of course, graceful shutdown would need to cover all SIG events not just ctrl+c. SIGKILL a forced and immediate shutdown  would then resort to  "diff from last trusted listing" and handle the edge case of conflicts as in #7471.

With graceful shutdown perhaps you could even resume file upload from where it was left off when files have not changed on either side (particularly useful for larger uploads).

**Comment by nielash** [comment]
@crocinsocks I did some work on this and have a working proof-of-concept. Would you like to try it and give feedback?

**Comment by crocinsocks** [comment]
Yes, of course can give feedback just let me know which branch to build.

I think that it should recover from graceful shutdown by default (e.g. no flag) and if ungraceful that perhaps it has a flag with warning/documentation of any potential edge cases as you've listed, if enabled. I also agree should probably be different to resilient as about recovering not retrying

And yes lockfiles will come into this so perhaps we should at minimum start a thread on lockfiles to hash that out there?

> Many (most?) rclone backends don't support partial uploads, so it's probably not possible, but check out https://github.com/rclone/rclone/issues/87... if it is someday supported in sync, it will be supported in bisync too.

Ahh okay perfect !

**Comment by nielash** [comment]
@crocinsocks  Great, check this out: https://github.com/nielash/rclone/tree/bisync-recover-WIP

`Ctrl+C` will trigger the graceful shutdown sequence which will use best efforts to exit cleanly before the timer runs out.

A second `Ctrl+C` will trigger an immediate un-graceful exit, which `--resilient` will recover from cleanly using the "diff from last trusted listing" method described above. (I stuck with `--resilient` for now but it's easy to change the flag later.)

I also implemented [`--max-lock`](https://github.com/nielash/rclone/commit/bd850ad26d463f4c450acb38bfcfe2da289c2baa) with a pretty robust auto-renewal heartbeat mechanism.

I recommend trying it with something like:
```
rclone bisync path1 path2 --resilient --max-lock 2m -vP
```
so you can see what it's doing more clearly.

It is not yet production-ready, so make sure you have a backup or use test data in case there are bugs. (And if you find any, please let me know!)

**Comment by crocinsocks** [comment]
Awesome! I'm going to have limited time now until the weekend and will need to put up a test vm unless I wait as need my active syncs to function (though I know these changes are unlikely to cause any issues with this).

Let me know if that repo changes before then otherwise will build from there with any new changes you might make and let you know how I get on. 

Thanks :)
