### ISSUE TITLE
Integration test breakage

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#7591]
It looks like the mega merge has broken some integration tests :-(

I'm pretty sure that these are a consequence of your changes @nielash - can you take a look? 

| suite | test |
| ---- | ---- |
| fs/sync |	TestFixCase |
| fs/operations |	TestCaseInsensitiveMoveFileDryRun |
| fs/operations |	TestApplyTransforms |

To run the tests for a suite do this

```
cd fs/sync
go test -v -run TestFixCase -remote TestWhicheverFails:
```

To see which remotes to try see the integration test results here: https://pub.rclone.org/integration-tests/current/ (these are generated daily). I would test and fix one remote and hope that the fix works for the others!

These ones were broken before the merge but need fixing too - I @ncw - will do these.

| suite | test |
| ---- | ---- |
| backend |	TestIntegration/FsMkdir/FsPutFiles/FsIsFile/FsRoot |

The other breakages are known about.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
Yep, looking at it now.

**Comment by nielash** [comment]
Ok I think I figured it out. Branch with fixes: https://github.com/nielash/rclone/commits/fix-int-tests/

Three different issues, involving different remotes. (Btw, all 3 tests are new ones I added -- not regressions.)

### TestFixCase

Proposed fix: https://github.com/nielash/rclone/commit/a369fcb9059c7bd5e672f8a7c9d9d28b4bf7c3aa
I think this actually revealed a pre-existing bug in rclone that was not previously covered by the tests. In a nutshell, `operations.moveOrCopyFile` had a special section to handle changing case of a file on a case insensitive remote, but `operations.Move` did not. The issue only affects backends that are incapable of renaming a file in-place to an equal-folding name, which is not all case-insensitive remotes. This is why I did not catch it when testing on macOS (which is case-insensitive but can rename in place.)

Note also that while testing, Dropbox sometimes complained about `too_many_write_operations` unless I slept for a second or two between moves (https://github.com/nielash/rclone/commit/a85313cee4d22a097768c4a7e0de380abd3c9938). This probably isn't the right fix, and may not actually be needed (is it just a limitation of the free account I'm using? does the real integration test account have higher API limits?)

### TestCaseInsensitiveMoveFileDryRun
https://github.com/nielash/rclone/commit/a2dccf8ba35f2c9ccc31d67cbc531dd79f69f3b6

It appears that `ci.DryRun = true` affects the behavior of `r.WriteObject` on `chunker` only, and no other remotes. This change puts a quick bandaid on it by setting it later on in the test, but perhaps the underlying issue warrants a closer look at some point... is `chunker` checking `ci.DryRun` itself in a way that no other remote does? If so, should it? (Does this break encapsulation?)

### TestApplyTransforms

I think this one is actually an issue with the 3 failing backends (Jottacloud, Koofr, and Owncloud) not the test or code. I suspect the issue is that these 3 are normalizing to NFC on the server side, so they are actually incapable of supporting `NoUnicodeNormalization` (i.e. if you give it NFD, it will convert it to NFC anyway). A quick search seems to confirm this (for example, see Owncloud issue 6338.) So, not sure what the right fix is here -- perhaps we should just skip this test for these 3 backends, by name?

CI is passing for my branch with the fixes: https://github.com/nielash/rclone/actions/runs/7632382555

**Comment by ncw** [comment]
> Ok I think I figured it out. Branch with fixes: https://github.com/nielash/rclone/commits/fix-int-tests/
> 
> Three different issues, involving different remotes. (Btw, all 3 tests are new ones I added -- not regressions.)

Great

> ### TestFixCase
> Proposed fix: [nielash@a369fcb](https://github.com/nielash/rclone/commit/a369fcb9059c7bd5e672f8a7c9d9d28b4bf7c3aa) I think this actually revealed a pre-existing bug in rclone that was not previously covered by the tests. In a nutshell, `operations.moveOrCopyFile` had a special section to handle changing case of a file on a case insensitive remote, but `operations.Move` did not. The issue only affects backends that are incapable of renaming a file in-place to an equal-folding name, which is not all case-insensitive remotes. This is why I did not catch it when testing on macOS (which is case-insensitive but can rename in place.)

Yes I think you are right. Good fix :-) I have merged that.

> Note also that while testing, Dropbox sometimes complained about `too_many_write_operations` unless I slept for a second or two between moves ([nielash@a85313c](https://github.com/nielash/rclone/commit/a85313cee4d22a097768c4a7e0de380abd3c9938)). This probably isn't the right fix, and may not actually be needed (is it just a limitation of the free account I'm using? does the real integration test account have higher API limits?)

I haven't merged that patch. The pacer should be retrying these and backing off I think - that is the best place to fix the problem I think. Dropbox is stingy with there iops and a lot of rclone users run with `--tpslimit 12` which seems to be the right number for uploading lots of files - not sure about moves.

> ### TestCaseInsensitiveMoveFileDryRun
> [nielash@a2dccf8](https://github.com/nielash/rclone/commit/a2dccf8ba35f2c9ccc31d67cbc531dd79f69f3b6)
> 
> It appears that `ci.DryRun = true` affects the behavior of `r.WriteObject` on `chunker` only, and no other remotes. This change puts a quick bandaid on it by setting it later on in the test, but perhaps the underlying issue warrants a closer look at some point... is `chunker` checking `ci.DryRun` itself in a way that no other remote does? If so, should it? (Does this break encapsulation?)

OK, weird, but good enough for now! Merged.

> ### TestApplyTransforms
> I think this one is actually an issue with the 3 failing backends (Jottacloud, Koofr, and Owncloud) not the test or code. I suspect the issue is that these 3 are normalizing to NFC on the server side, so they are actually incapable of supporting `NoUnicodeNormalization` (i.e. if you give it NFD, it will convert it to NFC anyway). A quick search seems to confirm this (for example, see Owncloud issue 6338.) So, not sure what the right fix is here -- perhaps we should just skip this test for these 3 backends, by name?

I prefer not to have backends named in the tests.

This can be done in two ways
1. one is add an exception to [the integration test config](https://github.com/rclone/rclone/blob/master/fstest/test_all/config.yaml) - the test will still fail but the integration tests will pass as this is an allowed failure.
2. Add a Feature flag to the backend so we know which backends can't support `NoUnicodeNormalization`.

I don't think the Feature flag is useful except in the tests, so I'd probably go with 1. What do you think?

> CI is passing for my branch with the fixes: https://github.com/nielash/rclone/actions/runs/7632382555

Thanks for fixing those @nielash . I pulled those locally gave them a test and I've merged them now and we can check [the integration tests](https://pub.rclone.org/integration-tests/current/) tomorrow to see how we did!

**Comment by nielash** [comment]
> I don't think the Feature flag is useful except in the tests, so I'd probably go with 1. What do you think?

I agree. I also have one other idea, inspired by [this test](https://github.com/rclone/rclone/blob/master/vfs/vfs_case_test.go#L49-L64) which I happened to be looking at yesterday. The test ultimately tests case sensitivity but first tests whether the test can even be performed, and skips if not. We could potentially do the same here, without needing the backend to self-report its features (which could eventually change).

On the other hand, it's sort of a self-fulfilling prophecy... and if a backend were to change its encoding some day, maybe that's a change we'd want to know about?

**Comment by nielash** [comment]
> We could potentially do the same here, without needing the backend to self-report its features

Here's an example of how this could be done here: https://github.com/nielash/rclone/commit/da487ba695d85af4751f799702f9b8e4fcf50bdc

**Comment by nielash** [comment]
@ncw I see that `TestFixCase` is now failing in a different way, and I think I see why -- the `dirCache` is not getting properly flushed after the first move. This fixes it for me on OneDrive: https://github.com/rclone/rclone/commit/365f5394c674506710266a9a084541d5876fcf27 (although I wonder if it would be more properly addressed in `dircache`... is this expected behavior?)

I think this should fix it for most of the others too, as they are failing in the same way and also use `dircache`. Possible exceptions are `Linkbox` and `jottacloud`, which I think may be failing due to [this](https://rclone.org/jottacloud/#troubleshooting):

> Jottacloud exhibits some inconsistent behaviours regarding deleted files and folders which may cause Copy, Move and DirMove operations to previously deleted paths to fail. Emptying the trash should help in such cases.

Looking at the others now.

**Comment by ncw** [comment]
> > We could potentially do the same here, without needing the backend to self-report its features
> 
> Here's an example of how this could be done here: [nielash@da487ba](https://github.com/nielash/rclone/commit/da487ba695d85af4751f799702f9b8e4fcf50bdc)

I think that looks fine :-) Do you want to PR it? Or I can cherry-pick it to master if you want.

> @ncw I see that `TestFixCase` is now failing in a different way, and I think I see why -- the `dirCache` is not getting properly flushed after the first move. This fixes it for me on OneDrive: [365f539](https://github.com/rclone/rclone/commit/365f5394c674506710266a9a084541d5876fcf27) (although I wonder if it would be more properly addressed in `dircache`... is this expected behavior?)

I don't understand why that fix changes the directory cache? If we are making a new backend it should have its own directory cache. /insert puzzled face emoji

Comments on that bit of code:
- `fs.NewFs` is expensive - some backends do multiple HTTP calls when you make them - can we avoid it?
- The `filepath.Join` look wrong - rclone paths are always unix paths so this should be `path.Join` or possibly even `fspath.Join`

What change would you propose in the directory cache code to fix it?

> I think this should fix it for most of the others too, as they are failing in the same way and also use `dircache`. Possible exceptions are `Linkbox` and `jottacloud`, which I think may be failing due to [this](https://rclone.org/jottacloud/#troubleshooting):
> 
> > Jottacloud exhibits some inconsistent behaviours regarding deleted files and folders which may cause Copy, Move and DirMove operations to previously deleted paths to fail. Emptying the trash should help in such cases.
> 
> Looking at the others now.

:+1:

**Comment by nielash** [comment]
> I don't understand why that fix changes the directory cache?

The `DirMove` method calls `f.dirCache.DirMove` to set up the move:

https://github.com/rclone/rclone/blob/2abeda5961615c304348c4886a1d42f4ae30c876/backend/onedrive/onedrive.go#L1717

and then flushes the cache after the move:

https://github.com/rclone/rclone/blob/2abeda5961615c304348c4886a1d42f4ae30c876/backend/onedrive/onedrive.go#L1762

We do two moves [here](https://github.com/rclone/rclone/blob/365f5394c674506710266a9a084541d5876fcf27/fs/sync/sync.go#L1161-L1167) (to temp name, then real name). The first move succeeds. For the second move, `f.dirCache.DirMove` returns `fs.ErrorDirExists` instead of `nil` because it thinks the old dir is still there. The reason it thinks that is because `newDirFs` was created before the move that flushed the cache, and `newDirFs` wasn't involved in that first move, so its cache wasn't flushed. So when we use it for the second move, it still has the old cache. But if we create it after the first move, then it inherits the correct already-flushed cache. 

It's possible I'm misunderstanding something, but that really seems to be what's happening as far as I can tell!

> * `fs.NewFs` is expensive - some backends do multiple HTTP calls when you make them - can we avoid it?

Possibly -- the issue is that `sync.MoveDir` doesn't take a `remote` string, it expects the root. But maybe I can find a different function to use. 

Would `cache.Get` be a better choice?

> * The `filepath.Join` look wrong - rclone paths are always unix paths so this should be `path.Join` or possibly even `fspath.Join`

That's actually what I had originally, but then it [errored on windows](https://github.com/rclone/rclone/pull/7356#issuecomment-1758700673) because of the `\`.

> What change would you propose in the directory cache code to fix it?

I'm not quite sure yet. This may just be expected behavior, but I think the thing that is surprising to me is that the caller would need to be concerned with tracking which Fs's have been flushed and when... I'd have expected the backend to manage that independently, so that the outcome doesn't change depending on where in your code you call `NewFs`. I guess I assumed I had a pointer to some shared cache, instead of a copy.

**Comment by nielash** [comment]
### TestApplyTransforms

Yes, I think we should go ahead with https://github.com/nielash/rclone/commit/da487ba695d85af4751f799702f9b8e4fcf50bdc. I tested it with Dropbox just now and confirmed this is the issue:

```
    check_test.go:575: Fs is incapable of running test, skipping: NFC checkfile vs. NFD remote (expected: 測試_Русский___ě_áñ (NFD) actual: 測試_Русский___ě_áñ (NFC))
```

I guess a surprising number of backends auto-convert NFD to NFC (it turns out to be more than three -- we were previously skipping all the ones without `MD5` support).

It looks like `mailru` might still fail even with this fix, as it won't even attempt to convert it to something it finds valid:

```
run.go:285: Failed to put "測試_Русский___ě_áñ" to "[rclone-test-kajugal2ciruquc7hihifuy6]": invalid characters in object name
```

So that one may need another look. But I think this should resolve the others.

### TestCaseInsensitiveMoveFileDryRun

This one appears to be fixed now.

### TestFixCase

The two outliers here are `jottacloud` and `linkbox`. `jottacloud` has a relavant [known issue](https://rclone.org/jottacloud/#troubleshooting) and is failing before it even gets to the real test. It appears to be not only case-insensitive but also not even case-preserving (we're putting `EXISTING` and it is returning `existing`.) So, I don't think it is actually capable of supporting `--fix-case`, and it probably needs either an exception or to be skipped with a meta-test similar to https://github.com/nielash/rclone/commit/da487ba695d85af4751f799702f9b8e4fcf50bdc.

`linkbox` seems to be failing all kinds of encoding tests at the moment:

```
TestIntegration/FsMkdir/FsEncoding/leading_dot, TestIntegration/FsMkdir/FsEncoding/trailing_space, TestIntegration/FsMkdir/FsEncoding/trailing_CR, TestIntegration/FsMkdir/FsEncoding/trailing_LF, TestIntegration/FsMkdir/FsEncoding/trailing_HT, … (10 more)
```

so it is maybe not surprising that it's failing this one too. Seems like there is some larger issue there.

The others are all failing in the same specific way as `onedrive`, so I predict they would be fixed by https://github.com/rclone/rclone/commit/365f5394c674506710266a9a084541d5876fcf27, although it remains entirely possible that I'm misunderstanding _why_ the change fixes it (in which case, please correct me 😄)

> Possibly -- the issue is that `sync.MoveDir` doesn't take a `remote` string, it expects the root. But maybe I can find a different function to use.

Maybe [`operations.DirMove`](https://github.com/rclone/rclone/blob/2abeda5961615c304348c4886a1d42f4ae30c876/fs/operations/operations.go#L2206) is the answer? Could it be that simple?

**Comment by nielash** [comment]
@ncw I tried `operations.DirMove` and it worked like a charm. Seems like a cleaner solution for multiple issues here. Thoughts? https://github.com/nielash/rclone/commit/34c632e51d568d865e515a7efba6a9504466b516

**Comment by ncw** [comment]
> @ncw I tried `operations.DirMove` and it worked like a charm. Seems like a cleaner solution for multiple issues here. Thoughts? [nielash@34c632e](https://github.com/nielash/rclone/commit/34c632e51d568d865e515a7efba6a9504466b516)

Yes DirMove seems like a good idea. That was made for the vfs to rename directories and will use the underlying `DirMove` primitives if available so will be much more efficient.

> It's possible I'm misunderstanding something, but that really seems to be what's happening as far as I can tell!

Got it - your explanation sounds correct to me.

Will reply to other queries above later!

**Comment by ncw** [comment]
> Would `cache.Get` be a better choice?

In general you should always use `cache.Get` instead of calling NewFs directly. That said, we are going to ditch that code path so this is just an FYI!

> > * The `filepath.Join` look wrong - rclone paths are always unix paths so this should be `path.Join` or possibly even `fspath.Join`
> 
> That's actually what I had originally, but then it [errored on windows](https://github.com/rclone/rclone/pull/7356#issuecomment-1758700673) because of the `\`.

Odd but we are probably ditching that bit too!

> > What change would you propose in the directory cache code to fix it?
> 
> I'm not quite sure yet. This may just be expected behavior, but I think the thing that is surprising to me is that the caller would need to be concerned with tracking which Fs's have been flushed and when... I'd have expected the backend to manage that independently, so that the outcome doesn't change depending on where in your code you call `NewFs`. I guess I assumed I had a pointer to some shared cache, instead of a copy.

Backends don't share directory caches for quite a few reasons. The main one is that it is difficult to tell whether backends are pointing to the same thing, and if the root is different the contents of the directory cache will be different.

> ### TestApplyTransforms
> Yes, I think we should go ahead with [nielash@da487ba](https://github.com/nielash/rclone/commit/da487ba695d85af4751f799702f9b8e4fcf50bdc). I tested it with Dropbox just now and confirmed this is the issue:

Sounds good to me.

> ### TestCaseInsensitiveMoveFileDryRun
> This one appears to be fixed now.

:-)

> ### TestFixCase
> The two outliers here are `jottacloud` and `linkbox`. `jottacloud` has a relavant [known issue](https://rclone.org/jottacloud/#troubleshooting) and is failing before it even gets to the real test. It appears to be not only case-insensitive but also not even case-preserving (we're putting `EXISTING` and it is returning `existing`.) So, I don't think it is actually capable of supporting `--fix-case`, and it probably needs either an exception or to be skipped with a meta-test similar to [nielash@da487ba](https://github.com/nielash/rclone/commit/da487ba695d85af4751f799702f9b8e4fcf50bdc).
> 
> `linkbox` seems to be failing all kinds of encoding tests at the moment:
> 
> ```
> TestIntegration/FsMkdir/FsEncoding/leading_dot, TestIntegration/FsMkdir/FsEncoding/trailing_space, TestIntegration/FsMkdir/FsEncoding/trailing_CR, TestIntegration/FsMkdir/FsEncoding/trailing_LF, TestIntegration/FsMkdir/FsEncoding/trailing_HT, … (10 more)
> ```
> 
> so it is maybe not surprising that it's failing this one too. Seems like there is some larger issue there.

Note that linkbox has some overrides in the integration test config

https://github.com/rclone/rclone/blob/f4c058e13e3b0af3bed5c4e6db39599e5e440694/fstest/test_all/config.yaml#L376-L382

I'm not sure what is up with it though - I think there may be a PR in the queue.

> The others are all failing in the same specific way as `onedrive`, so I predict they would be fixed by [365f539](https://github.com/rclone/rclone/commit/365f5394c674506710266a9a084541d5876fcf27), although it remains entirely possible that I'm misunderstanding _why_ the change fixes it (in which case, please correct me 😄)

That fix looks OK if we need it, but I think we probably won't with DirMove.

Fixing the integration tests is an iterative process, I tend to fix one set of stuff a day until it is all clean!

Happy for you to merge fixes for integration tests when you are happy with them.

**Comment by nielash** [comment]
Update: the latest fixes have helped a lot. We're down to just a few outliers now. 

- `Linkbox`: see [comment here](https://github.com/rclone/rclone/issues/7591#:~:text=will%20bring%20one.-,Note%20that%20linkbox%20has%20some%20overrides%20in%20the%20integration%20test%20config,was%20deemed%20impossible%2C%20I%20suspect%20we%27ll%20reach%20the%20same%20conclusion%20here.,-That%20fix%20looks)
- `mailru` (and `chunker` wrapping `mailru`): The error is:
```
Failed to put "測試_Русский___ě_áñ" to "[rclone-test-cubumak9yoneric9nupaneb3]": invalid characters in object name
```
So it seems like maybe the backend's MultiEncoder defaults are set incorrectly, as it is trying to `PUT` a filename that mailru won't accept. I'm not sure exactly which characters mailru doesn't like (but I'm guessing it's not the Russian ones!)

- `OpenDrive`: The error is:
```
EXISTING: Couldn't move: You cannot move or copy file to same folder (Error 403)
...
DirMove error File or folder with such name already exists (Error 409)
```
I am not too familiar with `OpenDrive`, but I looked into this a little bit and I think the problem might be that we are using the wrong API operation. We are using [`/file/move_copy.json`](https://github.com/rclone/rclone/blob/137f7f62fbc4161b67360a45cb761a3bf255aa2c/backend/opendrive/opendrive.go#L454), but `OpenDrive` has a separate `/file/rename.json` for renaming files within the same directory (p. 22 of the [API guide](https://www.opendrive.com/wp-content/uploads/guides/OpenDrive_API_guide.pdf)) and likewise `/folder/rename.json` for directories (p. 37). So, I think perhaps the backend should be checking whether the move is within the same directory and using `rename` instead of `move_copy` if so. Does that sound plausible to you, and would you like me to try to implement that? (It seems a little surprising to me that this wouldn't have come up before, including on other tests...)

**Comment by ncw** [comment]
> Update: the latest fixes have helped a lot. We're down to just a few outliers now.
> 
> * `Linkbox`: see [comment here](https://github.com/rclone/rclone/issues/7591#:~:text=will%20bring%20one.-,Note%20that%20linkbox%20has%20some%20overrides%20in%20the%20integration%20test%20config,was%20deemed%20impossible%2C%20I%20suspect%20we%27ll%20reach%20the%20same%20conclusion%20here.,-That%20fix%20looks)

Add in an override in config.yaml is probably what I'd do at this point!

> * `mailru` (and `chunker` wrapping `mailru`): The error is:
> 
> ```
  > Failed to put "測試_Русский___ě_áñ" to "[rclone-test-cubumak9yoneric9nupaneb3]": invalid characters in object name
> ```
> 
> So it seems like maybe the backend's MultiEncoder defaults are set incorrectly, as it is trying to `PUT` a filename that mailru won't accept. I'm not sure exactly which characters mailru doesn't like (but I'm guessing it's not the Russian ones!)

The encoder only really works for ASCII punctuation. It doesn't deal with other sorts of replacements. Not sure what to do about this

A bit of testing indicates that mailru doesn't like any of the accented characters `йěáñ`

```
>>> s="йěáñ"
>>> s
'йěáñ'
>>> s.encode("utf-8")
b'\xd0\xb8\xcc\x86e\xcc\x8ca\xcc\x81n\xcc\x83'
```

It is the combining characters it doesn't like by the look of it

```
>>> for i in s: print(hex(ord(i)))
... 
0x438
0x306
0x65
0x30c
0x61
0x301
0x6e
0x303
```

I guess mailru just can't cope with this, so I'd mark it so in config.yaml

> * `OpenDrive`: The error is:
> 
> ```
> EXISTING: Couldn't move: You cannot move or copy file to same folder (Error 403)
> ...
> DirMove error File or folder with such name already exists (Error 409)
> ```
> 
> I am not too familiar with `OpenDrive`, but I looked into this a little bit and I think the problem might be that we are using the wrong API operation. We are using [`/file/move_copy.json`](https://github.com/rclone/rclone/blob/137f7f62fbc4161b67360a45cb761a3bf255aa2c/backend/opendrive/opendrive.go#L454), but `OpenDrive` has a separate `/file/rename.json` for renaming files within the same directory (p. 22 of the [API guide](https://www.opendrive.com/wp-content/uploads/guides/OpenDrive_API_guide.pdf)) and likewise `/folder/rename.json` for directories (p. 37). So, I think perhaps the backend should be checking whether the move is within the same directory and using `rename` instead of `move_copy` if so. Does that sound plausible to you, and would you like me to try to implement that? (It seems a little surprising to me that this wouldn't have come up before, including on other tests...)

I suspect that the opendrive API has improved since the backend was written...

Yes your fix seems like the correct one if you want to have a go :-)

**Comment by nielash** [comment]
> Yes your fix seems like the correct one if you want to have a go :-)

Here's my proposed fix: https://github.com/rclone/rclone/pull/7636

**Comment by nielash** [comment]
That seems to have solved it 🙂

**Comment by ncw** [comment]
Yes that looks much better. I just need to fix the Error IsFile Root ones and then we should be back below 10 failures again before I merge the directory modtime/ metadata which is bound to break more stuff!

**Comment by ncw** [comment]
I'm going to close this one as all the action points on it are done.

I'm sure we are going to need a new issue tomorrow though!
