### ISSUE TITLE
Support proxy option for `serve s3 <remote>` similar to `--auth-proxy`

### ISSUE THREAD

**Issue by saw-jan** [rclone/rclone#7645]
#### What problem are you are trying to solve?
**Scenario:**
An org has a WebDAV server where most of the files/folders are stored and they have s3 clients. The s3 clients want to access the files from that webdav server.
So I want to serve webdav backend with `serve s3` command. Allow multiple s3 clients to access webdav server via rclone's `serve s3` server.

Use case:
1. add a WebDAV backend without `user` and `password` in rclone
2. serve with `rclone serve s3 <remote> --proxy-mode`
3. Multiple s3 clients send requests to acces the files that are stored in that webdav server

![rclone_s3_proxy](https://github.com/rclone/rclone/assets/52366632/981b2007-25f5-4fc7-a802-509f75609f7e)

#### How do you think rclone should be changed to solve that?

I tried to implement `--auth-proxy` but that works only with `user:pass`. Since the S3 client sends signed `Authorization` header, it is not possible to parse `user:pass` from the request by `serve s3`.

So, the one way is to work with oauth token. The s3 client uses oauth token as the accessKey (doesn't care about the secretKey).
`serve s3` will then parses the oauth key from the request, creates new vfs and authorize that vfs with oauth token (Bearer token) per request.

Changes required:
1. method `setBearerToken` should be made public
https://github.com/rclone/rclone/blob/8f0e9f9f6bd78f6ac7488ac48bbe7e9a9ba418ab/backend/webdav/webdav.go#L521
2. `--proxy-mode` option for `serve s3` so that the default would be off.
3. Parse oauth token from each s3 client request and create new vfs for the request context
4. Requires gofakes3 Backend methods to receive request object:
    ```go
    ListBuckets(r *http.Request) ([]BucketInfo, error)
    ```

POC PRs in https://github.com/rclone/rclone/pull/7646, https://github.com/Mikubill/gofakes3/pull/3

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by saw-jan** [comment]
>I think we should try to make this work within the --auth-proxy framework.
>So doing this should work:
>1. checking the signature is correct (proves the user knows the secret_access_key)
>2. passing the access_key_id to the auth proxy as username with a blank password

Thanks, that would be really great if it works with --auth-proxy. I will give it a try

>I would have thought that should work?
>I'm not familiar with using an oauth token with s3 though - how does that work?

s3 client would use oauth token as `access_key_id` and send the request to rclone, rclone then parses the access_key_id, pass it proxy as username.

I will work on your suggestions.

**Comment by saw-jan** [comment]
@ncw I have made the changes to the PRs. Please have a look

https://github.com/Mikubill/gofakes3/pull/3#discussion_r1502249619
and also https://github.com/rclone/rclone/pull/7646

**Comment by nanawel** [comment]
I'm currently testing this feature under v1.66 and it works with some clients but not some others. After digging a few hours I noticed that compared to other S3 services (here with MinIO), rclone returns the value inside `<Key>` (= filenames) as an **URL-encoded** string.

While it's a bit unclear in the specs, some clients seem to expect a proper UTF-8 string and so it leads to issues when they reuse it and re-URL-encode it before sending a `HeadObject` request for example, because it returns a 404.

[The doc says](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax) _Encoding type used by Amazon S3 to encode the [object keys](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) in the response. Responses are encoded only in UTF-8._ so unless you pass the `content-encoding=url` parameter in the query, returned filenames should not be encoded that way.

Expected: `<Key>Æther Realm/[2011] Odin Will Provide/cover.jpg</Key>`
Actual: `<Key>%C3%86ther+Realm/%5B2011%5D+Odin+Will+Provide/cover.jpg</Key>`

I've tried with a WebDAV backend and the local filesystem, the result is the same.

Dunno if I'm at the right place to report this, but as the `serve s3` feature is still beta, I thought this might be interesting to know.

**Comment by ncw** [comment]
@nanawel I suggest you make a new issue about that - thanks

**Comment by nanawel** [comment]
I've opened a new issue regarding the wrong content-type: https://github.com/rclone/rclone/issues/7836

**Comment by saw-jan** [comment]
I am closing this here as respective PRs have been merged (https://github.com/rclone/rclone/pull/7646)
