### ISSUE TITLE
Using rclone in a Go app (2024 edition)

### ISSUE THREAD

**Issue by jsumners** [rclone/rclone#7674]
👋 I am contemplating porting https://github.com/ep1cman/unifi-protect-backup to Go. Ultimately, that application basically does an `os.exec.Command` of `rclone`. I'd prefer to avoid that if I decide to move forward with this project. Is https://github.com/rclone/rclone/issues/361#issuecomment-1611890274 still the recommended way to utilize `rclone` via Go that is effectively "rclone, do what you do and give me back an `err` if something went wrong"?

**Comment by jsumners** [comment]
I have a GitHub account.

**Comment by ncw** [comment]
@jsumners librclone is the recommended way of using rclone in-process because it uses a stable API (the [rc API](https://rclone.org/rc/)) and will work cross language.

If you don't mind using it out of process then just use the rc API.

You can, if writing in Go, use the underlying primitives. This is probably slightly more convenient, but we don't keep a stable Go API so it isn't recommended.

I should really write this up as an embedding rclone doc...

**Comment by jsumners** [comment]
> I should really write this up as an embedding rclone doc...

Please do. That would be very helpful. My Go proficiency is still nascent. As much clear documentation as possible would be tremendous. I'd like to avoid CGO if I can.

**Comment by ncw** [comment]
The example referenced above https://github.com/rclone/rclone/issues/361#issuecomment-1611890274 should work just fine. It doesn't require CGO.
