### ISSUE TITLE
Enhancement: persist rclone state across multiple instantiations

### ISSUE THREAD

**Issue by DanielDent** [rclone/rclone#771]
Possibly related issues: #180, #711 

A package I maintain, git-annex-remote-rclone, uses rclone as a simple unified interface to rclone's nice long listed of supported cloud providers. I'm aware of other software which does the same thing (e.g. hashbackup).

Usage of git-annex-remote-rclone often involves repeatedly calling "rclone copy [source] [destination]". During a run, rclone will refresh auth tokens, get object IDs for directories, and various other tasks depending on the cloud provider.

Each time rclone is called, additional API calls end up being made. The additional network RTTs lower performance and the additional API calls also contribute to unnecessary resource use and  provider rate limiting.

One approach which would help would be for rclone to provide a mechansism by which it's state could be saved to a file, with a mechanism to provide the state to rclone to be re-loaded during the subsequent invocation . 

Another approach would be to provide an interface by which rclone could be used interactively, with file requests being sent to a long-running rclone process over an interface of some kind.

It's possble that some of this functionality has already been created for the recently added FUSE support and it's just a question of adding a different interface to access it.

**Comment by ncw** [comment]
Saving and loading state would be hard and different for each provider, so I'm reluctant to go down that route.

What would be easier would be to run an rclone process you can send commands to somehow.  rclone would have to cache the `remote:` objects between invocations to be of any use.

Imagine for a moment that rclone opened a socket (or maybe you could pipe stuff on stdin), one rclone command per line.  Would that be the kind of thing that would be useful? How would rclone return errors?

It would be helpful to have a bit more detail about what exactly are in those `rclone copy [source] [destination]` commands. Do they go both ways upload and download?  Is it files or directories you are transferring? What about the paths do they change much?

An alternative to making a command line interface might be to make a simple API, simple enough that you could WGET or CURL it from a script.

PS what does git-annex-remote-rclone do?  I'm not familiar with git-annex.

**Comment by ncw** [comment]
I had an idea to refine the above...

Make a command called `rclone client`.  This would have some subcommands

```
rclone client start_server [opts]
rclone client stop_server [opts]
rclone client run [opts] -- rclone command
```

The opts would be:

```
--addr host:port - where to bind to - defaults to localhost:19384 (say)
--auth string - string that must be supplied as a password to use the server- defaults to ???
```

These should be usable as environment variables ideally also

Might want another command to say you are going to be re-using a particular remote which would help rclone working out what to cache.

```
rclone client cache_remote [opts] remote:path
```

`rclone client start_server` would start a server in the background running on the port you gave. It would implement some sort of http API - the details of which are irrelevant.

So you would use it like this

```
rclone client start_server
rclone client run -- copy /path/to/dir remote:
rclone client run -- copy remote: /path/to/dir
rclone client run -- delete remote:path
rclone client stop_server
```

Things to think about
  * the logs should probably be streamed back from the server to the client, failing streaming they need to be returned somehow.
  * working out how to cache the remotes is tricky because of the path after the remote
    * might want to implement a reset root command? which would take a remote: and change the path it was attached to. This might kill the directory caching though...
  * the internals of rclone will only allow one command to be run at once (there is too much global state at the moment) so need to enforce that
  * might want rclone to choose a random port and password and return these as strings that a shell could intepret (like ssh-agent does)

**Comment by animosity22** [comment]
Is this now covered via the webgui?

**Comment by ncw** [comment]
I think this issue is covered by the [remote control api](https://rclone.org/rc/) which the webgui uses. That is the way to persist rclone and run it with the minimum number of operations.

So I'll close this now :-)
