### ISSUE TITLE
bisync through Dropbox+crypt constantly critically fails due to off-by-one differences in modtime

### ISSUE THREAD

**Issue by Asmageddon** [rclone/rclone#8025]
#### What is the problem you are having with rclone?

Almost everytime I run bisync first on one of my devices and then the other, bisync fails due to modtimes of multiple(not all) files on one of the endpoints being off by 1s

#### What is your rclone version (output from `rclone version`)

Android 14(crDroid): `v1.66.0-termux`
Manjaro Linux: `v1.67.0`

#### Which cloud storage system are you using? (e.g. Google Drive)

Dropbox, accessed through the crypt backend.

#### The command you were trying to run

On desktop: `rclone bisync Local:Documents/WorkingDocs Dropbox_crypt:WorkingDocs --fast-list --checkers 64 --transfers 32`

On mobile: `rclone bisync Dropbox_crypt:WorkingDocs Local:storage/shared/share/WorkingDocs --fast-list --checkers 64 --transfers 32`

#### A log from the command with the `-vv` flag

I don't want to repeat the failure yet again, so here's the self-explanatory output without the flag, with filenames anonymized:

```
2024/08/19 15:14:55 NOTICE: bisync is IN BETA. Don't use in production!
2024/08/19 15:15:08 ERROR : -          Modtime not equal in listing. Path1: 2022-03-20 19:14:59 +0000 UTC, Path2: 2022-03-20 19:14:58 +0000 UTC - Path1/File1.md
2024/08/19 15:15:08 ERROR : -          Modtime not equal in listing. Path1: 2021-05-14 11:59:18 +0000 UTC, Path2: 2021-05-14 11:59:17 +0000 UTC - Path1/Subdirectory/File2.pdf
2024/08/19 15:15:08 ERROR : -          Modtime not equal in listing. Path1: 2021-05-14 11:56:10 +0000 UTC, Path2: 2021-05-14 11:56:09 +0000 UTC - Path1/Subdirectory/File3.pdf

...this repeats several dozen times...

2024/08/19 15:15:08 ERROR : -          Modtime not equal in listing. Path1: 2021-05-14 11:59:24 +0000 UTC, Path2: 2021-05-14 11:59:23 +0000 UTC - Path4/File50.md
2024/08/19 15:15:08 ERROR : -          Modtime not equal in listing. Path1: 2022-02-06 20:33:42 +0000 UTC, Path2: 2022-02-06 20:33:41 +0000 UTC - Path5/File51.txt
2024/08/19 15:15:08 ERROR : Bisync critical error: path1 and path2 are out of sync, run --resync to recover
2024/08/19 15:15:08 ERROR : Bisync aborted. Must run --resync to recover.
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
I think this is because the `dropbox` backend rounds modtimes to second precision to get around an API limitation:

https://github.com/rclone/rclone/blob/4e708e59f2e21c9751e7023925071a2689a73d0f/backend/dropbox/dropbox.go#L1751-L1752

But this means that a time like `2022-03-20 19:14:58.500000000 +0000 UTC` will get rounded to `2022-03-20 19:14:59 +0000 UTC` and not `2022-03-20 19:14:58 +0000 UTC` (simply ignoring the extra precision) as bisync expects.

I think the line above should be using `Truncate` instead of `Round`, @ncw do agree?

**Comment by ncw** [comment]
Hmm. Does bisync use the Precision of the Fs? A one second precision should make these match shouldn't it? 

> I think the line above should be using `Truncate` instead of `Round`

That would make the timestamps less accurate wouldn't it?

I think bisync needs to be taking the precision of the two fses into account.

If we change the modtime rounding then it will likely cause rclone sync to re copy half the files so  care is needed with that option.

**Comment by nielash** [comment]
Bisync does already take the Fs precision into account:

https://github.com/rclone/rclone/blob/be448c9e1359ef7e61517575c93870d3c0ed3662/cmd/bisync/compare.go#L195-L215

But if the `modifyWindow` is `1s`, times that are exactly `1s` apart are not within the window. 

Perhaps it should be using `<=` and `>=` instead of `<` and `>`?

> That would make the timestamps less accurate wouldn't it?

In a sense yes, as any loss of precision is, by definition, less accurate. But I'm not sure I'd consider rounding down to be less accurate than rounding up, if thought of as just a loss of decimal places. And there is an advantage to truncating instead of rounding, as it means you can then use `.After()` to reliably determine which of two times has the greater precision. There an example in the comment here:

https://github.com/rclone/rclone/blob/be448c9e1359ef7e61517575c93870d3c0ed3662/cmd/bisync/listing.go#L453-L469

**Comment by nielash** [comment]
@Asmageddon in case this is helpful to you in the short-term while we discuss the proper long-term fix: 
I think adding `--modify-window 2s` to your command would likely stop the critical errors.

**Comment by Asmageddon** [comment]
Wow, I'm amazed at how quick the reply and analysis of the issue have been, complete with advice for a temp fix within less than half a day. Thanks :D 

`--modify-window 2s` seems to work, so far. So, thanks again :)

**Comment by nielash** [comment]
> Could bisync keep that original time 12:54:49.7 and use that instead in the modifyWindow comparison?

I think actually it could, now that bisync considers the `modifyWindow` for same-side comparisons as well. I'm now remembering that the truncation stuff dates back to a time before we did that. Back then, it was problematic to save a listing with `12:54:49.7` for a backend that can't handle that precision, as on the next run the backend would report the time as `12:54:50` and bisync would think the file had changed. So the truncation was a workaround to anticipate this and proactively record the time with the precision we expect to receive next time. 

But now that we do consider the `modifyWindow`, I don't think it's a problem to save the time with extra precision. On the next run, bisync will compare it to the rounded time reported and if it's within the `modifyWindow`, it will treat them as equivalent. And therefore it should not matter whether the backend rounds up or down.

I will try this with the integration tests to make sure I'm not missing something, but I am optimistic that this is the answer.

**Comment by ncw** [comment]
> I will try this with the integration tests to make sure I'm not missing something, but I am optimistic that this is the answer.

Great news and crossed fingers!
