### ISSUE TITLE
Support multiple range requests in cat command

### ISSUE THREAD

**Issue by boxerab** [rclone/rclone#8132]
First of all, thank you for this wonderful piece of software.

I want to use rclone to read compressed files from S3 and decode. My codec does the following:

1. reads main header, which contains offsets for the tiles
2. reads selected tile headers - each header gives offset for compressed packets
3. reads compressed packets and decompresses
4. the tiles and packets are not contiguous

As these files are on the network and can be terabytes in size, I would like to issue a prefetch of the tile headers and then the tile packets, while I am processing the file. This will give a large speed boost.

I can already do a single range request :

`rclone cat --header "Range: bytes=0-1023" minio:foo/bar > range_data.bin`

Proposal: add API so that I can issue

`rclone cat --header "Range: bytes=0-1023, 2048-40966" minio:foo/bar > range_data.bin`

Thanks!
Aaron

**Comment by ncw** [comment]
Rclone only supports a single range in `Range` requests internally because of the lack of support by cloud providers for multiple ranges. It is quite an esoteric feature I think. A lot of cloud providers have trouble implementing a single range - rclone has a suite of fixups here for them!

https://github.com/rclone/rclone/blob/75257fc9cdcaba71aba29e733c75c253fcf1540d/fs/open_options.go#L137-L145
