### ISSUE TITLE
OpenWriterAt implementations causes problems when copying bigger files

### ISSUE THREAD

**Issue by Jeah42** [rclone/rclone#8147]
See discussion in 

https://forum.rclone.org/t/copy-sync-of-large-files-to-pcloud-always-failing/48334

Workarrounds are the options:

--multi-thread-streams=1

or

--disable OpenWriterAt

**Comment by ncw** [comment]
@gfelbing this looks like it is the new code introduced in 4c1cb0622e39a2a91edcab28ebea95c77f186b9d - any thoughts?

**Comment by JohnRichardKlein** [comment]
Oh, my lord, this bug caused me to waste some much time and bandwidth as I am new to rclone and assumed I was doing something wrong.  Please fix this. :) Thankfully for this bug report, I'm using 1 multi-thread-streams to get around it.

**Comment by gfelbing** [comment]
The whole OpenWriterAt was exactly for large files, I will try to reproduce and play with the API again, to find out what changed here...

**Comment by gfelbing** [comment]
@ncw , I think I found the culprit: We need to pull the client creation into each writeAt, as the client is forced to only hold a single TCP connection, which may be unstable for larger files.
But at the same time, this increases the overhead for each writeAt, so I would really love to increase the default bufferSize (IMHO even to the same as chunkSize). But I don't see an easy way to do that with OpenWriterAt, any hints there? 
Otherwise we would need to switch to OpenChunkWriter...

**Comment by ncw** [comment]
@gfelbing I've had to disable OpenWriterAt for the 1.70 release as the API seems to be blocked by pcloud.

See f226d12a2f26cf1df74c82bee62add4e2fb88e41 for info.

**Comment by gfelbing** [comment]
Sad, but thats how it is..
