### ISSUE TITLE
[Request] Add an option to display Google encoded files

### ISSUE THREAD

**Issue by jpat0000** [rclone/rclone#838]
Every time you upload a video to Google Drive, Google goes through the trouble of converting this media into various bitrates and resolutions. Being able to download these files, as well as point to them with applications such as Plex using rclone's mount feature, could be greatly beneficial.

There is a similar request on another project which may contain relevant information:

https://github.com/thejinx0r/node-gdrive-fuse/issues/59

My personal preference for the naming structure would be something along the lines of: 

filename-Google_bitrate.filetype

**Comment by ncw** [comment]
Sounds interesting...  Any chance you could dig up the API docs for this?

**Comment by savahu** [comment]
Maybe this still works to retrieve the transcoded videos:
https://gist.github.com/wnielson/bed435005c0bd338e672

**Comment by B4dM4n** [comment]
I'm not sure how hard it would be to implement this feature.

It definitely requires a additional API call to retrieve the actual transcode URL for each file to `https://docs.google.com/get_video_info?docid={docid}`. This could be done similar to the `--drive-v2-download-min-size` flag which also does this.

Another question are the available formats and resolutions. If they are always the same and only depend on the source resolution, the list of available transcode settings could be calculated without the need of calling `https://docs.google.com/get_video_info?docid={docid}` beforehand. Otherwise the number of API calls during a folder listing would be to much.
Calculating the list of formats ourselves has the risk of breaking if google changes the list of available formats. 
There should also be a way to filter the generated list of file names. A subset of https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection would be very flexible but require a bit of work to implement.

**Comment by animosity22** [comment]
This looks to be pretty stale as well. Closing out as it doesn't seem to have any takers.
