### ISSUE TITLE
[Hubic] Panic

### ISSUE THREAD

**Issue by fbastok** [rclone/rclone#933]
Using 1.34 on a Mac.
When copying a large directory, had a panic crash after a few hours.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x136596]

goroutine 273 [running]:
panic(0x5fe1a0, 0xc420010080)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ncw/rclone/local.(*Object).Size(0xc4207180c0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/local/local.go:540 +0x26
github.com/ncw/rclone/fs.Copy(0x9c4d80, 0xc420069500, 0x9c5500, 0xc420118500, 0x9c5380, 0xc4207180c0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:242 +0xfdb
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopier(0xc4205f6000, 0xc4205e6480, 0x9c4d80, 0xc420069500, 0xc4205f6088)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/sync.go:251 +0x2b5
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/sync.go:349 +0x108 
```

**Comment by ncw** [comment]
The crash was here indicating that `o.info` was nil.  There shouldn't be any code paths which allow `o.info` to be nil, so that is a bit of a puzzle.

It is as if os.Lstat returned nil, nil which it shouldn't really, but would be easy to check for.

Can you reproduce this problem?  Might something else have been changing that large directory (removing, renaming fles)? Anything else that might be helpful?

```go
// Stat a Object into info
func (o *Object) lstat() error {
	info, err := os.Lstat(o.path)
	o.info = info
	return err
}
```

**Comment by fbastok** [comment]
Nothing has changed in the directory.
I was able to replicate the issue with the same commande. It follows another error:
Failed to calculate src hash

**Comment by animosity22** [comment]
Stale issue. Closing out. If you have a question, you can always ask on the forums!
