### ISSUE TITLE
Slight logical flaw in NeedTransfer

### ISSUE THREAD

**Issue by bep** [rclone/rclone#962]
I guess the only real effect of this is more work being done if `UpdateOlder` in some rare cases, but here:

https://github.com/ncw/rclone/blob/master/fs/sync.go#L169

I don't see why that `else` shouldn't be run if none of the cases in the previous branch is caught.

**Comment by ncw** [comment]
The Equal predicate checks to see whether two files are the same by checking size, modtime and hash in various combinations depending on the flags set by rclone.

The updateOlder flag is 

    -u, --update                            Skip files that are newer on the destination.

So are you saying that the `--update` flag should skip if the files are `Equal` too? That might be OK, but in the case of using the `--checksum` flag that doesn't check the modtimes at all so that could end up updating the mod time to an older one which isn't what `--update` implies.

Is that what you mean?

In the code for Equal - you'll see a branch which updates the mod time on the destination if the hashes match.

**Comment by bep** [comment]
What I'm saying is that the conditional looks confusing and slightly wrong to me.

So given:

* updateOlder = true
* File is not newer on the destination (so not skipped)
* File has not changed, is not skipped just because I set a totally unrelated updateOlder flag.

The odds of the two last items getting any relevance is pretty low, and of no real practical difference -- but it get people looking at the code thinking "that looks like a bug".

**Comment by ncw** [comment]
I think you are correct.  There is a corner case which is worrying me though...

If `--checksum` is set, then `Equal` will not update the modtime of the destination file.  This will mean that after the sync the destination file will not have the correct modification time.

**Comment by ncw** [comment]
I think this was fixed here f3b0f8a9f06b4e3407ea04c37e23b1ebee34cc79 so I'm closing this issue :-)
