### ISSUE TITLE
Feature Request: mount.rclone helper

### ISSUE THREAD

**Issue by gordan-bobic** [rclone/rclone#992]
It would be really handy if there was a mount.rclone wrapper that can be used in /etc/fstab. It would need to accept all the usual paremeters using slightly different syntax, e.g.

rclone --max-read-ahead 4M --read-only --config /path/to/config mount foo:/bar baz

would need to be expressed to the mount helper as:

mount.rclone -o max-read-ahead=4M,ro,config=/path/to/config foo:/bar baz

And, of course, mount.rclone would have to wait until the fs has completed mounting and then go into the background.

Perhaps this could be done by making rclone check whether the binary name it was invoked as is mount.rclone, and if so, alter it's parameter format expectations?

**Comment by ncw** [comment]
Nice idea.

I think this could be achieved by detecting the name of the binary as you say then doing textual manipulation of the `-o parameters` to make the as per what rclone normally requires.

note putting rclone in the background is #723

**Comment by gordan-bobic** [comment]
This should work for mount.rclone until the functionality is folded into the rclone binary:

```
#!/bin/sh

src=$1
dst=$2

shift 2

# Process -o parameters
while getopts :o: opts; do
	case $opts in
		o)
			parms=`echo $OPTARG | sed -e 's/,/ /g'`
			for parm in $parms; do
				if [ $parm == "rw"   ]; then continue; fi
				if [ $parm == "dev"  ]; then continue; fi
				if [ $parm == "suid" ]; then continue; fi
				trans="$trans --$parm"
			done
			;;
		\?)
			echo "Invalid option: -$OPTARG"
			;;
	esac
done

trans="$trans $src $dst"

rclone mount $trans

```

Then in fstab:

`mount.rclone#crypt:/media       /mnt/tmp        fuse    config=/home/media/.rclone.conf,allow-other,default-permissions,read-only,max-read-ahead=16M 0 0`

It produces the command line, but for some reason I cannot actually get it to work because $PATH seems to disappear half way through the mount process, so mount can find neither mount.rclone nor fusermount. And for once it doesn't look like it's SELinux getting in the way...

**Comment by gordan-bobic** [comment]
Now on the wiki: https://github.com/ncw/rclone/wiki/rclone-fstab-mount-helper-script

**Comment by keithchilders** [comment]
+1 for the main rclone binary to function as an fstab helper. Using shell script until then.

**Comment by ncw** [comment]
I'll try to do this for the 1.37 release...

Or unless anyone else wants to have a go?

**Comment by dragetd** [comment]
So the script currently in the wiki has a fews issues.

The 'total 0' does not work for localized systems. The script returns immediately which causes an error in the journal and a failed access. Only on the second access it works. And as the comment says: Empty remotes cause it to hang.

I would be okay with the mount-binary being a script, so rclone does not have any logic for handling this. But the script needs to be a little more robust. :-)

Instead of trying to figure out if the mount was successful, it would be nice if rclone mount would have an option to only background once the mount is successful.

Any thoughts on this?

As for making the script a little more robust than it is right now, I would suggest:
```
#!/bin/bash

remote=${1}
mountpoint=${2}
shift 2

# Process -o parameters
while getopts :o: opts; do
    case ${opts} in
        o)
            params=${OPTARG//,/ }
            for param in ${params}; do
                if [ "${param}" == "rw"   ]; then continue; fi
                if [ "${param}" == "ro"   ]; then continue; fi
                if [ "${param}" == "dev"  ]; then continue; fi
                if [ "${param}" == "suid" ]; then continue; fi
                if [ "${param}" == "exec" ]; then continue; fi
                if [ "${param}" == "auto" ]; then continue; fi
                if [ "${param}" == "nodev" ]; then continue; fi
                if [ "${param}" == "nosuid" ]; then continue; fi
                if [ "${param}" == "noexec" ]; then continue; fi
                if [ "${param}" == "noauto" ]; then continue; fi
                if [[ ${param} == x-systemd.* ]]; then continue; fi
                trans="${trans} --${param}"
            done
            ;;
        \?)
            echo "Invalid option: -${OPTARG}"
            ;;
    esac
done

# exec rclone
trans="${trans} ${remote} ${mountpoint}"
# NOTE: do not try "mount --daemon" here, it does not play well with systemd automount, use '&'!
PATH=${PATH} rclone mount ${trans} </dev/null >/dev/null 2>/dev/null &

# Wait for rclone to finish the mount
# WARNING: this will loop forever if remote is actually empty!
sleep 1
until [ ! -z "$(ls -A ${mountpoint})" ]; do
    echo "Waiting"
    ls -A ${mountpoint}
    sleep 1
done
```

**Comment by gordan-bobic** [comment]
Thanks for the proposal to make the mount wrapper more robust.
Empty mount is a legitimate case and looping forever is similarly a non-starter for something that is there specifically to run unattended from fstab.

**Comment by dragetd** [comment]
Maybe we should include the script in the source and not in the wiki, instead link and document it there?

**Comment by ncw** [comment]
@dragetd that sounds like a good idea! There is a place for it now in `contrib`. Fancy tidying the script up, making sure it works then sending a pull request to place it in `contrib/mount-helper`?

**Comment by dragetd** [comment]
The `until [ ! -z "$(ls -A ${mountpoint})" ]; do` is still a hack. It considers a mountpoint 'ready' when there are files. Empty remotes trigger an endless loop.

Anyone got a better idea to to check if a mount is ready?

Maybe a simple `sleep 1` might be still better than assume there is always some file?

**Comment by eatnumber1** [comment]
Was only backgrounding after the mount was successful not an option? As you mentioned earlier, that sounds like the best option.

Failing that, other options include:
 - [Watch for kernel mount events](https://stackoverflow.com/a/1113371) via uevents, then check /proc/mounts to see if it's rclone. You'd have to write this in a different language to do it though.
 - Check that there is a mount on the directory with `$(stat -c '%m' /mnt/point) == /mnt/point`, but that has the race that rclone can fail and something else mount over it instead
 - Check that the mount itself is a fuse mount, e.g. `$(stat -f -c '%T' /mnt/point) == fuseblk`, but if /mnt/point is not mounted at all and /mnt is a fuse filesystem it will also return true.

**Comment by dragetd** [comment]
Someone wrote that --daemon does not play along nice with systemd. I tried it and found out it results in: `Found left-over process 975 (rclone) in control group while starting unit. Ignoring.` when restarting.

Tho I am really not sure why this works with & any better. How does sshfs or other fuse-filesystems do it? I'd much prefer systemd working together with rclone doing the mount and then backgrounding instead of such hacks.

I started noting down my changed in commits here: https://github.com/dragetd/rclonefs/blob/master/rclonefs

Nice ideas @eatnumber1 . Just also thought of: Why not check /etc/mtab for fuse.rclone on the right path? I'll update the script – ideas and PRs welcome.

**Comment by ncw** [comment]
> Anyone got a better idea to to check if a mount is ready?

Rclone emits a systemd notification when it is mounted. I don't know how that actually works though - I just used this libary: https://github.com/okzk/sdnotify

You could of course just wait 10 seconds in that loop so it isn't infinite. A bodge but one without an infinite loop at least!

If an environment variable was set then rclone could write to a file/socket on successful mount.

> Was only backgrounding after the mount was successful not an option?

The Go runtime hates `fork()` since it is highly multithreaded so daemonisation (implemented with https:github.com/sevlyar/go-daemon ) actually runs a new copy of rclone.

The way it would have to be done is that the new rclone would have to run the mount then signal to the old rclone that it was successful somehow. Not impossible, but not trivial either!

Re-using the systemd notification might work as it seems to send a message to a socket...

> Someone wrote that --daemon does not play along nice with systemd. I tried it and found out it results in: `Found left-over process 975 (rclone) in control group while starting unit. Ignoring.` when restarting.

That is because of the non-forking --daemon flag. I think running rclone without `--daemon` is the right thing to do if you are running it off systemd isn't it? I run rclone mounts off systemd like this just fine.

> Edit: Out of curiosity, what is your view of integrating said functionality in rclone itself @ncw ? Checking if the name of the binary as which it was started is 'mount.rclone' and then doing a 'mount' ? Would you accept PRs in this direction?

I did have that idea in the past too, and yes I like it very much! It then means that all we have to do to install is add a symlink to the rclone binary and we are away.

**Comment by dragetd** [comment]
Okay, I have figured out the pflag flags parsing and trying to figure out cobra for the sub command things. Basically I thought before parsing the flags in setupRootCommand (cmd/help.go:168) I'd check the binary name it was called by is mount.rclone. If it is, then maybe we need to strip away some of the general mount-parameters (as the bash script did above), but I am not really sure who else handles those. Then switch to the mount subcommand and setup some things.

Something along those lines was my idea. But I struggle a little and I know myself: I will most likely not finish this anytime. So for transparency and being realistic I'd rather say right ahead: if someone else wants to have a go, please!

Or if someone - who knows a bit about go, wants a random voice/screensharing/pair-coding chat with a stranger on the internet, I might be also up for that. :P

**Comment by ncw** [comment]
@dragetd I made a quick attempt to translate the bash script into Go to get you going. I probably got it wrong since I'm not very good at bash, but it should give you a starting point! I didn't try mounting anything with it but it seems to do the right thing (maybe!).

```patch
diff --git a/cmd/cmd.go b/cmd/cmd.go
index 01f0426db..8dfbdb533 100644
--- a/cmd/cmd.go
+++ b/cmd/cmd.go
@@ -13,6 +13,7 @@ import (
 	"os"
 	"os/exec"
 	"path"
+	"path/filepath"
 	"regexp"
 	"runtime"
 	"runtime/pprof"
@@ -496,9 +497,59 @@ func AddBackendFlags() {
 	}
 }
 
+// If rclone was invoked as "rclone.mount" act as if we are a mount
+// script.
+func invokedAsMount() {
+	if filepath.Base(os.Args[0]) != "rclone.mount" {
+		return
+	}
+	log.Printf("Rclone invoked as %v", os.Args)
+	if len(os.Args) < 3 {
+		log.Printf("Too few arguments - need 3")
+		os.Exit(1)
+	}
+	remote, mountpoint := os.Args[1], os.Args[2]
+
+	newArgs := []string{"rclone", "mount"}
+	// Do a quick and nasty job parsing the arguments
+	option := false
+	for _, arg := range os.Args[1:] {
+		if arg == "-o" {
+			option = true
+		} else if option {
+			values := strings.Split(arg, ",")
+			for _, value := range values {
+				switch {
+				case value == "rw":
+				case value == "ro":
+				case value == "dev":
+				case value == "suid":
+				case value == "exec":
+				case value == "auto":
+				case value == "nodev":
+				case value == "nosuid":
+				case value == "noexec":
+				case value == "noauto":
+				case strings.HasPrefix(value, "x-systemd"):
+				default:
+					newArgs = append(newArgs, "--"+value)
+				}
+			}
+		} else {
+			log.Printf("Ignoring argument %q", arg)
+		}
+	}
+
+	newArgs = append(newArgs, remote, mountpoint)
+
+	log.Printf("Translated args: %v", newArgs)
+	os.Args = newArgs
+}
+
 // Main runs rclone interpreting flags and commands out of os.Args
 func Main() {
 	rand.Seed(time.Now().Unix())
+	invokedAsMount()
 	setupRootCommand(Root)
 	AddBackendFlags()
 	if err := Root.Execute(); err != nil {
```

**Comment by ncw** [comment]
I put the above patch into a test release if anyone wants to have a go and comment!

https://beta.rclone.org/branch/v1.51.0-314-g78ffe370-fix-992-rclone.mount-beta/ (uploaded in 15-30 mins)

**Comment by dragetd** [comment]
Please excuse the lack of feedback for such a long time! :(

So I tested the branch. One awkward observation I made on my Ubuntu 18.04 system is, that in fstab I had to write the exact binary name:
> rclone.mount#myremote: …

instead of :
> rclone#myremote: …

I thought the system would look up the `.mount` binary automatically. But when just using `rclone#myremote: …` it would invoke the rclone binary directly and your patch would not trigger.

Moving along, I encountered the following issue:

```
2020/08/04 22:45:26 Rclone invoked as [rclone.mount draget-study: /mnt/study -o rw,config=/root/.config/rclone/rclone.conf,vfs-cache-mode=minimal,dir-cache-time=20s,allow-other,allow-non-empty,gid=1002,umask=002,max-read-ahead=32M,dev,suid]
2020/08/04 22:45:26 Ignoring argument "draget-study:"
2020/08/04 22:45:26 Ignoring argument "/mnt/study"
2020/08/04 22:45:26 Translated args: [rclone mount --config=/root/.config/rclone/rclone.conf --vfs-cache-mode=minimal --dir-cache-time=20s --allow-other --allow-non-empty --gid=1000 --umask=002 --max-read-ahead=32M draget-study: /mnt/study]
2020/08/04 22:45:26 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount": executable file not found in $PATH
```

So the issue is, that there is not environment available in the context of the fstab. With no PATH, 'fusermount' is not found. Tho this is only partly true… fstab entries are converted on the fly to systemd-mount-units on systems using SystemD.
One could edit this mount-unit and add environment variables, that does work. But handling mount-units manually can be cumbersome if you ask me (especially with paths containing spaces etc.), it would be nice if it worked with the fstab.

I hacked yet another workaround-script to see if it would work: /usr/local/bin/rclonefs
```
#!/bin/sh
export PATH="$PATH:/usr/local/bin:/bin"
rclone.mount $@
```

And changed my fstab mountpoint to `rclonefs#myremote: …`, which fixed the PATH issue.

Next thing I encountered is the option 'nofail' I had set, which is not filtered and trips up rclone. It was not in the original wrapper script either. It is described along with `defaults, noauto,user,owner,comment,nofail` here: https://man7.org/linux/man-pages/man5/fstab.5.html

When researching for 'common options' I was surprised to see that SSHFS also does not filter 'nofail'(https://github.com/libfuse/sshfs/blob/master/sshfs.c#L529) but a bunch of others not on our list, too.

Last but not least I do required the option 'daemon' to be set, otherwise rclone does not return from the mount command. Did not try it, but I assume this might cause issues during boot.


Where does this leave us?
- Am I missing something or might it be an alternative to also trigger on 'rclonefs' binary name, which would look a bit prettier in fstab.
- I did not yet explore where fusermount is called as an executable from rclone. Without PATH it might be a bit tricky to solve this one, open for ideas.
- We might consider adding 'daemon' by default.

Apart from that, it works! :-)

**Comment by gordan-bobic** [comment]
Shouldn't the fstab entry be something like:

```
myremote /mount/point rclone defaults,options 0 0
```
I thought the whole point was to avoid using generic fuse syntax by using rclone as the FS type and having mount.rclone helper to mount it?

**Comment by ncw** [comment]
> So I tested the branch. One awkward observation I made on my Ubuntu 18.04 system is, that in fstab I had to write the exact binary name

What did you write in the fstab?

I think @gordan-bobic suggestion might be correct to get it to use rclone.mount

> I did not yet explore where fusermount is called as an executable from rclone. Without PATH it might be a bit tricky to solve this one, open for ideas.

Fusermount isn't called directly by rclone, it is called by the library.

Sshfs will need to call fusermount too - I wonder how it manages to do that?

> We might consider adding 'daemon' by default.

That is probably a good idea

**Comment by ivandeex** [comment]
> Maybe we should include the script in the source and not in the wiki, instead link and document it there?

We should make rclone work like sshfs (mount then daemonize, plus support "mount -t rclone" or "fusermount -o subtype=rclone" or similar compatible ways of being invoked as a mount helper), describe that in official doca and get rid of hackish wrappers in wiki or in source tree.

**Comment by ivandeex** [comment]
>     * [Watch for kernel mount events (https://stackoverflow.com/a/1113371) via uevents, 

Supporting a kernel-specific syscall/subsystem in rclone is an overkill. We can simply poll for our mount in /proc/mounts every 100-200ms until success or until _--daemon-timeout_ (or introduce new _--mount-timeout_ as the former is OSX-specific).

> then check /proc/mounts to see if it's rclone. You'd have to write this in a different language to do it though.

It has been implemented in 3 lines of go code: https://github.com/sapk/docker-volume-rclone/blob/3a3eff3b3d1dd258a8710edb8bf5dd7ceb58d23e/rclone/driver/driver.go#L36

The code checks that the mount: (1) exists (2) belongs with sshfs (3) is done with rclone.
It's better than buggy-wrong `-z "$(ls -A ${mountpoint})"` check.
/proc/mounts comes straight from kernel (unlike /etc/mtab manipulated by /bin/mount and sisters) and is read-permitted for everyone.

**Comment by ivandeex** [comment]
> Shouldn't the fstab entry be something like:
> myremote /mount/point rclone defaults,options 0 0

There are various historical ways to do a fuse mount, and rclone should support most (all?) of them for compatibility.

A line `xyz /dir rclone opts,... 0 0` in /etc/fstab results in `/bin/mount -t xyz -o opts... src /dir`, which in turn will search for /sbin/mount.xyz and invoke it as `/sbin/mount.xyz -o opts... src /dir` (see https://salsa.debian.org/debian/util-linux/-/blob/master/libmount/src/context.c#L2125).
This can pass extra cli flags to rclone (symlinked or hard-linked as /sbin/mount.rclone or /sbin/mount.rclonefs) which should be accepted (and ignored) by rclone (see https://salsa.debian.org/debian/util-linux/-/blob/master/libmount/src/context_mount.c#L661). Command-line translation in this case is activated if `HasPrefix(Basenane(os.Args[0]),"mount.rclone")` accepting mount.rclone, mount.rclonefs etc, but I'd rather use cobra's `rootCmd.SetArgs(translatedArgs)` instead of overwriting `os.Args`.

A line `xyz /dir ssh.rclone opts,... 0 0` in /etc/fstab or results in `/bin/fusermount -t xyz -o opts... src /dir`, which looks up `rclone` (without any prefixes) on system path and invokes it as `rclone xyz /dir -o opts...` (see https://github.com/libfuse/libfuse/blob/master/util/mount.fuse.c#L423). Detection here is more tricky, especially since `-o opts...` is optional. However, we can require:
- strictly 2 or 4 arguments
- the 1st one must look like "remote:.*" (if it doesn't have ":" then it's a local path, and /bin/mount would handle it directlt)
- the 2nd one must contain "/" or be an existing directory
- the 3rd one must be "-o" (if exists) and have non-empty 4th one

A line `sshfs#xyz /dir ... ...` is a historical compatibility syntax for the above (search for the word `deprecated` in https://linux.die.net/man/8/mount)

The _systemd_ `[Mount]` unit simply invokes `mount` and expects it to exit with success/failure (forking and daemonizing if it needs to, see https://github.com/systemd/systemd/blob/master/src/core/mount.c#L839 and https://github.com/systemd/systemd/blob/master/src/shared/mount-util.c#L27).

The `sshfs` implements a straight-simple daemonization and plays well with systemd, so rclone could adopt that to some extent (see https://github.com/libfuse/sshfs/blob/master/sshfs.c#L4389 and https://github.com/libfuse/libfuse/blob/master/lib/helper.c#L248)

**Comment by ivandeex** [comment]
I'm going to investigate further and submit a PR.

**Comment by ivandeex** [comment]
> Someone wrote that --daemon does not play along nice with systemd. I tried it and found out it results in: `Found left-over process 975 (rclone) in control group while starting unit. Ignoring.` when restarting.

@dragetd
Will it reproduce if we replace _rclone wrapper_ with _sshfs_? The latter is battle-tested and works smoothly as a systemd mount/automount unit, under automount daemon or from /fstab

Try repeating your steps with fstab like:
`user@server:/remote/dir /mbt/dir fuse.sshfs rw,opts... 0 0`
(run `sudo systemctl daemon-reload` to let systemd translate fstab into a transient mount unit like _/run/systemd/generator/mnt-dir-path.mount_)
Does the message still appear? If yes, then since sshfs is known to be "good", it's a feature, not a bug :)

If not, we can try to detach rclone from the unit cgroup, e.g. using https://github.com/containerd/cgroups#add-a-process-to-the-cgroup which under covers just writes process's pid to detach in a text pseudo-file under _/sys/fs/cgroups_ (see https://stackoverflow.com/questions/35200232/how-to-launch-a-process-outside-a-systemd-control-group/35219752#35219752)
You could add that in the _rclonefs_ wrapper:
```
rclone remote: /mnt/dir &
rclone_pid=$!
echo $rclone_pid | sudo tee /sys/fs/cgroup/systemd/rclone
```
and see if it helps

**Comment by ivandeex** [comment]
> 2020/08/04 22:45:26 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount": executable file not found in $PATH

@dragetd 
systemd runs units with PATH reduced for security to `/bin:/sbin:/usr/bin:/usr/sbin`.
First, try `sudo apt-get install fuse` or `yum ...` if you're on centos. If needed, also do `ln -s /usr/local/bin/fusermount /bin`.

rclone might call _fusermount_ indirectly from two places. First, when it hooks to fuse session at https://github.com/rclone/rclone/blob/v1.52.3/cmd/mount/mount.go#L96 (_rclone mount_) or at https://github.com/rclone/rclone/blob/v1.52.3/cmd/cmount/mount.go#L168 (for _rclone cmount_).

Next, when it unmounts before process exit, at https://github.com/rclone/rclone/blob/v1.52.3/cmd/mount/mount.go#L118
This time it indirectly invokes `fusermount -u /mnt/dir`, which, if run as root, is completely equivalent to `/bin/umount -l /mnt/dir` (see https://github.com/libfuse/libfuse/blob/master/util/fusermount.c#L1421).
Moreover, it's redundant if running under _automount_ since that will ask rclone to exit only when someone has commanded to unmount /mnt/dir either manually or due to idle timeout.

**Comment by ncw** [comment]
> As a mount helper, rclone has to support a special option (e.g. `-o mount.verb=...`) that selects _mount_, _cmount_, or _mount2_ mount method (see [#4393 (comment)](https://github.com/rclone/rclone/issues/4393#issue-647386306), the 2020 Nobel prize for fragmentation goes to Tim Cook).

I should just say I'm planning to make the `rclone mount` command take an `--engine` flag which can then select `mount` or `cmount` or `mount2` (I might rename these!).

At some point I might make `cmd/mountlib` become `cmd/mount` and move the `engine`s into that directory - what do you think?

**Comment by ivandeex** [comment]
> I should just say I'm planning to make the `rclone mount` command take an `--engine` flag which can then select `mount` or `cmount` or `mount2` (I might rename these!).

😍 

> At some point I might make `cmd/mountlib` become `cmd/mount` and move the `engine`s into that directory - what do you think?

I don't see advantages of it 🤔

**Comment by ivandeex** [comment]
Related: a PR for https://github.com/rclone/rclone/issues/4702 will add _linux/amd64_ binary with _cmount_ support to new releases

**Comment by ivandeex** [comment]
blocks on #2968

**Comment by ivandeex** [comment]
Currently `--mount-enginge cmount` is default on windows and macosx. We could also make it default on linux if rclone is built with `cgofuse`. The idea is to use the best standards compatible engine whenever possible keeping `mount` only as fallback for static build.

**Comment by ivandeex** [comment]
Since version 1.57 on rclone can act as a mount helper on its own. See updated https://github.com/rclone/rclone/wiki/rclone-mount-helper-script
